### ISSUE TITLE
Add more descriptive page titles

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#10007]
## Summary

Sentry is painfully missing descriptive page titles for many pages.

## Motivation

Many pages in Sentry lack distinctive titles. This makes identifying tabs or navigating between back/forward buttons difficult.

For example, every subtab under a project simply has that project's name. Here's me clicking between Issues -> Overview -> Releases -> User Feedback for the "javascript" project:

![image](https://user-images.githubusercontent.com/2153/46440391-0b729000-c718-11e8-8aea-044100e4cf05.png)

---

~~Other pages affected:~~

* Project Settings ...
  * Some pages here have complete, descriptive titles e.g. `Project Alert Settings - MyCompany`
  * Many just show the project name (e.g. `javascript`)
  * Others just say the organization (e.g. `MyCompany`)
  * Others just say the page name without additional context (e.g. `Client Keys`)
* Assigned to me / Bookmarked issues / Recently viewed ...
  * All just say the organization (e.g. `MyCompany`)

It's all over the place, really.

Here are the views that are missing a title:
Organization settings pages should say `<title> - <org slug>`
Project settings should say `<title> - <project slug>`

- [ ] Projects Dashboard
- [ ] Organization Settings
  - [ ] General Settings
  - [ ] Teams
    - [ ] Team Details
  - [ ] Integrations
  - [ ] Developer Settings
- [ ] Project Settings
  - [ ] Project Teams
  - [ ] Alerts
  - [ ] Tags
  - [ ] Environments
  - [ ] Data Forwarding
  - [ ] Debug Files
  - [ ] Processing Issues
  - [ ] Inbound Filters
  - [ ] Error Tracking	
  - [ ] Release Tracking (Inconsistent title)
  - [ ] Security Errors
  - [ ] User Feedback
  - [ ] Legacy Integrations

**Comment by dylmye** [comment]
Happy to help out if this still needs doing? :)

**Comment by dylmye** [comment]
I'm a bit stuck on how to add titles for the Project Details tabs. It seems that in some places, `getTitle()` is used, however I'm not sure how to implement this on [ProjectDetails](https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/views/projectDetails.jsx)/[ProjectDetailsLayout](https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/views/projectDetailsLayout.jsx) as they're not AsyncViews. Any ideas?

**Comment by benvinegar** [comment]
@billyvg Could you help @dylmye with his comments above? (Thanks!)

**Comment by billyvg** [comment]
@dylmye Sorry for the slow reply, this got lost - If a component does not extend `<AsyncView>` you can use `react-document-title` to add a title (see: https://github.com/getsentry/sentry/pull/10441)

Otherwise you can add a `getTitle` method on an `<AsyncView>` component (e.g. https://github.com/getsentry/sentry/pull/10457)

I would start with the "Assigned to me / Bookmarked issues / Recently viewed" components - they define a `getTitle` but it's actually used as the page title (and not document title).  I would use `react-document-title` here and use the format `<title> - <org slug> - Sentry`.

For the project settings, this might be a bit trickier if we wanted to be a bit smart about it. We mostly define a custom property `name` on our routes which we can use as a default title. I would look into adding `<DocumentTitle>` to `SettingsProjectContext` or `ProjectSettingsLayout` - you may be able to inspect `children` (or the router via context) for the route + route name. Please reach out if you have any more questions!

**Comment by dylmye** [comment]
Thanks, I'll try to work on it this weekend!

**Comment by bsr3000** [comment]
@benvinegar I can take this one.

But I have a question about formatting of those document titles

currently they are different in organization settings between routes:
`organization -> projects` = `<capitalized(orgId)> Projects - Sentry` ~ ex. `MyCompany Projects - Sentry`
`organization -> members` = `<capitalized(orgId)> Members - Sentry` ~ ex. `MyCompany Members - Sentry`
`organization -> repositories` = `Repositories - Sentry`

some have nothing as you posted in issue

in issue you have `<title> - <org slug>` for organization, which formatting should I stick to?

**Comment by billyvg** [comment]
hi @bsr3000 thanks for helping. It would be great to split these into multiple pull requests (e.g. `Projects`, `Org Settings`, and `Project Settings`). 

As for your question, let's try to stay consistent with the titles on our main pages. e.g. for Issues it is `Issues - org - Sentry`.

**Comment by bsr3000** [comment]
@billyvg okey, I ll start it today :)

**Comment by benvinegar** [comment]
Wow! You literally finished this exactly 1 year after I opened this issue. 🙌
