### ISSUE TITLE
Password set policy

### ISSUE THREAD

**Issue by AlekseiSmirnov** [getsentry/sentry#10067]
## Possibility to enable password set policy

Recently found that some team members use simple passwords like 123456. By far the only default restriction is 6 letter length. It'd be great if administrators can specify password requirements like (at least 1 uppercase letter, at least 1 digit)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by Bessonov** [comment]
@BYK this is still use case for us.

**Comment by BYK** [comment]
@Bessonov I understand. It is just very unlikely that this will be picked up by anyone soon or ever to be honest. Instead of having a system for password requirements configuration I think an easier thing to do would be adding a password-strength meter.

**Comment by Bessonov** [comment]
It would be nice to have a configuration for password requirements, but a single boolean to activate strong passwords (topic to define) would be enough.

If you think of a password-strength meter, then I can imagine to have a static definition of "weak", "good" and "strong" password and let admin define which level is necessary with an select control. But I'm also fine if it's forced client side only.

The main problem why this is needed, it's because sentry must be public to get events from apps or websites. Is there any way to let event API public and hide developer/admin login?

**Comment by TeckTn** [comment]
Any news about this issue ?

**Comment by BYK** [comment]
I'll reopen as this might be something we'll look into. That said there are no solid plans or timeline yet.

**Comment by mdtro** [comment]
@AlekseiSmirnov I've merged PR #43815 that partially addresses this issue. It increases our minimum password requirements (detailed in the PR), but does not provide organizations a way to set custom requirements. A feature that allowed this could be problematic since a user can be a part of multiple organizations and end up in conflict with varying password requirements.

Our recommendation for organizations with unique password requirements is to [use our SSO/SAML integrations](https://docs.sentry.io/product/accounts/sso/) and enforce those requirements with the third-party provider.
