### ISSUE TITLE
Help, 504 Gateway timeout - happens all of sudden

### ISSUE THREAD

**Issue by RamuRChenchaiah** [getsentry/sentry#10481]
We get below error all of sudden - any RCA & possible fix?

<img width="1401" alt="sentry-error" src="https://user-images.githubusercontent.com/14149055/48217081-76188a80-e3ac-11e8-8a75-063b48aefab3.png">

**Comment by mattrobenolt** [comment]
Is there some proxy between you and us? I say this because the protocol you have is "spdy" and we don't support spdy. So this seems to imply that you're not communicating with us directly. Also the timing is 5ms and 4ms. That's way too fast for us to return back a 504. And on top of that, we're not seeing ant 504s on this endpoint in any recent history.
