### ISSUE TITLE
GitLab Repos Fail to Add after Deletion

### ISSUE THREAD

**Issue by lauryndbrown** [getsentry/sentry#10565]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
I'm not savvy enough with js to really debug this. I previously added these and then deleted them. I can no longer add them. And get this error.

https://cl.ly/aa9b9178d42b

**Comment by markstory** [comment]
I can take a look.

**Comment by markstory** [comment]
This was fixed in #10572

**Comment by jtraulle** [comment]
@markstory Is this fixed in SaaS on sentry.io ? I am having the exact same issue I believe.

I started by creating/adding the Gitlab app on a Gitlab admin account. The repo was successfully linked to Sentry.

Then, I deleted the repo and integration on Sentry and the App on my Gitlab instance.
I preferred to create a specific user for Sentry on my Gitlab server and assigning it only some repo.
I have created the app again into the new Gitlab user, linked it into Sentry but now, when I click on the repo name on Sentry to add it, I got an error :
```
Error Communicating with GitLab (HTTP 403): 403 Forbidden
```

**Comment by markstory** [comment]
> Is this fixed in SaaS on sentry.io ?

Yes it should be. The error communicating with GitLab sounds like a permissions issue for your integration user in GitLab. If you login as that user can you see the repositories you're trying to add?

**Comment by jtraulle** [comment]
Thanks. Yup, I can see the repo on Gitlab. And the repo is also listed in the Sentry drop down list but I got the error when clicking on the repo name.

**Comment by markstory** [comment]
Ok. If you could give me the organization slug in sentry.io I can look into the issue further? If you're not comfortable posting that here, could you open a support issue using Help > Contact Support when logged into your sentry account.

**Comment by jtraulle** [comment]
Thanks for your help. The organization slug is opencomp :wink:

**Comment by markstory** [comment]
@jtraulle I took a look and from what I can tell the user you've linked to sentry is unable to read/write project hooks. We need to [add a project hook](https://docs.gitlab.com/ee/api/projects.html#add-project-hook) in order to receive push and merge_request events.

**Comment by jtraulle** [comment]
Thanks :+1:  Got it, I switch user permissions from "Developer" to "Maintainer" for the project and it works great now :slightly_smiling_face:
