### ISSUE TITLE
Last seen date (sometimes) not updating

### ISSUE THREAD

**Issue by LeonB** [getsentry/sentry#1212]
I think there's a bug in 7.0.0 with the "Last seen" date (sometimes) not updating

![sentry-last-seen-date](https://cloud.githubusercontent.com/assets/3979/3467944/b9eaf310-0297-11e4-9734-f6d38b710c6c.jpg)

The event is first reported on june 26, the last reported event is juli 2 but the "Last seen" field reports the first date.

I'm using the redis CACHES and SENTRY_CACHE.

**Comment by mastacheata** [comment]
I can confirm this bug in 7.4.3
The stats graph correctly counts updates, but the list view simply doesn't report anything new and the last seen timestamp isn't updated.
It took me quite a while to realize there was nothing wrong with my clients at all.

I thought this might be caused by the sampling feature, but your event has a mere 20 messages.

**Comment by dcramer** [comment]
I dont think this is actually still a bug. At one point it was, but it's more likely that your workers aren't running or something is misconfigured, especially if you're not seeing other things reported.

Please re-open if there's more information that validates this as not working.

**Comment by mastacheata** [comment]
Is there a mailing list or forum where I could get help with checking my configuration? I feel like the issues on github is not exactly the right spot to do that.
Sentry seems to be working just fine on a different server and while I'm familiar with programming and server administration, I've only got very little knowledge about python in general and even less about the Django Framework or celery workers.
