### ISSUE TITLE
Filtering, groups and events

### ISSUE THREAD

**Issue by BlueMoebius** [getsentry/sentry#1267]
With more events in a group, it is almost impossible to find a specific one, or events with a specific tag...
Example:
![example4](https://cloud.githubusercontent.com/assets/4996003/4115758/7927c866-327c-11e4-8eb2-2b3f2fce3e9d.png)
Here we can see a group of events, thrown by applications from different application instances (servers). Each event has the same title and stacktrace, with different tags and messages.

I would like to know which servers sent the last 100 events, or how many events, and from where (specific tag), were sent between two dates. 

Would it be possible, when clicking on a tag in group view, to only get events with that tag from that group. Maybe creating a new page for searching events in the specified group, with tag and date filters?

**Comment by jaysoffian** [comment]
+1

**Comment by SlKelevro** [comment]
Can't imagine why would someone need tags without filtering. +10

**Comment by dcramer** [comment]
@SlKelevro you can already filter the stream by tags. This ticket is about searching the sampled events, which is misleading since in many cases the event you're searching for isn't stored.

We plan to address this in the future, but until we can safely store every event (or at least do something more clever than we do today), it's not the most useful thing in the world.

**Comment by simon-weber** [comment]
> until we can safely store every event...it's not the most useful thing in the world.

For what it's worth, I think even limiting this functionality to finding the first stored event in an aggregate would be a huge improvement.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
