### ISSUE TITLE
Can't setup github enterprise integration on a sentry 9.1.0

### ISSUE THREAD

**Issue by yufuluo** [getsentry/sentry#12765]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Other [k8s container installed by helm chart, version 9.1.0]

## Description

Tried to setup GitHub Enterprise integration, the app shows installed in GHE, but shows `Not Installed` in Sentry `/settings/sentry/integrations/`

## Steps to Reproduce

Following this guide:
https://docs.sentry.io/workflow/integrations/global-integrations/github-enterprise/

1. Add new GitHub App on GHE
2. Register a new GitHub App on GHE
3. Install GHE App in sentry (click Add Installation and fill all the settings, then it jumps to GHE and says app installed. But GitHub Enterprise still shows `Not Installed` in `/settings/sentry/integrations/`)

Restart the container and logs shows:
`21:45:58 [INFO] sentry.plugins.github: apps-not-configured
WSGI app 0 (mountpoint='') ready in 10 seconds on interpreter 0x563f2738ca60 pid: 24 (default app)`

### What you expected to happen

Be redirected back to Sentry and see GHE installed in `/settings/sentry/integrations/`

### Possible Solution

Is there a way to set this up with variables in `config.yml`?

**Comment by zetaab** [comment]
I think the problem is that what is the correct value for callback URL? https://docs.sentry.io/workflow/integrations/global-integrations/#github-enterprise says that the url should be `https://sentry.io/extensions/github-enterprise/setup/`. However, if I try url `https://own.sentry.local/extensions/github-enterprise/setup/` It says 404 not found. So what is correct callback url for on-premise sentry installations?

**Comment by zetaab** [comment]
in my opinion this GHE cannot even work (yet?). https://github.com/getsentry/sentry/blob/master/src/sentry/identity/github_enterprise/provider.py#L29 this is missing things here. 

@MaxBittker as you are original author of PR https://github.com/getsentry/sentry/pull/8348 could you instruct how to use this GHE integration? At least I cannot get it working. My callback url from GHE APP is `http://localsentry/extensions/github-enterprise/setup/` and the GHE will redirect to `http://sentry.local/extensions/github-enterprise/setup/?application_id=xx&setup_action=install` but that page will crash? or something. I am getting just 503 error code back from loadbalancer. I cannot see anything in logs where it will crash. Could you please tell us what is needed to get this working? If there is code missing could you say where this code is missing, because I cannot get any log rows through because its crashing.

**Comment by zetaab** [comment]
@benvinegar @mattrobenolt seems that max is not working anymore for sentry, so I will ping you as well. What is status of GHE. See post above ^

**Comment by BYK** [comment]
@zetaab no one is actively working on this. If you have a GHE instance available, would you like to give this a shot? You can use this branch to get a local Sentry installation working for you for testing from latest master or any SHA you may have locally: https://github.com/getsentry/onpremise/pull/220

**Comment by zetaab** [comment]
Ok we take that item to backlog, we will try it

**Comment by zetaab** [comment]
@BYK I am now running Sentry 10.1.0.dev029f8169 but I cannot get this working
