### ISSUE TITLE
Allow linking a single repo to a project

### ISSUE THREAD

**Issue by trondhindenes** [getsentry/sentry#12906]
## Summary
We h ave multiple groups in Gitlab, which forces us to have multiple instances of the gitlab integration configured. This causes the following in the Issue ui:   
![Screenshot from 2019-04-24 17-17-08](https://user-images.githubusercontent.com/1747120/56671470-fe69be00-66b4-11e9-962d-f93ba97ac3f4.png)

It would be good if a repo could be linked to a project, so that it was the only "issue link" showing up. Furthermore it would allow git repo "activations" to be moved from the "org setting" down to each project, which makes much more sense IMHO.

## Motivation
Sentry's notion of what's global and what's project-local is strange, and causes weird side effects.

**Comment by Jean85** [comment]
As said in https://github.com/getsentry/sentry/issues/12774#issuecomment-529957156, I have the same issue. I want to restrict this integration or vice versa enable "see all repos", to avoid having 40+ "Link GitLab Issue" on every event. Is it even possible to disable GitLab issues on a per-project basis? It would be enough for me since I do not use this, I just want the commit references.

**Comment by markstory** [comment]
>  Is it even possible to disable GitLab issues on a per-project basis? 

It is not possible to do that currently.

**Comment by Rush** [comment]
It's unfortunate. It seems the feature to link repos is much less useful than it could be,.

**Comment by BYK** [comment]
@scefali @MeredithAnya @manuzope - Is this something that can be done fairly easily or does it require significant refactoring?
