### ISSUE TITLE
Any updates on Python 3 support status? Python 2 EOL is imminent.

### ISSUE THREAD

**Issue by madnight** [getsentry/sentry#12943]
It would be nice to allow an open community discussion about this (in my opinion very serious) issue and not close/silence it immediately with maintainer override forces. Thanks in advance!

**Comment by untitaker** [comment]
What's the purpose of this ticket? What do you want to discuss? From our side very little has changed since the last two tickets (https://github.com/getsentry/sentry/issues/1152 and https://github.com/getsentry/sentry/issues/8806).

**Comment by madnight** [comment]
"From our side very little has changed since" 

okay but i'm interested in other viewpoints, this repository has 383 contributors

**Comment by untitaker** [comment]
I am asking if there's anything new to discuss. If there is, of course opening a ticket makes sense. But opening a ticket just because you didn't like that the other one is locked is puzzling to me. It seems like a magnet for drive-by commentary like the previous ones, such as "project management is blind" or "upgrade or RIP".

People who want to raise a new point that has not been brought up before are capable of opening a new ticket themselves. I doubt this will happen though.

**Comment by madnight** [comment]
> People who want to raise a new point that has not been brought up before are capable of opening a new ticket themselves. I doubt this will happen though.

Ah okay, other projects allow (somtimes quiet lengthy) discussions in their Issues, where people can raise new points as a post to an existing Issue, rather than new Issues for each new view point. That's why i got confused.

**Comment by madnight** [comment]
Update: 

>  We’re going to be off of Python 2 by the end of the year ...

https://blog.sentry.io/2019/05/14/sentry-9-1-and-upcoming-changes

This resolves my Issue and all similar eralier Issues about that topic, thanks.
