### ISSUE TITLE
What are the metrics names that pushed to metrics backend?

### ISSUE THREAD

**Issue by minhdanh** [getsentry/sentry#13119]
I have enabled internal metrics with statsd backend (it's a telegraf container).
But I'm not so sure if it works when looking at the metrics I have from telegraf:

```
wget localhost:9273/metrics -O -| grep sentry
Connecting to localhost:9273 (127.0.0.1:9273)
# nothing
```
```
Connecting to localhost:9273 (127.0.0.1:9273)
internal_gather_gather_time_ns{input="statsd"} 17438
internal_gather_metrics_gathered{input="statsd"} 1
# HELP internal_statsd_tcp_bytes_received Telegraf collected metric
# TYPE internal_statsd_tcp_bytes_received untyped
internal_statsd_tcp_bytes_received{address=":9125"} 0
# HELP internal_statsd_tcp_current_connections Telegraf collected metric
# TYPE internal_statsd_tcp_current_connections untyped
internal_statsd_tcp_current_connections{address=":9125"} 0
# HELP internal_statsd_tcp_max_connections Telegraf collected metric
# TYPE internal_statsd_tcp_max_connections untyped
internal_statsd_tcp_max_connections{address=":9125"} 250
# HELP internal_statsd_tcp_packets_received Telegraf collected metric
# TYPE internal_statsd_tcp_packets_received untyped
internal_statsd_tcp_packets_received{address=":9125"} 0
# HELP internal_statsd_tcp_total_connections Telegraf collected metric
# TYPE internal_statsd_tcp_total_connections untyped
internal_statsd_tcp_total_connections{address=":9125"} 0
```

There're several metrics names that have `statsd`.
Does that means the internal metrics integration work or not?

**Comment by minhdanh** [comment]
@tkaemming @mattrobenolt @ckj Can someone help answer this?

**Comment by mattrobenolt** [comment]
There are hundreds and hundreds of metrics. What do you wanna know? You can look anywhere int he codebase for `metrics.incr` and `metrics.timing` to get a sense of what they are.

**Comment by mattrobenolt** [comment]
Also, we don't personally use the statsd backend because we use datadog, so it's possible we broke it somehow. Unlikely, but it's definitely a path we don't really test.

**Comment by Dizzydaizys** [comment]
Sent from my MetroPCS 4G LTE Android Device
-------- Original message --------From: Matt Robenolt <notifications@github.com> Date: 5/13/19  10:37 PM  (GMT-05:00) To: getsentry/sentry <sentry@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [getsentry/sentry] What are the metrics names that pushed to metrics backend? (#13119) There are hundreds and hundreds of metrics. What do you wanna know? You can look anywhere int he codebase for metrics.incr and metrics.timing to get a sense of what they are.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/getsentry/sentry/issues/13119?email_source=notifications\u0026email_token=AISUNRHYXDTWNOAEZLZ6V3LPVIQWHA5CNFSM4HLODVEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVKC4ZI#issuecomment-492056165",
"url": "https://github.com/getsentry/sentry/issues/13119?email_source=notifications\u0026email_token=AISUNRHYXDTWNOAEZLZ6V3LPVIQWHA5CNFSM4HLODVEKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVKC4ZI#issuecomment-492056165",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by minhdanh** [comment]
Looking at the code of `metrics.incr` and `metrics.timing`:
https://github.com/getsentry/sentry/blob/d292fd4680274bf638ffb73fa5584593bd0642f7/src/sentry/metrics/statsd.py
https://github.com/getsentry/sentry/blob/8be33e3baa990442dcfc836473c3c8d81ecfe7ec/src/sentry/utils/metrics.py#L89
I'm still unsure which metrics are pushed to statsd.
Looking at the metrics that telegraf collects it looks like the integration doesn't work, as I don't see any metrics that has `sentry` in its name.

**Comment by minhdanh** [comment]
Also are the metrics pushed from web or worker or cron process?

**Comment by markstory** [comment]
@minhdanh All 3 process types send metrics.

**Comment by dcramer** [comment]
Please use the forums for general questions. The issue tracker is reserved for accepted bug reports.

https://forum.sentry.io

**Comment by minhdanh** [comment]
Update: it was my fault. The sentry processes could not reach telegraf's statsd port.
I fixed that and could see the metrics:

```
sentry_buffer_pending_size_count{metric_type="timing"} 1
sentry_buffer_pending_size_lower{metric_type="timing"} 0
sentry_buffer_pending_size_mean{metric_type="timing"} 0
sentry_buffer_pending_size_stddev{metric_type="timing"} 0
sentry_buffer_pending_size_sum{metric_type="timing"} 0
sentry_buffer_pending_size_upper{metric_type="timing"} 0
sentry_jobs_all_dispatched{metric_type="counter"} 2
sentry_jobs_all_finished{metric_type="counter"} 2
sentry_jobs_all_started{metric_type="counter"} 2
sentry_jobs_delay_count{metric_type="timing"} 2
sentry_jobs_delay_lower{metric_type="timing"} 0
sentry_jobs_delay_mean{metric_type="timing"} 0
sentry_jobs_delay_stddev{metric_type="timing"} 0
sentry_jobs_delay_sum{metric_type="timing"} 0
sentry_jobs_delay_upper{metric_type="timing"} 0
sentry_jobs_dispatched{metric_type="counter"} 2
sentry_jobs_duration_count{metric_type="timing"} 2
sentry_jobs_duration_lower{metric_type="timing"} 0
sentry_jobs_duration_mean{metric_type="timing"} 0
sentry_jobs_duration_stddev{metric_type="timing"} 0
sentry_jobs_duration_sum{metric_type="timing"} 0
sentry_jobs_duration_upper{metric_type="timing"} 0
sentry_jobs_finished{metric_type="counter"} 2
sentry_jobs_memory_change_count{metric_type="timing"} 2
sentry_jobs_memory_change_lower{metric_type="timing"} 0
sentry_jobs_memory_change_mean{metric_type="timing"} 0
sentry_jobs_memory_change_stddev{metric_type="timing"} 0
sentry_jobs_memory_change_sum{metric_type="timing"} 0
sentry_jobs_memory_change_upper{metric_type="timing"} 0
sentry_jobs_started{metric_type="counter"} 2
sentry_response{metric_type="counter"} 8
sentry_view_duration_count{metric_type="timing"} 7
sentry_view_duration_lower{metric_type="timing"} 80
sentry_view_duration_mean{metric_type="timing"} 120.85714285714286
sentry_view_duration_stddev{metric_type="timing"} 47.5347348831164
sentry_view_duration_sum{metric_type="timing"} 846
sentry_view_duration_upper{metric_type="timing"} 233
sentry_view_response{metric_type="counter"} 7
```
