### ISSUE TITLE
Slack integration link does not contain environment

### ISSUE THREAD

**Issue by tylermarien** [getsentry/sentry#13458]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
When an issue is sent to Slack, the Slack message contains a link to the issue on Sentry. This link does not contain a reference to the environment (eg. https://sentry.io/organizations/[organization-name]/issues/[issue-number]/?referrer=slack). When you click on the link, it takes you to Sentry but redirects you to the last selected environment (eg. https://sentry.io/organizations/[organization-name]/issues/[issue-number]/?environment=[last-selected-environment]&project=[project-id]&referrer=slack). If the issue does not exist in the last selected environment, then you get an error page.

![Screen Shot 2019-05-29 at 2 05 12 PM](https://user-images.githubusercontent.com/897223/58587496-cc4efd00-821a-11e9-8a49-427d8aedb061.png)

## Steps to Reproduce

1. Connect Slack integration
2. When issue is pushed to Slack, click on Slack link.

If your last selected environment does not contain the issue, you will get the error page.

### What you expected to happen

Expected to see a page with the issue/event details.

### Possible Solution

Add the environment to links pushed to Slack integration (eg. https://sentry.io/organizations/[organization-name]/issues/[issue-number]/?environment=[last-selected-environment]&referrer=slack). I have confirmed that this link will show the appropriate page.

**Comment by SomniumDigital** [comment]
I actually raised a support ticket regarding this a week or two ago which I am on the process of following up on. Up until we realised that this was a problem we actually missed issues in our production environment because the issue did not exist in the last selected environment as you mention.

If I get any news via the support ticket I'll update you here.

**Comment by BYK** [comment]
Ping @EvanPurkhiser

**Comment by ryanshuya** [comment]
Affecting me too. Status update?

**Comment by manuzope** [comment]
Hey @ryanshuya, this issue was resolved at the end of June (we just didn't end up closing the issue). However, maybe it's reappeared. Would you mind filing a ticket with our support reps (`left nav -> Help -> Contact Support`) with your org and a video of you running into this issue? It'll greatly help us debug this issue.

**Comment by manuzope** [comment]
Closing this issue cause the underlying problem has been fixed.
