### ISSUE TITLE
Filter SIGPIPE crashes in-app

### ISSUE THREAD

**Issue by garvankeeley** [getsentry/sentry#13642]
Our app sends thousands of SIGPIPEs reported as crashes. 
Is there a way to filter these on the app-side to stop this from being sent?

**Comment by BYK** [comment]
Hi @garvankeeley - this seems more like a question rather than an issue with Sentry itself so I'm going to refer you to our community forums and close this issue: https://forum.sentry.io/

Feel free to posting your question there with as many details as possible. For instance stating which programming language and SDK you are using, whether you are using sentry.io or a self-hosted version of Sentry along with the version would be very valuable for people to help you.
