### ISSUE TITLE
GroupMeta doesn't have a fallback mechanism if the cache is empty

### ISSUE THREAD

**Issue by rogerhu** [getsentry/sentry#1368]
This commit started relying on caching GroupMeta. https://github.com/getsentry/sentry/commit/7640827ee4733d23353eeff400c57eb814654d68

Our auto-filing Sentry plugin started creating multiple tickets for the same event because the cache is not populated on multiple workers.  A workaround was done to populate this cache, which sort of defeats the whole purpose of this caching approach.

https://github.com/hearsaycorp/sentry-jira/pull/6

**Comment by rogerhu** [comment]
Also, I'm not seeing events being tallied anymore.  Part of me thinks this commit should be reverted.

**Comment by dcramer** [comment]
We're definitely not reverting this behavior. The objects should be cached before referenced. This was needed due to some fairly inefficient patterns that end up in plugins where installs were doing far too much for simple operations.

This wouldn't be related to counts either as GroupMeta is purely used by plugins.

That said we could be more intelligent about where we populate the cache. The "auto create ticket" workflow isn't natively supported by us, which I think is the better answer here. It'll ensure that any plugins that use this maintain the same efficient sql behavior as well as a common solution to this common implementation.

**Comment by dcramer** [comment]
@rogerhu does the above seem like a reasonable enough short-term solution to the problem?

**Comment by rogerhu** [comment]
It turned out to be the branch I had wasn't tracking for is_new calls and creating dup tickets...(see https://github.com/hearsaycorp/sentry-jira/compare/0.8.2...master).  The GroupMeta.objects.get_value() call in was simply masking this problem since it would prevent duplicate tickets from created if an accompanying ticket was created.

The counts was related to https://github.com/getsentry/sentry/issues/1369, which we resolved by adding celerybeat to the list.

I think we can close this ticket...I do agree that there should be something about populating the cache.  If a cache hasn't populated, does it make sense to even call get_value()?

**Comment by dcramer** [comment]
Yeah I'm still +1 on causing this to error with a descriptive message, as its definitely a code error. That said there's likely still places we can automate cache population for users, as we want to avoid the need for someone to call it manually.

Basically we're trying to avoid the "I have 6 plugins enabled and each of them hit the db for the same info" situation.

I'll close this since the original issue is resolved.
