### ISSUE TITLE
SASL & SSL Support for kafka config

### ISSUE THREAD

**Issue by bountyx** [getsentry/sentry#14123]
## Summary

Kafka and Zookeper support encryption and authentication as part of their standard setup, but these configuration options are not available as environment variables in Sentry's KAFKA_CLUSTERS config option or as environment variables to Snuba.

## Motivation

Securing data in transit adds an additional layer of security and compliance for sentry.

## Additional Context

I propose adding  security_protocol, sasl_username, sasl_password and sasl_mechanisms to implementations of KAFKA consumer and producer methods and exposing those options consistently to Sentry, Snuba and related applications.

**Comment by bountyx** [comment]
I think batching-kafka-consumer project may need to be updated too.

**Comment by hexa2k9** [comment]
This would indeed be super useful (and basically required) to make use of e.g. Confluent Cloud to offload Zookeeper & Kafka Hosting in Sentry On Premise.

**Comment by BYK** [comment]
Hi @hexa2k9 and @bountyx - we provide full config customization support for Sentry over at [getsentry/onpremise](https://github.com/getsentry/onpremise) and trying to stay away from environment variable based configuration (as it is not practical to support all of these with rich data types python and yaml offers without some non-trivial serialization/deserialization).

Is this solution not enough for you to get going?

**Comment by alexef** [comment]
@BYK I believe the problem is not that the kafka cannot be configured. In particular cases, the kafka configuration is not passed along consistently in client classes, for instance here: https://github.com/getsentry/sentry/blob/d46213a3cb4fea1653724ac58bcd78e32a3dda05/src/sentry/eventstream/kafka/backend.py#L87

I can give it a shot as I'm already working on security/sasl support in snuba.
