### ISSUE TITLE
Slack integration still not working on 9.1.2

### ISSUE THREAD

**Issue by trondhindenes** [getsentry/sentry#14179]
## Important Details
* [x] On-Premise docker [Version 9.1.2] (custom docker image)

## Description
We tried re-enabling the Sentry integration after upgrading to 9.1.2, but I'm just getting "OAuth Error: Please specify `client_id`" when trying to add a workspace. I can't see any official documentation for how to configure Slack when self-hosting, so I'm a bit unsure how to proceed. My impression was that with 9.1.2 one wouldn't have to go thru all of the steps to configure things "manually" (manually configure slack app etc). I can't find any documentation specific to 9.1.2 or higher, so it's all in a bit of limbo. Some clarification from the Sentry team on what the experience should be would be beneficial.

## Steps to Reproduce
Clicked "Add workspace" in the global Slack integration under settings. The oauth error comes from Slack.

### What you expected to happen
I was hoping it would work.

**Comment by silvez-dh** [comment]
Btw, following this tutorial worked (was totally manual process because of this error on 9.1.2 version): https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463

**Comment by trondhindenes** [comment]
ok thanks. I was under the impression that 9.1.2 contained an overhaul to the slack integration, but I may have been wrong. In any case, the steps for setting up the integration seems to be the same regardless of whether or not the instance is running 9.1.2 (or newer). Thanks for clarifying.

**Comment by EvanPurkhiser** [comment]
As @silvez-dh has mentioned, you will still need to follow the manual slack setup instructions.

> I was under the impression that 9.1.2 contained an overhaul to the slack integration

It only contains this fix https://github.com/getsentry/sentry/pull/13184 (and a few other minor changes). But this was the critical one as slack removed the ability to create workspace apps.

Unfortunately there is no "template" app for slack, you will still manually have to create the app. This is due to the nature of onpremise, if we were to provide our own app used by onpremise users, it would have to talk to the sentry.io backend and then communicate back to your onpremise instance, which defeats one of the primary reasons to use on premise.

**Comment by trondhindenes** [comment]
gotcha @EvanPurkhiser, thanks for clarifying.
