### ISSUE TITLE
install by python source,but failed

### ISSUE THREAD

**Issue by violetgo** [getsentry/sentry#14176]
I tried to use the steps of this page(https://docs.sentry.io/server/installation/python/) to install sentry with source code:

```
You can also use pip to directly install the package from GitHub:

$ pip install -e git+https://github.com/getsentry/sentry.git@master#egg=sentry-dev
```

but got some error like this:

```
UnsupportedPythonVersion: Package 'more-itertools' requires a different Python: 2.7.5 not in '>=3.4'
```

**Comment by BYK** [comment]
You need Python 2.7 for Sentry. I think the error message states that pretty clearly.

**Comment by jie** [comment]
still have error:
ERROR: Package 'more-itertools' requires a different Python: 2.7.15 not in '>=3.5'

we use python2.7 to install sentry-9.1.2

**Comment by BYK** [comment]
@jie - Sentry does not depend on `more-itertools`: https://github.com/getsentry/sentry/blob/9.1.2/requirements-base.txt

This must be coming from somewhere else.

**Comment by jie** [comment]
@BYK 
more-itertools is required by pytest.

I fixed it by install pip8.x.x to install sentry instead of the latest pip.

thanks

**Comment by BYK** [comment]
@jie - I expected us to freeze the version of that sub-dependency in our requirements file, my apologies. `pip` 19.3 should be good but we only tested it with latest master (aka Sentry 10) so cannot guarantee and from what you say, apparently it is broken. Hopefully Sentry 10 will be out very soon.

Btw. would you mind sharing why you prefer installing from `pip` from source instead of the wheel or the Docker-based installation?

**Comment by jie** [comment]
@BYK 
Docker is great. But we have not import docker architecture to our system and we are not familiar with docker.
