### ISSUE TITLE
Upgrade Error 7.2.0 -> 7.4.1

### ISSUE THREAD

**Issue by maggo2801** [getsentry/sentry#1457]
After sentry --config=/etc/sentry.conf.py upgrade I get the following exception.

FATAL ERROR - The following SQL query failed: ALTER TABLE `sentry_apikey` ADD CONSTRAINT `organization_id_refs_id_961ec303` FOREIGN KEY (`organization_id`) REFERENCES `sentry_organization` (`id`);
The error was: (1005, "Can't create table 'sentry.#sql-483_fd8' (errno: 150)")

**Comment by dcramer** [comment]
Honestly, I dont have a clue. I would suggest using Postgres. If someone else finds the solution we'll happily fix this, but there are far too many issues with MySQL/Django and quite frankly I simply don't care to try and fix them anymore.

**Comment by derenix** [comment]
Due to MySQL foreign key checks, both fields needs to be of the same type. In my installation (7.1.4) `sentry_organization.id` is a `INT(11)` while `sentry_apikey.organization_id` is created as `BIGINT(20)`.

Dropping the `sentry_apikey` table and setting `SENTRY_USE_BIG_INTS = False` in my `sentry.conf.py` worked for me.

**Comment by maggo2801** [comment]
Thx, it works for me too.

**Comment by davewongillies** [comment]
This didn't work for me :(

**Comment by davewongillies** [comment]
This didn't work for me :cry:
