### ISSUE TITLE
GitLab Complete Integration

### ISSUE THREAD

**Issue by matthewpull** [getsentry/sentry#14799]
## Summary

Currently (unless my understanding is incorrect, in which case apologies!) it is only possible to create a GitLab integration at a group (or sub-group) level, regardless of if the integration is with GitLab.com or a self-hosted instance. With the GitHub Enterprise integration, it is possible to setup Sentry across the entire self-hosted instance - I would like this to be possible with GitLab as well.

## Motivation

I would imagine that it is common for an organisation to have both a Sentry account and a self-hosted GitLab instance, and want the Sentry account to integrate with all of the repos across the entire self-hosted GitLab instance. This is already possible (again, unless I have misunderstood) with the GitHub Enterprise integration, but not with the GitLab plugin. I assume that the GitLab plugin was originally designed for just GitLab.com support, whereas with GitHub there are two plugins, for GitHub.com and for GitHub Enterprise.

**Comment by markstory** [comment]
One reason that the gitlab integration is scoped to a group is that up until recently GitLab didn't have search APIs that allowed nested groups to be queried. This made searching repositories to add in sentry much harder.

The GitHub integrations both bind to a single organization at a time, however they differ in that github.com uses a sentry controlled github application, while github-enterprise requires you to setup your own github-app.

**Comment by matthewpull** [comment]
Ah I see, thanks for that detailed response, I wasn't aware of the specifics of how the integrations operated. That being said, I still think that it would be useful to have a GitLab instance-wide installation. I certainly want it on my entire setup and I have to think that I'm not the only one who could benefit from it.

This definitely isn't a high priority ticket, but I do think that it would be very useful to those who do indeed run their own GitLab infrastructure.

Thanks :)

**Comment by Venus713** [comment]
Hi @markstory 
By my understanding, the reason of this issue is to add a function to integrate Sentry account  with all of the repos across the entire self-hosted GitLab instance since currently the gitlab integration is scoped to a group.
In the above, you mentioned that GitLab didn't have search APIs that allowed nested groups to be queried. 
But as far as I concerned, we can get all repositories with Gitlab api.
let me see following api:
```
curl --header "PRIVATE-TOKEN: XXXXXX" "https://gitlab.com/api/v4/projects"
```
That would return all projects that are visible to you, including other user's public projects.
And If I wish to view just my projects, then you should use the GET /users/:user_id/projects endpoint.
Then, I think it would be implemented the completed gitlab integration, what about you?

**Comment by markstory** [comment]
> That would return all projects that are visible to you, including other user's public projects.
And If I wish to view just my projects, then you should use the GET /users/:user_id/projects endpoint.
Then, I think it would be implemented the completed gitlab integration, what about you?

The current GitLab integration doesn't operate on user accounts though. We now include the `include_subgroups` flag on the group projects API so we can traverse into subgroups. I'm not familiar with the /projects endpoint enough to know if it also traverses all the subgroups.

**Comment by Venus713** [comment]
Hi @markstory 
By checking previous issues and comments, as you can see in https://github.com/getsentry/sentry/pull/15188, this problem was mentioned earlier by @kinghuang , and He has been created a PR for that.
But the PR is still blocked. I'm not sure why is it. If that is unnecessary or now not available yet, then why does this issue still exist?

**Comment by Venus713** [comment]
Hi @markstory 
You can check out the api endpoint in the following doc.
https://docs.gitlab.com/ce/api/projects.html#list-all-projects
And as you can see in #15188, this problem was mentioned earlier by @kinghuang , and it has been created a PR for that by him.
I really think that is pretty correct, but I'm not sure why it is still blocked.
So I wonder if the function is unnecessary, and if so, then why does this issue still exist?
Would you explain about that?

**Comment by Venus713** [comment]
Hi Mark Story,

Would you take a look at my Comment posted in #15188
<https://github.com/getsentry/sentry/pull/15188> ?

Best,

Li

**Comment by BYK** [comment]
@manuzope @philipphofmann ping for triage

**Comment by manuzope** [comment]
Hi all! Seems like a valuable add. It's in our backlog but we're unlikely to get to it soon. 

If someone wants to pick up https://github.com/getsentry/sentry/pull/15188 and help it over the line (rebase + clear up code review comments), we'd accept that but we don't have the bandwidth to do that right away.

**Comment by ceorourke** [comment]
Fixed in https://github.com/getsentry/sentry/pull/31375
