### ISSUE TITLE
400 BAD REQUEST User Feedback

### ISSUE THREAD

**Issue by udahari** [getsentry/sentry#15310]
## Important Details

How are you running Sentry?
- Saas (sentry.io)

## Description

400 BAD REQUEST

## Steps to Reproduce

url : `https://sentry.io/api/0/projects/organization/projectname/user-feedback/`
headers : 
`Content-Type: application/json`
`Authorization: Bearer  authToken`
body :
`{"comments":"aaa","email":"hari@xxx.co","event_id": "123xxx","name":"Hari"}`
response :  `"Invalid origin: https://deploy-preview-1223--xxxxxii-xxxxx.netlify.com/"`

### What you expected to happen
200 success

**Comment by udahari** [comment]
i have allowed all domains *
![PixelSnap 2019-10-29 at 14 46 46](https://user-images.githubusercontent.com/14860018/67747280-f5d6b380-fa5a-11e9-9d04-2b6582ded10b.png)

**Comment by udahari** [comment]
![PixelSnap 2019-10-29 at 15 26 19](https://user-images.githubusercontent.com/14860018/67749810-7d72f100-fa60-11e9-9132-6278f755d843.png)

i got success in report issue but 400 bad request in user feedback

**Comment by heartbeatLV** [comment]
same

**Comment by lelvisl** [comment]
Any updates?

**Comment by mattcheah** [comment]
Don't know if this will help anyone but in order to make this work for me, I had to go to: 
Settings > Developer Settings > Internal Integrations > New Internal Integration
Fill out Name and Authorized JavaScript Origins with each domain you're planning on using (Localhost works, I don't think `*` was allowed)
I just gave Admin access for all permissions dropdowns even though I'm sure that isn't wise. 
Save, and use the token that is generated at the bottom of the page. 

I have no idea if this is the right way to do things but that's just the way I got this to work after running into the "Invalid Origin" error.

**Comment by BYK** [comment]
This sounds similar to #19632.

**Comment by backent** [comment]
> Don't know if this will help anyone but in order to make this work for me, I had to go to:
> Settings > Developer Settings > Internal Integrations > New Internal Integration
> Fill out Name and Authorized JavaScript Origins with each domain you're planning on using (Localhost works, I don't think `*` was allowed)
> I just gave Admin access for all permissions dropdowns even though I'm sure that isn't wise.
> Save, and use the token that is generated at the bottom of the page.
> 
> I have no idea if this is the right way to do things but that's just the way I got this to work after running into the "Invalid Origin" error.

It works, thanks

**Comment by HazAT** [comment]
I think this is more or less resolved, feel free to comment if you feel like it isn't
