### ISSUE TITLE
Support "all environments, except for..." filters in alert rules

### ISSUE THREAD

**Issue by tabascoterrier** [getsentry/sentry#15799]
## Summary

Provide the ability for alert rules to be invoked on "all environments, except for..."

## Motivation
Alerts for all of our environments to go into a Slack channel, except for a couple of development environments which are notifying users directly.

At the moment the solution is to explicitly create rules for every environment, and while this isn't a huge effort, it does mean that if somebody starts using a new environment string but forgets to create an alert rule for it, no alerts will be raised.

Having a negation filter ("all environments excluding dev-env-x, dev-env-y") would make that easier to set up and remove the possibility of missing things.

**Comment by AvnerCohen** [comment]
I might be wrong, and I really hope I am not hijacking something here.
I think the issue is the complexity or advanced level of Alert Rules.
While I can set multiple conditions, The relation between them can only be "AND" or "OR".

I suspect this is a solved issue, many solutions allows setting up more complex conditions in a flexible way and I suspect that this will be very helpful to reduce alert fatigue.
