### ISSUE TITLE
Is there will be any security issue if I put my DSN Client key (public key) in Public ? 

### ISSUE THREAD

**Issue by ethicalbughunter** [getsentry/sentry#15877]
Hello,

Client key (public key) is intended to be public or it should be private ?

Thanks

**Comment by untitaker** [comment]
The worst thing people can do with a DSN is to send you crashreports.

**Comment by ethicalbughunter** [comment]
Thanks for the information.

 So it will create data integrity issue ?

**Comment by untitaker** [comment]
Please refer to
https://forum.sentry.io/t/how-does-sentry-prevent-spammers/8188

**Comment by ethicalbughunter** [comment]
There must be a restriction otherwise anyone can able to use the DSN and send crashreports

**Comment by untitaker** [comment]
There is none and as explained in the thread it is not a solvable problem, and it affects many services. Don't make it easily accessible, that's all I can tell you.

**Comment by ethicalbughunter** [comment]
Thanks for the information,

from the thread,

>It is the same situation as with any other application identifying auth tokens. For example you can also extract oauth credentials from an official Twitter app and use them to access the Twitter API (which allows you to get much better rate limits and to pretend to be sending tweets from the official app)


it is critical security issue for them,I don't think twitter will put oauth credentials in their official Twitter app. that means anyone can gain unauthorised access to their application. 

accessing someone  else Token,APIKEY,Secret is definitely a security issue.

**Comment by untitaker** [comment]
@ethicalbughunter they 100% do, and it is not a practical problem. Please do not say security issue without going into details.

**Comment by ethicalbughunter** [comment]
like for example 

1.User A have  Twitter oauth credential which have read write permission in his app.

2.Now User B extract the User A's twitter oauth credential.

3.Now B can have access to A's twitter account now B can call all the Twitter APIs.

4.So therefore A is responsible as he put his oauth credential in the app. 

An similar example where GitHub token leaks  
https://hackerone.com/reports/396467

**Comment by untitaker** [comment]
@ethicalbughunter you are talking about user-identifying credentials while I am talking about application-identifying credentials. The first is a security issue and the second one (where Sentry DSNs fall into IMO) is a minor inconvenience.

Twitter embeds a token in their Android APK to let the app tell the server "I am the official Android app for Twitter". Since this token is inside the APK, it's possible to extract that token to make your own application look like an official one. If you're too lazy to download apktools, here is a list: https://gist.github.com/shobotch/5160017 People use this to get around rate limits, but my point is that on the technical side, Twitter can do very little against it.

To make this much simpler:

* If you have OAuth **app** credentials for Twitter, you cannot do anything. You still need to have user credentials which are entirely separate and not part of any APK.
* If you have just a Sentry DSN, you can't access or modify any data at all. You can only submit new crashreports.
* If you have a GitHub token you can do a lot of things depending on how you configured the token.

Seriously, this is not a security issue. If you say this can be used to "malform" data in Sentry, then I'd argue you can "malform" Google Analytics data by refreshing the website a bunch of times.

**Comment by ethicalbughunter** [comment]
It's not about the production of best "argument" to obliviate an important issue at hand.

please consider your statements

1.If you have OAuth app credentials for Twitter, you cannot do anything. You still need to have user credentials which are entirely separate and not part of any APK.


**from the thread** https://forum.sentry.io/t/how-does-sentry-prevent-spammers/8188
2.It is the same situation as with any other application identifying auth tokens. For example you can also extract oauth credentials from an official Twitter app and use them to access the Twitter API (which allows you to get much better rate limits and to pretend to be sending tweets from the official app) 

these are seemingly contradictory statements can you please clarify further

**Comment by BYK** [comment]
@ethicalbughunter I am locking this issue as it seems like we are going in circles here and the forums are a better medium for these kinds of discussions. Feel free to continue there.
