### ISSUE TITLE
Capturing all Frames

### ISSUE THREAD

**Issue by aryeh-looker** [getsentry/sentry#1611]
Thank you for all the wonderful hard work you have done to make Sentry such a great tool. We would like to be able to capture and view all stack frames. Does stack frame omission occur at Raven or at Sentry? What is the best way to allow this functionality? We are using the official Ruby Raven client.

Thank you kindly!
aryeh

**Comment by dcramer** [comment]
Right now we don't support this, and the server has hard limits on what it will capture.

Are you seeing cases where its losing valuable data?

**Comment by aryeh-looker** [comment]
Hi David,

I'll talk with the team about this. We are transitioning from an older system (emails with full stack traces) and while it is rare that the middle portions of big traces are important, but in theory, entire traces can sometimes be helpful, especially with a language like Ruby which can sometimes be especially dynamic.

If we want to test playing these limits for an internal build — would you have any suggestions of where to look?

In general I agree with Sentry's predilection towards omitting frames. 

One possibility: perhaps this setting could live on django.conf.settings and could have a default value if not specified in the sentry configuration file. I understand that there may be more nuanced ways in which Sentry is configured and this would not be the right place. I also understand if you are trying to cut down on the number of settings. It's great how simple it was to set up Sentry — and having relatively few settings certainly helps to enable that.

kindest regards,
aryeh

**Comment by dcramer** [comment]
We definitely could make it configurable on the server.

The primary issue just comes down to storage and general render performance. The storage concern we have solutions forthcoming, and I'm sure render performance is resolvable.

**Comment by aryeh-looker** [comment]
@dcramer sounds great! I did notice, however — perhaps it is just a matter of setting `SENTRY_MAX_STACKTRACE_FRAMES` in the sentry configuration file? Performance issues aside — perhaps this is not good enough because changes to front-end are necessary? 

Thank you kindly for your help and consideration!

https://github.com/getsentry/sentry/blob/aec96d0f00db66466775d6e1e6ed377cda4219b0/src/sentry/conf/server.py

**Comment by dcramer** [comment]
Actually that probably works. These days I don't remember what we have as settings and what are constants. 






On Fri, Jul 17, 2015 at 1:31 PM -0700, "aryeh-looker" <notifications@github.com> wrote:












@dcramer sounds great! I did notice, however — perhaps it is just a matter of setting SENTRY_MAX_STACKTRACE_FRAMES in the sentry configuration file? Performance issues aside — perhaps this is not good enough because changes to front-end are necessary? 



Thank you kindly for your help and consideration!



https://github.com/getsentry/sentry/blob/aec96d0f00db66466775d6e1e6ed377cda4219b0/src/sentry/conf/server.py
