### ISSUE TITLE
Expand Plugin v2 API

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1628]
- [ ] Plugins should be passed configured options upon instantiation
  (This will make it easier to implement "Test Configuration" type behavior)
- [ ] Things like get_rules need to be more dynamic. For example, the Slack integration should be able to define a rule to say "Post to Slack Channel". However, that rule should not show up unless Slack is configured for the project.

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry-slack/issues/17
https://github.com/getsentry/sentry-slack/pull/15

**Comment by dcramer** [comment]
Considering if we need to split off project-specific bits from the core API.

We have things like Notifier which in theory could be where we inject options so it solves one bit behavior. For rules we could simply add a conditional to expand its available API to allow what we need. Either on the Rule class itself, or on the get_rules call.

**Comment by Surgo** [comment]
:+1:

**Comment by dmclain** [comment]
I was sitting down to update getsentry/sentry-slack#15 and it seemed like there were two approaches to the problem of per project rules

1. **More options to `get_rules`**: This approach takes the currently global rules registry and makes it per-project. Also, this means that plugins are ultimately the ones who decide whether a rule should be active for a given project, which isn't unresaonable since the code to determine if the plugin is installed and configured is there too.
2. **Add to the API for `sentry.rules.base.RuleBase`** This approach leaves the registry as implemented, but relies on consumers of it to know that they need to do something different than just iterate over it. I would envision that https://github.com/getsentry/sentry/blob/master/src/sentry/web/frontend/project_rule_edit.py#L28 could be rewritten to be something like:
```
for rule_type, rule_cls in rules.filter(project=project, user=request.user):
```
and then the rule registry would have something like:
```
class RuleRegistry(object):
    ...
    def filter(self, project=None, user=None, **kwargs):
        for rule_type, rule in self:
            if rule.is_valid(project=project, user=user, **kwargs):
                yield rule_type, rule
```
sentry-slack can then have an action like so:
```
from sentry.plugins import plugins

class NotifySlackRoomAction(EventAction):
    ...
    def is_valid(project=project, user=user, **kwargs):
        plugin = plugins.get('slack')
        return plugin.is_enabled(project) and plugin.is_configured(project)
```

The upside of 2 is that the rule registry doesn't need to undergo a large refactoring, and the user impact of any missed iteration that needs to be filtered is relatively low. By passing the user through we can also get rules that can only be configured by owners/admins.

**Comment by dcramer** [comment]
closing this out in favor of future integrations framework
