### ISSUE TITLE
Release stream's should provide link to view more results (in full stream)

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1640]

**Comment by ckj** [comment]
I had a difficult time figuring out where to put these. This default alert style was the best thing I could come up with:

<img width="1262" alt="screen shot 2015-08-17 at 7 46 27 pm" src="https://cloud.githubusercontent.com/assets/30713/9319169/6b4db902-4519-11e5-99c4-7446ebe1da6d.png">

@dcramer Gonna assign to you so that you can actually point them to the stream w/ the proper query.
