### ISSUE TITLE
[Feature] Integration with recently launched Zeit Log drains

### ISSUE THREAD

**Issue by Vadorequest** [getsentry/sentry#16764]
https://zeit.co/blog/log-drains

> TL;DR The Zeit platform has released a new Log drain feature, which basically allows to forward logs from their services to another 3rd party, such as Sentry.

They've also released two open source integration with DataDog and LogDNA.
https://zeit.co/integrations?category=Logging

We use Sentry and we would love to benefit from this feature as well.  

_Maybe this isn't the best place to ask for such a feature, but I didn't know where to ask_

**Comment by manuzope** [comment]
Interesting. @Vadorequest -- how do you picture this working with Sentry?

**Comment by Vadorequest** [comment]
@manuzope I'm not quite sure to be honest. Sentry already does process "events", but not really "logs". So, I'm not sure if it's out-of-scope. But, an integration Vercel <> Sentry that allows to watch for errors and report them into Sentry automatically would be very efficient.

My current pain with Vercel is that it only shows a limited amount of logs. And they're volatile as they disappear quickly. The goal, by using Sentry, would be to capture all stuff that goes wrong and then use Sentry to redirect those issues into Slack, etc. as we do it already.

It's a bit different, but maybe not too different? It's a bit more similar to what Epsagon/Lumingo do.

**Comment by scefali** [comment]
@Vadorequest Thanks for making this issue. We've actually looked into reading logs directly from AWS CloudWatch which is effectively the same as this. It's pretty neat because you can add Sentry instrumentation without changing your code! That being said, we are working on a new SDK for Next.js that will allow us to capture errors automatically once you add a package. The one thing we are missing out there that we get with logs is the run time and memory of the lambda functions. We might be able to use this for transactions as well. We'll keep this in mind for the future if we can find a good way to use it in conjunction with the upcoming SDK.

**Comment by Vadorequest** [comment]
I don't know if that can be useful, but it might since you're targeting Next.js specifically.

I've integrated and worked with Sentry in Next.js for about a year, and made it open-source in **Next Right Now**:

- https://github.com/UnlyEd/next-right-now/blob/v2-mst-aptd-at-lcz-sty/src/utils/monitoring/sentry.ts
- https://unlyed.github.io/next-right-now/guides/monitoring/setup-sentry.html
- https://unlyed.github.io/next-right-now/concepts/monitoring

**Comment by Vadorequest** [comment]
I heard there was some stuff in the work regarding Next.js, might it be related?

Not sure if this issue should be closed @manuzope

**Comment by AbhiPrasad** [comment]
Hey folks! We just moved the Vercel Log Drain endpoint to Early Adopters. If you’re interested in being an Early Adopter, you can turn your organization’s Early Adopter status on/off in Settings > General Settings. This will affect all users in your organization and can be turned back off just as easily.

See the docs for setting up the log drain here: https://docs.sentry.io/product/drains/integration/vercel/
