### ISSUE TITLE
cd sentry-9.1.2; python2 setup.py build; Could not determine sentry version or build

### ISSUE THREAD

**Issue by patsevanton** [getsentry/sentry#17234]
cat /etc/redhat-release
**CentOS Linux release 7.6.1810 (Core)**

Prepare
```
wget https://github.com/getsentry/sentry/releases/download/9.1.2/sentry-9.1.2.tar.gz
tar zxvf sentry-9.1.2.tar.gz
cd sentry-9.1.2/
/usr/bin/python2 setup.py build
```
Run /usr/bin/python2 setup.py build
```
running build
running build_integration_docs
running build_assets
pulled version information from 'sentry' module
using node (v12.16.1) and yarn (1.21.1)
pulled version information from 'sentry' module
building assets for sentry v9.1.2 (build UNKNOWN)
Could not determine sentry version or build
```

Check
```
./setup.py --version
9.1.2
```

How change setup.py for fix error?

**Comment by mattrobenolt** [comment]
I’m not sure what you’re doing or why you’re trying to do this, but pretty sure it’s because you’re building this now outside of the git repository and it wants the git sha. 

You can bypass this by setting SENTRY_BUILD environment variable. https://github.com/getsentry/sentry/blob/master/src/sentry/__init__.py#L30

**Comment by patsevanton** [comment]
I try build sentry to rpm
https://gist.github.com/patsevanton/919f994bbb8ec8e8437c8485915a1e98
