### ISSUE TITLE
Sentry 9.0.0 On-Premise docker not working with C# .NET Core 2.1 AWS Lambda project type

### ISSUE THREAD

**Issue by weare8** [getsentry/sentry#17354]
## Important Details

How are you running Sentry?

* [X ] On-Premise docker [Version 9.0.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When using C# .NET Core 2.1 and AWS Lambda project type for any function handler (DynamoDB, SQS, SNS) Sentry will not report unhandled exceptions to the dashboard. I try multiple ways to report an exception.

- Sentry.Extensions.Logging
- Configure manually (see below)
- Using SentrySdk.Init{} in code

Manual configuration.
```
private static void SetupLogger(bool isDevelopment, ILoggerFactory loggerFactory, IConfiguration configuration)
        {
            var loggerOptions = new LambdaLoggerOptions(configuration);
            loggerFactory.AddLambdaLogger(loggerOptions);
            loggerFactory.AddSentry(sentryOptions => OptionsConfiguration(sentryOptions, configuration));

            if (isDevelopment)
            {
                loggerFactory.AddConsole();
            }
        }

        private static void OptionsConfiguration(SentryLoggingOptions sentryLoggingOptions,
            IConfiguration configuration)
        {
            var sentryConfigurationOptions = configuration.GetSection("Sentry");
            sentryLoggingOptions.Dsn = sentryConfigurationOptions["Dsn"];
            sentryLoggingOptions.MinimumBreadcrumbLevel =
                sentryConfigurationOptions["MinimumBreadcrumbLevel"].ToEnum<LogLevel>();
            sentryLoggingOptions.MinimumEventLevel = sentryConfigurationOptions["MinimumEventLevel"].ToEnum<LogLevel>();
        }

Sentry SDK.
```
using (SentrySdk.Init(_appSettings.SentryDsn))
            {
                await _programEntryPoint.HandleEvent(dynamoEvent, context,
                    new CancellationTokenSource(_requestTimeoutInMilliseconds).Token);
            }
```

I have successfully used the above configuration from .NET Core 2.1 Console project type running as background daemon in Kubernetes cluster and Sentry.Extensions.Logging with ASP.NET Core 2.1 setup successfully.

I created a reproducible project where you can find attached in this bug report.

[Sentry.LambdaFunction.Issue.zip](https://github.com/getsentry/sentry/files/4263897/Sentry.LambdaFunction.Issue.zip)

```

## Steps to Reproduce **(See attached project sample)**

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration when relevant

### What you expected to happen

An exception should be logged in Sentry dashboard. `(Sentry 9.0.0 On-Premise docker)`

### Possible Solution

Not sure exactly the conflict but might have to do with ILambdaLogger and ILogger conflicting Sentry when registering the Sentry.Extensions.Logging or the AWS lambda lifecycle;

**Comment by mattrobenolt** [comment]
I don’t know, but 9.0.0 is [really old](https://github.com/getsentry/sentry/releases/tag/9.0.0). I’d suggest first to try upgrading to 10.0 and see if you have the same issues.

**Comment by weare8** [comment]
OK thanks, we will upgrade soon and will follow up if the issue is still there.

**Comment by bruno-garcia** [comment]
@weare8 I suggest creating an account on sentry.io and trying to point errors there.
If it works you know it's likely your Sentry instance.

To be honest I assume this is SDK related since nothing special is needed (no server side symbolication etc) for ASP.NET Core events.

The SDK submits events in the background and AWS lambda will often shutdown and unless you made sure to flush events, they can get lost.

If you tried on sentry.io and it didn't work, raise it in the SDK repo; https://github.com/getsentry/sentry-dotnet

**Comment by weare8** [comment]
@bruno-garcia I followed your recommendation and found the below.

When wrapping the main function code with `SentrySdk.Init` it won't report the exception, as you assume, this is related to the lambda killed immediately and the stateless model so no exception reported.

public async Task FunctionHandler(SQSEvent evnt, ILambdaContext context)
        {
            using (SentrySdk.Init("https://4716597eee934fe381677ca315e6eedc@sentry.io/3575858"))
            {
                // Will throw exception but never reach the Sentry dashboard
                throw new NotImplementedException($"thrown as new {Guid.NewGuid()}");
                 
                // It will report the exception to the dashboard since this is imeediate capture and flush I assume
                SentrySdk.CaptureException(new NotImplementedException($"thrown as new {Guid.NewGuid()}"));
            }
        } 

I guess there's a couple of ways to work around that like try/catch around the main code block and report the exception manually.

I ended up doing this, it is fine and acceptable for lambda project types.

```
public async Task FunctionHandler(SQSEvent evnt, ILambdaContext context)
        {
            using (SentrySdk.Init("URI"))
            {
                try
                {
                    throw new NotImplementedException($"thrown as new {Guid.NewGuid()}");
                }
                catch (Exception ex)
                {
                    SentrySdk.CaptureException(ex);
                }
            }
        }
```

**Comment by bruno-garcia** [comment]
Glad you figured it out. I'll actually write some docs for serverless use cases, needs such.

Just to clarify what's happening here and also for future reference:

An UnhandledException that goes unhandled is captured by the SDK but in this case, since it bubbles out of the SDK and out of your `FunctionHandler` back to AWS control, the SDK got disposed (when leaving `using`) before an exception was even captured. This pattern works on processes that have no `catch` block all the way up the stack because `AppDomain.UnhandledException` is triggerd and the SDK detects that, captures the exception and blocks the thread until flushing is complete before returning control (usually means process is shutdown at that point).

What you did works because the SDK on dispose detects there's an event in the queue and blocks the thread until submission is complete (or up to default: 2 seconds trying to finish flushing).

**Comment by xplatsolutions** [comment]
Glad I helped! Reminds me the good old days! I am ex-BugSense (acquires by Splunk) .NET SDK developer ;)
