### ISSUE TITLE
Beta - Everything is too big when window width > 1720px

### ISSUE THREAD

**Issue by Tomdarkness** [getsentry/sentry#1740]
1719px:

<img width="1831" alt="screen shot 2015-08-11 at 15 07 53" src="https://cloud.githubusercontent.com/assets/1273529/9199647/7dfffeb2-403b-11e5-9d68-0154386151fd.png">

1721px:

<img width="1833" alt="screen shot 2015-08-11 at 15 08 05" src="https://cloud.githubusercontent.com/assets/1273529/9199661/901ccd3c-403b-11e5-9571-c7ee0fe9bf93.png">

**Comment by mattrobenolt** [comment]
I brought this up internally a few days ago. Personally, I'm on the fence. It doesn't look terrible at the larger size, but it does feel a bit too big to me.

I'll let @ckj weigh in on this since it was partly an intentional decision to scale up for the larger widths. I think to fill in some of the excess whitespace and not look empty.

**Comment by ckj** [comment]
Addressed in latest release.
