### ISSUE TITLE
Long culprits visual issues

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1806]
Wrapping isnt desirable. Ideally we'd left-truncate.

https://www.dropbox.com/s/sagdm5rncxujzay/Screenshot%202015-08-19%2017.33.58.png?dl=0

**Comment by ckj** [comment]
Left truncating with ellipsis alone isn't possible in css due to a chrome bug. I can clip it without ellipsis but a hard cut off mid-letter looks kind of shitty... Maybe we should do this via js? The only other thing I can think of for now would be positioning a gradient over the left side so it fades out instead of just cutting it off.

**Comment by dcramer** [comment]
Right truncation is fine if its too complicated

**Comment by dcramer** [comment]
Closing this as we reverted two-line
