### ISSUE TITLE
How to integrate sentry issues with youtrack

### ISSUE THREAD

**Issue by tonal** [getsentry/sentry#18094]
## Summary

Need integrate sentry issues with youtrack.

I found it, but looks like only old repos with issues without solution.
For example https://github.com/getsentry/sentry-plugins/issues/439

## Motivation

Really need

**Comment by scefali** [comment]
@tonal Is this for SaaS or on-premise Sentry? We actually removed YouTrack from SaaS today because it was not working.

**Comment by gonimar** [comment]
what about on-premise Sentry and YouTrack

**Comment by Floeig** [comment]
I would definitively be interested on this too.
There's this repo: https://github.com/getsentry/sentry-youtrack/ but it don't support the new versions of sentry.

**Comment by manuzope** [comment]
Hey ya'll, yea you're right -- the sentry-youtrack plugin has been deprecated.

We don't have a youtrack integration on the roadmap but the [integration platform](https://docs.sentry.io/product/integrations/integration-platform/) should allow ya'll to build out your own solution. You can also add [UI components](https://docs.sentry.io/product/integrations/integration-platform/ui-components/) so that you can link tickets through a sentry issue.
