### ISSUE TITLE
Bug reporting dialog requires "unsafe-inline" for "style-src-elem" CSP

### ISSUE THREAD

**Issue by jens-duttke** [getsentry/sentry#18126]
## Summary

Since there are many browser extensions (and also some ISPs) which inject scripts and styles into my web application, which results into errors, I use a restrictive CSP setup, which bans inline code, evals, etc.

Unfortunately, to be able to use the Sentry dialog for bug reporting, I need to set "unsafe-inline" for "style-src-elem", because it uses inline styles, which openes a door for errors.

## Motivation

My motivation is, to prevent injected code into my webapp as much as possible. To prevent errors, which are triggered by browser extensions and ISPs.

## Additional Context

I'm using JavaScript and the following call, to open the report dialog:
```js
Sentry.showReportDialog({ eventId: event.event_id });
```

**Comment by jens-duttke** [comment]
Are there any news regarding this issue?

**Comment by mfb** [comment]
FYI I created a related issue #34415

**Comment by s1gr1d** [comment]
**Why was this issue closed?**

While we think it would be helpful to solve this issue, we're busy with a lot of other tasks at the moment. 
Therefore, this issue is not a priority for us at this time.
If you still want to see this resolved, please consider opening a PR for it - we're always happy to review them. 

Please feel free to leave a comment if you think this issue should be reopened.
