### ISSUE TITLE
Slack Integration: I can't add a new channel to the configuration

### ISSUE THREAD

**Issue by Sergio-Sanchez-Polaroo** [getsentry/sentry#18279]
Hi, I just added Slack integration and I made it works.
In the configuration I specified the channel which sentry could has permission to send notification.
All this work well.

Now, the problem is that I want to add just another channel for other kind of notifications and I don't find the way to do that.

**Comment by jonesphillip** [comment]
@Sergio-Sanchez-Polaroo if I'm understanding your question, you want to add another channel that the Sentry Slack app has permissions to access?

In order to do that you will want to:
* Navigate to: https://slack.com/apps
* Click 'Manage' on the top right
* Go to Sentry, in the listing. Then click 'Settings' underneath the Sentry icon. 
* From there you can add Sentry to any additional channels you need.

Does that answer your question?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
