### ISSUE TITLE
Do server install for sdk(s) 

### ISSUE THREAD

**Issue by I-Cat** [getsentry/sentry#18998]
![sdk](https://user-images.githubusercontent.com/58572646/82741667-9efc3880-9d22-11ea-9dd1-d403fc851c53.png)
## Important Details

How are you running Sentry?

On your web site

On-Premise w/ Docker, version x.y.z

as (sentry.io)

Other, version x.y.z, [briefly describe your environment]

## Description

[What happened]

It asks me to install sdks for (sentry.io) to work

## Steps to Reproduce

1. [First Step]
sign up
2. [Second Step]
make project
asks to install sdk's
All of the sdks can be hosted on (sentry.io)

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

[What you think should be happening]

### Possible Solution
Make the sdks run off the host aka web site.
Makes no scene to install a bunch of sdks to be able to run the website. 
Since I half to install sdks i might as well install free sdks and leave (sentry.io)
thanks 

[If you have an idea on how this could be solved include that detail here.]

**Comment by untitaker** [comment]
The SDKs are necessary to collect data that is ultimately fed into sentry.io. sentry.io runs on our servers (or one you provide with onprem), the SDKs run on your server (because they need to collect the data).

I think you fundamentally misunderstand how Sentry works. Please read up on a little of the documentation before creating an issue like this.
