### ISSUE TITLE
Error message missing from raw view

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#1912]
Might only be affecting Python.

**Comment by hheimbuerger** [comment]
For the record, if this was a conscious choice, I would like to express my unhappiness with this design decision. I think the message should be prominently shown, not only in the page title and the raw view. Let me elaborate.

I have my loggers connected to Sentry, so everything on level Warning and Error is logged to Sentry. I believe this isn't an odd use case.
The same log line captures a various errors, so the embedded error code or error message in the log line is essential for me to know what's going on. The messages also often contain which customer account caused the error, another important information I often need to look up.

Due to repeating stack traces of these log messages, they are grouped together in Sentry, usually for many different errors.

*Sometimes*, Sentry v8 shows a message box on each individual event like the following:

![2015-09-09_1545](https://cloud.githubusercontent.com/assets/159414/9763447/d8335f70-5709-11e5-9a9a-365c9c6a42eb.png)

Other times, Sentry just omits that information. I don't understand why and I don't think it's a good idea.

![2015-09-09_1544_001](https://cloud.githubusercontent.com/assets/159414/9763428/b933248e-5709-11e5-9c0c-767d6ae3c997.png)

Is this by design?

**Comment by dcramer** [comment]
We can probably just always show the message.

With that said, this is unrelated to the raw view, and didnt change between the new and old Sentry. We always showed it dynamically based on if it was long or had newlines in it, otherwise we left it in the title area.

**Comment by hheimbuerger** [comment]
Well possible, I remember occasionally struggling with this in the old UI as well, just could never find out when it appears and when it doesn't.

Always showing it would be a highly welcome UX improvement for v8!

Would also love to see the message distribution across the event group in the 'Tags' view at some point!
