### ISSUE TITLE
Web API access to event attachments

### ISSUE THREAD

**Issue by daxpedda** [getsentry/sentry#19692]
## Summary

Currently it isn't possible to gain access to event attachments through the Web API, as far as I know at least.

## Motivation

I just stumbled upon it while doing integration tests for my Rust wrapper on `sentry-native`, but this is actually an issue that is quiet important to us.
We are planning to use event attachments quiet extensively, currently the plan was to make a second small frontend for non-programmers to look through issues, in which the main focus would be event attachments.
As far as I know this would not be possible if there was no API to query and access those event attachments.

## Additional Context

Some thoughts:
- downloading event attachments over a Web API might be quiet traffic heavy, depending on the size of course, I'm unsure how this would affect Sentry
- the "get-an-event-endpoint" should probably only be used to get IDs to the attachments, because of the size, so a new endpoint would be needed for this

Also I am aware that event attachments are still in (closed) beta 😉.

**Comment by jan-auer** [comment]
Public documentation for the API endpoints is still pending the official release of event attachments. 
You can retrieve meta data about attachments in two ways:

- For an individual event via `GET /api/0/<org>/<project>/events/<event-id>/attachments/`
- For an entire issue via `GET /api/0/<org>/issues/<issue-id>/attachments/` 
- ... or `GET /api/0/issues/<issue-id>/attachments/`

To retrieve information about an individual attachment by ID:
- `GET /api/0/<org>/<project>/events/<event-id>/attachments/<attachment-id>`

To download the attachment:
- `GET /api/0/<org>/<project>/events/<event-id>/attachments/<attachment-id>?download=1`

The schema for each of the attachments is (comes as list in the first endpoints):

```json
{
    "sha1": "82c8831975c78c054b66c32e8c64f9fbcbf4976b",
    "name": "57b0cdfb-f891-468d-a97c-9e9c16b3a16e.dmp",
    "event_id": "37bb04ea0d294bc88d2d4e363b5ece79",
    "dateCreated": "2020-07-01T09:27:28.905556Z",
    "headers": {
        "Content-Type": "application/octet-stream"
    },
    "type": "event.minidump",
    "id": "376308741",
    "size": 21824
}
```

At the moment, this requires your organization to be enrolled into the Event Attachments Preview. Otherwise, Sentry does not store event attachments.

**Comment by daxpedda** [comment]
Thanks!

**Comment by daxpedda** [comment]
I found that the only endpoint I got to work is that one: `GET /api/0/issues/<issue-id>/attachments/`
All other endpoints return `404` for me, tested on both sentry.io and onpremise.

**Comment by jan-auer** [comment]
Correction, the endpoint to resolve attachments for individual events should have been (note the `projects`):

```
GET /api/0/projects/<org>/<project>/events/<event-id>/attachments/
```

**Comment by daxpedda** [comment]
Works like a charm, thanks!
