### ISSUE TITLE
Investigate issue with SelectedGroupStore and actions

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1971]
Reports of resolve all not actually resolving everything and other mismatches with selections. I haven't reproduced yet.

**Comment by kylebragger** [comment]
We've got this issue for exposure-labs-inc/statshot. I'm using Mac OS 10.10.5 with Chrome latest stable, if that helps.

**Comment by benvinegar** [comment]
Hey @kylebragger – any additional insight you might have into how we can recreate this? I've been clicking around the checkboxes + "all" checkbox, and can't seem to get this scenario to trigger.

**Comment by kylebragger** [comment]
@benvinegar not really, sorry. I clicked the select all checkbox, and then the red button that is supposed to mark all events as resolved, but it only resolves the visible (current page) events. That's about all I got. :-( 

(I also just opted-out of the beta so I could do a Resolve All, FWIW)

**Comment by benvinegar** [comment]
Ah, I think that is the issue – "all" checks everything on the current page, not on pages you haven't seen yet.

I'm not sure if we're going to change this, because we designed this new stream to work like GMail, which has the same behavior (only checks items on the current page).

I'm going to reach out privately via email to better understand your situation, see if we can come up with a workaround.

**Comment by kylebragger** [comment]
No worries. kyle at kylebragger.com is me.

**Comment by benvinegar** [comment]
@kylebragger – my bad, I was totally confused about this button. It should work as you expect it to. I'll have it addressed shortly.

**Comment by kylebragger** [comment]
Okay, awesome!
