### ISSUE TITLE
If a file path is encoded, it should still be matched for sourcemaps

### ISSUE THREAD

**Issue by AssisrMatheus** [getsentry/sentry#19713]
How are you running Sentry?
Sentry.io

## Description

I'm using Next.js to run my app, and to declare routes with next we have to use a square brackets notation for dynamic route values, for example: `user/[id].js`.

I am then uploading my sourcemaps to Sentry and reporting errors normally using the sdk.

When the sourcemaps are uploaded to sentry, their names/paths are NOT encoded, resulting in paths like:
![image](https://user-images.githubusercontent.com/12276174/86593108-07b61200-bf6b-11ea-92b1-04894540e6ac.png)

Which is correct, as the brackets are correctly being considered.

If I capture an exception at next.js' server side, which is using @sentry/node, the stack trace paths are not encoded, and the sourcemap file is correctly matched for where the exception was thrown:
https://sentry.io/share/issue/3d6a7e53fba547dfbef17e1e247553cf/

If I capture an exception at the client side(browser side), which is using @sentry/react(same issue with @sentry/browser), the stack trace paths are sent as encoded but then, they are not decoded when they reach the sentry server.

Since the path is encoded and the string `%5Blocale%5D.js` is not equals to `[locale].js`, the sourcemap is not matched/not found

Notice the brackets [] of `[locale].js` that have been converted to %5B %5D:
https://sentry.io/share/issue/1720ebb792c7411a9f2bb8ce2952a9e4/ 

## Steps to Reproduce

1. Upload sourcemaps
2. Run Sentry.captureException(error); in the browser/client side with @sentry/react, In a file that contains characters that are usually encoded, like square brackets `[]` 
3. You'll see the bug
4. Run Sentry.captureException(error); in the browser/client side with @sentry/react in a file that does NOT contain characters that are usually encoded
5. You'll see that it works

### What you expected to happen

As declared in this comment, I think this is a bug, and sentry should decode the path before matching it with its sourcemap, or whenever it is fit, while still fixing the bug:
https://github.com/getsentry/sentry-webpack-plugin/issues/186#issuecomment-654168739

### Possible Solution

Maybe decode the paths before matching them with the sourcemap path? Maybe decode them at the exact moment it reaches the server?

Allowing us to manually encode the paths before uploading them is not a solution, because even thought it would fix by making it work for the client side, It would break the server side, which pushes the exception without encoding the values.

**Comment by jasonwilliams** [comment]
Looks related to https://github.com/vercel/next.js/issues/15823

**Comment by paeolo** [comment]
Exact same issue for me.
I tried to find a workaround without success.
Maybe Sentry should try to match the url with the encoded version of the sourcemap filename, or maybe @sentry/browser shouldn't encode the URL (not sure wether it's @sentry/browser fault anyway).
Unfortunately, this bug makes Sentry source map feature not usable with Next.JS.

**Comment by paeolo** [comment]
I found the fix.

This issue can be closed since Sentry already provide the tool to fix this issue very easily.

The problem with NextJS (which is not really a problem) is when it's generating the HTML, either at build time or with SSR, it will escape (encodeURI) every URL in the link tags. So an URL containing for instance [locale] will contain %5Blocale%5D instead.

Actually, this behavior is intended since it fixes an issue with NextJS (can't remember where).

Anyway, Sentry when sending the frames will include this encoded URI instead of the decoded URI. Luckily we can rewrite StackFrame. Just add the following line:

`frame.filename = decodeURI(frame.filename);`

in the _app.tsx file of the example https://github.com/vercel/next.js/tree/canary/examples/with-sentry, right after the line

` frame.filename = frame.filename.replace(distDir, 'app:///_next');`

Good luck.
