### ISSUE TITLE
Can't install Sentry add-on on Heroku

### ISSUE THREAD

**Issue by Tyrrrz** [getsentry/sentry#20115]
## Important Details

I'm not running it yet. Planning to run it via Sentry.io with Heroku integration.

## Description

I'm trying to add Sentry as a plugin on Heroku via https://elements.heroku.com/addons/sentry. In doing so, I get an error when I click "provision".

![image](https://user-images.githubusercontent.com/1935960/89110552-709e8600-d454-11ea-9279-b64d5b3ec24e.png)

To reproduce, just try to install the add-on on Heroku. I don't know if there's anything external that can influence this behavior.

### What you expected to happen

For it to work 😄 

### Possible Solution

From a clueless outside perspective, it seems like some sort of integration between the two services broke.

**Comment by Tyrrrz** [comment]
The issue is fixed now.

**Comment by emilesilvis** [comment]
I'm getting this issue as well. Contacted Heroku support to help troubleshoot.

**Comment by Neilpoulin** [comment]
I am also having this exact issue.

**Comment by emilesilvis** [comment]
@Tyrrrz could this be the same issue?

**Comment by Dreamersoul** [comment]
This issue is making Sentry unusable for me. I just want to **pay** for the higher tier in order to start receiving issues on the dashboard. I currently can't because my sentry organization is tied to the Heroku addon. There is no way for me to remove such connection and upgrade the origination subscription normally through `sentry.io`.
I tried contacting customer service but because I the account is in the free tier I don't have access to email support even though I am willing to pay and get the support.

I have already submitted an issue to the sentry forum last week but still no response from sentry staff. [Forum link](https://forum.sentry.io/t/heroku-sentry/12027)

I really don't feel comfortable migrating from Sentry which worked for me seamlessly for a year now to something else. However I am running the project in production. I need to track bugs/releases/runtime errors so I am afraid if this doesn't get resolved soon I will be forced to move on to another service.

We can clearly see that the issue is from sentry and not Heroku from the forum post [Heroku forum](https://help.heroku.com/942248):

> I let the Ecosystem team (they manage all things Add-ons around here) know what's going on and they shared a couple of notes:
> The Sentry add-on error is coming from Sentry sending back an error when we try to provision an account with their APIs. The team have noted reports of this for a few weeks now, but haven't heard anything back from Sentry, yet, as to why that is.
>.....
