### ISSUE TITLE
Uploaded source-map artifacts not working without sourceMappingURL comment

### ISSUE THREAD

**Issue by Fonger** [getsentry/sentry#20916]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description
We're using sentry with sentry-cli to manually upload source maps.

## Steps to Reproduce

1. Generate source maps (with #sourceMappingURL comments)
2. Upload source map with sentry-cli (artifact)
  `sentry-cli upload-sourcemaps --ext map --url-prefix xxxx --rewrite`
3. Remove all *.map in production release.
4. Remove all `#sourceMappingURL` comments in *.js
  `find '.next' -type f \( -iname \*.js -o -iname \*.css \) -exec sed -i -E 's/\/(\/|\*)# sourceMappingURL=[^ ]*\.(js|css)\.map(\*\/)?//' {} +`

### What you expected to happen
The error should still report with source map without sourceMappingURL comment.
(note: I can see the correct artifacts uploaded in sentry admin console )

I can confirm it works perfectly without step 4.

### Possible Solution

The reason we want to strip the comment is that the browser will throw 404 warning when we open the console by default (chrome and safari) because we explicitly remove all *.map files on our actual server.

We want to console.log() some hiring information there but there're many *.map 404 warnings obstructing the information.
I google for a while and find `SourceMap` HTTP response header but it is not what we want. If browser see the header it will try to fetch the source map file and get 404 error.

It should work without the comment. ( like hidden-source-map? )

**Comment by BYK** [comment]
@mitsuhiko @untitaker is this something we can do easily?

**Comment by untitaker** [comment]
@HazAT is a better contact point for this than me.

**Comment by Fonger** [comment]
Thanks you for the response. Really looking forward to this feature.
Also thanks Rodolfo B who created the feature request.

**Comment by Fonger** [comment]
Any update?

**Comment by xgqfrms** [comment]
# watcing ... 👀

**Comment by IhToN** [comment]
I'm having the exact same issue. Would be a good thing to have.

**Comment by HazAT** [comment]
Hey,
Sorry for being silent for so long.
Did you try to upload the JS Source file and Source Map to Sentry _WITH_ the comment but to your website without it?
This should work I think.

Anyway, we can look into this but since it's not really breaking anything I don't know when we prioritize this in. The only thing I can say is we'll consider this when working on generally improving the source map experience.

**Comment by Fonger** [comment]
We don't upload the JS source file. We only upload source maps.
Is it necessary to provide source code to sentry?

**Comment by IhToN** [comment]
In our case we are uploading both, and it only works if we leave the comment in the website source code.

Not the best case scenario but does the trick, but could be a good improvement for the future.

**Comment by ismailcherri** [comment]
In our case we uploading both js files and source maps.
It doesn't work unless we add the comment on the files in live production servers. The latter is annoying because it displays warnings or 404 errors which is not optimal in our case.

Is there a planned solution to this?

**Comment by bruno333** [comment]
I understand it's not breaking anything, but without this feature, Sentry is only usable for simple environments?

#Did you try to upload the JS Source file and Source Map to Sentry WITH the comment but to your website without it?
This should work I think.

No, we did not, cause imagine the complexity and duration of our CI/CD if you have a complex environment as we do. 

Angular is making it possible to generate maps without sourceMappingURL to be able to hide it in production, but unfortunately, it's not compatible with sentry yet. 

I really hope this will be picked up sooner than later. 
Despite that, I'm a huge fan of Sentry, thanks for this amazing tool ;)

**Comment by raine** [comment]
This issue should be of higher priority.

You basically can't avoid warnings in console if you want to use Sentry with sourcemaps that are uploaded, instead of being published in public internet.

**Comment by danielsdeboer** [comment]
This is also a problem with Vite apps, when you emit hidden sourcemaps (https://vitejs.dev/config/#build-sourcemap):

```js
export default defineConfig({
  build: {
    sourcemap: 'hidden',
  },
})
```

Supporting this would make the deploy process a lot less annoying.

**Comment by Fonger** [comment]
Any update?

**Comment by viddo** [comment]
Found this issue when looking for an answer to whether sourcemaps are _required_ in production - However, from what I can tell source maps works fine without the `sourceMappingURL` comment in the runtime code. I'm using [`devtool: 'hidden-source-map'`](https://webpack.js.org/configuration/devtool/) for a Webpack build. I figure other build tools have some equivalent setting.

I suspect this issue could probably be closed, since it's an old report and the issue probably got resolved at some point and this issue was missed? 

Also suggested improvements to the docs to cover this aspect: https://github.com/getsentry/sentry-docs/issues/9557
