### ISSUE TITLE
Expose an exact error count in UI

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2101]
Re: https://sentry.zendesk.com/agent/tickets/598

Not sure if we want to use a real tooltip or just a `title` attribute here, but it's probably worth exposing IMO.

Right now, we generalize at a very high level of "1.1M" without any way to see what the absolute number is.

**Comment by bsr3000** [comment]
@billyvg I can take this, even I have it partially done, using tooltip, I have some questions about styling. Position of tooltip and text on it, currently I gave `Exact: count.toLocaleString()` Would it be ok?

**Comment by billyvg** [comment]
@bsr3000 I think a tooltip may be too heavy - can we just add a `title` attribute to the element? I think `count.toLocaleString()` would be enough. Thanks!

**Comment by bsr3000** [comment]
@billyvg ok, I ll add a title to it

**Comment by varun-karandikar30** [comment]
I am interested in working on this issue. Can you provide some information regarding it?

**Comment by billyvg** [comment]
@varun-karandikar30 Sure... there are many places in our application where we display an abbreviated number, e.g. if it's 1000, it will become `10k`, we want to apply the `title` attribute to this component so that it will display the exact number.

This is the component that we use for this (`<Count>`): https://storybook.getsentry.net/branches/master/index.html?path=/story/utilities-formatters--count

**Comment by infinityxxx** [comment]
Created this PR https://github.com/getsentry/sentry/pull/21583 as part of hacktoberfest, can someone take a look?
