### ISSUE TITLE
Decouple source maps from releases

### ISSUE THREAD

**Issue by seroy** [getsentry/sentry#21087]
## Summary

Allow to use source maps independently of a release

## Motivation

In cases when only backend code is changed its not needed to run release deploy with building frontend code (javascript/source maps), so currently it is not possible to view source code in stack trace for such releases.

**Comment by BYK** [comment]
Ping @lobsterkatie and @kamilogorek

**Comment by lobsterkatie** [comment]
The easiest option here is to use different release names in Sentry for front and back end, so that you can bump your backend independent of your front end. (This is what we do in our own use of Sentry.)

Past that, if we were to implement the ability to use previous releases' source maps, it would need to be on the ingestion end, specifically here
https://github.com/getsentry/sentry/blob/86fed44b9edffcd4a6f2398368ba4e4a0112e05e/src/sentry/lang/javascript/processor.py#L254-L258.
We'd also need to implement some UI for (no pun intended) mapping one release's maps to another release, and/or a command in the CLI to do it.

@jan-auer or @mitsuhiko or @benvinegar might have thoughts or opinions here.

**Comment by mitsuhiko** [comment]
We discussed a few times instead of making source maps be bound to releases we can bundle them independently and identify them by a separate identifier. We're doing that with debug information files already with great success. Unfortunately there is no timeline and no concrete work scheduled for this at the moment.

Making them point to a specific other release is unlikely to happen.

**Comment by chadwhitacre** [comment]
Title/description updated per @mitsuhiko's comment. Thanks for the report @seroy, and for bearing with us as we triaged! :)

**Comment by mydea** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
