### ISSUE TITLE
Notification summaries

### ISSUE THREAD

**Issue by ckj** [getsentry/sentry#2134]
We've been brainstorming how notification summaries might work in Sentry. Here are some visuals born out of these discussions:

#### A rollup of messages triggered by a single rule:

![screen shot 2015-10-08 at 3 39 44 pm](https://cloud.githubusercontent.com/assets/30713/10381833/d8218a04-6dd2-11e5-9b4b-8fbc8f55bc63.png)

#### A rollup of messages triggered by multiple rules:

![screen shot 2015-10-08 at 3 40 57 pm](https://cloud.githubusercontent.com/assets/30713/10381849/026b51dc-6dd3-11e5-99fa-d756d71f3f42.png)

**Comment by tkaemming** [comment]
Is the "N issues affecting M users in the last X minutes" line derived from statistics for the entire project, or limited to the groups that are listed in the email? The full project statistics seem more useful, but a little confusing since those items will not necessarily be included in the digest.

It seems like we should probably include absolute dates somewhere (since who knows when the message will actually be read after we send it.) It might also make sense to note somewhere how long the delay period will be between sending the next update ("we'll update you again in 30 minutes if there are any new notifications", etc) so radio silence isn't interpreted as a sign that nothing is wrong.

**Comment by ckj** [comment]
> Is the "N issues affecting M users in the last X minutes" line derived from statistics for the entire project, or limited to the groups that are listed in the email? The full project statistics seem more useful, but a little confusing since those items will not necessarily be included in the digest.

I had imagined this being the full scope of the issues listed in the email, across all rules as a summary of the information you're about to read.

> It seems like we should probably include absolute dates somewhere (since who knows when the message will actually be read after we send it.)

Agreed - I'll see if I can work that in.

> It might also make sense to note somewhere how long the delay period will be between sending the next update ("we'll update you again in 30 minutes if there are any new notifications", etc) so radio silence isn't interpreted as a sign that nothing is wrong.

Yeah, love that idea. I'll work that in towards end of the email.

**Comment by tkaemming** [comment]
Note to self: the "N issues affecting M users in the last X minutes" summary line requires updating #2130 to handle merging distinct counters for all keys provided (essentially, allow calculating the estimated cardinality of all results currently included in `get_distinct_counts_totals`.)

**Comment by ckj** [comment]
For posterity, we've changed the goal of this specific project to be more along the lines of "notification rollups" than digests. I've updated the sketch to reflect these changes:

![screen shot 2015-10-09 at 1 51 30 pm](https://cloud.githubusercontent.com/assets/30713/10405646/1aa12b8e-6e8f-11e5-83ec-7880c276e9ad.png)

**Comment by tkaemming** [comment]
We did it!
