### ISSUE TITLE
Crash Reports not generated for iOS App

### ISSUE THREAD

**Issue by sudipta17** [getsentry/sentry#21472]
1. Integrated the Sentry SDK in iOS project using cocoapods

2. After that  added this line of code 
SentrySDK.start { options in
        options.dsn = "https://examplePublicKey@o0.ingest.sentry.io/0"
        options.debug = true // Enabled debug when first installing is always helpful
    }

3.  Then added the script in xcode (Uploading Symbols with sentry-cli)

4. Debug symbols are uploaded successfully . But crash reports are not generated.

**Comment by BYK** [comment]
This is not enough data for anyone to figure out what might be going wrong. Can you please share more details and follow the issue template?

**Comment by Sun-ifly** [comment]
options.dsn = "https://examplePublicKey@o0.ingest.sentry.io/0"
o0.ingest  why add this

Self-Hosted Sentry also have  Debug symbols are uploaded successfully . But crash reports are not generated
 delete o0.ingest it success

**Comment by BYK** [comment]
@Sun-ifly your issue seems like https://forum.sentry.io/t/o1-ingest-appears-in-dsn-settings-after-upgrading-from-v9-to-20/11707. Closing as it doesn't seem related to the original issue and @sudipta17 haven't responded in a while.

Please reach out to our support first if you are using sentry.io. If you decide to file an issue, make sure you follow the issue template and fill all the fields.
