### ISSUE TITLE
Sentry scaling issue ???

### ISSUE THREAD

**Issue by sahilsk** [getsentry/sentry#2204]
Greetings,

We're getting following errors repeatedly and our dashboard shows a lag of 30 minutes in all registered applications.

We're using cyclops as our entry point which is autoscaled behind ELB.  Cyclops (nginx) talk to two sentry server behind each running sentry(sentry) and workers(celery). We're using redis(for cache also) and postgresql database
Previously cyclops server were on high cpu alert. So, we autoscaled it. Nowaday's we're getting cpu high alerts for sentry servers and lots of errors of `data not available ..` .
Before we scale sentry  (& workers) i want to know  why this errors are coming  and why 30 minute lag in dashboard? :(

One reason could be cyclops are overwhelmed with requests and keeping it all in memory(no redis for cyclops here).  And churning rate of sentry workers (celery) might be slow.

![image](https://cloud.githubusercontent.com/assets/5857895/10571446/e8cd8488-765c-11e5-8f58-7fca52682a16.png)

Any guidance here would be great.

**Comment by dcramer** [comment]
Cyclops being unrelated here, as its not something we (the team that operates getsentry.com and assists with on-premise installs) operate.

The problem is simply your queue is overloaded. You're sending more volume than the system can handle. These specific errors are saying the data for the event no longer exists by the time the workers go to process it. This happens if it takes more than one hour to process the data or if the cache LRU is configured and it gets expired.

The reason *why* you'll have to dig into on your own, but something is not keeping up, which means something needs capacity. Usually that something is task workers. If you're a larger company we provide services contracts around helping with these situations. If you're not, I'd highly recommend using getsentry.com as we're able to handle throughput much easier there.

**Comment by sahilsk** [comment]
Thank you so much for your swift reply.It's helpful.

I'll discuss with the team and take it forward as per the conclusion. For now i think we can roll few more aws instances to answer this problem. If didn't work, we may need sentry support contracts

Thanks again :)
