### ISSUE TITLE
Improve Release API Experience

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2227]
There's general confusion of how API keys work and this complicates things when people are trying to setup releases via API.

The issues include:

- Admins can't access API keys, and dont even know they exist
- The Token gets confused as an API key

**Comment by dcramer** [comment]
As an aside, this will likely lead us into improving the API experience. A simple solution here is if we had API keys which were user specific, thus granting the same level of access the user has, thus being accessible by all users. This is nice, but it complicates things in that now we have yet another API key (org keys, user keys, client keys). Additionally the organization-wide API keys provide good flows to automate things, and they ensure that keys arent bound to personal accounts which has the nice effect of them never breaking when a user poofs.

**Comment by mitsuhiko** [comment]
One thing to consider is that internally currently it's really confusing as well how this works because the system evolved over time.  The current setup we have is:

* many endpoints expect `request.user` because those endpoints were primarily written for the react UI and not as API calls directly.  Some of those calls currently do fewer things if the user is not set.  For instance `isBookmarked` cannot be changed unless the API call indicates a user.
* internally we still support legacy project bound keys and some calls get confused when the key for the request is indeed a project one.
* many API calls assume the call does come from a organization level key.

Ideally we would not expand too much on those keys and let users issue their own keys which can have more or fewer scopes attached including not being bound to the user.  So for instance as a user I might want to issue a key that can be used to update one or two projects I have access to as a user, but I still might not want that key to actually indicate myself as a user.  I don't think that will result in a good user experience, especially for project admins.

Maybe we want to allow users to request keys and they still show up in the org panel?

**Comment by dcramer** [comment]
We could also consider a plan to unify API keys as part of this. i.e. being able to view project keys within the API Keys scope. We would show them differently (like in a tab) and clearly label them as SDK keys or something.

**Comment by tomazzaman** [comment]
Maybe for starters just update the docs to say we need to use the organization API keys, not the project ones.

Additionally, It would be nice to see the release files in the dashboard.

**Comment by mattrobenolt** [comment]
> Additionally, It would be nice to see the release files in the dashboard.

This is buried away, but it exists today under: `https://app.getsentry.com/<org>/<project>/releases/<release>/artifacts/`

**Comment by dcramer** [comment]
We added a webhook, which imo solves this for now.
