### ISSUE TITLE
redmine issue sync

### ISSUE THREAD

**Issue by ideepika** [getsentry/sentry#22390]
## Summary

We have a pretty entensive database for tracking issues on redmine, which are not just limited to integration tests, but to open source users as well, finding and creating issues from sentry is good for mid/small size projects but when we are looking for larger user base, we need to track and sync existing reported issues instead of creating new ones.

## Motivation

The communities for such projects will largely benefit from this feature as it rather makes the whole process much seamless and transparent. 
- sync redmine tracker
- redmine tracks sentry failed events ID's + short message to either comment/ add description

ambitious
- redmine issue failure suggestions with similar failed events

**Comment by BYK** [comment]
Hi @ideepika, thanks for raising this! I don't think we'll invest in Redmine integration any time soon (if ever, given its lack of relative popularity). That said we have an integration platform where you can build this yourself and even publish for others to use: https://docs.sentry.io/product/integrations/integration-platform/#creating-an-integration

If you are interested in that, we are happy to assist you. Otherwise I'm inclined to close this issue to signal that is very unlikely to happen.

/cc @manuzope

**Comment by ideepika** [comment]
@BYK I understand, we do have something as mentioned in docs, are you talking about
![sentry](https://user-images.githubusercontent.com/22215384/100993480-7bd8fe00-357b-11eb-8238-a4a12003182c.png)

**Comment by manuzope** [comment]
Hi @ideepika, BYK is talking about going to the cog icon on the top, then going to Developer Settings and creating a new internal integration. That should allow you to create an issue tracking integration. And then you'll be able to code up the syncing functionality.
