### ISSUE TITLE
tlsv1 alert internal error

### ISSUE THREAD

**Issue by tyler274** [getsentry/sentry#2242]
https://gist.github.com/tyler274/df0506c223a4ed192a32

Happens while testing and in general use as well. 

`from raven.contrib.django.raven_compat.models import client; client.captureException()`

**Comment by mattrobenolt** [comment]
Hey @tyler274, this has less to do with sentry, but more to do with whatever is terminating your TLS.

I've never seen that error personally, but I'm pretty sure it has to do with using an old version of TLS that is considered insecure now.

I _think_ skipping SSL validation here would solve the problem, but not entirely sure.

Can you try putting `?verify_ssl=0` to the end of your DSN?

Also, closing this ticket since it's not really an issue with Sentry.

**Comment by tyler274** [comment]
putting `?verify_ssl=0` at the end fixed it, but doesn't explain why it's having issues when it worked fine with the 7.x version of sentry, only when I upgraded to the current git version.

**Comment by mattrobenolt** [comment]
Did you also upgrade raven? Either way, sentry doesn't do anything with TLS itself, that'd be your webserver.

Are you using nginx?

**Comment by tyler274** [comment]
I did not upgrade raven, tried, same error. 

Running nginx 1.8, openssl 1.0.2d,

**Comment by mattrobenolt** [comment]
I'm honestly not sure, and there's not much I can do without being in your machine. And as I said, this isn't related to Sentry itself.

I'd start with something like this: https://serverfault.com/questions/704376/disable-tls-1-0-in-nginx

Something you're doing new, and I don't know what, now doesn't like TLSv1. I think newer python complains about this now? Python 2.7.10. I'm not 100% sure off the top of my head.
