### ISSUE TITLE
The link with Jira disappears after event merging

### ISSUE THREAD

**Issue by foal** [getsentry/sentry#2274]
Now 
- Link to Jira disappear in the event
- Link in the Jira issue leads to "The issue you were looking for was not found." 

Wish
- Link to the Jira issue move to the new "merged" event
- Add/update Jira with new link
- Optional. In case if few events contains Jira issues ask/mark other Jira issue as duplicates.

**Comment by mattrobenolt** [comment]
> Optional. In case if few events contains Jira issues ask/mark other Jira issue as duplicates.

I think this is the tricky case, and unfortunately, it'd be something we have to address somehow since plugins are a generic IssuePlugin abstraction.

So right now, this is obviously pretty easy if only one of the groups has an issue attached to it, but this becomes a bit unclear what to do if there are various issues across all of them.

There's only two real possible outcomes:

1. Support merging issues of same type. This would have to provide a "merge" method into the interface. I don't really like this idea since this probably doesn't really apply to most issue trackers, and probably difficult to them merge more than 1.
2. Support multiple issues of the same type on one group. This is likely the easiest option here with the least ambiguity.

I'm not sure if either of these are feasible in the short term though.

**Comment by foal** [comment]
Few more outcomes for case of several tickets:

- Do not merge the events (with notification)
- Add to merged event text comments with all tickets and implement #991. User will resolve it manually
- Ask an user to select one issue

**Comment by dcramer** [comment]
I think at least as a stop gap we can simply throw away duplicate data.

That's how we approach other things w/ the merge step.

i.e. JIRA-1 and JIRA-2 get merged, whichever one is the parent wins (which is generally random to the end user)

**Comment by dcramer** [comment]
We throw away the duplicate and at least keep one, so this should be good-enough for now.
