### ISSUE TITLE
Event De-Duplication

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2320]
Implement basic interface de-duplication per the future API schema/spec.

Goals:
- Store all events (thus replacing the need for EventMapping)
- Blob per interface [at minimum] to generate smaller blobs and support de-dupe

Notes:
- NodeStore can accept SHA1 as blob IDs (Django NodeStore might need modified)
- Need some kind of GC process / ref counting to ensure we clean up old blobs

**Comment by dcramer** [comment]
@mitsuhiko gonna take this over and let you handle vcs/celerymaster

**Comment by dcramer** [comment]
Some concerns:

- some fields like `version` is lightweight and isnt fitting of its own blob
- Event.data can fit "list of hashes" to lookup, but it will greatly complicate things to re-use it

**Comment by mitsuhiko** [comment]
Some of my notes with might be useful:

* we currently go through the data twice already, checksumming adds a third
  time. ideally we go through the data once in general and normalize,
  slices it up and generate checksums.
* checksumming code exists in sentry-next, can work well with what we have.
* we can't be too static for the deduping logic: in particular a dangerous
  thing is to have blobs that do not dedupe because of a single field that
  changes against anticipation or splitting into blobs that do not dedupe
  against expectations.  From the data in sentry-next this is so easy to
  accidentally produce that we need to track this or we do more damage
  than good.  So data never dedupes we need to know about this.
* the work from sentry-next cannot really be plugged into what we have
  currently because it just assumes much more split data already.  The
  data format there was already cleaned up to support de-duping a lot better
  than what we have currently.

Things that are known to be problematic without further splitting:

* stacktraces
  * filename often contains locations in the file names that are related
    to the releases
  * line numbers move around.
  * java stacks are long, and 90% the same between many apps, but then
    differ in the actual app path.  Without splitting, little saving.
  * vars/args need separation
* http data: too different in general to make sense deduping other than
  separating out internal http stuff that is local to the app
* process env: that one i noticed would be perfect for deduping because
  it's very common but unfortunately often has machine local data in that
  changes on restarts.

I ran this over data I had from a sentry installation:

* ~1 million events
* check-summed up a subset of data (stacktrace only)
* barely any deduplication without removing vars/filenames/lineno

However stacktraces there are both low and number of different events and
releases was high as the data was retained over long periods of time.  I
might try this with sentry/sentry data if i can download it.

Some other things I noticed:

* right now our blob fetching code scales really bad with large number
  of blobs to look up.

**Comment by mitsuhiko** [comment]
Some related issues:

* https://github.com/getsentry/sentry/issues/1320

And gists:

* https://gist.github.com/tkaemming/303f0761723801f350b92345a53a46e2#file-split-py-L81-L109

**Comment by dcramer** [comment]
Some notes:

- Let's try to re-using existing hashing for stacks so they maintain awareness of things like java lambdas
- Vars can do something along the lines of what @tkaemming is doing to improve storage

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
