### ISSUE TITLE
Long key names cause overflow

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2384]
![1 12 2015 - 14 26 15](https://cloud.githubusercontent.com/assets/23610/11508695/fdb3629a-980e-11e5-8a30-ed593ad32da0.png)

**Comment by dcramer** [comment]
I thought we had fixed this. Can we fix it once and for all so it can never happen again?

**Comment by dcramer** [comment]
GH-2246

**Comment by dcramer** [comment]
https://sentry.zendesk.com/agent/tickets/1225

**Comment by ckj** [comment]
> I thought we had fixed this. Can we fix it once and for all so it can never happen again?

This is due to the `max-height` property on `.box-clippable` and unrelated to long key names. The reveal animation requires there to be a value set for `max-height`. I had it set to 5000px, which is why we don't see this often. I'm going to set it to 50000px and increase the animation length by 10x as well.
