### ISSUE TITLE
Missing `icon-minus` from IcoMoon generated font (sentry-simple) on Trace Detail view

### ISSUE THREAD

**Issue by nickpresta** [getsentry/sentry#2398]
Hello,

It seems the Icon Font generated from IcoMoon is missing the "minus" icon.

# `icon-plus` when collapsed

<img width="882" alt="screen shot 2015-12-04 at 2 23 59 pm" src="https://cloud.githubusercontent.com/assets/49090/11599110/f9393e98-9a92-11e5-8695-a13a78e9daa2.png">

# Missing `icon-minus` when expanded

<img width="887" alt="screen shot 2015-12-04 at 2 24 09 pm" src="https://cloud.githubusercontent.com/assets/49090/11599122/07b602da-9a93-11e5-97cd-fc6b80adcf4c.png">

# `icon-plus` has font entry

<img width="931" alt="screen shot 2015-12-04 at 2 24 38 pm" src="https://cloud.githubusercontent.com/assets/49090/11599133/0f824596-9a93-11e5-9a3d-18824cd90ffa.png">

# But not `icon-minus`

<img width="769" alt="screen shot 2015-12-04 at 2 25 01 pm" src="https://cloud.githubusercontent.com/assets/49090/11599136/18ead24c-9a93-11e5-9c48-f7d38abbfaf4.png">

I would submit a fix but I don't have access to your account to generate the glyph :smile:

**Comment by ckj** [comment]
@nickpresta Thanks for the heads up. I'm going to re-add the glyph and then try to figure out how we lost it in the first place. 

Ideally we'd have bundled tooling to generate the font rather than relying on IcoMoon. If anyone has thoughts around managing a custom icon font in a more sane way we'd love to hear them.
