### ISSUE TITLE
/src/sentry/rules/__init__ line27 ``register`` should be ``registry``?

### ISSUE THREAD

**Issue by wuzhentang** [getsentry/sentry#2404]
And the time of  initial  globle scope variable ``rules``  will easy cause bugs. Because  when a registering plugin import ``module`` or ``class`` from ``/src/sentry/rules`` package,  the global variable ``rules`` is initialized,  so the rules of plugins from this and after  will no be  add to ``rules``. May be a better time initial ``rules`` is after registered all plugins.

**Comment by dcramer** [comment]
@wuzhentang I think you're right in that order is incorrect, and we'll probably want to remove this bit all together. You could sentry.rules.registry.add(...) within your plugins import file and I believe things would work fine. This hasn't been a used feature yet, mostly because the rules API will ilkely change soon.
