### ISSUE TITLE
Include the environment in fingerprints

### ISSUE THREAD

**Issue by checkphi** [getsentry/sentry#24061]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 20.9.0

## Description

Sentry does not include the environment in the fingerprint. Errors from other environments have the same fingerprint, so aggregation of errors is wrong.

## Steps to Reproduce

1. Throw exception Foo in environment A
2. Throw exception Foo in environment B
3. Filter for exceptions from environment B

Now exception Foo is not shown, as all occurences of that exception are aggregated to the exception from environment A (as it was the first to report the exception). If B would have been the first to report, all exceptions coming from A would be aggregated to environment B.

### What you expected to happen

The environment should be part of the fingerprint. Aggregation should not happen across environments so that proper filtering is possible.

**Comment by chadwhitacre** [comment]
Thanks @checkphi, routing to @getsentry/owners-ingest for [triage](https://www.notion.so/sentry/How-to-Process-Issues-PRs-e9657c0fa77d407ebe7c878076f63e35#0b4da6c630c84c26beafc0f9bb3b4844) [internal].

**Comment by untitaker** [comment]
I get the point you're making but I think the answer here is to show per-environment event-/usercounts instead of adjusting how grouping works. FWIW I think we already show user- and event-counts that respect your search query, so you should see "there are n events in this group matching your query" in addition to the regular count. I am not sure if this is featureflagged and if I fully understand if you mean search or environment-selector when you say "filtering".

If we were to add environment to the fingerprint, you will force new groups for everything and create tons of alerts the moment you rename "prod" to "production" or start adopting environments at all.

**Comment by untitaker** [comment]
FWIW this is what we show in issue search:
![Screenshot 2021-02-24 at 16 59 49](https://user-images.githubusercontent.com/837573/109028198-da68d080-76c1-11eb-9f59-4688ea202785.png)

**Comment by checkphi** [comment]
> I get the point you're making but I think the answer here is to show per-environment event-/usercounts instead of adjusting how grouping works.
But only because it's the same exception doesn't mean that it has the same cause. So do you want to _resolve_ an issue for all environments at the same time?
 
> If we were to add environment to the fingerprint, you will force new groups for everything and create tons of alerts the moment you rename "prod" to "production" or start adopting environments at all.
Yes true. As you can't differentiate whether you rename or really have another environment. From my point of view this is just an issue of backwards-compatibility.

**Comment by untitaker** [comment]
>But only because it's the same exception doesn't mean that it has the same cause. So do you want to resolve an issue for all environments at the same time?

I guess I don't understand then. Just because it's two different environments it also doesn't mean it's two different issues. Maybe the key to splitting up the events is somewhere else?

In any case you can already control how issues are grouped using SDK fingerprinting: https://docs.sentry.io/platforms/python/data-management/event-grouping/sdk-fingerprinting/#group-errors-with-greater-granularity -- maybe that helps as a crutch for now
