### ISSUE TITLE
Ignored issues are not transitioning to unresolved when they happen again

### ISSUE THREAD

**Issue by piloos** [getsentry/sentry#24497]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

When ignoring an issue until the associated event happens again, the issue is not marked as unresolved when the associated event happens again.

## Steps to Reproduce

1. Ignore an issue in Sentry _until this occurs again one time from now_
2. Retrigger the associated event
3. Check in Sentry: the issue is still in the _ignored_ state, the `mute` icon is gone though.

### What you expected to happen

Resurfacing issues that were `ignored`, should be moved to `unresolved` state.

![image](https://user-images.githubusercontent.com/3332602/111442537-c20c3480-8708-11eb-840e-3fe6c8d1434c.png)

**Comment by BYK** [comment]
Pinging @getsentry/workflow for triage.

**Comment by wedamija** [comment]
@piloos How long after you ignored the issue did you try sending another event? If you send another event after a few minutes, does it successfully move it to unresolved?

**Comment by piloos** [comment]
@wedamija it is definitely a couple of hours for a new event to occur after the issue was ignored.  Sending a new event does not always move the issue to unresolved.

**Comment by Louis-T** [comment]
Hi, I noticed the same problem with a self hosted instance of sentry (version 21.3.0) after ignoring an issue _until this occurs again one time from now_.

After occurring one time, the issue was "unignored" (meaning it wasn't ignored in the issue detailed page, and it wasn't muted either) but it did not show with the _is:unresolved_ filter.

Another error was triggered ~4min after the "ignore until" action, but it still did not show.

However, it did come back when yet another error occurred ~30min later.

**Comment by wedamija** [comment]
This is likely due to some delays we have during processing. Since Sentry receives a large number of events, we buffer writes to the `times_seen` counter on an issue for around 45 seconds before we write them to the table, which does a lot to prevent load on our primary database.

The issue here is that these writes don't end up happening before we evaluate whether to unignore an issue. So from the point of view of the system at the time, the issue hasn't been seen an additional time.

I don't think we're going to work on fixing this in the near term. One work around for this is to use `ignore this until it occurs one time per hour`. The time range forces us to make a query to our column store database, which will have this data available and should work just fine.

**Comment by wedamija** [comment]
I've made some changes to how we handle incoming events, so this issue should now be resolved.
