### ISSUE TITLE
Add List-ID header for email messages

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2461]
See: https://github.com/blog/695-easily-filter-notifications-by-repository

**Comment by tkaemming** [comment]
The List-ID specification is here: https://www.ietf.org/rfc/rfc2919.txt

**Comment by tkaemming** [comment]
Okay, so my thinking here is to set it up so that there is a "mailing list" per project, where the List-ID takes the form of `{project}.{organization}.{list-id-namespace}`. Any email sent via `MessageBuilder` with a `reference` attribute that is a `Project`, `Group`, or `Event` instance would map to the project mailing list.

For our use, the `list-id-namespace` would be `getsentry.com`. I am less sure for self-hosted installations — the RFC states:

> While it is perfectly acceptable for a list identifier to be completely independent of the domain name of the host machine servicing the mailing list, the owner of a mailing list MUST NOT generate list identifiers in any domain namespace for which they do not have authority.

So, this rules out `SMTP_HOSTNAME`, the domain part of `DEFAULT_FROM_EMAIL`, or the domain name from `system.url-prefix`. The RFC says you can use `localhost` as a default, which might make the most sense here:

> If the owner of the list does not have the authority to create a list identifier in a domain-based namespace, they may create unmanaged list identifiers in the special unmanaged domain "localhost".  This would apply to personal users, or users unable to afford domain name registration fees.

We could also generate the List-ID for self-hosted as `getsentry.com`, if we don't care about collisions. (Realistically, this isn't a significant issue, but it'd be nice for it not to be an issue at all.)
