### ISSUE TITLE
Receiving "An unknown error occoured." error

### ISSUE THREAD

**Issue by SerenModz21** [getsentry/sentry#24816]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Hello, I am trying to activate my [Education Pack](https://sentry.io/for/education/) receiving it from my [GitHub Student Developer Pack](https://education.github.com/?utm_source=github+sentry) but every time I press *"Activate Plan"*, I get a message saying *"An unknown error occurred."*.

The activate plan page:
![image](https://user-images.githubusercontent.com/41450647/112920130-42b33380-9100-11eb-999a-ac937674e3e3.png)

The error message that was shown after pressing *"Activate Plan"*:
![image](https://user-images.githubusercontent.com/41450647/112920207-68d8d380-9100-11eb-95e2-caa4088eb7f1.png)

I don't know what is wrong or how I could fix it. I have signed into the correct GitHub account and the correct Trello account.

## Steps to Reproduce

1. I went to https://sentry.io/for/education/
2. I signed in
3. I chose the organisation I want to use
4. I pressed *"Activate Plan"*

### What you expected to happen

I don't know what is wrong or how I could fix it. I have signed into the correct GitHub account and the correct Trello account.

**Comment by BYK** [comment]
Pinging @getsentry/enterprise as I think this falls under there. Pinging @EvanPurkhiser as I think he fixed something around this some time ago.

**Comment by EvanPurkhiser** [comment]
Hi there @SerenModz21,

I see the error but I can't say what the issue here is. I've added some more context to the error to better understand the problem.

When you have a chance could you give it another go? It's unfortunately a little hard to test this without actually being part of GitHubs student program :)

**Comment by SerenModz21** [comment]
> Hi there @SerenModz21,
> 
> I see the error but I can't say what the issue here is. I've added some more context to the error to better understand the problem.
> 
> When you have a chance could you give it another go? It's unfortunately a little hard to test this without actually being part of GitHubs student program :)

I will give it a try now

**Comment by SerenModz21** [comment]
Sadly, I still get that error

**Comment by EvanPurkhiser** [comment]
Sorry I should have been more clear :)

I added some additional error context capturing for this particular problem, I haven't actually resolved it yet, but it's hard for me to test since I don't actually have a GitHub student account! For whatever reason your github organization slug isn't being passed along with the activation request.

Are you changing the default selected org with the dropdown?

**Comment by SerenModz21** [comment]
Yes. I change it from "KyeKillerBot" to "TDA" as I don't want to activate it on the "KyeKillerBot" org
![image](https://user-images.githubusercontent.com/41450647/113465244-75279e00-942a-11eb-9e67-758f27d53682.png)

**Comment by brianthi** [comment]
It's been a while since the last message on this ticket. If this issue persists, please reach out to our [support team](https://sentry.zendesk.com/hc/en-us) and they can help you redeem the EDU pack.
