### ISSUE TITLE
Recipients are disclosed in the Reply-To

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#2481]
I realized I got an email with all recipients in the 'Reply-To' header.  Is that intentional because I have not setup the inbound mails feature?

UPDATE: It's happening at least since April, 2015 in my server.

**Comment by mattrobenolt** [comment]
This is correct behavior and intentional.

Is there a problem with doing this?

**Comment by mvaled** [comment]
In my env this is not an issue.  We all know each other and we're very open about what's going on with our system.  I just thought it may be an issue for other environments where privacy is a concern.

I'm closing this.

**Comment by mattrobenolt** [comment]
> I just thought it may be an issue for other environments where privacy is a concern.

Yeah, I'm not sure of this being true, since the list of project members is "public" inside Sentry anyways, and these members in reply-to will all be people who are a part of the project. I'd just argue that if you are sending around sensitive stuff that you don't want other teammates to see, they shouldn't be on the project.
