### ISSUE TITLE
Feature request: allow GitHub Integration between one GitHub org and multiple Sentry orgs

### ISSUE THREAD

**Issue by ChrisBAshton** [getsentry/sentry#24995]
## Summary

The [GitHub Integration](https://docs.sentry.io/product/integrations/github/) only allows one Sentry organisation to connect to a GitHub organisation. It should be possible for multiple Sentry organisations to connect to the same GitHub organisation.

## Motivation

I work for an organisation that has multiple departments. Each department manages its own Sentry organisation independently. However, we manage all of our code under the same GitHub organisation. Only one department can use the GitHub Integration as a result, as they've linked their department's Sentry account to the shared GitHub organisation.

Other teams would like to make use of the GitHub integration, but are unable to as it is linked to one department's Sentry account. This seems a somewhat arbitrary limitation, which we suspect affects other large organisations too.

## Additional Context

We've considered 3 options:

1. Splitting our GitHub organisation into multiple GitHub organisations
2. Consolidating all of our Sentry accounts into one
3. Leaving things as they are

Option 1 would require a lot of work, and the increased administrative and financial burden of managing multiple GitHub accounts, whilst quite possibly breaking other third-party integrations which rely on our repositories being under one GitHub org.

Option 2 would require a lot of work and co-ordination across multiple departments, and comes with the unacceptable downside that each department would share the same quota. We cannot justify the operational risk of one department's outage or misconfigured load test impacting the monitoring of other departments. This issue could therefore be interpreted as another feature request: the ability to set a per-team limit (rather than just per-project or an org-wide limit).

All things considered, we're going with option 3 for now, as we cannot justify that the workload and risk would be worth the benefit of the integration (even though we're really very keen to enable the [suspect commits](https://docs.sentry.io/product/sentry-basics/guides/integrate-frontend/configure-scms/) feature!). We would consider option 2 if there were a per-team rate limit, but the simplest solution would be to allow multiple Sentry orgs to connect to one GitHub org.

**Comment by BYK** [comment]
Pinging @getsentry/ecosystem for triage

**Comment by MeredithAnya** [comment]
@ChrisBAshton unless GitHub has changed how their GitHub Apps work, you can only install a GitHub App once per GH organization or GH user account. 

As you might have experienced, when you attempt to install the GitHub integration from a different Sentry organization it will you show on GitHub that it is already 'configured'. 

It is technically possible on our end to share an integration across Sentry organizations, as we do with other integrations. However, given GH's limitations I'm not sure how easy it would be to support this. We essentially are only allowed to do the OAuth flow once per GH organization. I don't know what the "install" flow would look like for the additional Sentry organization (with the GitHub App already installed on your GH organization).

Other concerns I have:
* Because the installation would be shared, any changes of repository permissions added would affect both Sentry organizations, and unless you gave access to all repositories, I could see it being very easy for someone to accidentally add/remove repositories without realizing which Sentry organization needed what. 
* In kind of the same vein, if you were ever to uninstall from GH's side, it would uninstall for both Sentry organizations. We don't have any control over the UI in GitHub so it's not like we could warn someone that they might be uninstalling the GitHub App for another Sentry organization that is using it.

**Comment by ChrisBAshton** [comment]
@MeredithAnya thank you for the fast triage and detailed comments. That does seem a bit of an insurmountable problem!

I'm pleased we've been able to document the pain points around the problem and the proposed solution.

It seems to me that there's little value in keeping this issue open, as it's unactionable. However, as noted in the feature request, one of the main barriers to us consolidating our departments onto one Sentry account is the lack of a team-level rate-limit; we're concerned that high volumes of errors associated with one department could impact the Sentry service of other departments. Shall I write up a separate feature request for a team-level rate-limiting feature (which would in effect supersede this one)?

**Comment by BYK** [comment]
@ChrisBAshton 
>However, as noted in the feature request, one of the main barriers to us consolidating our departments onto one Sentry account is the lack of a team-level rate-limit; we're concerned that high volumes of errors associated with one department could impact the Sentry service of other departments. Shall I write up a separate feature request for a team-level rate-limiting feature (which would in effect supersede this one)?

Yes, please file a new issue as a feature request so we can route it to the appropriate team and track it properly there.

Closing this issue as you suggested since it is not actionable for the foreseeable future.

Thanks a lot for sharing your thoughts and needs with us to help make Sentry better for everyone!

**Comment by ChrisBAshton** [comment]
Thanks @BYK - I've now raised #25037.
