### ISSUE TITLE
HTTP 500 for _static files

### ISSUE THREAD

**Issue by sul4bh** [getsentry/sentry#2517]
I just upgraded to rc2 and I get 500 for files that are in _static folder.
_static/1452116721/sentry/dist/vendor.js ---> 500

I followed the documentation here (https://docs.getsentry.com/on-premise/server/upgrading/)

What could be the cause for HTTP 500? Is the documentation missing some steps?

**Comment by dcramer** [comment]
@sul4bh do you see a stacktrace in Sentry's internal app or in the logs?

**Comment by sul4bh** [comment]
Yes,
Here is the trace: http://pastebin.com/DXJwgjjB

**Comment by mattrobenolt** [comment]
Was this working fine on rc1?

**Comment by mattrobenolt** [comment]
From that stacktrace, it looks like that's coming from the 404 page.

**Comment by sul4bh** [comment]
I was on 8.0.0dev (I guess). It was working fine.

The trace looks like the url was supposed to generate a 404 page but 404 page generation somehow failed.

**Comment by mattrobenolt** [comment]
Yeah, trying to figure out why it's a 404 in the first place.

Can you try deleting all pyc files?

`$ find /opt/sentry/local/lib/python2.7/site-packages/sentry/ -name '*.pyc' -delete`

Then restart processes?

**Comment by sul4bh** [comment]
Just did. It did not help.

**Comment by sul4bh** [comment]
If this helps:
* installed rc2 from github using pip
* running behind nginx
* using mysql database

**Comment by mattrobenolt** [comment]
Oh, you installed from GitHub? What exactly did you run?

You should install from pypi at least for most compatibility.

I think the case now is you're missing the static assets and they didn't get compiled, which is why it's getting a 404.

Can you uninstall and install from pypi to see? `pip install sentry==8.0.0rc2` should do it.

**Comment by mattrobenolt** [comment]
Also worth noting, as of 8.0, we don't officially support MySQL anymore. (unrelated, just an observation since you mentioned it)

**Comment by sul4bh** [comment]
I ran pip install --upgrade git+git://github.com/getsentry/sentry.git@8.0.0rc2
I tried installing from pip first but I got kombu version related error.

I noticed MySQL related change. I think, removing MySQL support was very opinionated. But django supports it. So I am hoping sentry will run on it.

**Comment by sul4bh** [comment]
Uninstalling and installing from pypi worked. Thanks.

**Comment by mattrobenolt** [comment]
Awesome. Thanks for confirming. :) I'm assuming how you installed it from GitHub like that, static assets weren't compiled correctly. (I've verifying this method locally to make sure we handle that case).

What's happening here is that the 404 page was erroring itself, so you're seeing a 500 because of the 404. If that makes sense. :)

Going to fix that up, and investigate how you installed it a bit more and see if this is a case we don't handle correctly.

**Comment by mattrobenolt** [comment]
Fixed 404 page erroring here: https://github.com/getsentry/sentry/commit/c954e18fc9374b620ca3bcff4ef40a712e872ae1

**Comment by mattrobenolt** [comment]
And fixed installing from git with https://github.com/getsentry/sentry/commit/f91afbcbd5ef8818c9b4e2de1b68839190fb768d
