### ISSUE TITLE
Cannot digest timeline, timeline is not in the ready state.

### ISSUE THREAD

**Issue by MartyRong** [getsentry/sentry#2542]
when run "sentry celery beat",it throw 
 File "/home/bot/services/pyenv27/lib/python2.7/site-packages/sentry/digests/backends/redis.py", line 402, in digest
    raise Exception('Cannot digest timeline, timeline is not in the ready state.')

Message Error: Couldn't apply scheduled task schedule-digests: Cannot digest timeline, timeline is not in the ready state.

**Comment by MartyRong** [comment]
whether if the key too long lead to this，error message too long

**Comment by tkaemming** [comment]
This is primarily a diagnostic message and only is an issue if it is happening repeatedly. It usually happens if a lot of errors are being reported for a project very quickly while an email is already being constructed and sent. If this is the case, you wouldn't be receiving any emails for the project that is having problems.

**Comment by tkaemming** [comment]
This will only be logged at an `INFO` level now. If you're not receiving emails *at all*, let us know, but otherwise this is generally safe to ignore.

**Comment by MartyRong** [comment]
You're right. Thanks  :） 
 Good evening。 Greetings from across the Pacific
