### ISSUE TITLE
sourcemap is missing for certain error, but it's working for others. 

### ISSUE THREAD

**Issue by lambdanetwork** [getsentry/sentry#25613]
## Important Details

I encountered issues where for certain error there is sourcemap available, but for other there will be an error shown (like image below) that source code was not found
<img width="1237" alt="Screenshot 2021-04-26 at 11 27 52" src="https://user-images.githubusercontent.com/58059627/116040979-40141180-a69f-11eb-994e-247cc5bfd18c.png">

I have checked that the minified code has sourceMappingURL and it's verified when I check it with this link https://sourcemaps.io/
<img width="1251" alt="Screenshot 2021-04-26 at 14 43 54" src="https://user-images.githubusercontent.com/58059627/116041012-499d7980-a69f-11eb-899f-39f8a2c3ec71.png">

Here is the javascript url: https://cdnmambet-a.akamaihd.net/booyah/build/pc/static/js/2.2f0eba06.chunk.js

How are you running Sentry?

On-Premise w/ Docker, version 9.1.2

## Description

Some error has sourcemap, while other error does not have sourcemap.

## Steps to Reproduce
Normal error report using "@sentry/react"

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

All error has sourcemap, or all error has no sourcemap.

**Comment by BYK** [comment]
Pinging @kamilogorek and @lobsterkatie for triage/help :)

**Comment by kamilogorek** [comment]
"Source code was not found" is `JS_MISSING_SOURCE` error from https://github.com/getsentry/sentry/blob/c51e74dfb91fcf88d2642c536507f2a0d974422d/src/sentry/lang/javascript/processor.py
which is most likely caused by the on-prem instance being unable to fetch the source file that `abs_url` is pointing to. Unfortunatelly that's all I know here.

**Comment by lobsterkatie** [comment]
Have you uploaded the source maps and the bundle files to your sentry instance? This is an error about source maps being missing, not invalid.

**Comment by lambdanetwork** [comment]
We haven't try to upload the sourcemaps directly.
Because on our sentry, some of the error actually has sourcemap, 
Image below are the same version with image above, and the sourcemap shows. 
<img width="1206" alt="Screenshot 2021-04-29 at 10 03 20" src="https://user-images.githubusercontent.com/58059627/116493856-2b6b8f80-a8d2-11eb-8efa-2de5e9003bc5.png">


I expect that when all error has NO source map, then we will have to upload the sourcemap for all.
Because uploading sourcemap means we have to change our code, and check it the version matches. 

What do you think about the above problems: some has sourcemap and some has not.
also In your opinion what is the best way for us to go?

**Comment by lobsterkatie** [comment]
If you're not uploading any source maps, then the instances in which it works represent your sentry server being able to find both the minified file and the source map online, and conversely, the instances in which it doesn't work represent it searching online and not finding one or both of those files.

So, for instance, if on Monday you deploy `main.bundle.a1b2c3.js` (and its associated source map) and on Tuesday you deploy a new version, `main.bundle.d4e5f6.js`, anyone who loads your site on Monday and has an error originating in the main bundle file will get their error correctly source mapped. But if that same person has left their tab open, and runs into another error in the main bundle on Tuesday, that error won't be source-mapped correctly, because your server will be unable to download `main.bundle.a1b2c3.js` (assuming you don't host all previous versions of the bundle file in addition to the current one). The advantage of uploading, then, is that once you've done that, the files are there and you never have to worry about it again.

**Comment by lambdanetwork** [comment]
thanks
