### ISSUE TITLE
Sentry clients for c++ version?

### ISSUE THREAD

**Issue by hustcc** [getsentry/sentry#2583]
I did not found Sentry client. for c++ language. Where can I find or how can I write one?
![image](https://cloud.githubusercontent.com/assets/7856674/12500823/a69ae184-c0f1-11e5-986f-53da3dd5fd1f.png)

**Comment by mattrobenolt** [comment]
Hey! The only client I know if is https://github.com/truszkowski/raven-cpp which, unfortunately, won't work at all since it's UDP, and we haven't supported UDP for a while.

But if you're interested in writing a client, we'd all happily support and help as much as we can, and we have full docs here: https://docs.getsentry.com/on-premise/clientdev/

**Comment by hustcc** [comment]
I hava scaned his code, maybe not very profect, do not follow the [guide](https://docs.getsentry.com/on-premise/clientdev/).

I also review the code of python client, supported all kinds of web server and all kinds of running environment. In cpp, the running environment is relatively simple, the code maybe not very hard.

Maybe I can write one client with c# reference.

**Comment by mattrobenolt** [comment]
Let us know if you get something up and working. :) We're also available on Freenode in `#sentry` if you want to ask questions. You can ping me `mattrobenolt`.

**Comment by tsondergaard** [comment]
For (C++) coredump support on Linux you could try my raven-coredump script: https://github.com/tsondergaard/raven-crashdump/blob/master/README.md
