### ISSUE TITLE
Execute migrations from dependences(celery, kombu)

### ISSUE THREAD

**Issue by nielsonsantana** [getsentry/sentry#2589]
When I execute `sentry upgrade`, only migrantions from sentry are applied.
How can I run migrations from dependences like celery, kombu.
After try start the celery work, this problem displaied:

    ProgrammingError: relation "djkombu_queue" does not exist
    app[celery_worker.1]: LINE 1: ..."djkombu_queue"."id", "djkombu_queue"."name" FROM "djkombu_q...

**Comment by mattrobenolt** [comment]
We don't support running Celery with the Postgres backend. We require either Redis or RabbitMQ.

**Comment by nielsonsantana** [comment]
Greate! Working now! 
Thanks

**Comment by jean** [comment]
In this case, is it maybe a good idea to change broker to redis in https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L361 ?

**Comment by mattrobenolt** [comment]
@jean yeah, that's probably fair. This default gets overridden when you run a `sentry init` and we spit this out: https://github.com/getsentry/sentry/blob/master/src/sentry/data/config/sentry.conf.py.default#L66

I might as well update here as well since we don't ever want to use the `django://` `BROKER_URL`.

**Comment by mattrobenolt** [comment]
@jean see #3471

**Comment by jean** [comment]
@mattrobenolt thanks :-) because I'm an idiot and I have limited time, I was stuck at that stupid `djkombu_queue` error for a couple of months .
