### ISSUE TITLE
ELB health check fails - Bad Request (400)

### ISSUE THREAD

**Issue by DaveBlooman** [getsentry/sentry#2590]
I have setup a basic instance on EC2 with Sentry sitting behind an ELB.  Initially it seemed to work, but after a couple minutes i started seeing Bad Request (400), then my health check failed.  On the instance i see in the logs the health check fails but i'm unsure why

```sh
Jan 23 22:20:17 ip-***** supervisord: sentry-web ***** - - [23/Jan/2016:22:20:17 +0000] "GET /_health/ HTTP/1.1" 400 26 "-" "ELB-HealthChecker/1.0"
```

**Comment by mattrobenolt** [comment]
So this was recently brought to our attention in our IRC channel, #sentry, and it turns out, ELB doesn't send a `Host` header with it's health checks, which is why this fails since we do a strict check based on the `system.url-prefix` config setting.

`/_health/` is also not a great endpoint to use for health checking from a load balancer, which is a separate issue. `/_health/` reports information about the status of your Celery workers, and will fail if workers are not running, etc. Which isn't useful for a load balancer.

We need to think about this slightly differently and ideally, expose a load balancer friendly endpoint that bypasses the `Host` validation and simply returns a `200 OK` with no other checking.

If you are hosting this with nginx, you could simply add a route to nginx and do something like:

```nginx
location = /_health/ { return 200; }
```

This will obviously help with reporting that the host is online and working, but doesn't necessary say if the backing sentry process is running.

/cc @dcramer

**Comment by DaveBlooman** [comment]
An ELB friendly URL would be nice, even it is just a `OK` statement.  I might have to hold off until this feature is complete, thanks for the response.

**Comment by mattrobenolt** [comment]
@DaveBlooman Is this a blocker for running Sentry entirely? Do you mind explaining your setup a bit? Or you can email me offline if you'd rather not disclose publicly. matt [at] getsentry

**Comment by DaveBlooman** [comment]
I have a simple CF setup at the moment - https://github.com/acervos/sentry, but I would rather not fudge the ELB health check, I am going for a HA setup, so ensuring uptime is essential.
