### ISSUE TITLE
User defined theme colors

### ISSUE THREAD

**Issue by Sorien** [getsentry/sentry#26067]
## Summary

User defined theme colors 

## Motivation

we are using sentry in docker so question is there any way how to edit color palette? it's probably just my opinion but there is too much pinkish colors in dark theme ...

**Comment by BYK** [comment]
Sorry, this is not an option. You may dive into the code and change our CSS styles but I think that's a very heavy-handed solution to a mere annoyance.

Tools like [Stylish](https://userstyles.org/) might be better options.

**Comment by Sorien** [comment]
if I create a new dark theme is there any chance that it would be merged to master?

**Comment by BYK** [comment]
To be honest, very unlikely as it would incur maintenance costs. But let me ping @getsentry/design and @billyvg who was leading the project to get their perspective directly instead of putting words into their mouths.

Here's more information around how we approached building dark mode and what making changes to it incurs: https://blog.sentry.io/2021/03/16/building-dark-mode/

**Comment by Sorien** [comment]
s/t like 
![image](https://user-images.githubusercontent.com/1270275/118492065-ef348d80-b71f-11eb-8f05-17b043506acf.png)

from 

![image](https://user-images.githubusercontent.com/1270275/118492023-e04ddb00-b71f-11eb-8e40-83518765d314.png)

**Comment by billyvg** [comment]
Yeah, like BYK said - we don't really have the resources atm to support a user defined theme, or adding another dark theme. It's already difficult enough to maintain light + dark modes.
