### ISSUE TITLE
throw error on failure to insert or update in create_or_update

### ISSUE THREAD

**Issue by ehfeng** [getsentry/sentry#2611]
Should BaseManager.objects.create_or_update throw an exception when it fails to create or insert? 

Currently, we return (0, False)

**Comment by mattrobenolt** [comment]
To be clear about the issue here:

The problem was the `INSERT` failed and triggered an `IntegrityError` out of human error. The value being inserted was `NULL` in a non-`NULL`able column. So the `IntegrityError` was picked up and treated as a row already existed. So went to the `UPDATE` path, which then returned 0 rows since the row didn't really exist.

This made it hard to figure out what the issue was.

Need to figure out if we can determine the difference.

If we can't, and we updated 0 rows, this is likely a case to re-raise the original `IntegrityError`.

**Comment by tkaemming** [comment]
> Need to figure out if we can determine the difference.

Couldn't we figure this out just by running the `UPDATE` first and checking how many rows were affected?

**Comment by mattrobenolt** [comment]
Yeah.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
