### ISSUE TITLE
Android proguard handling

### ISSUE THREAD

**Issue by thierryxing** [getsentry/sentry#2613]
Does somebody manage to see de-obfuscated stacktrace on Sentry when the Android app source is obfuscated with Proguard ?

**Comment by tkaemming** [comment]
Right now, Sentry doesn't support decoding stacktraces that were output by code that was obfuscated with ProGuard. From my understanding, this feature should be possible to implement with the [plugin preprocessing hooks](https://github.com/getsentry/sentry/blob/master/src/sentry/plugins/base/v2.py#L346-L358) and [release files](https://github.com/getsentry/sentry/blob/master/src/sentry/models/releasefile.py), similar to how we handle dealing with rewriting stack traces that were generated by minified JavaScript.

We don't have any immediate plans to implement this as part of the Sentry core, but we may look into implementing it as a plugin in the future. We're also always pleased to recommend quality third-party plugins or include them as part of hosted Sentry if it's something that you'd be interested in implementing independently.

In the meantime, I'm going to close this ticket since it's not really an issue, but more of a question/feature request, which we'll keep in mind for the future. Thanks!

**Comment by thierryxing** [comment]
OK, I got it ,thanks a lot.
Maybe I will try to write a plugin for this feature ;-)
