### ISSUE TITLE
@mentions in comments should trigger email notifications to mentioned users

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2634]
Users have reported that it would be useful to mention users in comments and have them be notified. Right now this does nothing.

**Comment by dcramer** [comment]
I dont feel this is important. People want it because they're used to other tools, but those other tools have wide reaching scopes where you *need* mentions (e.g. GitHub).

In Sentry comments already go to your team members. It's unlikely team members are unsubscribing from notifications of comments as they're hugely valuable. If too many people are getting notified about comments it's likely that your team needs broken up into multiple teams (or in the future, simply multiple projects).

**Comment by cneller** [comment]
@dcramer I definitely see your point that the team level should handle this.  That said, it is such a common function in similar systems that I suspect customers will continue to expect it to be there and ask for the feature. 

I've used Sentry with several different teams, and I've always struggled to keep the team engaged with the tool.  In general - virtually without exception - team members get to the point where they ignore it all together.  Any feature that could improve the signal-to-noise ratio will only improve the value of your tool & service by helping keep teams engaged with the tool.

**Comment by dcramer** [comment]
@cneller let's say we email people on mentions -- how does that differ from today? If you're already ignoring the comment emails, why would you not ignore the ones where you're mentioned?

**Comment by jbrooksuk** [comment]
Being mentioned in something has more importance than just a system notification, no?

**Comment by dcramer** [comment]
I'm going to backpedal on my views here and say we should do this. I think it that whle for notifications it's less significant, for general workflow it's useful and engaging. There's some complexity in how we do it since we use email addresses instead of usernames now, but if we can sort that out we should be good.

**Comment by benvinegar** [comment]
Implemented in #5255.
