### ISSUE TITLE
GitHub Enterprise Integration Problem

### ISSUE THREAD

**Issue by mentorplatform190** [getsentry/sentry#26728]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version x.y.z

Saas (sentry.io)

Other, version x.y.z, [using for python on free trial]

## Description

[What happened]

## Steps to Reproduce

1. [Trying to add Github Enterprise App]
2. [After Clicking on installation and filling out all the details when I click on submit button]
3. [github enterprise app is not being installed also no configuration are present]

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

[Expected Github Enterprise app should be added with given configurations]

**Comment by BYK** [comment]
You issue is lacking critical information for us to act on it:

- Your Sentry version (or whether you are using sentry.io or not)
- Some screenshots or logs

Please provide these for us to be able to diagnose the issue.

PS: This sounds related to #26281.

**Comment by pa1op** [comment]
It seems to me that sentry is trying to authenticate with GitHub Enterprise by passing OAuth access token as query parameter. This is deprecated in github and oauth access tokens should be passed in headers. Could this be fixed so that we can use self-hosted sentry with new Github Enterprise versions?

From sentry web pod logs: 
`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://github.devcloud.mycorp.com/api/v3/user/installations?access_token=<mytoken>`

Response from github when trying to access the same address:
`{
  "message": "Must specify access token via Authorization header",
  "documentation_url": "https://docs.github.com/enterprise/3.0/v3/#oauth2-token-sent-in-a-header"
}`

Github access_token query parameter deprecation notice:
https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
