### ISSUE TITLE
Track received vs occurred timestamp

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2702]
Often we see issues where events occurred at X time (usually this is wrong, and its a timezone issue), and then received by sentry at Y. This causes some confusion in Sentry, because in most cases all you care about is when the server received it.

We should add an additional timestamp which is "received at", which is the time when Sentry has gotten the event. The event metadata would still store the origin time, but things like first seen/last seen/charts would reflect the time it was received.

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry/issues/2577

**Comment by tkaemming** [comment]
> Often we see issues where events were recorded at X time (usually this is wrong, and its a timezone issue), and then received by sentry at Y. This causes some confusion in Sentry, because in most cases all you care about is when the server received it.

I disagree with this and I think that this is an oversimplification of the scenario, especially if we're planning on targeting mobile applications where there is potentially unbounded latency between when the exception is logged and the device is able to access the network to send the report. From what I've seen, we don't get very many questions/complaints about this, and changing the current behavior to suit what seems to be the uncommon case at the expense of real use cases where it is beneficial seems like the wrong approach. 

> We should add an additional timestamp which is "reported at", which is the time when Sentry has gotten the event.

I think this is a good idea (although I think "reported" is the wrong verb — "received" seems more accurate.) I also think that it would be useful to be able to show the latency between when the payload was generated and when the server received it. It would also be helpful to display somewhere (maybe the organization stats page?) the latency percentiles so that we can quickly diagnose these issues instead of having to dig into logs or just guess, which seems to really be the only way to identify these issues at the moment.

> The event metadata would still store the origin time, but things like first seen/last seen/charts would reflect the time it was received.

I disagree with changing the graphs. It also doesn't (or at least I hope it doesn't — I haven't confirmed this, but I am pretty sure this is correct) match the behavior of the implementation of first and last seen which add another point of confusion, especially considering how that data is basically shown side by side.

**Comment by dcramer** [comment]
I pretty much agree with ted here. We need uniformity, and need to clarify things on the org stats page. We also likely need to ensure "last seen" is clear what it represents, and have the ability to both record and sort the seen (generated?) in addition to received.

**Comment by tkaemming** [comment]
For posterity, adapted from internal chat: I think that all graphs should be based on client provided timestamps (graphs could also be configurable if we record time series data for both the client provided timestamp and the server received timestamp), with the exception of any graphs specifically dealing with ingestion rates (e.g. organization statistics as they relate to quota usage, other system health graphs, etc.)

**Comment by dcramer** [comment]
I think we're content w/ this for now. Sampling/etc is based on received timestamp. We can definitely expand on this, but its at least a lot better.
