### ISSUE TITLE
Tooltips on 14 day graphs have incorrect hour intervals

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2717]
![image](https://cloud.githubusercontent.com/assets/2153/13185465/28aff348-d6f6-11e5-99af-5a6771467189.png)

This should say "12:00 AM to 11:59 PM", or we should just drop the hours entirely.

**Comment by mitsuhiko** [comment]
Related issue: it uses a custom format string that does not translate into other languages meaningfully.

**Comment by kengruven** [comment]
@mitsuhiko: That could explain #2716, then!

**Comment by mitsuhiko** [comment]
We should only be using localized format strings going forward: http://momentjs.com/docs/#/displaying/format/

(Search for `LLLL` and friends on that page. Unfortunately the docs are very java script and you cannot jump to anchors)

**Comment by tkaemming** [comment]
This was half-fixed with GH-2749, which ensures charts maintain a consistent interval over their duration. 

However, when displaying the 14 day graph, the tooltip for each 24 hour interval only shows the date (not including the time), which is misleading since these graphs are now fixed to UTC day boundaries.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
