### ISSUE TITLE
Keep on getting a postgres SQL Operational Error about transactions

### ISSUE THREAD

**Issue by esn89** [getsentry/sentry#2776]
Lately, my sentry-worker (as set up in supervisor as per: https://docs.getsentry.com/on-premise/server/installation/#configure-supervisord) keeps on throwing this stack trace in my error logs.

This has gotten to the point where my getsentry instance even reports this as an error: 
https://i.imgur.com/ixUbgzo.png

[a stacktrace here](http://pastebin.com/qcHjbg57)

I'm really stuck as to what's going on.  I tried reinstalling postgresql, restarting all the processes, to no avail.  Has anyone ever gotten this before?

**Comment by mattrobenolt** [comment]
I'm not entirely sure what the issue here is, but it sounds like the data directory for your postgres install got corrupted somehow.

I've never personally seen this error, but it's definitely an issue with the postgres filesystem itself. My guess is a bad disk? A quick Googling of such thing suggests that you should restore from a backup. I also don't find much information.

Also, what version of postgres are you running? I read some other stuff that maybe suggests this is an error in older versions, 8.1.x era.

**Comment by esn89** [comment]
After doing some googling, it does look that way.  Right now I'm running postgresql-9.3.  I think I will have to restore from a backup then.
