### ISSUE TITLE
Most of the events in sentry are 'Sentry responded with an error: timed out'

### ISSUE THREAD

**Issue by NotSqrt** [getsentry/sentry#2803]
Hi,

I've got a Celery worker on my project that has to send errors to sentry.
I guess most of the errors time out after 1 second (the default value).
The timeout error is then printed by raven, and celery logs it back to the ``'celery.redirected'`` logger as warning, and that warning is sent to sentry successfully.

I added ``"%(msecs)"`` to the ``log-format`` of uwsgi, and I indeed see some requests over 1 second, while most are around 100ms.

Where can I filter the events sent to Sentry to avoid seeing so many ``Sentry responded with an error: timed out``, and eliminating the risk of amplification ?

Thanks !

**Comment by dcramer** [comment]
I'd highly recommend reading a recent post on our blog:

http://blog.getsentry.com/2016/02/09/what-is-crash-reporting.html

The issue here is you're "logging" to Sentry. You can simply change your logging configuration to not send 'celery.redirected' to Sentry. In a near future Sentry will be moving away from using log handlers to capture errors.
