### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by ashwin31** [getsentry/sentry#2816]
I am developing opensource project management tool to create tickets based on sentry issues.

The api is not working for me,
https://docs.getsentry.com/on-premise/api/ couldn't find way to get authentication key for /api/0/organizations/ and got error {"detail": "Authentication credentials were not provided."}

please update documentation or let me know if i am missing something.

**Comment by dcramer** [comment]
The keys are all generated via the same means, and are all going to be organization-bound. You generate them via the "API Keys" page.

**Comment by ryanbagwell** [comment]
@ashwin31 

I was having some problems with this as well. I think the problem is there's a difference between an "API key" and an "authentication token." All of the examples in the docs use authentication tokens passed in the Auth header. When using an api key, you have to pass it as the username, like ```curl -u [your api key]: http://sentryapi.com```

I have not actually found where I can create an authentication token in the admin.

**Comment by dcramer** [comment]
Tokens are created within an individual account and are bound to the user. API Keys are disabled by default in Sentry now unless you previously had created them.

**Comment by ryanbagwell** [comment]
Thanks. We're still on 8.4 and can create api keys. Will upgrade to 8.5.

**Comment by jazoom** [comment]
I was surprised to find out today that my process for uploading releases/sourcemaps to sentry failed due to "invalid token". This process had been working fine for the better part of a year and all of a sudden just didn't. It took me a while to work out what was going on. Apparently whatever (key?) I had been using before, just disappeared. I created a token and tried that and it worked.

Might it have disappeared when I changed the name/domain of the project?
