### ISSUE TITLE
Searching exception body

### ISSUE THREAD

**Issue by jszwedko** [getsentry/sentry#2817]
Hi all,

It looks like when searching with plaintext, Sentry does not search the exception associated with a given issue (this is somewhat confirmed by looking at what is indexed in Elastic Search (https://github.com/getsentry/sentry/blob/930cbca0e99db519edca117580680c5005b17b01/src/sentry/search/elastic_search/backend.py#L52)).

Is this intentional (I realize that not all events have this data)? Or would it be possible to also index the exception as well?

Thank you!

**Comment by dcramer** [comment]
We're working towards expanding search, but today Sentry more or less only does:

- exact matches on tags
- partial matches on the canonical (most recent) "message" and "culprit"

The Elastic Search stuff actually was never used and was committed more as a prototype. Today everything is built on top of SQL, and because of the heaviness of events, and the complexity of good search we've chosen not yet to do extreme indexing on terms.

I'm going to close this, not because we won't do this, but because we're going to be actively improving this but we're not making commitments yet to what that means.

**Comment by jszwedko** [comment]
@dcramer thank you for the additional context!

**Comment by gnumoksha** [comment]
I also need this feature :)

**Comment by DroneZzZko** [comment]
any update?

**Comment by dcramer** [comment]
This ticket was closed three years ago and search is drastically different than it was then. Locking this conversation to avoid house.
