### ISSUE TITLE
Early Adopters: Team Stats 📊

### ISSUE THREAD

**Issue by adhiraj** [getsentry/sentry#28405]
## Problem

Sentry is good at surfacing and helping diagnose specific problems, but it can be much better at enabling teams understand the overall health of their projects and whether they're using Sentry effectively to improve the metrics they care about.

## Solution Brainstorm

A set of reports on application health and team engagement.

##### Stability
- Crash rate
- New, regressed, and unignored issues
- Top Issues by frequency
##### Performance
- User misery of key transactions
- Top performance regressions
##### Release Velocity
- Release Frequency
- % of releases rolled back
- Lead time: time from master to production
##### Engagement
- Issues viewed, assigned, ignored, resolved, and deleted
- Average issue age and time to resolution
- Number of alerts generated and actioned

## Feedback
We're currently developing this feature. If you're interested in early access, please leave a reaction/comment below and/or email workflow-feedback@sentry.io.

**Comment by jdschmitt** [comment]
> Whether they're using Sentry effectively

This is something I'd love to see. For a given project, I can see the most frequent events over a given time interval but are teams paying attention to those? As one example, if I wanted to set a goal of addressing all events seen more than X times in Y hours, how could a track that we're meeting that goal?

How can we set engagement goals so that Sentry isn't a just a place where you go when you're troubleshooting but the source of signals when things need attention?

**Comment by BobbyJohansen** [comment]
Something that would be nice to see is under stability a mean time to recovery or resolution trend/stat (MTTR). This is just as important of a metric for teams to know how quickly we can resolve issues when they come up. Are we alleviating customer pain quickly enough? Are the problems we are running into hard or easy to recover from? This is a good metric for leadership to understand so that it can be determined if time should be invested in solving the root cause of the problem or in creating a tool to help remediate the issue after it happens e.g. prevention vs ease of remediation.

**Comment by silverroots** [comment]
For Stability - I would also like to see ANR as a separate category to measure/track?
For performance -  It would be great if these metrics also support percentile for user/session based?

**Comment by adhiraj** [comment]
v1 of this is available at https://sentry.io/organizations/{your-org-slug}/stats/team/ (only on the Business plan for now).

![sentry io_organizations_sentry_stats_team_](https://user-images.githubusercontent.com/693121/141015328-1165c187-f209-42f1-af70-fa9a41030788.png)

**Comment by gimp87** [comment]
gh pr checkout 31190
