### ISSUE TITLE
Allow to search by log level range.

### ISSUE THREAD

**Issue by msjaiswal** [getsentry/sentry#2917]
We should be able to search by "minimum level". For example if I set "level:warning", it should return result of level warning, error or fatal. If I set "level:error", it should return result of level error or fatal. 

This is in very much in sync with how log level works.

**Comment by dcramer** [comment]
It's important to note that Sentry is for errors and while we support the level tag (for historical reasons) sentry doesn't *really* know what it means, or that it's a range. We will likely support enum selections when we introduce a future priority concept but it's unlikely we will apply this to level as we're trying to remove the "sentry is logging" misinterpretation.

**Comment by msjaiswal** [comment]
"level" indicates the severity of the error and as far as I understand, sentry is all about errors and exceptions (at least as of now). Level should indeed be a first class citizen on Sentry. Level is already treated in special manner signified by colours that we use i.e red for error, yellow for warning etc. I find this so useful personally. Continuing to give a special status to level should be worth it. 

<img width="241" alt="screen shot 2016-03-28 at 9 43 21 pm" src="https://cloud.githubusercontent.com/assets/1758886/14082536/282c6c20-f52e-11e5-873f-03207989144e.png">

All this being said, there is certainly direction that you are driving sentry as a product. I respect that. Just wanted to put my two cents.

**Comment by dcramer** [comment]
@msjaiswal level pretty much exists because of ``log.info``, not because there is an "info level" error. It does makes sense in some cases like warning, when its less critical, but even that is a lie we convince ourselves of. We tried killing it as we don't think its the best representation of things, but there was a lot of push back since people were (mis)using it in Sentry. In the future our goal is to allow you to both manually and rule-based define a priority of events, similar to an issue tracker. This priority may be high because its a billing error, or low because it's not user facing. The important thing though, will be that it actually reflects the kind of data Sentry captures, instead of hooks on to a legacy concept.

We'll continue to support level when there are log-style events sent, but it will slowly play less and less of a role in the UI.

**Comment by msjaiswal** [comment]
Sounds like a plan. Thank you for your explanation. Appreciate it.
