### ISSUE TITLE
Bad Request (400) - missing Django's ALLOWED_HOSTS

### ISSUE THREAD

**Issue by zarnovican** [getsentry/sentry#2974]
#### Bad Request (400) problem

Community version of Sentry web server is returning HTTP 400 right on the first hit. This is due to Django rejecting queries for Host header not matching his `ALLOWED_HOSTS`.

```
GET / HTTP/1.1
Host: sentry.example.com:9000
User-Agent: curl/7.43.0
Accept: */*

HTTP/1.1 400 BAD REQUEST
Vary: Accept-Language
Content-Length: 26
Content-Type: text/html
Content-Language: en-us

<h1>Bad Request (400)</h1>
```
Same issue happens when Sentry is behind Nginx reverse proxy (and/or SSL).

There is no info in logs pointing to the root-cause. If you turn on Django `DEBUG = True`, it will disable the ALLOWED_HOSTS check and everything magically works.

#### Workaround

Add your domain to `sentry.conf.py`:
```
ALLOWED_HOSTS = ['.example.com', ]
```

I believe, it should be documented at the very least.

#### Versions

```
Django (1.6.11)
sentry (8.3.0)
uWSGI (2.0.12)
```

#### Not-completely-unrelated-issue

When you do not have ALLOWED_HOSTS configured _and_ your `mail.backend: 'dummy'`, you will get this nice stacktrace:
```
     klass = import_by_path(backend or settings.EMAIL_BACKEND)
   File "/www/sentry/local/lib/python2.7/site-packages/sentry/../django/utils/module_loading.py", line 19, in import_by_path
     error_prefix, dotted_path))
 django.core.exceptions.ImproperlyConfigured: dummy doesn't look like a module path
```
Workaround for that is to specify module path `mail.backend: django.core.mail.backends.dummy.EmailBackend`. What's interesting, I haven't seen that problem after fixing the ALLOWED_HOSTS issue.

**Comment by mattrobenolt** [comment]
We set ALLOWED_HOSTS automatically if you declare `system.url-prefix` to the correct host. The only time you really need to set this manually is if you're doing a non-traditional setup, like, needing to be accessible via multiple hostnames. Otherwise we handle this automatically.

As for the second issue, this is a side effect. I'll fix this behavior to be a bit more sensible. It's related to changes in 8.3, but don't affect correct setups and only happens when `DEBUG = True`.
