### ISSUE TITLE
Select a default organization to load

### ISSUE THREAD

**Issue by jacob-v-dam** [getsentry/sentry#3040]
When you login on Sentry a organization is loaded (if used). But in my case an organization is displayed which I don't use that often. It would be nice to set the default organization to load, this makes it easier to use.

**Comment by dcramer** [comment]
Currently the most recently used organization is what's used the next time you visit Sentry. I'm a bit against having some kind of selector here, as multiple organizations aren't overly common to begin with. Happy to hear more reasoning around this, but otherwise it's unlikely we'll add this feature with the way things are right now.

**Comment by Christilut** [comment]
Hey I found this issue because I have the same problem.

My default org is one I don't use a lot and it keeps switching back to it every time I do something. For example if I delete a project from org B then it goes back to the default org A dashboard.

So I'm not sure how it works what you described above, but my default org doesn't seem to change at all right now.

**Comment by dcramer** [comment]
This ticket is super old, but what you're describing above sounds like a bug more than any behavior with defaults.

**Comment by Christilut** [comment]
Yeah, would you like me to make a new issue?
