### ISSUE TITLE
Stats graph misrepresents values

### ISSUE THREAD

**Issue by mitchhentges** [getsentry/sentry#3041]
Maybe I'm looking at the graph wrong, but it looks like it's not showing each value independently.
![2016-04-12-143334_1041x128_scrot](https://cloud.githubusercontent.com/assets/7784737/14460023/89b397d2-00bb-11e6-81fa-89e0d1d60ab0.png)

So, `8 accepted`, `0 dropped (RL)`, and `0 dropped (BL)`
![2016-04-12-143416_1023x296_scrot](https://cloud.githubusercontent.com/assets/7784737/14460045/a186e3e6-00bb-11e6-83f0-a69bebf8e65a.png)

In the actual graph, right after April 12, it looks like all three values reach ~6. Since no requests were dropped (for any reason), shouldn't the red and orange lines still be at 0, and only the blue area should stretch up?

Additionally, shouldn't the blue line go all the way to 8, not just to 6?

**Comment by mattrobenolt** [comment]
The graphs are stacked, so the orange and red lines are still at 0. If you hover over the graph, it'd become more clear since a tooltip would spell out the values.

As for 8 vs 6, if you look at the graph closely, there are 2 points there, one going up to 6, the other going up to 2 right after it. It makes the graph curving down slightly. Again, you'd see this by hovering over the points in the tooltip.
