### ISSUE TITLE
Add Custom Commands for Queue Workers and Beat

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3046]
Currently we have a "sentry celery" command which dispatches to the celery command line interface. This has worked quite well in the past but there are a huge amount of options on this, some of which completely break our setup.  In particular the `-B` flag is known to cause many different issues where file descriptors randomly close or become different files (case in point: https://github.com/getsentry/sentry/issues/3044).

This way we could control exactly which features we support.

**Comment by mattrobenolt** [comment]
The first idea is that we'd reserve completely new commands for when we replace celery entirely. My first plan was to outright replace `sentry celery beat` with `sentry cron`, but this new `cron` would be 100% different and not just call out to `celery beat`.

I mention this because if/when we move to new commands, I'd rather the CLI args match what we want for our new tool, and not try to port the existing ones from `celery` into these commands. If we port commands, that means we are going to either conform our new replacements to _look_ like celery, or we'll be breaking compatibility again.

My plan was to replace `sentry celery {beat|worker}` with our own wrappers in `click`. This way we can start reducing the public footprint and even set some defaults ourselves/read settings from `config.yml`, etc. With this shim, we can remove features such as `-B` and keep only the ones needed without outright using a new top level command and migration will be painless.

**Comment by mattrobenolt** [comment]
Note, this also allows us to catch `-B` and deprecate it and yell loudly. "Hey, stop doing this! Run `sentry celery beat` instead."

**Comment by mitsuhiko** [comment]
@mattrobenolt we could also detect -B and spawn a process outselves for beat. But i dislike the idea of running a beat with each worker anyways so not sure if that's a good idea.

**Comment by mattrobenolt** [comment]
> we could also detect -B and spawn a process outselves for beat. But i dislike the idea of running a beat with each worker anyways so not sure if that's a good idea.

I see no value in doing that. People are capable of running multiple processes and we make it pretty easy to do so. Saving 1 process doesn't help anything if it only causes problems and more work for us to maintain.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
