### ISSUE TITLE
Project created with API call, doesn't show on interface, but is listed when calling API

### ISSUE THREAD

**Issue by miniyuuzhan** [getsentry/sentry#3079]
Hi, 

So basicaly, I have a ghost project in my sentry database.
A week ago I created a few test projects using Create new project API endpoint calls.
All worked fine, I was able to see in them in the interface.

5 days later I had to delete them. I did it using the interface. I deleted one by one, and it doesn't show anything for my team right now.

The thing is when I listed my teams project for debugging reason, there is one still listed.

I tried a few things, calling for its keys : returns an empty dict []
I tried deleting it just now : returned a HTTP 204, so I was like, okay it got deleted, but no, still listed.
I use requests for my API calls, and here is what it prints when I list my team's projects right now:

[{u'slug': u'something-controllernamesometh', u'name': u'something-controller.name.something.a.local.com', u'isPublic': False, u'dateCreated': u'2016-04-14T15:44:42.777Z', u'firstEvent': u'2016-04-15T10:08:17Z', u'id': u'87', u'features': [u'quotas', u'user-reports']}]

FYI : the company is using Sentry 8, so maybe it has been patched.
Still haven't checked in database, but it sure must be there since it's listed.

**Comment by dcramer** [comment]
Likely the project is marked as ‘pending deletion’ or ‘deletion in progress’. I don’t know what version we added status into the API, but if you’re using an API key as of all released version right now it does not restrict the project results to only visible instances.

On April 20, 2016 at 2:17:04 AM, Leblanc Pierre (notifications@github.com) wrote:

Hi,

So basicaly, I have a ghost project in my sentry database.
A week ago I created a few test projects using Create new project API endpoint calls.
All worked fine, I was able to see in them in the interface.

5 days later I had to delete them. I did it using the interface. I deleted one by one, and it doesn't show anything for my team right now.

The thing is when I listed my teams project for debugging reason, there is one still listed.

I tried a few things, calling for its keys : returns an empty dict []
I tried deleting it just now : returned a HTTP 204, so I was like, okay it got deleted, but no, still listed.
I use requests for my API calls, and here is what it prints when I list my team's projects right now:

[{u'slug': u'something-controllernamesometh', u'name': u'something-controller.name.something.a.local.com', u'isPublic': False, u'dateCreated': u'2016-04-14T15:44:42.777Z', u'firstEvent': u'2016-04-15T10:08:17Z', u'id': u'87', u'features': [u'quotas', u'user-reports']}]

FYI : the company is using Sentry 8, so maybe it has been patched.
Still haven't checked in database, but it sure must be there since it's listed.

**Comment by miniyuuzhan** [comment]
Alright, is there a way for me to delete it ?

Because it looks impossible without going in the database and delete it with postgre

**Comment by dcramer** [comment]
@miniyuuzhan we dont yet have a script in place to "force" resume deletions.

You can run this:

```
from sentry.models import Project, ProjectStatus
from sentry.tasks.deletion import delete_project

for project in Project.objects.filter(status__in=[ProjectStatus.PENDING_DELETION, ProjectStatus.DELETION_IN_PROGRESS]):
    delete_project(project.id)
```
