### ISSUE TITLE
Can't disable error notifications

### ISSUE THREAD

**Issue by Rambomst** [getsentry/sentry#3098]
Some of our users including me are having issues with notification emails being set even when the notification settings have been turned off.

If I go to the user dropdown then "Account" and then the "Notifications" tab the checkboxes are all off and the settings have been saved however I still receive the emails for some of our newly created projects.

Both dropdowns for "Alerts" and "Notes" are set to "Do not subscribe"

We are using version 8.3.1 current but upgrade pretty regularly, this issue has been happening for 2 or so months.

**Comment by dcramer** [comment]
I'm at a loss for what would be the culprit here unless you happen to have multiple accounts with alerts set to the same address. We dont currently do verification on emails, and its possible for any account to change their notification email address. Is this happening to multiple accounts or just yours? It's definitely not likely (and I want to say not possible) that its related to your account settings.

**Comment by Rambomst** [comment]
This happens to a few users but not all.

I just checked and my user account is the only one with this email so I am not receiving emails from another account.

All tickboxes are unticked in the "Notifications" screen.

The emails I receive appear to only be for new not seen before errors.

**Comment by Rambomst** [comment]
When I receive the email at the bottom it says "You are receiving this email due to matching rules: Send a notification for new events". Shouldn't this check the users notification settings before sending? I don't want to disable the rule for the project as other people may use it.
