### ISSUE TITLE
Jira Cloud Sentry App doesn't work on Brave 

### ISSUE THREAD

**Issue by tamademicheli** [getsentry/sentry#31415]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. open jira cloud (in Brave Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (x86_64))
2. install sentry app
3. click "Get Started"
4. then you get an error

### Expected Result

should work as in other browser (like chrome)

### Actual Result

![image](https://user-images.githubusercontent.com/24875849/151313066-1479d3d7-24bc-4c00-8685-abe18b0161e1.png)

**Comment by ceorourke** [comment]
Hi @tamademicheli - I installed Brave and tried this myself and successfully installed it. I've never used it before today so I don't know what's standard, but I clicked the lion icon to turn the shields off and that seemed to be the key.

**Comment by tamademicheli** [comment]
Hi. up to you to fix it or not. I just notified the behaviour for correctness. Brave is used ablot nowadays and behave like chrome, except bloks strange behaviours. You can close the ticket if u want. 

Have a nice day.

**Comment by ceorourke** [comment]
Hi @tamademicheli, it seems like this has to do with Brave using easylist, which blocks Sentry. You can see a previous reply here: https://github.com/getsentry/sentry/issues/26583#issuecomment-860794845

I'm going to close this issue since we unfortunately can't do anything, but if you turn the shields off you'll be able to install it.
