### ISSUE TITLE
Customizable / Translated Crash Dialog

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3218]
Currently the crash dialog always comes up in English and is not yet translated. It would be nice to be able to either manually define the strings or select a language.

**Comment by gilbarbara** [comment]
Yes, please! I'd definitely translate it to Portuguese myself.

**Comment by dcramer** [comment]
I think what we should do here is:

1. mark this as translatable using our current tools
2. allow a 'lang' tag to be specified in the config
3. default lang to browser lang

**Comment by stiller-leser** [comment]
Any news on this issue?

**Comment by sylfabre** [comment]
I may do it for French!

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by gilbarbara** [comment]
Yes, definitely. The world speaks hundreds of languages besides English!

**Comment by BYK** [comment]
@gilbarbara indeed! That's why we have the option to customize all the fields there: https://docs.sentry.io/platforms/javascript/enriching-events/user-feedback/#customizing-the-widget

It is quite challenging to maintain translations for this, especially translations that would fit into every different product that would use the feature so we chose the path of customization over providing translations.

**Comment by sylfabre** [comment]
@BYK and yet you managed to provide the English translation for it. Having it in any other language should be a no-brainer.

This was an issue for me, and we decided to drop this feature

**Comment by BYK** [comment]
>@BYK and yet you managed to provide the English translation for it.

English is the main language our company and code is working in so it is not a _translation_, it is just the base text.

Anyway, as I mentioned earlier, we are not planning to invest into this yet and we think the customization options at least provide an option to localize this dialog to an extent. We may revisit this decision in the future.

**Comment by sylfabre** [comment]
@BYK Sorry, I was not precise enough.

You're saying it's challenging to find the right words that would fit into every different product that would use the feature.
And yet you managed to do it in English as a base text.

So it does not look so challenging to me in English, and thus it is doable in other languages as long as you find yourselves a good translator.

However, I understand you don't want to spend time on translations, and that this feature is not your core business.
It is a valid business decision, just to try to sell it with a bullshit reason ;)

We decided to drop the feature because any change you make to the feature is a risk for our customization if we do them.
So these are a no-go for us as we are using Sentry to get a working solution right out of the box: we stick to your main feature.

**Comment by dcramer** [comment]
@sylfabre i believe we made translations available (using our standard i18n database)? though they may not actually be translated. theres some docs around passing the language locale:

> An override for Sentry’s automatic language detection (e.g. lang=de)

i would just test to see if yours is translated - if not we manage them all via transifex and once and a while batch-pay for updates
