### ISSUE TITLE
Change non-digest notifications on bursts

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3247]
Open for discussion.

tl;dr its cool that we avoid spamming your inbox, less cool that we flood Slack/etc

**Comment by tkaemming** [comment]
Is this something we want to come up with a solution to (other than rate limiting, which should already exist) aside from or prior to issue prioritization?

**Comment by yannispanousis** [comment]
Hi everyone,

we are currently in the situation of having the rule that says when "An event is first seen" then notify Slack.

We want to switch to using when "An event is seen" but are afraid of what will happen during wild bursts of errors.

I take it this is what this issue is about and was wondering if you have any ideas about how to deal with this with the current state of the product, or whether change is indeed needed for this.

Thanks!

Yannis

**Comment by dcramer** [comment]
@yannispanousis the 'every event' rule generally isn't something safe to use. It mostly exists as a pure customer demand so people can shoot themselves in the foot.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
