### ISSUE TITLE
Improve display for events that are received far after the occurrence timestamp.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#3283]
A couple ideas on how to improve this:

- show some sort of indicator (e.g. :warning:) next to the event timestamp when the difference between the difference between the occurred and received timestamps exceed some threshold (60 minutes?)
- show the difference between the received and occurred timestamps as part of the tooltip when hovering over the event timestamp so that you don't have to manually do math to understand how delayed the event was

**Comment by mattrobenolt** [comment]
I mentioned that it might be worth indicating on the stream view that _any_ new events were seen with a timestamp of +/- 1 hour as a notice in the UI. Just something like, "Hey, did you know you're sending data with the wrong timestamps? Graphs may look weird." or something. I wouldn't want it to be annoying, probably dismissable. Just a heads up to let them know what's going on. I don't want to make a bit deal because in cases of offline processing, it's possible that this is actually correct behavior and not something for them to look into.
