### ISSUE TITLE
[Flaky CI]: Dashboards > Dashboard > dashboard adds new widget if component is mounted with newWidget prop

### ISSUE THREAD

**Issue by JonasBa** [getsentry/sentry#32924]
### Flakiness Type

Other / Unknown

### Name of Job

Issue opened from dashboard data

### Name of Test

see details

### Link to Test Run

n/a

### Details

Could be tests/js/spec/views/dashboardsV2/dashboard.spec.tsx or tests/js/spec/views/dashboardsV2/gridLayout/dashboard.spec.tsx

**Comment by shruthilayaj** [comment]
Going to close this one since it doesn't look like a flaky test, it only occurred on two [branches](https://sentry.io/organizations/sentry/discover/results/?field=title&field=branch&field=github_actions_run&name=Flaky+frontend+tests&query=transaction.op%3A%22jest+test%22+transaction.status%3Ainternal_error+project%3Ajest+%21branch%3A%22%22+title%3A%22Dashboards+%3E+Dashboard+%3E+dashboard+adds+new+widget+if+component+is+mounted+with+newWidget%2A%22&sort=-branch&statsPeriod=14d&yAxis=count%28%29) and both were expected failures during development,
([1](https://github.com/getsentry/sentry/runs/5666498329?check_suite_focus=true#step:9:209), fixed [here](https://github.com/getsentry/sentry/runs/5666498329?check_suite_focus=true#step:9:209) and [2](https://github.com/getsentry/sentry/pull/33025))
