### ISSUE TITLE
Unable to get lock (version 8.4.1)

### ISSUE THREAD

**Issue by boboli** [getsentry/sentry#3349]
I just did a new sentry install of 8.4.1. I'm seeing the `UnableToGetLock: Unable to fetch lock after 0.065s: <Lock: 'd:s:0'>` issue that was fixed in the 8.2 release. The setup isn't actually being used yet either, so I have no clients pushing events currently.

The internal Sentry event says:
UnableToGetLocksentry.utils.cache in __enter__
errorUnable to fetch lock after 0.065s: <Lock: 'd:s:0'>

My setup is this (all in AWS, Ubuntu 14.04 for EC2 instances):
- 2 EC2 servers running sentry web, sentry celery workers, and sentry celery beat on both boxes
- 1 EC2 server running rabbitmq 3.6.1 serving as the celery message broker
- ElastiCache Redis 2.8.24 is used for Cache/Rate Limits/Quotas/TSDB/etc, with the TSDB on a separate cluster from everything else.
- ElastiCache Memcached 1.4.24 for non-redis cache
- RDS Postgres 9.5.2 for DB as well as node store

I can dump more detailed config settings if necessary.

**Comment by tkaemming** [comment]
> 2 EC2 servers running sentry web, sentry celery workers, and sentry celery beat on both boxes

This is the issue — only one celery beat should be running for the cluster. If two beats are running, the digest scheduler will attempt to run twice and one will get the lock and the other will fail. This won't cause any issues with digests specifically, but may cause issues with other operations triggered by beat (as well as causing those annoying log messages and/or errors.)

**Comment by boboli** [comment]
Thanks the quick response!

From the documentation:
> It’s recommended to only run one of them at the time or you will see unnecessary extra tasks being pushed onto the queues but the system will still behave as intended if multiple beat processes are run. This can be used to achieve high availability.

This would imply that is it beneficial to run multiple celery beat services for HA purposes, and doesn't mention any consequential downsides. Is that not the case? Does that mean this "unable to get lock" message is harmless?

**Comment by tkaemming** [comment]
Running multiple beats shouldn't cause any major issues since most tasks are either safely repeatable or otherwise managed with locks. It can cause performance degradation in some cases, since tasks that were intended to be ran once are now being executed multiple times for each time interval. (I guess the choice is ultimately up to you, but we run a single beat for hosted Sentry and monitor it and the queues to ensure everything is running smoothly. If we were going to give advice on how to run it, it'd probably be this.)

This specific log message itself is harmless, as long as the other invocations of the task are able to acquire the lock. If no invocations can acquire the `d:s:*` locks (for instance due to a backend error), this can cause email notifications to not be delivered.

**Comment by boboli** [comment]
Alright, I'll go back and revise my setup then. Thanks for the detailed response!
