### ISSUE TITLE
Create initial implementation of a timeline minimap for replay events

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#33627]

**Comment by ryan953** [comment]
FYI i'm aiming for something like this:
<img width="1439" alt="Screen Shot 2022-04-19 at 3 05 50 PM" src="https://user-images.githubusercontent.com/187460/164109516-8107a520-16e2-43ac-b30a-c85ab40b84f3.png">
https://www.loom.com/share/af2e76e088b24638b38bd9a594d698ab

Rather than:
<img width="579" alt="Screen Shot 2022-04-19 at 3 06 36 PM" src="https://user-images.githubusercontent.com/187460/164109626-df40adb7-e86d-4353-b0cb-1bc485a27924.png">
https://www.loom.com/share/23377f92b7e344a48fa47403a0f8fdd0

In either case I think there's a distinction for click targets: 
- part of the thing could be a video scrobber, so you can get to that point in the video
- other elements should be clickable to reveal more about the event(s) that happened, before you go see that part of the video.
