### ISSUE TITLE
local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by MadWombat** [getsentry/sentry#3386]
I caught this in the "internal" project on my local sentry install. Here is the traceback:
```
UnboundLocalError

local variable 'response' referenced before assignment

    django/core/handlers/base.py in get_response at line 112

    break
    if response is None:
    wrapped_callback = self.make_view_atomic(callback)
    try:
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
    except Exception as e:
    # If the view raised an exception, run it through exception
    # middleware, and if the exception middleware returns a
    # response, use that. Otherwise, reraise the exception.
    for middleware_method in self._exception_middleware:

sentry/web/frontend/generic.py in static_media at line 72application
# at least the non-gzipped version exists, so in theory, this can
# only happen on the first .gz path
continue
# Make sure we Vary: Accept-Encoding for gzipped responses
response['Vary'] = 'Accept-Encoding'
```

Looking at the code it seems that the error is correct and the variable really is used before assignment. The existing code trusts a search loop to assign the variable, but that is not guaranteed to happen.

**Comment by mattrobenolt** [comment]
Were you doing something weird to trigger this possibly? There's a specific reason the search loop can be trusted, because we first confirm that at least one of the lookups exist on disk, so I'm not sure how in your case a `resolve()` call succeeded, but `static.serve()` then failed to fine one of them.

I can obviously guard against this by setting `response = None`, then checking `if response is None` and return a 404, but I'm more curious why you hit this case in the first place since it shouldn't happen.

**Comment by MadWombat** [comment]
It seems that our IT was running a vulnerability scanner and hit sentry vhost with it, so yes, it was probably a weird request of some sort. I get 
 http://mysentryhost/_static/31633a13250d151db904018a5b4bfc4d9954a727/sentry/dist/
as the request URL. Looks like the scanner was trying for directory list access.

**Comment by mattrobenolt** [comment]
Oh, I see. So in this case, resolve() was correct since it matched a directory, but it wasn't a file. That makes more sense.

I'll add a patch to return a 403 here instead of a 404.
