### ISSUE TITLE
Issue subscribe/unsubscribe

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3428]
- [ ] API
- [ ] UI @getsentry/ui 
- [ ] Backfill assignment/commenters to explicitly subscribe

**Comment by tkaemming** [comment]
We also should hook up signals to automatically create new subscription rows on assignment, commenting, and state changes here (so that we don't have to backfill them again later.)

If we're going to start sending mail because of these subscriptions, this will also require some changes to the mail plugin (to get additional subscribed users) as well as include subscription reasons, I guess?

**Comment by dcramer** [comment]
API is done, UI is done in #3613

**Comment by tkaemming** [comment]
This is done.
