### ISSUE TITLE
Add Contexts

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3510]
Let's start breaking up the `extra` data, and arbitrary state-based contexts we have into a new top level concept. This should allow multiple types of context to be passed, some structured, some unstructured.
- Add new 'context' top level attribute
- Each sub-item (similar to crumbs) has an optional type, and some core validated attributes based on the type (which is a schema)
- Each item can have arbitrary data attached (again, like crumbs)
- Anything specified with contexts becomes a new "Context" type interface (rather than overloading the existing registered interfaces).
- Tags are defined based on the schema, and would be [keyname_used].[attribute name]. So for example (below), server.name=web-1.example.com, model.name=iPad2,1

```
context: {
  // hardware
  "server": {
    "type": "device",
    "id": "web-1.example.com",
  },
  "model": {
    "type": "device",
    "name": "iPad2,1",
  },
  // software
  "os": {
    "type": "os", // could be inferred from key name?
    "name": "Windows",
    "version": "95",
    "build": "1341234",
    "title": "OS",
  },
  "runtime": {
    "type": "runtime",
    "name": "Python",
    "version": "2.7.6",
  },
  // specialized for JS
  "browser": {
    "type": "browser", // could be inferred from key name?
    "name": "Internet Explorer",
    "version": "8",
  },
}
```

Device
- name (hostname, or other unique machine ID)
- model
- os
  - name
  - version
  - build
    (TODO: figure out what basic system specs we should define/index)

(Used by things like Python processes)
Runtime
- name
- version
- build

BrowserRuntime
(same as Runtime, diff tag names)

**Comment by dcramer** [comment]
This will primarily affect people working with embedded software, so Unity, iOS, etc.

/cc @bsergean @garrynewman

**Comment by mitsuhiko** [comment]
Some notes: device name is always a device name, we add `id` for the hostname/etc.

**Comment by bsergean** [comment]
This is a great proposal as arbitrary data can become overwhelming when there's a lot of it.

There's a small typo in the 5 bullet point of the original description: server.name=web-1.example.com / the blob does not have name for the server entry but it has id.

**Comment by mitsuhiko** [comment]
I did an initial implementation on this but I have some bigger changes in mind. In particular about how the UI indicates the different aliases that can be provided (eg: right now the UI says 'os'). In particular my idea is that the schema of the type knows how to title the element more appropriately and then only show the alias as a secondary de-emphasized element to clear up why there might be two runtimes shown etc.

We might also want to consider letting the API "title" the different contexts if they want. For instance I was thinking this sort of stuff might be useful:

```
{
  "runtime": {
    "type": "runtime",
    "name": "python",
    "version": "2.7.11",
    "title": "Python Runtime"
  }
}
```

(In this case it's useful because we can generate that information from the schema. But for some other situations it might make sense to say `title` is a reserved key which always sets the title in the UI)
