### ISSUE TITLE
Workaround Firefox's lack of `effective-directive` in CSP reports

### ISSUE THREAD

**Issue by reedloden** [getsentry/sentry#3542]
Firefox currently doesn't send `effective-directive` or `status-code` in its CSP reports. Sentry's implementation of CSP report parsing currently rejects all such reports. Would be good to add a workaround to deal with this deficiency to at least make reports from Firefox somewhat useful.

@ScottHelme offered one such suggestion in https://bugzilla.mozilla.org/show_bug.cgi?id=1192684#c8

> I parse the effective-directive out of violated-directive but this does introduce additional problems. When the block was a fallback to default-src I end up with an effective-directive of default-src, which makes filtering in the GUI a pain. I could try and be smarter and detect the actual effective-directive, but decided how I currently do it is a good balance between dropping all Firefox reports and manually trying to identify the actual effective-directive.

**Comment by ScottHelme** [comment]
It will be interesting to get input from others on this, thanks for the mention @reedloden

**Comment by dcramer** [comment]
@getsentry/infrastructure

**Comment by mattrobenolt** [comment]
@reedloden I meant to follow up earlier this morning. :)

This was an explicit decision to not try and hack around Firefox's deficit. Rather, I'm not explicitly not choosing to ignore Firefox, but I'm expecting the `effective-directive` to be sent.

CSP reports are already noisy enough as it is, and Sentry's goal is to help surface signal instead of drowning you in noise, so the less noise we track, the better results we'll give.

Are there cases where a report would be sent from Firefox that wouldn't also affect Chrome? From my testing, there weren't any cases where Firefox would send anything new. So the only case that we'd fail to catch would be if your users were exclusively Firefox.

**Comment by benvinegar** [comment]
Agree with @mattrobenolt  here. Plus this has sat for 2+ years. Closing.
