### ISSUE TITLE
Bug: Tags is missing in the "top bar" layout

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#37202]
### Problem
Our layout options decide on what content can be shown to the user

### Acceptance Criteria
- As a user I can view tag's no matter the layout choice

### Solution
- Breadcrumb List header is removed in favour of a tab label titled "Bread crumbs" (Mock 1)
- If Player position doesn't equal top, then reposition the tabs to be below the replay controls (Mock 2)
- Selector for switching layouts uses a text label rather than a icon to explain its functionality.
#### Mocks
![Image](https://user-images.githubusercontent.com/6508377/189370339-61f8de7d-0eb6-4268-8a0e-36f1dba21d0f.png)
![Image](https://user-images.githubusercontent.com/6508377/189370321-6f3a4b4f-a824-45ac-b1f5-f28f5fe5457e.png)
#### Figma
- Player = Top: https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=189%3A8367
- Player = Left: https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=190%3A9890

#### Gotchas
The tabs component has a different vertical height than our URL input, which means this solution would require some CSS overwriting...

**Comment by billyvg** [comment]
This might be ok to punt for now if we are going to decide on a single layout format.

**Comment by Jesse-Box** [comment]
@jas-kas @ryan953, I had some time to look into this ticket, let me know your thoughts

**Comment by ryan953** [comment]
The 'top' arrangement seems like a good universal choice regardless of the browser window size, and capture size. Viewing an iphone capture in portrait mode with the Top layout would be painful.

It feels like lots of layout shift to toggle between these two options, the breadcrumbs teleport from left to right. 

Names are hard, but i'd venture to rename this pair of options to be 'big & mini player' instead of 'top & left position'. The 'top' option becomes 'big'
