### ISSUE TITLE
unlabeled event for django.secuity

### ISSUE THREAD

**Issue by samuelcolvin** [getsentry/sentry#3800]
I've modified `LOGGING['loggers']` in django settings to include:

``` python
        'django.security': {
            'handlers': ['mail_admins', 'sentry'],
            'level': 'ERROR',
            'propagate': False,
        },
```

(change was to add `, 'sentry'`)

This comes through to sentry more or less right (user etc. are correct), but the title is **`<unlabeld event>`** which isn't very helpful.

I would propose that where no other event label is available you use the last logger name, eg. in this case "SuspiciousOperation"?

Also (and less important to me) we get:

> There was 1 error encountered while processing this event: Discarded invalid value for parameter 'sentry.interfaces.Message' 

Screenshot:
![image](https://cloud.githubusercontent.com/assets/4039449/17133448/f46995a4-531d-11e6-8b4f-c441ed78d098.png)

**Comment by dcramer** [comment]
Something is being passed incorrectly it seems. The ‘Message’ interface is
effectively required here, as without an exception we have no way to
identify an event.

Im assuming this isn’t on getsentry.com, so could you investigate what the
error is with the message interface, or give me the output?



On July 26, 2016 at 3:47:48 AM, Samuel Colvin (notifications@github.com)
wrote:

I've modified LOGGING['loggers'] in django settings to include:

        'django.security': {
            'handlers': ['mail_admins', 'sentry'],
            'level': 'ERROR',
            'propagate': False,
        },

(change was to add , 'sentry')

This comes through to sentry more or less right (user etc. are correct),
but the title is *<unlabeld event>* which isn't very helpful.

I would propose that where no other event label is available you use the
last logger name, eg. in this case "SuspiciousOperation"?

Also (and less important to me) we get:

There was 1 error encountered while processing this event: Discarded
invalid value for parameter 'sentry.interfaces.Message'

Screenshot:
[image: image]
<https://cloud.githubusercontent.com/assets/4039449/17133448/f46995a4-531d-11e6-8b4f-c441ed78d098.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/getsentry/sentry/issues/3800>, or mute the thread

**Comment by samuelcolvin** [comment]
This is on getsentry. 

https://app.getsentry.com/tutorcruncher/tutorcruncher-beta/issues/145408600/

**Comment by dcramer** [comment]
So these entirely have no message? It's unclear to me how this is valid logging if they're completely empty. What does Django generally do with these?

**Comment by samuelcolvin** [comment]
> So these entirely have no message?

Apparently yes.

> What does Django generally do with these?

Django send an email with no message, eg the subject is `[TC2-BETA] ERROR (EXTERNAL IP):` eg. it looks like django is expecting to put the message after the colon (as it does with 500 errors) but there's no message.

Perhaps the message is the generally the reason passed to `SuspicousOperation` eg. the exception which causes the 400 response.

We should probably add a message where we raise that exception, but in it's absence a better default label would be useful.

**Comment by dcramer** [comment]
Are you explicitly logging the error yourself or is Django? Trying to understand the full scope. The easiest solution, if you're logging it yourself, would be to add ``exc_info=True`` to the logging call.

**Comment by samuelcolvin** [comment]
No, this is django's standard logging machinary: https://docs.djangoproject.com/en/1.8/topics/logging/#django-security

**Comment by Ismaestro** [comment]
I'm suffering the same now with Angular 5 and typescript.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
