### ISSUE TITLE
Filtering by date isn't working

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#38256]
![Image](https://user-images.githubusercontent.com/187460/187495908-7b80a86b-b5ec-4330-a308-e6f4837dc0c9.png)

**Comment by danecando** [comment]
Originally the statsPeriod filter would not apply to the replay list correctly when setting it as a first filter. If I filtered by a project and then applied the statsPeriod filter it would work as expected. Something has changed since yesterday and it is now functioning as expected in all normal scenarios as far as I can tell. I did some debugging and all the functionality supporting it seems to be working as expected so I don't think this is an issue for now. 


This screenshot shows proper statsPeriod filtering as the initial and only filter applied
![Image](https://user-images.githubusercontent.com/3721977/187739389-95907b32-ffc5-4441-af0a-bf0e7daa3d7a.png)

**Comment by danecando** [comment]
Originally the statsPeriod filter would not apply to the replay list correctly when setting it as a first filter. If I filtered by a project and then applied the statsPeriod filter it would work as expected. Something has changed since yesterday and it is now functioning as expected in all normal scenarios as far as I can tell. I did some debugging and all the functionality supporting it seems to be working as expected so I don't think this is an issue for now. 


This screenshot shows proper statsPeriod filtering as the initial and only filter applied
![Image](https://user-images.githubusercontent.com/3721977/187739389-95907b32-ffc5-4441-af0a-bf0e7daa3d7a.png)
