### ISSUE TITLE
Base url on SSO login form

### ISSUE THREAD

**Issue by bonroyage** [getsentry/sentry#3856]
The base URL on the SSO sign in page is not customised to the installation's root URL as written in the Settings. I found this to be confusing as I thought it let me login with an organisation hosted by Sentry.

![screenshot 2016-08-02 11 27 44](https://cloud.githubusercontent.com/assets/4411748/17334437/478a149e-58a4-11e6-9a41-d7231c3ae414.png)

I believe it is in [templates/sentry/login.html - line 67](https://github.com/getsentry/sentry/blob/481b4b9d2365749c7b8fcf55d5aa66ee5210ab93/src/sentry/templates/sentry/login.html#L67)

**Comment by mattrobenolt** [comment]
haha, wups. I guess most people don't run SSO with their own Sentry. Should be easy to fix up. Thanks for pointing it out.

**Comment by mattrobenolt** [comment]
I think we need to redesign this page a tiny bit to accommodate other urls. The styling here strictly accommodates `app.getsentry.com`, but will completely fail for basically anything else since it's sized exactly to fit. Even locally, I now hit:

![image](https://cloud.githubusercontent.com/assets/375744/17336498/4ba8a0f6-5893-11e6-9065-49ecd0d70c8f.png)

/cc @ckj 

I'll throw up code PR, and it'll need some styling I think to actually finish it off.
