### ISSUE TITLE
Bug: URL Walker page count on Details differs from Index

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#38628]
Example replay: https://sentry.io/organizations/sentry/replays/javascript:38cbd1518c1c4f0f8daf378f7aaad3bc/?referrer=%2Forganizations%2F%3AorgId%2Freplays%2F&t_main=network

-- 

The index page reports 69 pages, the details 54 pages -- the index seems to be "more" correct as we have a `countUrls` of 71.

**Comment by billyvg** [comment]
We should add tests for this component while we're fixing the bug.

**Comment by ryan953** [comment]
This is looking like an sdk type issue to start with.

What i've found so far:
*Index Page*
The index page is reading from `replay.url` (which matches up against `replay.countUrls` as it should) to display the UrlWalker. In the example replay that produces the 69 number we see (it's 69 in the drop down, and two more flanking it).
These urls appear to come from the SDK directly, the backend isn't parsing our breadcrumbs or anything.
One tradeoff to using the data inside `replay.urls` is that there is no timestamp, so the list is just informative, there are no urls to deeplink into the replay.
*Details Page*
The details page uses the breadcrumb data, filtered by `type==='navigation'` to create the list of 54 urls in this example. UrlWalker uses that list in order to associate timestamps with each url, so we can have links.


Obviously the two lists are different. We will need to check the SDK next to learn more.

**Comment by ryan953** [comment]
Closing. This doesn't seem to be an issue anymore. 

Please feel free to re-open if it does.
