### ISSUE TITLE
When merging groups, user counts don't take account for uniqueness

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3883]
If group A has 5 users, and group B has 5 users, after merging, we get a value of 10.

This is incorrect though if there's an overlap of users between them. If group A and group B contain the same users, the merge should result in 5, not 10.

**Comment by tkaemming** [comment]
This is the block that handles the merging of the `GroupTagKey` for `sentry:user`, which is used to retrieve the number displayed in the UI: https://github.com/getsentry/sentry/blob/master/src/sentry/tasks/merge.py#L197-L202

Thinking about it more, isn't this a problem for all `GroupTagKey` rows (not just `sentry:user`), since the `values_seen` is essentially equivalent to the number of `GroupTagValue` instance sharing the same `project`, `group` and `tag` attributes?
