### ISSUE TITLE
Notifications when issue is resolved

### ISSUE THREAD

**Issue by OJFord** [getsentry/sentry#3885]
For webhooks in particular it would be great if notifications were triggered by not only new errors/regressions, but also by their resolution.

**Comment by dcramer** [comment]
This is definitely something we want to do, but there's a bit of work to make it happen.

I believe the appropriate steps will be:

- Overhaul webhooks (roughly a v2) so that they have a type and a payload
- Extend webhooks to the new activity notifications introduced by workflows
- Allow each webhook to be configured on which events it receives (GitHub might be inspiration here)

**Comment by dcramer** [comment]
This is something that we ended up building.
