### ISSUE TITLE
Cocoa function signature truncation

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3902]
Currently signatures are being truncated to 256 characters. We need to determine what a good path forward here is, as this causes some usability issues. Increasing the length might help, but there also might simply be a better way we can represent these.

**Comment by dcramer** [comment]
@mitsuhiko @soffes

**Comment by mitsuhiko** [comment]
So this mostly is an issue for Swift because the demangling we're using produces insanely long symbols. With a bit of engineering we could customize this to produce smaller demangled symbols.

Alternatively a quick-fix would be to parse out the actual name with a regular expression and make sure that survives truncation in any case.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
