### ISSUE TITLE
Replay Details: the play button is unresponsive 

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#39338]
**Problem:**

For [this replay](https://sentry.io/organizations/sentry/replays/javascript:afd992fb239643aabc3993d456bfc765/?t=1290&t_main=console), the play button is unresponsive.

Replay ID: `afd992fb239643aabc3993d456bfc765`

**Solution:**

Replay video should begin when a user clicks the play icon.

**Comment by ryan953** [comment]
This replay has a missing segment early in the list, it's missing the 3rd recording segment :(
![Screen Shot 2022-09-29 at 2 58 48 PM](https://user-images.githubusercontent.com/187460/193149625-be77e79d-a9fb-452c-bbbc-6dd1785f7ea3.png)

That's going to prevent the replay from playing past that point in time. The url in the ticket is deeplinking into `?t=1290` and just shows a white screen because without that early segment the rrweb diffs can't be applied correctly.

**Comment by ryan953** [comment]
Note: This is the same replayId as in #39343
