### ISSUE TITLE
Design: Users struggle to contextualize their performance data inside the replay details

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#39619]
### Problem
- Users struggle to identify which user actions result in transactions being propagated
- Users have to navigate to a separate page to see the spans of a captured transaction

### Acceptance Criteria
- If the user hasn’t got performance monitoring instrumented, we encourage them to do so
- Users can see the current time index of the replay inside the super-trace view
- Users can see a transactions or spans start time is in relation to the replays duration
- Users can fast-forward or rewind the replay to the time index of when a transaction or span started
- Users can review the details of a transaction or span while the replay is playing
- Users can crop the super-trace view to see the duration of transactions or spans in a higher resolution
- Users can stay in this super-trace view to see any span associated to a captured transaction 

### Designs
Figjam: https://www.figma.com/file/rmpDYWJXOyddhmDJSReflI/Exploration%3A-Tracing-in-Replay-Details?type=whiteboard&node-id=0-1&t=4xqH6rkkFbQ3w1S5-0

**Comment by ryan953** [comment]
Could this be done now that we have designs for the Trace Navigator?

**Comment by Jesse-Box** [comment]
@jas-kas @ryan953 

I'd like to re-word this ticket because I haven't determined that the problem lies entirely inside the trace tab

Title:
~~Design: In the Replay Details, HMW rework the trace tab to demonstrate relationship between Replay to other events~~
Users struggle to contextualize their performance data inside the replay details

**Problem:**
~~Current trace view: we don't have a "super trace" representation.~~ 
- Users struggle to identify which user actions result in transactions being propagated
- Users have to navigate to a separate page to see the spans of a captured transaction

~~**Solution:**
We're going to redesign the trace tab in Replay Details to better represent the event relationships between transactions, traces and replays.~~

**Acceptance Criteria:**
- Users can see the current time index of the replay inside the super-trace view
- Users can understand what the replays time index would be by hovering inside the super-trace view
- Users can fast-forward or rewind the replay to the time index of when a transaction or span started
- Users can review the details of a transaction or span while the replay is playing
- Users can crop the super-trace view to see the duration of transactions or spans in a higher resolution
- Users can stay in this super-trace view to see any span associated to a captured transaction

**Comment by jas-kas** [comment]
@Jesse-Box Thanks for taking another look at this now very old ticket and rewording it to represent our current project!

**Comment by Jesse-Box** [comment]
@ryan953 @jas-kas 

I'm marking this task as done, but I'll create a separate ticket for the empty state

Figma file is [here](https://www.figma.com/file/BkgpCdPfr9AreSIUZLRrWk/Specs%3A-Tracing-Waterfall-View?type=design&node-id=29%3A14271&mode=design&t=r1Qm2MDoKwFaCvdh-1)
