### ISSUE TITLE
Support modifying plugin settings via the API

### ISSUE THREAD

**Issue by johanneswuerbach** [getsentry/sentry#3977]
We are currently using sentry in several project across several environments and updating plugin settings has become quite a burden.

We started using and extending https://github.com/jianyuan/terraform-provider-sentry, but as it is using the the Sentry API, it is limited to all options provided it supports.

Would be great if the API could be extended to support Plugin Management and allow to configure Plugin setting like the Slack Webhook.

**Comment by dcramer** [comment]
This is likely something that will happen soon, but it's not something we intend to document or offer as a public feature. We need it internally to migrate the remainder of the UI to React.

I'm going to close this out, as we're taking an active stance to remove feature requests from GitHub due to the large amount of noise. If you wish to continue discussion, feel free to take it over to our community forum: https://forum.sentry.io/
