### ISSUE TITLE
Issue Details shows an error when Replay is not found

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#40278]
The request for a replay record is 404ing... should this be hidden instead of showing an error when a 404 happens? Ideally we resolve the reason why it 404s in the first place, but in the meantime we may want to hide this error box on a 404.

![Image](https://user-images.githubusercontent.com/79684/196778775-6c6781c8-ff97-453b-9343-5c21ec0b644a.png)

**Comment by Jesse-Box** [comment]
Does 404 mean that there's a replayID associated with this event but no replay was found? Maybe I can mock up the alert if I had a bit more context about the problem

**Comment by ryan953** [comment]
The "error loading component" message will be gone/fixed when #41563 is merged. 

The same type of message appears on the details page though: 
![Image](https://user-images.githubusercontent.com/187460/202794492-747aedab-4d17-41d3-8e6c-265e96efa7b9.png)


I think it'd be nice to return `410 Gone` or remove the 'duration >=5` constraints from the database, so we can load the replay but then show a disclaimer message instead of that Page Not Found we have no.

**Comment by ryan953** [comment]
Closing this, it's covered by [#40719](https://github.com/getsentry/sentry/issues/40719) and https://github.com/getsentry/sentry/pull/41563 

If the Replay Details still needs love we'll make a new ticket for that.
The Issues Details
