### ISSUE TITLE
Bug: DOM events are not captured sometimes, resulting in Breadcrumbs being inconsistent with DOM Events tab

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#40399]
**Problem:**

DOM events are not captured sometimes, resulting in Breadcrumb events not lining up with DOM events. Data integrity issue.

_Example:_
https://sentry.io/organizations/sentry/replays/javascript:c67820f5bb0b4663829748481fe965b3/?referrer=%2Forganizations%2F%3AorgId%2Freplays%2F&t_main=dom

Replay breadcrumbs show two button clicks but there is only a DOM event captured for the first one.

**Solution:**

TBD.

**Comment by ryan953** [comment]
In this replay we can see the user click to filter the Issues list by project. They click 1) to open the project flyout 2) to select a specific project.

I think the issue is that the rrweb plugin we wrote to extract the html is running after the remove() step has finished. So the button in the flyout is removed from the DOM then we run our code afterwards. We can do something about this though, one way or another.
