### ISSUE TITLE
Replay Player area needs a label or something reminding people that they can open the inspector and see the html/css inside the replay

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#40519]
### Problem
Its impossible to know that you can inspect the DOM of this session

### Solution
Add a dismissible alert to educate the user on this hidden functionality. Once it's dismissed by the user, they shouldn't see alert again.

_**See latest designs in thread below...**_

---

~Text `Use your browsers developer tools to see how the DOM changes.`~

![Image](https://user-images.githubusercontent.com/6508377/199475401-883e2dbb-4bdb-4374-93e4-cbd0ff0369d3.png)

![Image](https://user-images.githubusercontent.com/6508377/199475438-a9da8a34-eef8-4dd8-bad2-5415bd7f2891.png)

**Comment by ryan953** [comment]
cc @Jesse-Box to add a mockup

**Comment by Jesse-Box** [comment]
@ryan953 see solution proposal above.

**Comment by jas-kas** [comment]
Hey @Jesse-Box! This looks good. :) A few thoughts:

1. I think we should be explicit in our messaging that you need to "right click" on the video player in order to have this benefit
2. I wonder if we can explore something different than an alert banner that sits on top of the video. Perhaps a dismissible overlay on the video that says "Right click to inspect"? It would save some real estate on the page if we did that/would be kind of neat as well but I can see it being annoying because we're blocking folks from watching the video

**Comment by Jesse-Box** [comment]
I think its worth exploring, ill mock it up :)

**Comment by jas-kas** [comment]
@Jesse-Box Here's the copy we want to go with:

> Right-click and Inspect the player window to view your application's DOM tree.

**Comment by Jesse-Box** [comment]
@jas-kas I had to trim down the text to account for different sizes of the player. I felt it was necessary to deviate from our existing alert UI because displaying text over a DOM reduces legibility and attention.

![Image](https://user-images.githubusercontent.com/6508377/199694165-17829732-9d5f-401e-9c1c-892fdd028c42.png)
![Image](https://user-images.githubusercontent.com/6508377/199694164-804e2127-2430-4e8a-9489-11057b40c079.png)

**Comment by ryan953** [comment]
@Jesse-Box should we flip the colors in dark-mode, or keep the white-on-blue?
