### ISSUE TITLE
Bug: DOM Events missing a user click (possibly due to ignored image?)

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#40715]
See this replay: https://sentry.io/organizations/sentry-emerging-tech/replays/billy-test:21fa4cead57c42a186a3f8119bdd9e90/?referrer=%2Forganizations%2F%3AorgId%2Freplays%2F&t_main=dom

**Comment by ryan953** [comment]
It looks like this is related to https://github.com/getsentry/sentry/issues/40399, in fact i'd say it's the same problem.

The issue is that the commit https://github.com/getsentry/sentry/pull/40421 didn't account for the first breadcrumb/render event. 
What is happening is that the rrweb plugin is only looking at `EventType.IncrementalSnapshot` events to populate the `this.nextExtract` field. But the node was rendered as part of the initial full-checkout render. So in this example the click is happening before that first incremental snapshot... `extractCurrentCrumb` can't find the node because it was removed ,and this.nextExtract is null.


What we should do is add a case to the `handler` method inside of `BreadcrumbReferencesPlugin`:
```
if (event.type == FullCheckout) {
  this.extractNextCrumb({replayer});
} 
if (event.type == IncrementalSnapshot) 
  ... existing ...
}
...existing ...
```
