### ISSUE TITLE
Improve source scrape debugability

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#4168]
There's an issue where source failed to extract, and its unclear why. So two issues with it:
1. We're not showing an error when we can't scrape the source (we should be)
2. It's not scraping the source when the use of tilde seems correct

[1] https://sentry.zendesk.com/agent/tickets/4523

**Comment by hilnius** [comment]
Where is this at ?
I've tried again making private source maps uploaded to artifacts work but it doesn't work.

I'm uploading it with : 
```
curl https://sentry.io/api/0/projects/supermood/supermood/releases/$APP_VERSION/files/ \
  -X POST \
  -H 'Authorization: Bearer XXX' \
  -F  file=@public/app/libapp.min.js.map \
  -F name="~/app/libapp.min.js.map"
```

I've also tried many many many many other names for the files, even changing manually the sourceMappingUrl comment in my .min.js file.

**Comment by mattrobenolt** [comment]
@hilnius do you mind kicking over to support and we can look into what's going on here to help debug? It's hard to say without seeing how things are setup.

**Comment by jpatters** [comment]
I can't make this work either. I've uploaded with the ~ and with the domain. Private source maps just seem to not work. 
No matter what I do I get `There was 1 error encountered while processing this event` and `HTTP returned 403 response on <url to map file>` when events come in. It is still trying to load the source as if it wasn't private.

**Comment by benvinegar** [comment]
> Private source maps just seem to not work.

For almost all users who experience the difficulties you're describing, it is because of a name mismatch. I recommend posting all pertinent details on forum.sentry.io (or if you're a sentry.io customer, via email support): the name of your source map artifact, the `<url to map file>`, etc.

**Comment by jpatters** [comment]
I've tried every combination the docs even hint at.
FWIW I've named the file `~/app.min.js.map` in sentry and the file is served at `domain.com/app.min.js` with `//# sourceMappingURL=app.min.js.map` at the bottom of it.  

I found this on the forums and I think it might be on the right track, but I can't get it to work. 
https://forum.sentry.io/t/offline-sourcemaps-not-used/548/3

So I feel like (at least in my case) it is caused by some missing instructions for the docker setup. I've mapped a folder from the host to `/var/lib/sentry/files` but no files get written to it. I've verified that it is attached and working properly and that the sentry user can write to it. I see this everywhere in the logs
```
[ERROR] sentry.lang.javascript.processor: [Errno 2] No such file or directory: u'/var/lib/sentry/files/17150/8267/9e803e0b20a240148c5e869945ed7068'
```

I am a sentry.io customer and have email support but not heard back. However I am in the process of moving to a self hosted version and that's where I am having the issue.

**Comment by jpatters** [comment]
Just tried to solve this by switching to s3 file storage and the files aren't getting uploaded to s3 either and there is no debug/error information about it.

**Comment by jonaskello** [comment]
I just hit the same problem with our on-premise installation. The solution is to have both the main sentry container and all worker containers map the path `/var/lib/sentry/files` to the same volume so the files are shared between main and worker containers.

**Comment by beaugunderson** [comment]
Hmm... What if mapping the path isn't an option? We're running inside Aptible for HIPAA compliance and I don't think we can do that...

**Comment by LukeIn2sc** [comment]
Thank you very much! I've just solved this problem which bothered me 3 days!

**Comment by llisonly** [comment]
> I just hit the same problem with our on-premise installation. The solution is to have both the main sentry container and all worker containers map the path `/var/lib/sentry/files` to the same volume so the files are shared between main and worker containers.

how to change it
