### ISSUE TITLE
I don't understand why server side data scrubbing with default scrubbers does NOT apply for stack trace variables.

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry#42317]
I don't understand why server side data scrubbing with default scrubbers does NOT apply for stack trace variables. I'm a long time Sentry user and this is (somewhat surprisingly) the first time I saw a clear text password in Sentry.

![image](https://user-images.githubusercontent.com/91906601/207448609-ac7fed79-8e35-4d57-ad23-14f34ce312c5.png)

Go under `Project → Settings → Security & Privacy → Data Scrubber + Use Default Scrubbers`

> Apply default scrubbers to prevent things like passwords and credit cards from being stored

_Originally posted by @fredericgboutin-yapla in https://github.com/getsentry/sentry-php/issues/965#issuecomment-1349771830_

**Comment by fredericgboutin-yapla** [comment]
> Please let us know on this issue if you're using SaaS or self-hosted, thank you.

SaaS version

**Comment by iker-barriocanal** [comment]
Hi @fredericgboutin-yapla, this shouldn't be the case. Could you provide a link to the Sentry issue where I can see this happening? Thanks.

**Comment by fredericgboutin-yapla** [comment]
@iker-barriocanal https://sentry.io/organizations/yapla/issues/3806292187/?project=3648938

**Comment by fredericgboutin-yapla** [comment]
Stupid bot.

**Comment by jjbayer** [comment]
@fredericgboutin-yapla data scrubbers are applied to stack trace variables by default ([code](https://github.com/getsentry/relay/blob/1df4656a7e6ff9e7b27e82a550364430637c4b0b/relay-general/src/protocol/stacktrace.rs#L114-L115)). I think the problem here is that `password` is an object, not a string. From our docs:

> Sentry will redact arrays and literal values, but not entire objects.

https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/

In your case, you might be able to use [advanced data scrubbing](https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/) to make sure `password.$eq` is also scrubbed. Let me know if this helps.

**Comment by fredericgboutin-yapla** [comment]
Wait. There is literally a variable named `password` in the stack trace.

Whatever the type / content / value, it should be masked automatically. It sounds like common sense to me, don't you agree?

I already knew I could customize the scrubbing behavior but the default one automatically realized by Sentry always sufficed to me up until this very use case.

**Comment by fredericgboutin-yapla** [comment]
How do I scrub existing events like in my example?

**Comment by iker-barriocanal** [comment]
Data scrubbing happens during ingestion, so it's only applied to new events. You can't apply data scrubbing to already ingested and stored events, unfortunately.
