### ISSUE TITLE
Support tagging multiple values for the same key

### ISSUE THREAD

**Issue by AlexandreBonaventure** [getsentry/sentry#43805]
### Problem Statement

Hi, 
We have a use-case for tagging events with multiple values for the same key.
Let me give an example:

We're developing an app that manage several devices and sometimes we need to dig into customer issues. Often times, technical support will know the affected devices serial number. In order to search for specific events in Sentry, we'd love to use the tag feature as it seems to be the perfect fit, but it does not support (as far as I know) to support multiple values for the same key, as such: `device:#1234` `device:#6789` ...

The reason why we can't have any unique tag here is that errors are not necessarily targeting specific devices but could still affect every single one of them.

### Solution Brainstorm

What about supporting collection values when setting a tag:

`Sentry.setTag("device", ["1234", "6789"]);`

**Comment by HazAT** [comment]
Thank you for opening an issue and generally, it's a great idea but this change is more significant than it looks - our whole pipeline is built so that a tag is unique.

And an issue group - meaning how we group errors should already support this.
One unique event is sent by one device, it can't be sent by two devices. 
If the event is grouped together in one issue an issue can have multiple tags so you should be able to exactly get what you want already.
