### ISSUE TITLE
Support for Clickup integration on self-hosted Sentry Kubernetes

### ISSUE THREAD

**Issue by armandofcom** [getsentry/sentry#43823]
### Problem Statement

Because they do not allow the integration of clickup in the self-hosted sentry

**Comment by hubertdeng123** [comment]
Unfortunately Sentry Kubernetes is not officially supported. For the reason why clickup is not supported for self-hosted, I'll have to ask the ecosystem team to see if there are additional reasons why this may be the case.

**Comment by scttcper** [comment]
Since clickup published it on our [integration platform](https://docs.sentry.io/product/integrations/integration-platform/) it would be up to them to describe how to set it up on self hosted. I imagine it would be possible to setup a similar integration locally once you know how they've configured the app.
