### ISSUE TITLE
[Feature Request] Group events by tag on project overview

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#43848]
### Problem Statement

There should be a way to group events by tags. Continuing with the example cases from #43846, this would provide a good overview of which instances of a project are having issues. 

![image](https://user-images.githubusercontent.com/51749023/215581072-e5e9fb8f-1b36-4dec-b19e-e516f34990a0.png)

**Comment by hubertdeng123** [comment]
I don't think people generally respond to the app-frontend handle. I think this should be routed to workflow since it is issues/events related

**Comment by scttcper** [comment]
This sounds a like top period in discover. I don't think we'd support this on the project details page since we don't know which tag to group by until you tell us. Discover allows you to group by any tag.

in this example i'm grouping by the browser.name tag
![image](https://user-images.githubusercontent.com/1400464/215893890-2191b72d-e1ee-4bca-8076-ec7944d0b804.png)

**Comment by jeengbe** [comment]
Great, didn't know Discover supported this!

**Comment by jeengbe** [comment]
@scttcper Is that a Business feature? I can't get any sort of grouping to work
![image](https://user-images.githubusercontent.com/51749023/216991717-f8707985-a6d7-47af-9fc7-9dd8b982cc1c.png)

**Comment by scttcper** [comment]
you'll need to remove the columns except count and the tag you're looking for. And change the display dropdown to Top Period. I believe it is a business feature
