### ISSUE TITLE
Email Improvements

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#4400]
- Require password confirmation (when available) to add an email -- this is a security concern as allowing someone to change an email without this means they can reset the account password. (https://hackerone.com/reports/176470)
- Tweak the UI so its just a list of emails with one active as primary. Secondary addresses can become primary. Alternatively, make the primary email a selector instead of a freeform text box. Alternative alternatively, keep it the same, but fix some behavior when trying to make an existing secondary a primary email address (you lose the old address)

**Comment by kjlundsgaard** [comment]
Do we want users to be able to make non-verified emails primary, or only emails that have been verified?

So far I'm making the behavior look like this:

![screen shot 2016-10-19 at 1 32 11 pm](https://cloud.githubusercontent.com/assets/9269824/19536373/951cdee6-9600-11e6-9245-349c525ae66a.png)

**Comment by mattrobenolt** [comment]
> Do we want users to be able to make non-verified emails primary, or only emails that have been verified?

I'd say it should be verified. The only issue here is that we don't really _require_ email verification, so there will have to be the default behavior still of users only having one single email address. But I'd say to add an addiitonal and to make it default, it must be verified.

**Comment by dcramer** [comment]
IMO require verification to make it a new primary email

@ckj can you help on UI thoughts here

I would also just put the verification part directly under new email (rather than having a header to separate it)

**Comment by kjlundsgaard** [comment]
Another question:
Would this form be read-only for any users?

**Comment by dcramer** [comment]
@kjlundsgaard so we do need to check "if user.has_usable_password(): # they can verify password" -- if thats not true we need to del the password field. Theres some others that do this for example.

**Comment by kjlundsgaard** [comment]
@dcramer Yeah, I have that part covered. But the account settings form can be read only (if user.is_managed...) while the notification settings form currently is not.

**Comment by dcramer** [comment]
@kjlundsgaard ah -- so i guess we shouldnt allow them to change primary email address if its managed, but they should be able to still add secondary addresses

**Comment by ckj** [comment]
General opinion: There's a lot going on, but I think there are some simple things we could do to make it better. Some thoughts in order of importance to me:

- Ideally, the primary email would be at the top of the list.
- "Set as primary email" should have the `btn-default` class.
- I think we could get rid of the 'Verified' badge... it's only worth highlighting the ones that require action
- 👍 on removing the verification header
- I'd consider making the 'Primary' badge text only. Something like "katie@sentry.io (Primary)" so again, there's less competing with the more important 'Unverified' badge
- We could probably do without `.table-bordered`. I'd wrap a standard `table.table` in a `.panel` so that you get the outer border without the other lines. (This one is the least important to me)

We'd be in a pretty good spot once those are addressed.
