### ISSUE TITLE
Crons: Add support for multi-tenancy

### ISSUE THREAD

**Issue by mariashulga** [getsentry/sentry#44230]
### Problem Statement

One job can be executed N times by one scheduled time (one time per tenant). We want to know on which tenant was missed job     execution (not just 0 executed, but know if N-1 times was executed). Cron statistic should contain data about tenants checkins. 

### Solution Brainstorm

Add Sentry configs support multi-tenancy. On Sentry side should be config list of supported tenants ids. During check in we can pass tenant id in request.

**Comment by davidenwang** [comment]
Thank you for this suggestion @mariashulga, We actually haven't considered this use case yet, could you give us more details on how you would like to configure a setup like this? Is the number of tenants/systems running the cron job defined beforehand or is it dynamic, etc... And would you want to get an alert everytime there is (N-1) checkins or set some kind of threshold for (N-X) checkins?

**Comment by mariashulga** [comment]
Thank you for clarifying information @davidenwang.

It will be great when we can defined the tenant configs beforehand, but during runtime new tenant can start job checkins and it should  be dynamically added to tenant Sentry configs.

Defining of threshold tenant checkins for alert it is looked like useful config. It will be great when we can set threshold of skipped tenant checkins for generating alerts. Alert will be generated every time by threshold configs by formula (N-X). (n - number of tenants, x - threshold of skipped tenants checkins, can be 0 in case when we want know about each tenant skipped checkins).

**Comment by mariashulga** [comment]
@davidenwang Can you say please, would you need more clarifying information? Because task status is "Stale".

**Comment by hubertdeng123** [comment]
@mariashulga sorry that this fell through, going to go ahead and route to Crons and make sure it's not marked as stale

**Comment by davidenwang** [comment]
@mariashulga Apologies for the incredibly late reply and sorry this fell through. We added this to the backlog a while back and discussed it briefly but I do think this use case is a little uncommon for the typical cron job scenario. 

Though, other ways I could see this working is with multiple monitors, each one representing one tenant and then having alerts on each one. Since we last spoke we have improved SDK integration and supported upsert more widely to allow for automatic creation of monitors from code, instead of manual creation via the UI. Those features might make it easier to maintain a monitor for each tenant.

I know it has been a while since you first opened this request, but let me know if you are still using Sentry crons and if multiple monitors is a viable path forward.

**Comment by mariashulga** [comment]
Thank you for response @davidenwang 
Yes we still use Sentry crons feature for scheduled jobs. In general concept one monitor per job per tenant - work scenario. We can create monitors by using SDK for list of jobs when new tenant created. About some minuses, it is long long list of monitors, in our case 5 tenants(will be increased) x 30 jobs per each tenant = 150 monitors. But it is work scenario. 
Thanks.

**Comment by davidenwang** [comment]
@mariashulga Ahh i see, I'm glad atleast it works for now, and thank you again for writing in with this feedback. If we ever make progress on official multi-tenant support we will be sure to reach back out to you.
