### ISSUE TITLE
Replay: Count on issue detail doesn't match rows - updates within a second

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#44267]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Load issues page: https://sentry.sentry.io/issues/?project=11276&referrer=sidebar
Open [Redirect with :orgId param on customer domain](https://sentry.sentry.io/issues/3740335939/?project=11276&query=is%3Aunresolved&referrer=issue-stream)

### Expected Result

number next to Replay matches the rows in the table

### Actual Result

Tab indicates a different number (twice I noticed a few times) as many events in the table below.

Changing the date range filter in the issue detail doesn't affect the count on the tab or number of rows in the table.

**Comment by JoshFerge** [comment]
## Problem
So I think I know what's going on here. the replay count endpoint works by doing a discover query for the issue id passed in, to find associated replay_ids. It then queries the replays dataset to confirm the existence of these replays, and returns an API response of `issue_id:N`, where N is the number of replays.


The replays search on that page works by doing a discover query to find associated replays, but does not verify their existence. I think with this we were operating under the assumption that data wouldn't be as sparse as it is on this issue. 

## Solution
on the replays_count endpoint, we can simply return a list of replay_ids that we've verified exist, along with the count, so that way the issue replays page can simply use those ids in its replay_index query.

@ryan953 lmk if that makes sense to you and i can whip up the backend changes

**Comment by ryan953** [comment]
@JoshFerge that makes sense to me. lets implement it!

**Comment by JoshFerge** [comment]
@ryan953 backend has been implemented: https://github.com/getsentry/sentry/pull/44774.

note that we still have an issue with non-deterministic counts, which i've written about here: https://github.com/getsentry/team-replay/issues/21
