### ISSUE TITLE
The billing address on the last receipt doesn't change after modifyin the billing address

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#44945]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Modify the Billing Address in Billing Details
2. Go to Receipts, all receipts should show the updated address
3. The last receipt doesn't have its address updated

### Expected Result

The billing address should update on all past invoices

### Actual Result

The billing address updates except on the last invoice

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1750) by [Unito](https://www.unito.io)

**Comment by mbauer404** [comment]
@dalnoki This is now the intended behavior for invoices. Since we started charging sales tax in certain locations, the billing address that was used when the invoice was created must stay consistent with the billing address displayed on the invoice to ensure it aligns with the tax rate charged (or not charged) for the given location.
