### ISSUE TITLE
Crons: Remove dual write logic for monitor checkins, leaving only writing to monitor environments

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#45023]
This involves moving most of the model logic for monitors into the `EnvironmentMonitor` model.

**Comment by evanpurkhiser** [comment]
https://github.com/getsentry/sentry/pull/46973 is going to help with removing some of these legacy fields

**Comment by rjo100** [comment]
Initial removal of references to params we want to remove/modify
https://github.com/getsentry/sentry/pull/47910

**Comment by rjo100** [comment]
First PR:
- Stop updating `Monitor` objects (status, check-in times)
- Remove check-in times from the `Monitor` serializer
- DRAWBACK: `Monitor` objects will have "dangling" `MISSED_CHECKIN\OK\ERROR` statuses that won't get updated (and are visible via the API)

Backfill PR:
- Ensure that all check-ins have an associated monitor environment

Migration PR:
- Remove `null` from `monitor_environment` for check-ins
- Update `Monitor` status to revert to `ObjectStatus` instead of custom `MonitorStatus`

Long term:
- Monitor list sorting will need some reworking, but depends on what frontend decides
- Improve `MonitorStatus` away from a subclass

**Comment by rjo100** [comment]
Am cutting another PR now to "fix" sorting

**Comment by rjo100** [comment]
https://github.com/getsentry/sentry/pull/48039 <- sortin
