### ISSUE TITLE
API permission scope issue when deleting a sepcific debug information file

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry#45089]
![Screenshot 2023-02-13 at 18 49 29](https://user-images.githubusercontent.com/6617432/221263398-43af1128-b8cc-4f2b-9102-a08c54305826.png)

Reported on our Discord https://discord.com/channels/621778831602221064/811725907840335883/1074707359915593750

The code in question might be https://github.com/getsentry/sentry/blob/184fa3bfd28266e7bd91abe4b2b3bdf6d11825a2/src/sentry/api/endpoints/debug_files.py#L196

https://docs.sentry.io/api/projects/delete-a-specific-projects-debug-information-file/

**Comment by brianthi** [comment]
I think this is better to be routed to the ingest team, let me know if i'm wrong

**Comment by kamilogorek** [comment]
It's been like this since it was implemented 5 years ago - https://github.com/getsentry/sentry/pull/10038

API: https://github.com/getsentry/sentry/blob/13f501b6448701324bd8f3f52c9a8fbee625c08c/src/sentry/api/endpoints/debug_files.py#L211
UI: https://github.com/getsentry/sentry/blob/13f501b6448701324bd8f3f52c9a8fbee625c08c/static/app/views/settings/projectDebugFiles/debugFileRow.tsx#L128

Not sure if this should be changed or if docs should be updated.
