### ISSUE TITLE
Show TOTP key below QR code during 2FA activation

### ISSUE THREAD

**Issue by dessant** [getsentry/sentry#4526]
Useful for platforms where QR code scanning is not readily available.

**Comment by bddenhartog** [comment]
Any update on this? I'm in the process of migrating my mobile 2FA via Google Authenticator to [pass-otp](https://github.com/tadfisher/pass-otp), which ends up being a more secure option (the otpauth uri is stored in a gpg-encrypted file).

I am currently unable to do this because you do not show the TOTP key during MFA setup.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by dessant** [comment]
The issue has been fixed for a while, the `Authenticator secret` is present below the QR code.
