### ISSUE TITLE
'Group.checksum' and its values cannot be restored.

### ISSUE THREAD

**Issue by wi-cuckoo** [getsentry/sentry#4529]
when I use sentry upgrade to create tables structure and data, on running command `> sentry:0184_auto__del_field_group_checksum__del_unique_group_project_checksum__del`, then error occurred. Please help me configure out the reason. I just have no idea now. The source code is hard to me

**Comment by mattrobenolt** [comment]
What error do you get?

**Comment by wi-cuckoo** [comment]
@mattrobenolt the title of issue is the error message.

**Comment by nschlemm** [comment]
Happened when testing an upgrade scenario for a customer while operating on a mysql dump that was generated with postgres compatible flag to prepare for db switch - and therefore lost the auto_increment info which in turn triggered "Duplicate entry '0' for key 'PRIMARY'" errors when recording south's migrationhistory - in our case because (oddly enought the same) migration 184 was the second one to be applied based from our "legacy" state. Took a while to figure this out, ...

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
