### ISSUE TITLE
Support long name of services in UI

### ISSUE THREAD

**Issue by Paxa** [getsentry/sentry#45302]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

UI still hard to filter apps with long names

<img width="423" alt="Screenshot 2023-03-02 at 16 40 22" src="https://user-images.githubusercontent.com/26019/222405145-8da9023e-17d3-43ff-adef-f7325ace87b9.png">

Previous issue wasn't actually fixed https://github.com/getsentry/sentry/issues/41256

### Expected Result

UI fit app names or drop down width is responsive (to support smaller devices)

### Actual Result

app names are trincated

**Comment by vuluongj20** [comment]
Hi @Paxa, I'm currently working on a UI update to the project selector — see https://github.com/getsentry/sentry/issues/45074. The new UI should help address your issue with the project names being cut off:

<img width="955" alt="Screenshot 2023-03-02 at 3 06 40 PM" src="https://user-images.githubusercontent.com/44172267/222584702-fdbdcc17-c321-4584-bd4b-ec7242b0a482.png">

Also, in the new design, project names will be ellipsized from the middle rather than the end, so rather than
`support-javascript-project-…`
`support-javascript-project-…`
we'd have something like:
`support-javascript…version-a`
`support-javascript…version-b`
which should help you find the projects you're looking for more easily, since we've noticed that project names usually have differentiated prefixes/suffixes.
