### ISSUE TITLE
Crons: Increase quota call API Sentry monitors "check-in"

### ISSUE THREAD

**Issue by mariashulga** [getsentry/sentry#45583]
### Problem Statement

Due multi-tenancy was reached quota call API Sentry monitors "check-in":
"You are attempting to use this endpoint too frequently. Limit is 40 requests in 1 seconds"

### Solution Brainstorm

Increase quota call API Sentry monitors "check-in"  at least to 60 requests in 1 seconds

**Comment by wedamija** [comment]
Hi @mariashulga, could you explain your use case a bit more here? Why do you need so many checkins per second?

**Comment by mariashulga** [comment]
Thank you for clarifying information @wedamija.

We have multi-tenancy system. Now system has 5 tenants, but this count can be double increase.  In our system there are near 30 cron jobs.  Each tenant has the same list of cron jobs (30 jobs).
Once we took alert about skipped some cron job. We checked logs in our system, that job was executed successfully by schedule. But we saw log next log: "You are attempting to use this endpoint too frequently. Limit is 40 requests in 1 seconds"
As I understand  cron jobs coincided in scheduling time and we reached quota.
Increasing quota call API Sentry monitors "check-in" will help us in feature to avoiding skipping cron jobs.

There is task for supporting multi-tenancy https://github.com/getsentry/sentry/issues/44230

**Comment by wedamija** [comment]
Ok, that sounds reasonable. Instead of increasing the number of requests per second allowed, my plan here is to widen the window to allow 40 * 60 (2400) requests a minute instead. This leaves the rate limit the same, but should help you avoid cases where all your checkins happen at around the same time and bump into our rate limiting.

This will be merged shortly https://github.com/getsentry/sentry/pull/45670

**Comment by mariashulga** [comment]
It is great. Thank you @wedamija.
