### ISSUE TITLE
"Cannot sort by a field that is not selected." when viewing performance tab

### ISSUE THREAD

**Issue by TheArcaneBrony** [getsentry/sentry#45948]
### Self-Hosted Version

23.3.0.dev0

### CPU Architecture

x86_64

### Docker Version

23.0.1, build a5ee5b1dfc

### Docker Compose Version

 2.16.0

### Steps to Reproduce

1. Open web panel
2. Go to performance

### Expected Result

Seeing performance statistics

### Actual Result

![image](https://user-images.githubusercontent.com/13570458/225167004-d76626df-360a-48ac-92cb-ad0b6a2464c8.png)
Notes:
- This error appears in all tabs under performance
- Selecting a project, environment, and different time range all give the same error.
- All tables show "No result found"
- This happened on an older version, not sure which, but upgrading to latest did not solve the issue.

**Comment by hubertdeng123** [comment]
Already done :)

**Comment by TheArcaneBrony** [comment]
Oh, neat :)

**Comment by TheArcaneBrony** [comment]
Can confirm on Firefox Developer Edition (imported LibreWolf profile).
Does not happen in a clean profile.
Wonder if it's some default setting set by LibreWolf?

**Comment by TheArcaneBrony** [comment]
Migrated over my whole prefs.js. Nothing in there.

**Comment by 0Calories** [comment]
Hey @TheArcaneBrony 👋 

I had a look at this earlier and it indeed does appear to be a bug specific to LibreWolf. Sentry supports all major browsers, but we unfortunately cannot promise that it's fully functional on browsers outside of those 😕 

The cause of the bug is not obvious to me so I can't recommend a fix or course of action other than to use Sentry on a supported browser.

Sorry that we can't do more to help here, but as we are an open source company, PRs are welcome if you find a fix!
