### ISSUE TITLE
Allow Configuring OpsGenie Teams for Alert Rules

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#45999]
### Problem Statement

The current OpsGenie integration is a Legacy integration. Currently, it is not possible to configure alert rules to send alerts to different OpsGenie teams for the same Sentry Project. The request is to have Sentry improve the OpsGenie integration to allow for configuring alert rules to send alerts to different OpsGenie teams for the same Sentry project.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1786) by [Unito](https://www.unito.io)

**Comment by cansin** [comment]
@brianthi will this be eventually worked on? Or should we assume that given OpsGenie is a legacy integration this feature might never arrive? I am trying to see if we should spend time creating a custom integration for our organization for this exact same purpose.

**Comment by Dhrumil-Sentry** [comment]
Hi @cansin thanks for bringing up this issue. a couple of questions:

1. Is it not possible for you to route the alert to the right team within Opsgenie itself? 
2. Is there something missing in the Sentry payload that prevents you from doing this?

We don't have any concrete plans to work on Opsgenie at this moment and that will likely be true for the next couple of quarters at least.

**Comment by Lingviston** [comment]
I can add more details on this. Hope it'll lead to the issue re-opening.

Opsgenie gives a bit limited capabilities in terms of team-to-team routing:
- You can't route to another team or escalation of another team from the "team routing rule";
- It looks like you can route to another team only from the escalation, which is too high level;
- Though you can route to another team from an escalation - you still can't route to an escalation of that team;
- All of the escalation/routing rules mentioned above have to be linked to the original team linked with Sentry. It means that analytics, which is automatically calculated by the OpsGenier, will be at least partially if not fully calculated for the original team instead of the routed one;
- Finally, it just makes the configuration way more complex as the "target team" have to modify the "original team's" config for way too many reasons.

**Comment by Dhrumil-Sentry** [comment]
Thanks for the feedback @Lingviston - This is currently on our backlog and we'll hopefully have an update about this soon.

If Sentry allowed you to choose an Opsgenie Integration and the Opsgenie team/service in your Sentry alert rules would that work for you?

That's how our Pagerduty integration works today:
![image](https://github.com/getsentry/sentry/assets/109983869/ad296926-16b4-4975-a084-386e92c1bfb3)

**Comment by Lingviston** [comment]
Hi
My final goal is to simple send alerts to multiple teams from the same
Sentry project. But from the OpsGenie POV it means that all these alerts
must use different API keys. If you let me configure that key in per alert
basis, rather than a per project, like now, then it'll work for me.

вт, 6 июн. 2023 г., 21:57 Dhrumil ***@***.***>:

**Comment by Dhrumil-Sentry** [comment]
We've built a new Opsgenie integration for Business plan customers. We're looking for customers who're willing to try the integration and provide feedback to us. Please see https://github.com/getsentry/sentry/discussions/54156 for more details

**Comment by Dhrumil-Sentry** [comment]
The new Opsgenie integration is now generally available. Please see our [changelog](https://changelog.getsentry.com/announcements/1-fba83fb7-b83e-47f9-bd7a-24a38257d1f5) for more details

cc @cansin

**Comment by Lingviston** [comment]
@Dhrumil-Sentry is it also available to self hosted Sentry users or still only to business plan holders?

**Comment by hubertdeng123** [comment]
@Lingviston It is enabled for self-hosted Sentry users too. If you're on the latest nightly images, you should be able to configure the integration. If you'd rather wait until the monthly release, 23.9.0 will be out later this month and it'll be included there as well.
