### ISSUE TITLE
Not possible to create JIra issue from sentry when tempo account field is used

### ISSUE THREAD

**Issue by izenk** [getsentry/sentry#46181]
This is duplicate of this [issue](https://github.com/getsentry/sentry/issues/45931)

But its still unclear for me. I can see support for exact tempo account field in [code](https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/jira_server/integration.py#L257)

**Comment by brianthi** [comment]
Hi @izenk the code you've referenced is was intended to support custom fields.  However, in the past couple of years we have not seen this working and have since stopped supporting this feature as documented here: https://docs.sentry.io/product/integrations/issue-tracking/jira/#cant-create-issues-using-a-custom-required-field.  I'll log this request and notify to the appropriate team, however it's unlikely that this is something we'll start supporting again soon.

**Comment by sergiosentry** [comment]
@brianthi Hey! Some customers have asked for custom fields support lately. Was there any progress or official answer on whether or not we can support these fields in the future?

**Comment by brianHK79** [comment]
Any news on this topic? The situation is similar at our company: we use the Tempo plugin in Jira, so Account is a mandatory custom field for our Jira projects.

The Jira-Sentry integration doesn't work that way. And this problem, in my opinion, cannot be solved by putting in the documentation that Jira custom fields are not supported for integration. A significant number of Jira plugins build on individual fields, and the number of compenies that use Jira without any plugins may be quite small.

**Comment by hostalp** [comment]
We recently setup a Jira integration and almost immediately encountered the same issue.

When we attempt to create a (self-hosted) Jira Server 9.12.16 (with Tempo Plugin 18.9.0) issue from (self-hosted) Sentry 25.12.1 where the _Account_ field is required, we get an error:
> (HTTP 400): Account id 'null' is invalid

Even though the field has the correct value - numeric ID of the desired Tempo Account that exists in Jira.

After checking the logs we found out that the value of the Tempo Account field (`customfield_12585` as shown below) is sent to the Jira server as unquoted number which is incorrect, the value should be quoted.
`[INFO] sentry.integrations.jira_server: jira_server.create_issue (organization_id=1 integration_id=3 jira_project='25325' cleaned_data={'summary': 'Test Issue Summary', 'issuetype': {'id': '3'}, 'security': {'id': '10000'}, 'priority': {'id': '5'}, 'description': 'Sentry Issue: [TEST3|https://sentry.local.loc/organizations/local-org/feedback/?referrer=jira_integration&feedbackSlug=test3%3A880&project=8]', 'labels': [], 'customfield_12072': 'P12345678-5483', 'customfield_12585': 285, 'project': {'id': '25325'}})`

Note the following: `'customfield_12585': 285`
Which should be actually: `'customfield_12585': '285'`

First we tried a workaround by quoting the number in the Sentry web form for creating the Jira issue, however that didn't help and only resulted in double quotations as the quoted input was treated as string this time and quoted again (which would be otherwise correct).

Then we tried a quick fix by modifying the following piece of code at our self-hosted Sentry instance:
https://github.com/getsentry/sentry/blob/25.12.1/src/sentry/integrations/jira_server/integration.py#L1062
`-                                v = int(v)`
`+                                v = v`
Which resulted in the Tempo Account request parameter value being correctly quoted and the issue created.

We aren't of course 100% sure if that's the right place to perform that code change, but it at least helped and confirmed out suspicion.
Could you please fix this properly?
