### ISSUE TITLE
issue reports invalid minidumps that appear valid in MSVC

### ISSUE THREAD

**Issue by marekr** [getsentry/sentry#46231]
### Environment

SaaS (https://sentry.io/)

### Link

https://kicad.sentry.io/issues/3993253449/

### DSN

https://463925e689c34632b5172436ffb76de5@sentry-relay.kicad.org/6266565

### Steps to Reproduce

This issue has 5 events that are marked <.unknown>: invalid minidump
They are valid and open in MSVC without issue.

I am unsure of which getsentry repo to report this in

Picking event b852d5559c1
https://kicad.sentry.io/issues/3993253449/events/b852d5559c1044ada045e90b4c25dfe0/?project=6266565

and event f0dadd5c

https://kicad.sentry.io/issues/3993253449/events/f0dadd5c27164c4f8ef04fe27ee537ce/?project=6266565

### Expected Result

MSVC is able to load and display the Modules List and stack trace just fine 

**Event b852d5559c1**
(Module List appears fine)
![image](https://user-images.githubusercontent.com/1838013/227058760-1f69ff0f-d017-4e55-92ae-35d05b024a59.png)

**Event: f0dadd5c** 
(module list and call stack loads fine)
![image](https://user-images.githubusercontent.com/1838013/227059241-a674a7ef-b18f-4800-8503-89d4f8e8558f.png)

### Actual Result

**Event b852d5559c1**
![image](https://user-images.githubusercontent.com/1838013/227058709-77064523-5fca-43b7-9be1-29e573bb2f3a.png)

**Event: f0dadd5c** 
![image](https://user-images.githubusercontent.com/1838013/227059155-2e30bfac-5384-4e49-9803-c56c0c3b4fb1.png)

**Comment by Swatinem** [comment]
Hi @marekr , thanks for the report.
I had a chance to inspect both minidumps:

The first one seems to be tripping this error here, because the library we use to parse minidumps seems to have very strict validation:

https://github.com/rust-minidump/rust-minidump/blob/0ef0ac5e9235222e09bae371a782f348d8e33c5b/minidump/src/minidump.rs#L1508-L1511

Indeed the last module in the ModuleList is supposedly a 0-size module located at memory offset 0. It has an empty name, and an empty CV record.

We are working on a fix and will be able to support this case soon.

---

The second minidump does contain some garbage data as one of the module names, as seen here in the hex view:
This is a 4-byte length prefix, plus the UTF-16 encoded file path. It does end in `MSCTF.dll`, but the beginning is garbled.

![Bildschirm­foto 2023-03-23 um 15 54 21](https://user-images.githubusercontent.com/580492/227242870-90bdb8dd-fbd3-4c4d-8090-1d104fb714e5.png)

It is possible that visual studio just ignores these, and otherwise parses the file normally. We have seen that these corrupted file names can cause problems for us internally and are thus validating them more strictly.

From looking at the hex view, it would appear that the filename is being overwritten with some garbage, which appears to be exactly 3 8-byte values, interpreted as little-endian, all starting with `0x0000_0202_...`.

I suspect that this might be a bug in Crashpad itself, as the minidump has a "crashpad info stream". As I see, you are using sentry-native in version `0.5.4`, so if you use the bundled crashpad version, that might narrow down the specific version which might have caused this data to be overwritten by garbage.

**Comment by loewenheim** [comment]
The first part of this is being addressed in https://github.com/rust-minidump/rust-minidump/pull/823.

**Comment by marekr** [comment]
> I suspect that this might be a bug in Crashpad itself, as the minidump has a "crashpad info stream". As I see, you are using sentry-native in version `0.5.4`, so if you use the bundled crashpad version, that might narrow down the specific version which might have caused this data to be overwritten by garbage.

Yep, we are using the bundled crashpad with sentry-native. 


If you look at event id 08d256dfde394efbbbb0ac4b43cd62b0 that's also in that issue, it's reported by the newer sentry-native 0.6.0. It displays the same error
![image](https://user-images.githubusercontent.com/1838013/227389444-17c701d7-8f3d-42e8-abce-3fcdd21632cc.png)

But MSVC opens it fine

![image](https://user-images.githubusercontent.com/1838013/227389474-cc7352cb-35c5-4703-9f77-2f53173fabba.png)

**Comment by marekr** [comment]
> It is possible that visual studio just ignores these, and otherwise parses the file normally. We have seen that these corrupted file names can cause problems for us internally and are thus validating them more strictly.


Yea I found it, Visual Studio actually tries to display it:
![image](https://user-images.githubusercontent.com/1838013/227390516-845549a5-2942-4d13-a9ac-acc57d930292.png)

But otherwise parses the file and handles opening the callstack

**Comment by loewenheim** [comment]
The problem here is that we need the code file name for processing. If it were just a matter of displaying it, we could make a best effort, but we need it to be correct.

**Comment by Swatinem** [comment]
My idea that crashpad itself may corrupt might have been the wrong idea.
Indeed, crashpad reads the name of the loaded module directly from the process memory here:

https://github.com/getsentry/crashpad/blob/e56784c9f2f53e0fe0e31717c965b7a14a0961b1/util/win/process_info.cc#L293-L296

So it might be possible that this exact part of the process memory was corrupted, maybe by the same bug that then lead to the crash being captured in the first place.

The reason we validate these file names is that we use them for various purposes, for example for symbol server lookups according to these conventions: https://github.com/dotnet/symstore/blob/main/docs/specs/SSQP_Key_Conventions.md#key-formats
… as well as to display in the Sentry UI. We have seen quite some garbage in there, like NULL-bytes, paths that exceed maximum path limits, etc.

One idea may be to not throw away the whole minidump, but rather replace such invalid file names with a sentinel value marking them as invalid/corrupted.

**Comment by loewenheim** [comment]
I opened an issue to track the second part of this (invalid `code_file`).

https://github.com/getsentry/symbolicator/issues/1115

**Comment by Swatinem** [comment]
Also thank you @marekr for the detailed and actionable feedback! This helped us find these things very quickly and start working on appropriate fixes, though it may take some time for those to land.

**Comment by Swatinem** [comment]
The bot is very right to remind us about this. We have since upstreamed (and updated) more lenient parsing in `rust-minidump`, and found a better solution for corrupted `code_file` properties. So this should be fixed now :-)
