### ISSUE TITLE
Version 8.11 "AttributeError: SafeMIMEMultipart instance has no attribute 'as_bytes'"

### ISSUE THREAD

**Issue by evan-ty** [getsentry/sentry#4635]
## Reporting Bugs
When reporting bugs, include details about your configuration, such as:

- The version of Sentry you're using
8.11
- Whether you're using Docker or another installation method
Python, no virtualenv

- Include a stacktrace or other logs when relevant
https://paste.debian.net/900898/

- Include a redacted version of your configuration when relevant
config.yml
https://paste.debian.net/900900/

sentry.conf.py
https://paste.debian.net/900902/

**Comment by mattrobenolt** [comment]
Hey @evan-ty, can you also dump `pip freeze` and `python -V`? It's unclear to me how this is possible.

**Comment by evan-ty** [comment]
@mattrobenolt 

Gladly:

pip freeze:
https://paste.debian.net/900918/

python -V:
Pyhon 2.7.6

**Comment by mattrobenolt** [comment]
I'm honestly unsure how that error could happening since it's effectively saying an attribute doesn't exist on a Django object here: https://github.com/django/django/blob/1.6.11/django/core/mail/message.py#L124-L154

So if Django is in fact, 1.6.11, there's no justifiable reason why it wouldn't have that attribute.

**Comment by evan-ty** [comment]
I'm quite confused myself.  I was pretty sure it was some sort of configuration issue.  The interesting thing is that, the emails and notification from my instance of sentry are still being sent though.

**Comment by mattrobenolt** [comment]
Yeah, because ironically, it's failing after sending the message trying to log the message length. :) So everything worked. https://github.com/getsentry/sentry/blob/master/src/sentry/utils/email.py#L403-L413

I'm going to close this out since there's something odd here, but I'm not convinced it's something we're doing wrong.
