### ISSUE TITLE
JS Loader: Sentry.init should be called - with defaults from docs for Performance/Replay

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry#46368]
As the title says, the goal should be that someone should be able to just paste the `<script/>` tag and without any manual calls to `Sentry.init` get the experience using it.
That means, for example, pageload transactions and Replays are automatically captured when Performance and/or Replay is enabled.

It should be possible to still call `Sentry.init` yourself and with that overwrite our defaults.

**Comment by mydea** [comment]
So, I think I have the loader stuff working (locally) now. However, IMHO it would be great to have some kind of E2E or integration test in sentry that actually checks the behavior, because this is not really tested as of now and I think very hard to test with the current setup. With the changes, there are basically the following scenarios that have slightly different behavior:

## Lazy mode

Lazy mode is only available for errors-only config. Users can manually opt-out of this by adding `data-lazy="no"` to their script tag.

In lazy mode, nothing happens until an error occurs. Once an error occurs, we download the CDN bundle, and then...:

* If `onLoad` is configured, trigger it
* If `SDK.init()` has not been called, call it with defaults

## Eager mode

If either performance or replay is enabled, we are always in eager (non-lazy) mode. In this mode, we'll automatically load the CDN bundle, and then...:

* If `onLoad` is configured, trigger it
* If `SDK.init()` has not been called, call it with defaults

## Defaults

The following default config is defined:

* `dsn`: Always set
* `debug: true` is set when debug bundles are enabled
* `tracesSampleRate: 0.1` is set when performance is enabled
* `replaysSessionSampleRate: 0.1` & `replaysOnErrorSampleRate: 1` are set when replay is enabled

This config can be overwritten by the user, and is merged. So e.g. if they do:

```js
Sentry.onLoad(function() {
  Sentry.init({
    tracesSampleRate: 0.5
  });
});
```

For a full loader build with every option enabled, the actual config will be:

```js
{
  dsn: 'your-dsn',
  debug: true,
  tracesSampleRate: 0.5,
  replaysSessionSampleRate: 0.1,
  replaysOnErrorSampleRate: 1
}
```

**Comment by AbhiPrasad** [comment]
We also need to add `Sentry.BrowserTracing` and `Sentry.Replay` as well for auto-instrumentation.

**Comment by mydea** [comment]
> We also need to add `Sentry.BrowserTracing` and `Sentry.Replay` as well for auto-instrumentation.

Right, this too (actually I did this but forgot to write it down xD) will add it to the list above for completeness!
