### ISSUE TITLE
Agreements PDF preview too small

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#46854]
### Environment

SaaS (https://sentry.io/)

### Version

n/a

### Link

https://prisjakt-ab.sentry.io/settings/legal/

### DSN

n/a

### Steps to Reproduce

n/a

### Expected Result

Either make the PDF full screen or add a link to open it in a new tab.

### Actual Result

![image](https://user-images.githubusercontent.com/51749023/229751190-e5c5572f-d9c1-4cb6-bc63-5c239e76d443.png)
![image](https://user-images.githubusercontent.com/51749023/229751210-f90fc900-db02-4334-8527-d2862f73966f.png)

**Comment by mitsuhiko** [comment]
I'm guessing the issue here is that your PDF viewer in the browser has the chapter sidebar expanded. The download button gives you the PDF to look at. I think that problem generally applies to other policy documents as well though I believe most of those are HTML pages which probably render better in that popup.
