### ISSUE TITLE
Replay Privacy Request

### ISSUE THREAD

**Issue by MarkFeed** [getsentry/sentry#46906]
### Problem Statement

We handle sensitive information in our application.  We need to be able to produce a log of who has seen various replays as well as for a particular user, which replays they have viewed.  If there is a breach situation, the log will validate (or confirm) that our user played a part.  While it won't be used often, breaches don't happen often, this is critical functionality when there is a breach situation.  Please consider expediting a solution.

**Comment by bruno-garcia** [comment]
> We handle sensitive information in our application.

Sentry's Session Replay is privacy-focused out of the box. On our [product docs, there's a Privacy section](https://docs.sentry.io/product/session-replay/protecting-user-privacy/) where we got in depth why that's the case, including capabilities to scrap PII when ingesting data. 
The [SDK docs also have a dedicated privacy page](https://docs.sentry.io/platforms/javascript/session-replay/privacy/). Where a series of options exist to allow you to **opt-in** to capturing text such as labels and other data with the Replay. That's because by default it captures none. 

The key take-away here is that **by default** Sentry won't be collecting any sensitive information. We're not planning on building an audit tool 

>  If there is a breach situation, the log will validate (or confirm) that our user played a part.

This is not a goal of our Session Replay product at this time. We're building a tool for developers to help them quickly assess the impact of bugs in their users' experience. And give them all the context they need to find a solution quickly. It sounds like you might be looking for a different tool such as https://futurefeed.co/ for this particular use case.

**Comment by bruno-garcia** [comment]
I believe I might have misunderstood your request btw. If your goal is to understand who accessed your org data over a period of time due to a breach in your system (or of a third party that might have exposed you) Sentry can definitely do that upon-request.

@misha-sentry mentioned internally:

> If a customer needs us to review and export their access/auth logs, we have done that before. 
> Generally we just ask that they are as specific as possible and provide a time frame.
