### ISSUE TITLE
User Token not revoked completely when deleting the user

### ISSUE THREAD

**Issue by magali-caruso** [getsentry/sentry#47474]
### Problem Statement

When a user is deleted by the admin of the platform, the tokens from it are not completely revoked. 
We add a security incident where one of these tokens was exposed and the user was no longer part of the company. So we deleted the user directly. 
When testing the revoked token we realized that the token was still able to successfully execute this curl:
`curl -X GET "https://sentry.io/api/0/" -H "Authorization: Bearer redacted-token-here" -H "Content-Type: application/json" -v`

This URL would return information about the user, such as the email, permissions, the last login, etc. This isn't critical information but any information is useful sometimes for a hacker.

### Solution Brainstorm

When a user is deleted, revoke completely any access tokens related to it.

**Comment by mdtro** [comment]
HI @magali-caruso 

This is expected behavior. Organization admins do not own the a user's API token -- the user does. In Sentry, a user can be a part of multiple organizations so we treat them as separate entities.

The user will need to remove the API token.

That said, removing the user from your organization will prevent the leaked token from being able to perform any operations on your organization. If you have a process or something that you do not want coupled to a user, but rather to the organization, I recommend using our [internal integrations](https://docs.sentry.io/product/integrations/integration-platform/internal-integration?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F).
