### ISSUE TITLE
Allow to define pluggable integrations for loader

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry#47540]
### Problem Statement

Currently, when using the loader, the only way to get pluggable integrations working is to load them in addition to the loader script from the CDN.

However, this is brittle, because for the CDN you'll have to define an exact version, while the loader will always load the latest SDK version. This can lead to the case where the integration version becomes incompatible with the main SDK version, as we generally assume these are in sync.

See also https://github.com/getsentry/sentry-javascript/issues/2476#issuecomment-1511445738

### Solution Brainstorm

We should allow a way to define integrations to load for the loader. For example, something like this:

```html
<script src="https://loader-url.com" data-integrations="HttpClient,CaptureConsole"></script>
```

We could then make sure to load the correct version of the integration in the loader script.

**Comment by andreyvolokitin** [comment]
Also note that currently lazy-loading and avoiding sentry scripts being ad-blocked is problematic due to inability to set SDK bundle url: https://github.com/getsentry/sentry-javascript/discussions/7288. Regular sentry CDN urls can be blocked by ad-blocker thus preventing SDK to load. This can be solved by serving SDK from the own host or using reverse proxy to change URL, e.g `myproxy.com/?url=sentry-cdn.com/bundle.js`. But for this we need an ability to pass the URL to the loader. Currently at my company we solve this by reverse proxy which rewrites JS urls inside JS files (so we "pass" our URL to the loader by replacing it inside the `loader.js` on the fly)

I guess loading integrations by the loader might further complicate this, as there will be more urls to handle (and those additional urls might be dynamically built preventing them to be replaced by reverse proxy as we currently do). I currently have no idea how this could be handled, but I guess again via some `data-attribute` on a loader `<script>` tag
