### ISSUE TITLE
Normalize URLs captured with error events

### ISSUE THREAD

**Issue by idosun** [getsentry/sentry#47795]
### Product Area

Issues

### Problem Statement

We're tracking [ HTTP Client errors](https://docs.sentry.io/platforms/javascript/configuration/integrations/plugin/#httpclient) for selected response codes (4xx, 5xx) and domains/URLs with Sentry's JS SDK. These are captured as Sentry error events containing metadata regarding the failed API call - `http.url, http.method, http.status_code,` etc.  

The problem is that the requested URL ( http.url ) is captured in its raw form (with dynamic parameter values). For reporting, alerting, and dashboarding purposes we'd like to see those parameterized so we can aggregate them properly. 

Of course, this would be relevant for all SDKs capturing HTTP client errors and URLs in general. 

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1814) by [Unito](https://www.unito.io)

**Comment by joelzimmer** [comment]
Normalizing these urls would be incredibly helpful for us

**Comment by AbhiPrasad** [comment]
[According to the spec](https://develop.sentry.dev/sdk/features/#http-client-errors) sets the Request interface and the Response context.

We can't do it on the SDK side because the client has no knowledge of the server's routing configuration. For example, the client has no way to tell if `/123` should be `/:id` or is intentionally `/123`.

This also makes it difficult for us to do it during ingestion, but it's the only way to get this to work.

The best way around this is to set a tag on your event based on the request/response in `beforeSend` that parameterizes the url accordingly, since the SDK user has full knowledge of their app setup.

I'm going to route to ingest, but it's a non-trivial problem so I think there is no immediate solution.

**Comment by narlei** [comment]
Hi, there is any updates about this topic?

**Comment by jjbayer** [comment]
@narlei this is still on our backlog and I don't think we will get to it anytime soon. Even with some effort, the server-side parametrization would be an imperfect heuristic. Would you be able to work around this on the SDK side, where you actually know what you want to group by?

> The best way around this is to set a tag on your event based on the request/response in beforeSend that parameterizes the url accordingly, since the SDK user has full knowledge of their app setup.

**Comment by Dav1dde** [comment]
This is currently unrealistic, the best way forward is this rely on the SDK and if it cannot extract that from the middleware, use the `beforeSend` hook to modify the URL.
