### ISSUE TITLE
Feature Request: Re-Scrub Sentry Event

### ISSUE THREAD

**Issue by matteius** [getsentry/sentry#4786]
**Do you want to request a *feature* or report a *bug*?**

Feature request.

**What is the current behavior?**

Currently if a sensitive field is not listed in the 'Additional sensitive fields' section when the event is logged, then the sensitive data is shown in the sentry error.  Adding the new field to the 'Additional sensitive fields' does not retroactively scrub the even, and there is no button on the event to re-scrub it against new filters.

**What is the expected behavior?**

I would expect that I could have Sentry re-scrub an event rather than the  only supported solution to delete the event altogether.

**Comment by dcramer** [comment]
Events are immutable in Sentry, and this would be an extremely expensive operation for many of our customers. Unlikely that we'll change this any time soon because of those reasons.

**Comment by matteius** [comment]
If the events are stored in a database like Postgresql how are they immutable?   How would it be an extremely expensive operation if you had to manually kick off the request to further scrub down a grouping of collected events?  More expensive than leaking sensitive information?

**Comment by dcramer** [comment]
@matteius they're not stored entirely in SQL, and they're immutable as a design constraint on the system. Not literally immutable, but its expensive to mutate them in some storage engines. The reason its expensive to scrub the events is because of the size of data we collect. Some customers have 10s of millions of events a day, and each of those events can be fairly large in size. Even iterating through this can be a costly cost, but parsing, scrubbing, and then eventually re-storing them (due to the constraints of mutation) is extremely expensive.
