### ISSUE TITLE
[SnubaError] - After processing, query is 642320 bytes, which is too long for ClickHouse to process. Max size is 262144 bytes.

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#47889]
**Sentry Event:** https://sentry.sentry.io/issues/3905418628/?project=1

**Note:**

> Not sure how easy it is to fix… we need to somehow control the size of the query… the query itself doesn’t look too big (just by eyeballing the code), of course, if there are a lot of projects the query can get arbitrarily big… .
> Not clear to me how we should fix it though ( of course we can impose a max number of projects specified in the query) … but the max number that snuba allows would depend on the overall size of the query, not the number of projects - Radu

**Comment by matejminar** [comment]
Happening only for one org. See the URL tags on the issue details.

**Comment by obostjancic** [comment]
This org uses it to display crash rate of their android project through one of the widgets on a custom dashboard

It happens when the parameter  `query=project:android` is present in the request. Interestingly, querying for other projects (i.e. `query=project:ios`) behaves as expected returning seemingly correct results. 

Additionally it seems to be independent of:
 - the metric that is being requested; simple metrics like [sessions.all](https://sentry.sentry.io/issues/3905418628/events/ba611584054f49348663cba474d91715/) and [sessions.crashed](https://sentry.sentry.io/issues/3905418628/events/dd09dd71f6324eef987b2c118c1f1e5f/) also result in an error when .`query=project:android` is present 
 - the time interval; even short time timeframes (2h) with period of 15m fail [link](https://sentry.sentry.io/issues/3905418628/events/31b9dfd0623644b19ab9abd2f831c569/)
