### ISSUE TITLE
Crons duplicating

### ISSUE THREAD

**Issue by cschubiner** [getsentry/sentry#47993]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

we have the django celery cron implemented, yet all are crons on dduplicated, and thus constantly throwing errors

### Expected Result

few errors

### Actual Result

login to our account and see the crazy number of errors that are thrown

### Product Area

Crons

### Link

https://shopcanal.sentry.io/crons/?environment=production&project=5875454

**Comment by gaprl** [comment]
Hey @cschubiner, we just checked and these aren't duplicates but instead different environments. Since you are using the Celerybeat auto discovery and the code was deployed to different environments, they all get created automatically.

If you don't want to have monitors created for specific environments, I recommend adding a condition during the Celerybeat integration setup to prevent it from initializing.

I'll close this issue for now, but let us know if you have any more questions or issues.

**Comment by cschubiner** [comment]
@gaprl I had to manually delete a ton of monitors, which is why you're not seeing any on my account. 

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1813241/234692353-cf537396-eb37-4232-922d-9cf652dcad8a.png">

we're drowning in sentry logs --- and this is _after_ I went in and made everything 99 minutes timeout & 99 minute duration max (instead of the default zero)

**Comment by gaprl** [comment]
Hey @cschubiner, my apologies for missing your follow-up. I wanted to let you know we've recently fixed an issue in our Python SDK that should take care of the problem you reported.

We recommend updating the SDK to [v1.23.0](https://github.com/getsentry/sentry-python/releases/tag/1.23.0).

Please let us know if after updating you still face issues.
