### ISSUE TITLE
Tooling to debug why/if a Sentry Issue transitioned to Escalating

### ISSUE THREAD

**Issue by NisanthanNanthakumar** [getsentry/sentry#48236]
I was thinking of making an endpoint that returns the forecast and the hourly event volume for the issue. We can have a simple line graph that can display both and we can see if it should have escalated if there was an intersection.

We can also confirm the change with logs & GroupHistory table.

We can put it in _admin. That should help us debug if it should have transitioned into the escalating state or not.

**Comment by brianthi** [comment]
Chatted with Nisanthan about this but taking notes here.  This sounds fine if the UI work in _admin is very simple, and the API that provides the data is implemented in a way which we can potentially reuse it in the issue details page in the future.  Also, the issue's activity tab should indicate the threshold and the current daily count so that users can see the cause of escalation, and not need to ask support or create a GH issue.

**Comment by robinrendle** [comment]
I reckon the Activity page is the best place for it. Something like this would be good, although I likely need to add more realistic examples based on how escalating is triggered:

<img width="870" alt="CleanShot 2023-05-01 at 14 54 39@2x" src="https://user-images.githubusercontent.com/1900676/235538436-e217bcf8-b66a-49f8-97c3-c9b1f173f4c7.png">
