### ISSUE TITLE
Sentry Transaction Page spans overflow

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#48356]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

see this replay: https://sentry.sentry.io/replays/javascript:8343dfb0c3f147eba781acfb531be289/?project=11276&query=user.email%3Ajosh.ferge%40sentry.io&referrer=%2Freplays%2F%3AreplaySlug%2F&statsPeriod=14d&yAxis=count%28%29&t=624

and this page: https://sentry.sentry.io/performance/sentry:0518b344deee4b60afc54972bb1e2a4e/?end=2023-04-26T09%3A37%3A43&project=1&query=http.method%3AGET&referrer=performance-transaction-summary&start=2023-04-23T18%3A51%3A57&transaction=%2Fapi%2F0%2Forganizations%2F%7Borganization_slug%7D%2Fusers%2F&unselectedSeries=p100%28%29

### Expected Result

I am able to view all the spans

### Actual Result

The spans end up getting cut off on the left side of the spans div

### Product Area

Performance

**Comment by silent1mezzo** [comment]
This is partially expected as we auto-scroll the horizontal axis to make sure the span name is readable. It gets wonky when there's a lot of nesting. This can always be manually fixed by using the scroll bar at the top.

<img width="594" alt="Screenshot 2023-05-02 at 2 19 28 PM" src="https://user-images.githubusercontent.com/155016/235751691-9058eda6-5f62-41b3-bbbb-8e50c2475668.png">

**Comment by olivier-w** [comment]
@JoshFerge can you share a bit more details on why you wanted to view all the spans in that event? I'm curious as to what details you wanted to have in context.
