### ISSUE TITLE
Grouping Investigations

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#48398]
- [x] Potential Grouping Issues: https://github.com/getsentry/sentry/issues/49584
- [ ] Groups without stacktraces: https://github.com/getsentry/sentry/issues/49585

**Comment by armenzg** [comment]
NOTES:
* It would be ideal that Sentry by default set a field of what URL was attempted and the status code. This would be incredibly powerful because it would allow filtering and grouping issues based on domain or status code

Some notes from Slack:

The advantage of rules like `error.type:ApiHostError -&gt; api-host-error, {{ transaction }}` is that when a host is not available we only get 1 group per transaction rather than N groups per transaction (N being the number of distinct API calls to that host).

[Since I removed the rule](https://sentry.sentry.io/discover/results/?end=2023-05-18T15%3A19%3A43.000&amp;id=20985&amp;project=1&amp;start=2023-05-17T17%3A19%3A43.000), you can see that we’re getting more than 1 group per transaction (see screenshot).

The screenshot below shows that both `process_commit_context` and the `derive_code_mappings` tasks created many groups when api.github.com had a blip. This is because their stack traces had different API calls coming from different parts of the code.

IIUC It all comes from a call to a socket’s connect that fails ([link](https://github.com/getsentry/sentry/blob/4466889956155cb9da7322d66a05142e6db451f5/src/sentry/net/socket.py#L149) to code)

Should we consider grouping certain network calls based on their transaction or module?

Perhaps in the UI, we give a setting to customers to choose if to NOT group certain network calls.

Perhaps this is a TSC topic or bad idea right away.

![image](https://github.com/getsentry/sentry/assets/44410/98389bb4-b0b0-4f66-a3bf-da9295808810)
![image](https://github.com/getsentry/sentry/assets/44410/80daed8c-8faf-4149-b6b2-627a23588d95)
![image](https://github.com/getsentry/sentry/assets/44410/ec0f9a11-c249-4f84-a2e2-b0eb22915ad4)

**Comment by armenzg** [comment]
The context-line changes, thus, it creates a new group.
Perhaps, we can suggest grouping for this new group with the old one.

NOTE: I grouped them already by hand.

[This code](https://github.com/getsentry/sentry/pull/49360/files#diff-5996232f4fd7afb156ac89ae6b48c03b48102576ca43bfe45e55ec4da422acaeL360) landed and it changed the line where the error is produced.

The error used come from [for user in get_suspect_commit_users(project, event)](https://github.com/getsentry/sentry/pull/49360/files#diff-5996232f4fd7afb156ac89ae6b48c03b48102576ca43bfe45e55ec4da422acaeL363) but now it comes from [get_suspect_commit_users(project, event)](https://github.com/getsentry/sentry/pull/49360/files#diff-5996232f4fd7afb156ac89ae6b48c03b48102576ca43bfe45e55ec4da422acaeR368):
<img width="575" alt="image" src="https://github.com/getsentry/sentry/assets/44410/7a6b727c-012e-4414-a778-a3b7a66e45c7">

See how the context-line changes:
<img width="963" alt="image" src="https://github.com/getsentry/sentry/assets/44410/d6551764-6e11-4fb2-b7cd-2d18f8c3dd8e">


- [Link to query](https://sentry.sentry.io/issues/?project=1&query=logger%3Asentry.notifications.utils.participants&statsPeriod=14d)
- [Link to old event](https://sentry.sentry.io/discover/sentry:26e8d80137854b8b83718e1a93ac51b4/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=Commit.DoesNotExist&project=1&query=issue%3ASENTRY-1065&sort=timestamp&statsPeriod=90d&yAxis=count%28%29) ([old group redirects](https://sentry.sentry.io/issues/4046641574/?project=1&query=logger%3Asentry.notifications.utils.participants&referrer=issue-stream&statsPeriod=14d&stream_index=1))
- [Link to new issue](https://sentry.sentry.io/issues/4192218215/?project=1&query=logger%3Asentry.notifications.utils.participants&referrer=issue-stream&statsPeriod=14d&stream_index=0)

<img width="909" alt="image" src="https://github.com/getsentry/sentry/assets/44410/165e26f3-917a-4861-99ef-1f7116a7f7dc">

**Comment by armenzg** [comment]
There's a Django project that does not have stacktraces and errors are being grouped by message, thus, UUIDs in the message produce different groups.

The Electron SDK includes the user paths in the `module` for stack traces, thus, generating groups per user.

<img width="343" alt="image" src="https://github.com/getsentry/sentry/assets/44410/2dae9598-d25d-4b2e-9f0e-b20162a03aaf">
<hr/>

![image](https://github.com/getsentry/sentry/assets/44410/6f0f8860-a196-4a72-9f3c-aa7857c645bc)

**Comment by armenzg** [comment]
Todo:
* create a way to see number of groups per platform across orgs.
* talk to data for similarity algorithms
  *  k=v
