### ISSUE TITLE
Changing project drops environment filter

### ISSUE THREAD

**Issue by samuelhwilliams** [getsentry/sentry#48526]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1) Be on a team plan (ie no cross-project search)
2) Look at issues for a project
3) Select an environment, eg production, and lock it
4) Change project
5) Environment filter returns to 'All envs'

### Expected Result

Environment is retained when changing projects (where possible)

### Actual Result

Environment filter is dropped

### Product Area

Issues

**Comment by vuluongj20** [comment]
Hello! This behavior is expected. The way Sentry currently works, projects _contain_ environments in a parent-child relationship. As such, changing the project selection will necessarily lead to the environment filter's value being reset. 

Try changing your project selections, and then open the environment filter: you should see that the list of selectable environments has changed based on which projects have been selected. Since the old filter value might not be available in the new list anymore, we need to reset the value to "All Envs".

**Comment by samuelhwilliams** [comment]
I suppose I knew that relationship was the case.

Consider this a vote for still carrying it over it possible though :(
