### ISSUE TITLE
Integration platform - Sentry shows app installed even if partner did not send the installation confirmation

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#48607]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Feedback from partner:

 During some testing of installing our public integration, we noticed that regardless of success or failure, and even when we don’t send the required `PUT https://sentry.io/api/0/sentry-app- 
installations/${installationIdFromUrl}
{
  "status": "installed"
}` request, it still says the integration was successfully installed on the integrations page. Is that expected behavior? It feels like a bug to us

### Expected Result

Sentry should not show the integration installed on sentry.io until you receive confirmation from the partner

### Actual Result

-

### Product Area

Settings - Integrations

**Comment by scefali** [comment]
@Dhrumil-Sentry They likely don't have the `verify installation` toggle selected.
<img width="583" alt="Screen Shot 2023-05-05 at 9 30 10 AM" src="https://user-images.githubusercontent.com/8533851/236514910-e6b9e692-8540-407c-af13-3da610ce8bca.png">

If they did, this is what happens when you don't verify the installation:
<img width="304" alt="Screen Shot 2023-05-05 at 9 29 28 AM" src="https://user-images.githubusercontent.com/8533851/236514758-9178f1b9-9527-4ef8-bb27-e52f2fa2923b.png">

**Comment by cdelst** [comment]
Hey @scefali, 

I am the dev who is responsible for this ticket... I just checked again, and it is in fact set 
![image](https://user-images.githubusercontent.com/44860108/236522269-4c88f4ab-a7dd-4754-9c14-d66dd18ad506.png)

I see the pending status on the integration now, but missed that previously.  The confusion I think was surrounding the fact that the 'uninstall' button pops up, insinuating that the integration is in fact installed.

It makes more sense to me now though, thanks!
