### ISSUE TITLE
No issues are getting auto-assigned from codeowners file

### ISSUE THREAD

**Issue by jangjodi** [getsentry/sentry#48734]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Add codeowners file
2. Create an issue whose path matches a rule in the codeowners file

### Expected Result

The issue should be assigned based on the rule in the codeowners file

### Actual Result

The issue is not assigned to anyone

### Product Area

Issues

**Comment by sanjaynichani** [comment]
Similar issue identified (& resolved on its own) 

**user uncovered an issue where Sentry auto-assigns based on CODEOWNERS under a specific scenario - the last rule that uses a ** in the rule seems to match for any new issue, even when the rule in full doesn't match the issue stack trace**

ie.  they see this: Assigned via Codeowners Rule: _codeowners:**/workers/user_deletion_worker*.rb #internal-tools_

On an event from their frontend project (served by the same CODEOWNERS file) via their JS SDK (ie. no ruby files in the stack trace)

Another piece of supporting evidence around the issue: every issue has Suggested Assigness for any team that has an ownership rule that contains a ** in it. So it seems like any rule with a ** in it is incorrectly matching every issue / any stack trace. 

After digging, they got a bit more information from the engineers on their side - the data suggests this issue likely started occurring in mid-February. They found an event that has been happening somewhat consistently for > 90 days. When it was first seen it wasn't auto-assigned because there were no matching ownership rules.  Then in mid-February (Feb 13th) when it fired, since it was still unassigned, it was still eligible to go through auto-assignment. Sentry matched CODEOWNERS rule (**/...*.rb style)  and assigned it based on that rule.

**As of April-end, this issue seems to have resolved itself.**

**Comment by jangjodi** [comment]
Discovered this was a discrepancy between the user's path in the codeowners file vs the issue
