### ISSUE TITLE
Instant slack alerts for errors

### ISSUE THREAD

**Issue by jshearer** [getsentry/sentry#4883]
Hi guys! Would it be possible to get a "1 minute" option for alert notifications? (or even 1 second?) Since our user base is still relatively small, one of the things we really want to be able to do is get near-instantaneous alerts every single time an error occurs on our platform. This is so that we can make contact with the user before they send us an email, letting them know that we're working on a solution. 

The 5 minute minimum for alerts feels too laggy compared to our previous solution of sending slack messages directly from the code when an exception happened. Obviously we would love to use Sentry as it provides amazing features that we love, instant alerts are a pretty important feature that's missing.

Thank you for your time!

**Comment by jshearer** [comment]
By the way, I would be happy to make a PR for this if it would be considered.

**Comment by JTCunning** [comment]
Hey @jshearer,

I'm closing this ticket because there is no underlying bug with the sentry server.

If you have any followups to my explanation below, please repost this on the [community forum](https://forum.sentry.io) and @ me, or find me on freenode/#sentry.

I think you may have gotten your wires crossed with the "Digests" section of your project configuration. Currently, digested alert settings only apply to mail. In this case, you're referring to the [sentry-slack plugin](https://github.com/getsentry/sentry-plugins/tree/master/src/sentry_plugins/slack) which only ever gets delayed if you receive more than [10 notifications per minute](https://github.com/getsentry/sentry/blob/master/src/sentry/plugins/base/notifier.py#L33-L37).

The average end-to-end latency for an event to be ingested and trigger a notification with sentry.io is about three seconds. So if you're using on-premise, I suggest taking a look at [your queue](https://github.com/getsentry/sentry/blob/master/docs/monitoring.rst#queue-monitoring) to assess the latency in which it takes to fire off the notification.
