### ISSUE TITLE
200 request investigation

### ISSUE THREAD

**Issue by scttcper** [getsentry/sentry#49142]
Requests with status code 200 are being reported and that's weird. Figure out why its happening and fix/ignore them.

**Comment by lobsterkatie** [comment]
Related PRs (Not linking them because it'll auto-close the issue):

https://github.com/getsentry/sentry/pull/49060
https://github.com/getsentry/sentry/pull/49253
https://github.com/getsentry/sentry/pull/49403
https://github.com/getsentry/sentry/pull/49469

This is really just debug logging. Haven't yet dug into why this is happening.
