### ISSUE TITLE
Design: Update design of the "no replay found" banner on Issue Details

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#49407]
We've got this banner, listing out some reasons why a replay is not appearing on an issue:

![Image](https://user-images.githubusercontent.com/187460/239273054-3436f118-fa04-4170-97e2-1502688cc683.png)

We should update the design of the banner. it's also an upsell opportunity.

See also: https://github.com/getsentry/sentry-docs/issues/6985

**Comment by Jesse-Box** [comment]
@ryan953 I don't see a problem statement here. The banner explains the current situation the user is faced, or is this not the case?

**Comment by ryan953** [comment]
The problem statement is that a) the design sucks, it takes up a bunch of space :( 

also, people do have problems and ask questions, so it could be clearer maybe?

Example question:
>  when does this message pop up on the issue details page? is it only when we expect there to be a replay but for some reason can't find it?
if a user sees this, there's nothing they can do to fix it right? it's more of an FYI , this is why you aren't seeing a replay

**Comment by Jesse-Box** [comment]
@jas-kas @ryan953 

I'm going to close this ticket as I believe I've found a solution that handles the most common case better (Point 1 below).

See [Figma Designs](https://www.figma.com/file/VYQS8oJ7wMh3wrfaa11DpL/Specs%3A-Replays-in-Issues-v4?type=design&node-id=602%3A3307&mode=design&t=eDd2xJwSk6kmFwe1-1)

I think to solve this problem fully, the backend should return reasons as why the replay cannot be found. 

As it is right now, we can't tell if
1. The replay wasn’t accepted because your replay quota was exceeded at the time
2. The replay was rate-limited and couldn't be accepted
3. The replay was deleted by a member of your org
4. There were network errors and the replay wasn't saved
