### ISSUE TITLE
Releases with incorrect date info

### ISSUE THREAD

**Issue by Phredward** [getsentry/sentry#4964]
After creating a new release (to upload artifacts), the first event is listed as 12 days ago, even though the release was newly created.

I note that we have other projects in the same sentry team with an identically named release.

The release was created with sentry-cli 0.19.5

**Comment by macqueen** [comment]
@Phredward that fix will go out on sentry.io shortly. however, it's also worth noting that releases can now apply to multiple projects within an organization (we updated our docs here: https://docs.sentry.io/api/releases/post-project-releases/) so if you want the releases in different projects to be treated as separate entities, you should make the version name unique across the organization.

**Comment by jazoom** [comment]
Why would you do this? It is not the expected behaviour. Also, those docs don't even mention this. Considering how surprising this is you should probably have a large warming up the top of the page.

Who would expect that uploading release 1.0.0 for project B would overwrite artifacts for version 1.0.0 of project A uploaded 6 months ago?

**Comment by mattrobenolt** [comment]
@macqueen I thought we removed this endpoint or at least planned to?

@jazoom This endpoint specifically was only left around for compatibility. We don't recommend using it anymore since as you mention, it's slightly confusing in this context. From what I can tell, we don't even document this anymore and no docs should reference this.

For context, a lot of work on our end went into making Releases scoped to org instead of project to facilitate a single release that spans multiple projects. This is why you're finding the potentially awkward behavior with `1.0.0` conflicting across multiple projects. Our recommendation here is that if you have distinct projects with different releases that don't related, you'd supply a prefix or suffix to differentiate.

**Comment by jazoom** [comment]
@mattroenolt I copied those POST requests from your documentation earlier this year.

I'm happy to update to the new format rather than mucking around adding prefixes. It's not clear from the docs linked but if I pass along the `projects` form field will the release be scoped to only the project mentioned?

**Comment by mattrobenolt** [comment]
No, release names are always scoped per org. The `projects` just creates a mapping on our side to say which projects were involved in that release. It doesn't prevent name collisions or anything like that.

**Comment by macqueen** [comment]
@mattrobenolt i don't think we ever talked about removing the endpoint because we wanted to leave for compatibility

@jazoom the docs for project version of this endpoint did [have a note about this](https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/project_releases.py#L81) for a while before we unlisted them

**Comment by jazoom** [comment]
Okay. I guess I'll just prefix the releases in the configs for Raven as well as the POST calls to create releases and upload artifacts. Thanks for the information.

**Comment by jazoom** [comment]
@mattrobenolt which one of the last 2 options on this page should I be using? Is the project one out of date?

https://docs.sentry.io/api/releases/
