### ISSUE TITLE
Legacy Browser Filter for older versions of Chrome or Firefox

### ISSUE THREAD

**Issue by ehfeng** [getsentry/sentry#4980]
For apps that use the latest JavaScript features (like MutationObserver), filtering out legacy versions of Chrome or Firefox would be valuable for cutting down noise.

**Comment by alistairhigson** [comment]
Having an option to filter out legacy FireFox and Chrome versions would definitely help cut down on noise for certain application types.

**Comment by ehfeng** [comment]
@alistairhigson I was reviewing this issue today. The inbound filters feature is built for filtering browsers that don't throw legible errors and our error-grouping mechanisms don't work well.

However, in cases like MutationObserver being not present in certain browsers, it isn't an error—the browser simply doesn't have that API and the application is breaking for your users and you should throw a modal asking your users to update.

I'm closing this for now, but if I'm misunderstanding, please feel free to comment and re-open.

**Comment by pgrm** [comment]
@ehfeng it seems to me, that it's starting to become common practice for B2B JS applications to only really support the last X versions of evergreen browsers. We do try display an error message for the users if their browser is outdated, but we don't care too much if it's so old, that they can't even load the application. And even if they see the error message, they often times choose to ignore it.

So errors from older versions of Chrome or Firefox are simply ignored, if reported by sentry and it would be nice if we had a choice to not even have them show up in sentry.

**Comment by SandeepJoelFreshdesk** [comment]
Couldn't agree more with @pgrm, and bumping this up again. @mattrobenolt @dcramer  I understand that there is a function in sentry config(`beforeSend`) using which we can hardcode the list of browser versions we want to ignore. But since the browsers keeps updating their versions, we need to repeatedly update the sentry configuration in our repos. So is there any update on providing the options similar to the ones we specify in `.browserlistrc`, like `last 2 chrome versions` etc.. so that we can focus on errors from browser versions that we want to support.
