### ISSUE TITLE
ClickUp integration doesn't work

### ISSUE THREAD

**Issue by aurelsziebert** [getsentry/sentry#50032]
### Problem Statement

"Unable to create ClickUp issue." error message pops up when I am trying to create a ClickUp task from the Sentry Issue screen.
Similarly I got "Unable to link ClickUp issue." error message when I am trying to link to existing task.

<img width="1440" alt="Screenshot 2023-05-26 at 10 23 32" src="https://github.com/getsentry/sentry/assets/7761856/8460784d-1c95-4f26-b0d1-e5e97b5eeb07">

<img width="1440" alt="Screenshot 2023-05-26 at 10 23 21" src="https://github.com/getsentry/sentry/assets/7761856/43f4029c-1927-4e87-94f5-f5dfcf05601c">

### Product Area

Settings - Integrations

**Comment by scefali** [comment]
@Fwang36 Your ClickUp integration seems to have valid credentials. But it looks like sometimes ClickUp is returning a 500 to Sentry's server
<img width="976" alt="Screen Shot 2023-05-31 at 9 06 51 AM" src="https://github.com/getsentry/sentry/assets/8533851/c3d46890-23bd-4f9b-80a1-6148e48efe40">

Since ClickUp is returning a 500 server error, you'll need to contact them for additional support.
