### ISSUE TITLE
Replay: Playback jumps to the end of the replay

### ISSUE THREAD

**Issue by stellaatsentry** [getsentry/sentry#50281]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Open a replay that was created due to an error.

### Expected Result

The playback shows the replay from start to finish.

### Actual Result

The playback jumps to the end of the replay, even when the user manually tries to play it from the start.

https://github.com/getsentry/sentry/assets/81985895/a13bb8b5-982b-4142-93f7-68cd63b041ec

I was unable to reproduce this on my test account so I'm linking the customer's replay in the internal ticket.

### Product Area

Replays

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1848) by [Unito](https://www.unito.io)

**Comment by bruno-garcia** [comment]
@stellaatsentry could you please share the link to the exact replay that cause this? Ideally the issue or search that led you to the replay.

I imagine the replay was loaded with a timestamp right at the end of the replay, but I'd like to confirm that.

**Comment by stellaatsentry** [comment]
@bruno-garcia I linked it inside the [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1848).

**Comment by hubertdeng123** [comment]
Looks like this should be waiting on a response, will mark it as `Waiting for: Product Owner`

**Comment by bruno-garcia** [comment]
The replay loads at the end because there was an error at second 21, and the link was generated pointing to that point in time (query string `&t=21`.

The behavior you shared on the video indeed looks buggy, but I can't reproduce that anymore. I believe this came up a while ago and got addressed. 

https://github.com/getsentry/sentry/assets/1633368/6b9fbf18-ad2a-4930-b132-8caf2d344da4

Please feel free to reopen in case this comes up again
