### ISSUE TITLE
Filter and aggregate data only if constant

### ISSUE THREAD

**Issue by matany-orca** [getsentry/sentry#50399]
### Problem Statement

In dashboards - Id like to be able to separate between sudden/temporary glitches and constant on going issues. 
Id like to be able to set up a rule in a table to present only issues that are raised over and over again - so i can prioritize them accordingly.

### Solution Brainstorm

I guess that it is pretty straight forward, considering the problem statement

### Product Area

Dashboards

**Comment by matany-orca** [comment]
hi @brentc ! tnx for the reply. the solution suggested doesnt answer my need - as it is based on issue count but not on its "continuousness". for example - id like to aggregate  only issues that happened during last 7 days, AT LEAST 4 DAYS IN A ROW. thats how i can filter "real" ongiong issue from a short surge of errors that could just be a short glitch and doesnt need my attention. hope i made sense

**Comment by brentc** [comment]
@matany-orca I see what you're saying. you want a way to see issues that have been consistently occurring over the last _n_ days, filtering out the issues that spiked briefly and aren't consistent.

You're right that there's no way to do this with Dashboards today (at least not that I can figure out). This feels like something that should be addressed directly in the Issues feature directly though rather than solving it via an obscure field for use within Dashboards.

I'm going to re-assign this to the issues team to explore further.

**Comment by matany-orca** [comment]
great. tnx!

**Comment by rachrwang** [comment]
Updating product area as something we should track as part of the ongoing issues<>dashboards investments

**Comment by alexjillard** [comment]
@matany-orca the issues team recently added the concept of "[Escalating Issues](https://docs.sentry.io/product/issues/states-triage/escalating-issues/)." Are you able to filter your dashboard query with `issue.status is: escalating` and does this give you the type of information you're looking for? There are[ other issue statuses](https://docs.sentry.io/product/issues/states-triage/) that might help build the type of query you're looking for.

<img width="999" alt="Image" src="https://github.com/user-attachments/assets/c1e84737-44e0-4717-b63b-b7088a444ba0" />

Feel free to reopen if you have any further questions 😄
