### ISSUE TITLE
Support more breadcrumbs or setting important breadcrumbs

### ISSUE THREAD

**Issue by ChrisBellew** [getsentry/sentry#5045]
I love the breadcrumbs feature, but often I find that the root cause of an issue is lost because there have been more than 100 breadcrumbs since the issue occurred. For example, our application's security token expired in the browser and there were more than 100 failed (401) requests to our backend services. I want to know why the token expired.

It would be great if there were some way of recording more breadcrumbs - I would personally like a limit of 1000 for our dev environment. Failing that, some way of telling sentry that a particular breadcrumb or error is of high importance, so that I could decorate the most important parts of code and I could be confident that any errors arising from these parts of code would be preserved in the Sentry logs.

Thanks
Chris

**Comment by untitaker** [comment]
@ChrisBellew the breadcrumb limit is imposed by the sdk, and a lot of sdks allow you to increase that limit (`max_breadcrumbs`).

If you think some data is particularly important, why not put it into the `extra` ("Additional Data") field instead of relying on the breadcrumbs buffer? https://docs.sentry.io/enriching-error-data/context/?platform=javascript

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
