### ISSUE TITLE
Short ID references are not preserved across group merges.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#5080]
These surrogate identifiers for groups should be stored in [`GroupRedirect`](https://github.com/getsentry/sentry/blob/master/src/sentry/models/groupredirect.py) along with the primary keys.

This probably only needs to be added to the existing write path for `GroupRedirect` here: https://github.com/getsentry/sentry/blob/a04438d7b555026f96e0e8a3df456f9b6d503f0e/src/sentry/tasks/merge.py#L104-L108

**Comment by G-Rath** [comment]
We have a situation where we've referenced a short-id in a commit, that Sentry has correctly picked up, but the short-id then later changed because of a merge. Now when searching the short-id mentioned in the commit, Sentry says the issue doesn't exist.

Is that what this issue proposes to fix? If so I'd love to see it merged, as it's a bit of a show-stopper for our issue management.

**Comment by dcramer** [comment]
@G-Rath yeah thats one of the things that breaks right now. We want to fix it for a number of areas, but thats probably the most visible.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
