### ISSUE TITLE
Okta sso: error creating user

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#50917]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a sentry organisation
2. Invite members to join the organisation
3. Setup SSO with Okta in the organisation
4. Try to add a group that has users already existing in Sentry.

### Expected Result

Group is assigned to the Sentry app in Okta for provisioning and SAML access with no issues.

### Actual Result

An error is displayed: 
<img width="997" alt="Screenshot 2023-06-14 at 09 48 20" src="https://github.com/getsentry/sentry/assets/64906376/3d4e1079-77e4-4e98-aac7-9dc33acad2b7">

### Product Area

Sign In

**Comment by AniketDas-Tekky** [comment]
@rodolfoBee This is actually expected. When a user already exists in the service, SCIM expects POST User to return a 409 Conflict. We actually have a bug right now where this doesn't always happen, so I can't check what the best next steps should be until that's fixed.

**Comment by MichalMMac** [comment]
Hey. I think we have been experiencing same or similar problem.
Our Sentry instance is integrated with Okta. We use SCIM provisioning for both users and groups.

When I assign Sentry Okta app to Okta user which already exists in Sentry following things happen:

- A. If Okta user provisioning to Sentry has both create and update functionality enabled -> We get following error message: "Conflict. Errors reported by remote server: User already exists in the database."
- B. If Okta user provisioning to Sentry has only the update functionality enabled -> We get following error message: "Matching user not found"

While `409` is expected from SCIM API when IdP sends POST message to create a resource which already exists downstream I believe the correct procedure is that IdP searches for the resource (user) first (by username) before sending POST. If the corresponding user is found in Sentry Okta is supposed not to sent POST and it stores Sentry used ID as externalID in Sentry Okta app user assignment profile so every following request can be made using this ID.

I think that for some reason unknown Sentry SCIM API is unable to retrieve the existing record Okta is searching for. However to confirm this we would need your help to troubleshoot since you can see the incoming raw SCIM request while we can not see the outgoing ones on our side.

**Comment by AniketDas-Tekky** [comment]
@MichalMMac Actually, Okta does not look for existing users before attempting to provision.

https://support.okta.com/help/s/article/RingCentral-Lifecycle-management?language=en_US

They don't support linking existing users and recommend removing the conflicting user from the application before provisioning through SCIM.

**Comment by MichalMMac** [comment]
@AniketDas-Tekky 
Actually, **Zoom** does not support linking of existing users.

Here is a quote from the support article you have just linked:
> Zoom does not support linking of existing accounts through provisioning and only supports pushing new users and/or updates.

We regularly link Okta users with existing users in apps during assignment. Could we troubleshoot together so we see what API calls does your SCIM endpoint receives when we assign Okta app to a user which already exists in Sentry?

**Comment by AniketDas-Tekky** [comment]
@MichalMMac The issue should be resolved now with this PR: https://github.com/getsentry/sentry/pull/53100
I verified it locally. Let me know if it works for you.

**Comment by MichalMMac** [comment]
@AniketDas-Tekky Thank you so much for fixing this! :-)
