### ISSUE TITLE
Use `bulk_reverse_resolve` in metrics layer

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#51227]
The reverse resolution of indexed ints to string happening in the metrics layer is causing a N+1 query problem, shown here: https://sentry.sentry.io/issues/4168846829/?project=1&query=is%3Aarchived&referrer=issue-stream&statsPeriod=14d&stream_index=7.

We would like to fix this problem by batching up the indexer requests with `batch_reverse_resolve`.

The code which exhibits the N+1 behavior is available here: https://github.com/getsentry/sentry/blob/1d7f72ae778807e17a92f9d06e2b080f750c4b07/src/sentry/snuba/metrics/query_builder.py#L1207-L1223

**Comment by obostjancic** [comment]
In order to solve this we first need to implement `batch_reverse_resolve` method in the indexer. Outline of how that would look like was done in https://github.com/getsentry/sentry/pull/51266

**Comment by RaduW** [comment]
Since this ticket involves both changes to the Indexer implementations and to the metrics layer I will split it in two.
1. Add `bulk_reverse_reslove` to all indexer ( to be reviewed and approved by SnS and us)
2. Use `bulk_reverse_resolve` in metrics indexer... (this ticket)  to be resolved internally by Telemetry experience.
