### ISSUE TITLE
Error 404 when I want to create an issue on Gitlab

### ISSUE THREAD

**Issue by bertrandjamin** [getsentry/sentry#5135]
Hi, I 'm using sentry.com with gitlab.com integration.

I have a 404 error when I try to create an issue...

<img width="618" alt="capture d ecran 2017-03-23 a 11 58 37" src="https://cloud.githubusercontent.com/assets/4040743/24244742/707bda12-0fc0-11e7-8aee-e1222e93d503.png">

**Comment by mikaelz** [comment]
Same for me with GitLab Community Edition 8.15.2 790035f
![screen shot 2017-05-07 at 10 11 52](https://cloud.githubusercontent.com/assets/454800/25778987/e3c607d4-330d-11e7-943c-08f4be3d2c18.png)
![screen shot 2017-05-07 at 10 12 20](https://cloud.githubusercontent.com/assets/454800/25778986/e3c5602c-330d-11e7-967a-094a50d32043.png)

**Comment by moosicalbovine** [comment]
Hi,

I get the same issue. This seems to be common issue. Is there something being done to fix it?

**Comment by moosicalbovine** [comment]
I just resolved this issue. This is happening for me, because of a trailing slash at the end of the "Repository name"

**Comment by MadLittleMods** [comment]
This ended up being a problem with the old GitLab Sentry plugin using GitLab API v3 which was removed via https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/18970 which was deployed in [GitLab 11.0 RC5](https://gitlab.com/gitlab-org/release/tasks/issues/247) on [2018-6-7](https://gitlab.slack.com/archives/C8PKBH3M5/p1528359031000529).

The fix was to upgrade to Sentry 9.0.0 which uses GitLab API v4, https://github.com/getsentry/sentry-plugins/blob/d68c48682f69aee2779330f0057b5dbe1b5e0387/src/sentry_plugins/gitlab/client.py#L22

**Comment by markstory** [comment]
Closing as upgrading sentry is the way to solve this problem.
