### ISSUE TITLE
Send "Quota depleted" emails also at 50%

### ISSUE THREAD

**Issue by edzis** [getsentry/sentry#51592]
### Problem Statement

Currently you are sending emails at 80% of quota usage. In the last couple of times this has been too late for me to tame the cause of the unexpected increase in Transaction usage. For the remaining part of the month I am left without that data.

For Errors at least I can sate rate limits, but those are not available for Transactions. Making changes to transaction sample rate is not desired nor even feasible at larger organizations and certain products.

### Solution Brainstorm

Can you please send the same type of message also at 50% to give me time to react?

Or add more controls for me to tame transaction rate limits, the same way as you do for Errors.

### Product Area

Settings - Spike Protection

**Comment by yuval-sentry** [comment]
cc @yuval-sentry

**Comment by Dhrumil-Sentry** [comment]
Hi @edzis Thanks a lot for the feedback- This is a very reasonable ask and I'll add it to our backlog. I will keep the issue updated

**Comment by jmesquita** [comment]
@Dhrumil-Sentry Although I think the feature that was requested here is useful, I don't think it solves the problem statement in its entirety. We have experienced for the second consecutive month a situation that led us to mismanage our quota because the rate in which we consumed events increased dramatically over the weekend where emails are not really observed. Spike protection did not help us here and we needed manual filtering to be put in place to get over the problem instead. Getting earlier feedback over email for our case would've not been sufficient for us to be protected and we currently have no means of alerting on call rotation for situations that would cause us to run over quota and starve competing projects.

I would love if we could instead provide means to establish monitoring of the quota overall and that customers would be able to establish their own alerting mechanisms for those. Ideally, in our case, we use multi-window multi-burn rate alerting for things like that using Prometheus but we currently have no way of exporting these overall metrics from Sentry into a TSDB.

We effectively have no means of managing quota efficiently today and remove the risk of keeping it within bounds.

**Comment by brianthi** [comment]
We have added configurable thresholds for spend notifications in 10% increments from 10 to 100. This is available for reserved volumes and pay-as-you-go, and can be found on the subscriptions page under the notifications tab. Dhrumil has also provided a means to get usage data per category by day. Closing this issue.
