### ISSUE TITLE
Support measuring Total Blocking Time (TBT)

### ISSUE THREAD

**Issue by cseas** [getsentry/sentry#51861]
### Problem Statement

Lighthouse measures [5 web vitals][1] in its latest scoring metrics. The highest percentage (30%) of this score is assigned to Total Blocking Time (TBT).

We want to setup monitoring and alerting for TBT slowdowns for our users but Sentry's list of web vitals seems to be outdated and doesn't have TBT. We need to consider other alternatives as a result.

[1]: https://developer.chrome.com/docs/lighthouse/performance/performance-scoring/#lighthouse-10

### Product Area

Performance

**Comment by mjq-sentry** [comment]
Hi @cseas! Thanks for your feedback. We haven't prioritized TBT because [it's considered a lab metric](https://web.dev/tbt/#lab-tools), and isn't recommended to be measured in the field. Of the two interactivity metrics meant to be measured in the field, we support [FID](https://web.dev/fid/) already. As for [INP](https://web.dev/inp/), there has been [some movement](https://github.com/getsentry/sentry/pulls?q=is%3Apr+is%3Aclosed+INP) but it doesn't mesh well with our transaction-based performance tracing model and so is blocked on some other work.

For now, for what it's worth we do record long tasks in our performance tracing and support recording [custom performance metrics](https://docs.sentry.io/product/performance/metrics/#custom-performance-metrics) if you wanted to record this metric yourself. Sorry I don't have an easier answer!

**Comment by cseas** [comment]
That makes sense, thanks!
