### ISSUE TITLE
Indicate in the UI when an array or dictionary variable value has been truncated

### ISSUE THREAD

**Issue by WouterHouwen** [getsentry/sentry#51998]
This is a duplicate of https://github.com/getsentry/sentry/issues/26977 which I can't re-open because I'm not a collaborator.

# Summary
The sentry python SDK truncates the values of some variables included in the error metadata JSON blob before sending it to the sentry server. When it does so it includes the full length of the array in the JSON. See https://github.com/getsentry/sentry-python/blob/b065890492/sentry_sdk/serializer.py#L327

Presumably the SDKs for other languages do the same.

But the UI just shows the truncated array, with no indication that it has been truncated or what the original size was.

# Motivation
- Engineers debugging issues based on the sentry report sometimes waste time attempting to reproduce errors with the wrong data.
- Engineers get confused by knowing that there are more values in the array/dictionary variable but aren't visible in the Sentry report

# Example
The image below shows the current visualization of when the variables have the following values:
```
dict_value {0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: '10', 11: '11', }
list_value [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ]
```

![image](https://github.com/getsentry/sentry/assets/42268945/6b5355a3-b28b-4bca-8c8d-3290869f9af4)

**Comment by antonpirker** [comment]
Yes, the truncation cases confusion for our users. 
We had discussions about removing the trimming altogether already a couple of times, but never reached an conclusion. Yesterday we again talked about it and made this issue, so we are finally will improve this at some point: https://github.com/getsentry/sentry-python/issues/2223

Another information: I guess only Python does this trimming logic. Other SDKs send all the data and let the ingest side decide (and as I understand, if relay thinks the event is too big, it is dropped. But I am not sure if the user sees what events have been dropped because of size. Stuff we need to figure out to make a nice experience for the users)

**Comment by malwilley** [comment]
Thanks for jumping in and making that issue @antonpirker!

Going to go ahead and close this issue since it will be tracked by https://github.com/getsentry/sentry-python/issues/2223
