### ISSUE TITLE
IntegrityError duplicate key value violates unique constraint "sentry_filtervalue_project_id_201b156195347397_uniq"

### ISSUE THREAD

**Issue by MikeVL** [getsentry/sentry#5232]
Sentry v8.15
```
IntegrityError: IntegrityError('duplicate key value violates unique constraint "sentry_filtervalue_project_id_201b156195347397_uniq"\nDETAIL:  Key (project_id, key, value)=(3, device, Other) already exists.\n',)
SQL: UPDATE "sentry_filtervalue" SET "times_seen" = "sentry_filtervalue"."times_seen" + %s, "data" = NULL, "last_seen" = %s WHERE ("sentry_filtervalue"."project_id" = %s  AND "sentry_filtervalue"."key" = %s  AND "sentry_filtervalue"."value" = %s )
  File "celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "sentry/tasks/process_buffer.py", line 45, in process_incr
    buffer.process(**kwargs)
  File "sentry/utils/functional.py", line 92, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "sentry/buffer/redis.py", line 149, in process
    super(RedisBuffer, self).process(model, incr_values, filters, extra_values)
  File "sentry/buffer/base.py", line 71, in process
    **filters
  File "sentry/db/models/manager.py", line 281, in create_or_update
    return create_or_update(self.model, **kwargs)
  File "sentry/db/models/query.py", line 75, in create_or_update
    affected = objects.filter(**kwargs).update(**values)
  File "django/db/models/query.py", line 493, in update
    rows = query.get_compiler(self.db).execute_sql(None)
  File "django/db/models/sql/compiler.py", line 980, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "raven/contrib/django/client.py", line 112, in execute
    return real_execute(self, sql, params)
  File "django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "sentry/db/postgres/decorators.py", line 75, in inner
    raise_the_exception(self.db, e)
  File "sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "sentry/db/postgres/base.py", line 39, in execute
    return self.cursor.execute(sql, params)
```

**Comment by mattrobenolt** [comment]
I think you're missing something here. This query cannot trigger that error. I think your first line is a part of the previous error, and the rest of the stack trace is a part of an error that you're leaving off.

**Comment by MikeVL** [comment]
![2017-04-12 22 11 25](https://cloud.githubusercontent.com/assets/118285/24975053/012a8a4c-1fcd-11e7-9d71-cb45b756dea2.jpg)

**Comment by mattrobenolt** [comment]
Weird. My only guess here is that it's another query within the same transaction, and then committing the transaction or something causes the issue. I'm not sure how you got into this state, and we don't hit this ourselves. The only thing I can reasonably recommend doing is deleting the existing row from the database.

Does this continue to happen, or did this just happen one time?

**Comment by MikeVL** [comment]
I have about 1000 such errors per day

**Comment by mattrobenolt** [comment]
Is it all complaining about the same row? Or are they all different?

Again, the only reasonably thing I think there is is to delete the one offending row, if that's it. Otherwise, there's some other systematic issue that I don't see and we don't experience.

**Comment by MikeVL** [comment]
I recent 10 rows:
```
Key (project_id, key, value)=(3, logger, django.request) already exists
Key (project_id, key, value)=(3, device, Other) already exists.
Key (project_id, key, value)=(3, browser, Mobile Safari 10.0) already exists.
Key (project_id, key, value)=(3, device, iPhone) already exists.
Key (project_id, key, value)=(11, device, iPhone) already exists.
Key (project_id, key, value)=(11, os.name, Windows 7) already exists.
Key (project_id, key, value)=(3, url, http://www.vluki.ru/help.txt) already exists.
Key (project_id, key, value)=(3, url, http://www.vluki.ru/spravka/page2.html) already exists.
Key (project_id, key, value)=(11, os.name, Windows 8.1) already exists.
Key (project_id, key, value)=(3, sentry:user, ip:141.8.142.16) already exists.
```

**Comment by mattrobenolt** [comment]
I honestly don't know how you'd be getting this. So the only thing I can do is point you to what I think may be happening.

So this behavior, based on the stacktrace shown is coming from incrementing after processing buffers, which starts here: https://github.com/getsentry/sentry/blob/master/src/sentry/buffer/base.py#L64-L72

So this is just generating the the fields to update, then we either create a new row, or update an existing one.

We then go into this `create_or_update`:

https://github.com/getsentry/sentry/blob/master/src/sentry/db/models/query.py#L54-L97

But where things get odd is that it's blowing up from line 75 in that file, which is at the `.update(**values)` piece, which lines up exactly with the SQL being shown.

But... this SQL alone would not generate that exception. If anything, this would come from down below, at L93 when we try to `INSERT` the new row.

There's absolutely no logical explanation of how that `UPDATE` query can trigger this `IntegrityError`. If anything, it'd just update the count on a row, or find no rows, and continue along to add it later.

So I'm not sure what else I can do here to help debug since this doesn't make sense how you'd be getting that error, especially based on the stacktrace.

I'll leave this issue open incase you figure something out so you can respond, but there's not much more I can do here to help you out, unfortunately.

**Comment by Phlamethrower** [comment]
I ran into this same problem today after upgrading to 8.15.0 (from an older Sentry version from mid last year; not sure of the version number). It looks like the problem was that some of the database indices became corrupt; the index was saying that there was only one entry in the table for a given (project_id, key, value) tuple but there were actually multiple entries. It took a fair amount of googling to discover that this was the problem; luckily, fixing it was much easier:

* Temporarily stop sentry to avoid any further damage being caused
* Connect to the database via psql and fix the indices: (if you're using docker, [see here](https://hub.docker.com/_/postgres/) for an example of connecting to dockerised postgres)
```
REINDEX SYSTEM sentry;
REINDEX DATABASE sentry;
VACUUM (FULL, ANALYZE);
```
* Restart sentry

Chances are the `REINDEX DATABASE sentry` will complain about duplicate unique values, these can be fixed by deleting any duplicate rows as described on the postgres wiki: https://wiki.postgresql.org/wiki/Deleting_duplicates

e.g. I had to use `DELETE FROM sentry_filtervalue WHERE id IN (SELECT id FROM (SELECT id, ROW_NUMBER() OVER (partition BY project_id, key, value ORDER BY id) AS rnum FROM sentry_filtervalue) t WHERE t.rnum > 1);`

Of course you may need to be careful about what values you're deleting this way. In my case it was just the sentry_filtervalue table which was broken, so having inaccurate data for the past few hours shouldn't be a major problem.

For my case, I'm not really sure how the database ended up corrupt. As part of the upgrade I did move the DB to another docker volume, but that was after stopping postgres.

**Comment by castlec** [comment]
@mattrobenolt, @MikeVL  are you able to confirm possibility of the description of the issue? If it is believed to be the core of the problem, how best to go about replicating and enhancing upgrade scripts to be more robust?

**Comment by mattrobenolt** [comment]
So, don't ask me how I know this.

But I think the problem around here is getting corrupt indexes due to either a Postgres upgrade, or some generic Postgres change.

If the version of musl or glibc changes under Postgres, indexes that utilize text data have a high possibility of being corrupt and need rebuilt.

Something like this: https://postgresql.verite.pro/blog/2018/08/27/glibc-upgrade.html
