### ISSUE TITLE
Review custom grouping rules in our FE project

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#52566]

**Comment by lobsterkatie** [comment]
High-level takeaways:

- Some were quite specific, and to error messages which seemed kinda like spam, and almost seemed like they should have been filters instead. Seems like the thinking might have been to silo all of a given kind of event into a single issue which could then be ignored.
- Many hadn't seen any events in at least 90 days. Could we have some way to track this and maybe even suggest to customers rules to get rid of?
- Would have been great to know who added each rule, and when, and why. Would be great if you either had to PR in changes to a file like `CODEOWNERS` or at least fill out some form in the UI in order to add a rule. (Some of this data may live in the audit log, but there's no good way to find it.)
- Would be nice if there were some way to keep track of how often a given rule fires (both how often it matches and how often it actually changes the outcome).
