### ISSUE TITLE
Issue alerts not alerting on regressions

### ISSUE THREAD

**Issue by scttcper** [getsentry/sentry#52849]
Issue alerts with "The issue changes state from resolved to unresolved" are not getting triggered when an issue is unresolved and has reappeared (resolved from not being seen).

**Comment by leighst-anchorage** [comment]
2 weeks is a pretty serious delay for something like this. We are currently depending on this for alerting to work  properly.

**Comment by Simonot** [comment]
Hi
Do we have any update on when this issue will be sorted out ?
We are also heavily depending on alert rules for our alerting system.

**Comment by snigdhas** [comment]
Hey folks, I'm actively looking into this and hope to have an update soon. The issue isn't present in most organizations, so we're hoping to narrow down what exactly is going on here.

**Comment by leighst-anchorage** [comment]
Any updates?

**Comment by liferthedude** [comment]
Our organization is also affected

**Comment by snigdhas** [comment]
Hi folks - thanks for adding to the issue. It's immensely helpful to find other affected organizations - @liferthedude @simonot and others, can I ask what your org slug is? Or please file a support ticket with additional info! 🙏

**Comment by liferthedude** [comment]
support ticket #100699 was placed earlier today

**Comment by masinette** [comment]
Also Support ticket #100820

**Comment by kerenkhatiwada** [comment]
Support ticket #101017

**Comment by kerenkhatiwada** [comment]
Support ticket #101274

**Comment by Simonot** [comment]
Support ticket
"Your request (99846) has been updated. To add additional comments, reply to this email."

**Comment by rodolfoBee** [comment]
@snigdhas @scttcper 

This issue is a simple enough issue to reproduce:
1. Create a alert rule that triggers on regressions
2. Send a test event to the project to create a new issue.
3. Go to the project settings -> general settings and set `Auto Resolve` to any value. 
4. Wait for the issue created on step2 to auto-resolve.
5. Send a new event to the same issue to trigger a regression

Expected: the alert created on step1 is triggered
Actual: the alert created on step1 is not triggered.

I just reproduced it:
Issue: https://dev-curumas.sentry.io/issues/4174538071/activity/?project=5591101&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
Alert rule: https://dev-curumas.sentry.io/alerts/rules/nextjs/14529739/details/
