### ISSUE TITLE
[impl] Update design of the "no replay found" banner on Issue Details

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#53082]
Follow up from https://github.com/getsentry/sentry/issues/49407

On the issue details page we try to show a preview of any associated replay, with a button to click through and see the whole replay.

But sometimes the replay is not available. There are some typical reasons why it's not there, but we can never know for sure. When the replay is missing we try to explain what the typical reason is so people are not confused.

It's time to build out the designs from https://www.figma.com/file/VYQS8oJ7wMh3wrfaa11DpL/Specs%3A-Replays-in-Issues-v4?type=design&node-id=602%3A3307&mode=design&t=eDd2xJwSk6kmFwe1-1

![Image](https://user-images.githubusercontent.com/187460/254340836-2617a7b3-0ed9-4d5b-8276-00f52cbd8ff6.png)

**Comment by michellewzhang** [comment]
cc @Jesse-Box @ryan953 is the goal here to remove the big list of reasons here and just have that one above showing every time?


![image](https://github.com/getsentry/sentry/assets/56095982/6d7b87ea-8d91-4893-a7d2-883188829b5e)

and does the up arrow/carrot in the new design collapse the text so that it's just a banner saying "The Replay associated with this event cannot be found."?

**Comment by ryan953** [comment]
I think we can put the specific reasons behind the chevron, the bullet list doesn't look great. Like, the bullet list has an item "Read the docs to understand why", it should be in sentence format like the mockup above imo
