### ISSUE TITLE
Setup: Cannot get past email settings page

### ISSUE THREAD

**Issue by mattheworiordan** [getsentry/sentry#5325]
When setting up Sentry for the first time (clean install), I was simply unable to get past the setup page as the Continue button was disabled no matter what I did.  I tried Chrome and Safari, I checked for script errors (there were none) and I tried lots of different values in the fields.

In the end I manually edited the HTML in the inspector (removing the button's disabled attribute) to complete the setup.

Here's the screen as it looks when loaded.  No matter values I placed in there, that button remained disabled.

![image](https://cloud.githubusercontent.com/assets/43789/25613876/ba6d8de2-2f27-11e7-86d6-0974caa251e9.png)

- The version of Sentry you're using

Sentry 8.9.0

- Whether you're using Docker or another installation method

Heroku. Using https://github.com/fastmonkeys/sentry-on-heroku

- Include a stacktrace or other logs when relevant

Not relevant I am afraid.

- Include a redacted version of your configuration when relevant

This is my heroku config:

```
DATABASE_URL:         postgres://[REDACTED]
REDIS_URL:            [REDACTED]
SECRET_KEY:           [REDACTED]
SENTRY_SMTP_FROM:     [REDACTED]
SENTRY_SMTP_HOST:     [REDACTED]
SENTRY_SMTP_PASSWORD: [REDACTED]
SENTRY_SMTP_USERNAME: [REDACTED]
SENTRY_URL_PREFIX:    https://[REDACTED].herokuapp.com
```

Note that after having been unable to get pass the setup screen, I tried to configure the SMTP settings using environment variables.  This did not work as I have no idea if these environment variables are event supported.

As an aside, given [the principles of 12 factor apps](https://12factor.net/), it would certainly make sense to allow all configuration properties or at least the ones with sensitive details, to be configued using environment variables.

**Comment by mattrobenolt** [comment]
From the screenshot, this version of Sentry you have is 7 months old. Try a newer version. 

We have nothing to do with this `sentry-for-heroku` project, so I'm not sure what it's doing. 

As for configuring with environment variables, nothing prevents you from doing this inside your `sentry.conf.py` file. It's what we do for lots of things in our Docker image. But again, the support you're currently getting for this is coming from `sentry-for-heroku` since our code doesn't support any of that out of the box.
