### ISSUE TITLE
Project name no longer visible on Slack iOS app

### ISSUE THREAD

**Issue by chschuermann** [getsentry/sentry#53327]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a new integration for Slack
2. Create a Sentry project
3. Set up a project alert for "all environments", **when:** a new issue is created, **then:** (select workspace and channel)
4. Send test notification
5. Open Slack app on iOS device and check message

### Expected Result

In the Slack integration, the Sentry project name should be displayed.

### Actual Result

Since about mid-May, the Sentry project name is no longer visible in the iOS Slack App. The problem seems to affect iOS only. In the desktop app and on Android, the project name is still visible.

<img width="1181" alt="slack_app" src="https://github.com/getsentry/sentry/assets/2847622/338eb5af-6fea-4317-9d5f-14e649383a8a">

### Product Area

Settings - Integrations

**Comment by brianthi** [comment]
Hi @chschuermann , thanks for filing this issue! We will look have someone on the team take a look to figure out what's going on here.

**Comment by isabellaenriquez** [comment]
Looked into this bug, here's what we found:
- the bug occurs because we use [Slack's legacy attachment fields](https://api.slack.com/reference/messaging/attachments#legacy_fields)
- both desktop and mobile notifications get the same information, but the footer (where project name is) is truncated automatically on smaller screens, hence why it doesn't appear on mobile
- Slack blocks (new system) offer a way to remediate this truncating issue but lack the extent of design customization we want for our notifications

**Comment by chschuermann** [comment]
Since the latest release last week, the project name is visible again in the iOS app. This ticket has therefore been resolved. Thanks!
