### ISSUE TITLE
Project creation confusing UX around custom alert

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#53791]
the custom alert placeholder text would make you think you can submit the form, but you have to fill in a value. we should either make the placeholder text an actual value, or provide a validation message when the form is attempted to be submitted. 

Context:
https://sentry.sentry.io/replays/908d64ebc1014edeb98a6469ad8b5b6c/?f_d_type=ui.slowClickDetected&query=&referrer=%2Freplays%2F%3AreplaySlug%2F&statsPeriod=14d&t_main=dom&yAxis=count%28%29&t=16
<img width="816" alt="Screenshot 2023-07-28 at 11 59 56 AM" src="https://github.com/getsentry/sentry/assets/1976777/8906434d-d8e3-49b3-b1fb-239627f6d208">

```[tasklist]
### Tasks
```

**Comment by ale-cota** [comment]
@priscilawebdev I would actually go with 10 being a default value, not just placeholder text. The default for now is the first option (on every new issue), so if someone chooses the 2nd option, they've likely actually checked what it means, instead of proceeding with the defaults. The input field is enough of a hint for people to see it's configurable, so I think it's the easiest option for a user.

I also like Josh's idea of having a "validation message", so maybe a tooltip on hover over the disabled "create project" button. By making the change above I think the only scenario that remains is that they didn't fill in the project name, so it should be fairly easy to spot, but it doesn't hurt.
