### ISSUE TITLE
[Replay Details] Update colors & icon of dead/rage clicks

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#54032]

**Comment by Jesse-Box** [comment]
@ryan953 @michellewzhang 

Here's the direction I think we should go in. Instead of trying to articulate the technology, we articulate the feelings customers will have.

This should be straightforward to design, I just need a couple of days
![IMG_1789](https://github.com/getsentry/sentry/assets/6508377/ea88dd51-369b-424c-ac14-247a3f46fd9f)

**Comment by Jesse-Box** [comment]
Left is dead click, right is rage click. Colours I'm not sure about right now
