### ISSUE TITLE
Source code was not found [native code]

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#5429]
We probably shouldn't attempt to treat this as a real URL.

![image](https://cloud.githubusercontent.com/assets/2153/26331022/a2ce04f0-3f03-11e7-938b-89571ace4d04.png)

**Comment by benvinegar** [comment]
@HazAT – are you looking into this?

**Comment by HazAT** [comment]
So this error should be fixed by now, it was an error on Android (only in release build) that we get a weird stacktrace.
So thats the fix: I've moved the `[native code]` from the url to function.
Because we decided to not just drop the frame, we still got the function call.

<img width="481" alt="screenshot 2017-07-31 09 15 49" src="https://user-images.githubusercontent.com/363802/28766760-414f9f5e-75d1-11e7-8154-52c8543bf8a7.png">

<img width="518" alt="screenshot 2017-07-31 09 16 03" src="https://user-images.githubusercontent.com/363802/28766782-5d5f4eec-75d1-11e7-9f7f-3d4b5380fa3f.png">

I will close it for now, feel free to reopen it if you have a better idea how I could've fixed it.

**Comment by benvinegar** [comment]
@HazAT I was also seeing this from errors submitted from Raven.js. I think we should just change the server to ignore the location.

**Comment by HazAT** [comment]
@benvinegar Before I work in any direction,
Should we remove these frames completely from the stacktrace?
OR
Should we mark these frames as `in_app = False`?

**Comment by HazAT** [comment]
I think we can close this, this has been fixed by @dcramer 
https://github.com/getsentry/sentry/blob/96bc1c63df5ec73fe12c136ada11561bf52f1ec9/src/sentry/interfaces/stacktrace.py#L385-L389
