### ISSUE TITLE
Adjust event tag statistics display mode

### ISSUE THREAD

**Issue by erictheswift** [getsentry/sentry#54444]
### Problem Statement

Hey! I find it useful to place error-related metrics (e.g. broken connection statistics) into error event tags.

It does allow some kind of search, however distribution display is definitely broken when number of possible values is broad.
<img width="340" alt="duration-tag" src="https://github.com/getsentry/sentry/assets/2434839/337231e0-284f-4f5a-b1b7-905da8026110">

### Solution Brainstorm

Transaction custom metrics seem to allow specifying different units and promise this will affect aggregation / display,
https://docs.sentry.io/platforms/javascript/performance/instrumentation/performance-metrics/#duration-units

however in my case transaction metrics do not fit well as there may be multiple sets of metrics (attached to error events) per single browser page transaction.

Would be nice to adjust event tags in the same way / allow attaching metrics per event.

Any other ideas how could I workaround that? Having another simultaneously running sentry on another dsn and begin/finish sentry transactions per connection?

### Product Area

Issues

**Comment by ceorourke** [comment]
Hi @erictheswift do the numbers on the tags page still present an issue? Like if you click "Other" and it opens up the page that shows all the values for that tag, are those 0 too? Would it be useful if we showed 0.05% (as an example) instead of 0 there, or is it still not useful because you send so many values for one tag key?

**Comment by udameli** [comment]
Hi @erictheswift,

Have you checked out [tag heat map](https://docs.sentry.io/product/performance/transaction-summary/#tags). I think it might be what you're looking for!

**Comment by gggritso** [comment]
@erictheswift 👋🏻 hi! I have a few questions/suggestions:

1. You mentioned that "transaction metrics do not fit well as there may be multiple sets of metrics". Can you describe your exact use-case? It would help us understand the problem
2. Tags, by definition should be a low-cardinality value. Setting high cardinality values like a duration will cause them to work incorrectly, sorry! What we usually recommend is _bucketing_ the duration. e.g., instead of sending durations like `10480`, `426004` and so on, you could send `<10,000`, `<100,000`, `<1,000,000`. This would convert the duration into a low-cardinality value, which is a better use case for tags

**Comment by gggritso** [comment]
@erictheswift gotcha! I wouldn't recommend setting up transactions per websocket connection, the product will not work very nicely if transactions stop representing individual pages.

If you're tracking stats for connections, I think [custom metrics](https://docs.sentry.io/platforms/javascript/performance/instrumentation/performance-metrics/) might be better suited to what you're doing. Otherwise, tag bucketing like I described would work.

Also, keep an eye out for Sentry's upcoming [developer metrics](https://github.com/getsentry/sentry/discussions/58584) product which might be a good fit, too.
