### ISSUE TITLE
Make Timestamp expandable when viewing All Events of an issue

### ISSUE THREAD

**Issue by rrgahan** [getsentry/sentry#54636]
### Problem Statement

I use sentry on a 13in screen. When viewing the All Events tab on an issue, there are many columns on the table. All of the columns are expandable, except for Timestamp. In order to get that column to be bigger, I have to shrink the other 11 columns. It would be great if I could just expand Timestamp on its own.

### Solution Brainstorm

I imagine this is just a bug since Timestamp is the last column on the table, and each of the other columns has a border on the right where you can resize from. 

### Product Area

Issues

**Comment by ceorourke** [comment]
This is related to https://github.com/getsentry/sentry/issues/54138

**Comment by rachrwang** [comment]
@rrgahan - thank you for filing this ticket! I'm Rachel, PM on the Issues team. Would you be open to chatting with me so we can talk more about how you use "All Events" today? It's been a while since we've touched that surface, and there's interest within the team to improve that experience. We can also spend that time talking about your Issues experience overall, and any other suggestions you have for improving the product. You can directly schedule here if you'd like: https://calendly.com/rachel-wang-sentry/30min, or you can email me at rachel.wang@sentry.io.

**Comment by dentarg** [comment]
@rachrwang Do you still need feedback?

IMHO it is pretty concrete feedback already stated in this issue. We just want to see the damn timestamp :)

**Comment by roggenkemper** [comment]
@dentarg the feedback about the timestamp is clear, but if you want to give more feedback about the issues experience in general, feel free to schedule something or email Rachel!

**Comment by MichaelSun48** [comment]
Closing this since it appears the issue has been solved – I can resize the timestamp column in All Events
