### ISSUE TITLE
Session Replay: Page level alerts for frustration signals

### ISSUE THREAD

**Issue by idosun** [getsentry/sentry#54693]
### Problem Statement

I'd like to be alerted when rage and dead clicks happen and trend (above X times) on specific pages of my front end. 

### Product Area

Replays

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1908) by [Unito](https://www.unito.io)

**Comment by lexprk** [comment]
We've been wanting this feature but our teams would not use this unless we have a way to get alerted. Alets would help DoorDash increase adoption of this feature

**Comment by bruno-garcia** [comment]
@lexprk how would you configure the alert? Matching on the raw URL + dead/rage click count?
Would you expect some default alert for new projects, if so, what would be sensible as default?

**Comment by kpujjigit** [comment]
Hi, is there an estimate on when Rage/Dead click alerts will be GA?

**Comment by michellewzhang** [comment]
Hi @kpujjigit, rage click issues & alerts are now available! Please follow the instructions in our [docs](https://docs.sentry.io/product/issues/issue-details/replay-issues/) to learn how to set up alerts for rage clicks. Be sure to note the prerequisites required to be able to receive these issues:

1. Be sending [session replay events](https://docs.sentry.io/product/session-replay/getting-started/)
2. Enable the JavaScript SDK (or framework-specific bundle), version 7.60.1 or higher

Note: While you can enable session replay with JavaScript SDK version 7.27.0, or higher, you'll need to have version 7.60.1 or higher in order to be able to see rage click issues.
