### ISSUE TITLE
Inconsistencies with releases and session data, numbers are not adding up for crash free sessions, crash free users, total users, total sessions..

### ISSUE THREAD

**Issue by yuval-sentry** [getsentry/sentry#54703]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The problem can be seen both on the Project Details page and also when building a dashboard.
1) Project Details Page: Check if number of Total Users at the bottom of the crash free users chart is aligned with the total number of unique users affected and crash free user rate.
2) Create a dashboard for a specific project using the following fileds:
SUM(SESSION) , CRASH_FREE_RATE(SESSION), COUNT_CRASHED(SESSION), COUNT_UNIQUE(USER), COUNT_ERRORED(SESSION) HEALTHY... etc...
	a)Check if the numbers are adding up
	b) Check if these are the same numbers that you are seeing in the Project Details page and the Releases page
3) The number of unhandled issues + level:fatal doesn't add up with the number of crashes

### Expected Result

Numbers should add up

### Actual Result

See steps to reproduce

### Product Area

Releases

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1932) by [Unito](https://www.unito.io)

**Comment by lobsterkatie** [comment]
@yuval-sentry Can you please post some links where this is happening in our own org, or one of our test orgs? We'll be able to debug faster if we don't have to set everything up from scratch.

**Comment by saivivek1987** [comment]
Hi team, this issue was observed in the project I am currently working at Amazon. Desktop app I have created using Qt C++ application and integrated sentry-native using 0.6.1 version. I was trying to forcefully crash app and also close app without any crash. I see no of session counts was coming correctly. But crash count was not getting captured correctly. Also crash_free_rate was totally incorrect

**Comment by saivivek1987** [comment]
<img width="846" alt="image" src="https://github.com/getsentry/sentry/assets/51218020/8e4af16c-6ddf-4aee-acec-c306f0df9850">

**Comment by ceorourke** [comment]
@yuval-sentry I've put this in our backlog to look into, thanks!

**Comment by jjbayer** [comment]
I found a specific issue with metrics queries in Dashboards: We query `sum(sentry.sessions.session)` to get the total session count, but that [maps to `SessionMRI.SESSION`](https://github.com/getsentry/sentry/blob/ebd28c8c3e37274ec3fe5207fcbbc939ceb8101f/src/sentry/snuba/metrics/naming_layer/mapping.py#L33), which is an internal metric that double-counts crashed sessions and should therefore not be used by the product. Instead, we should query `session.all` to get the correct number of total sessions.

I started a PR [here](https://github.com/getsentry/sentry/pull/56851) to improve the naming of metric identifiers on the backend, but I would ask @getsentry/product-owners-dashboards to fix the frontend code as described above.

**Comment by ale-cota** [comment]
Hi, @yuval-sentry and @saivivek1987! 
We've shipped a few changes which should address the inconsistencies between the project details page and dashboards. There might still be a very small apparent difference due to how the values are rounded.

Could you please verify and let us know if you still see any difference?

Thank you!

**Comment by yuval-sentry** [comment]
Thanks @ale-cota 
I will go ahead and check that.

**Comment by ale-cota** [comment]
Hi there,
Will proceed to close this issue since the fixes were delivered, but let us know if you still notice any other inconsistencies. Thank you
