### ISSUE TITLE
[Design Iteration] Play Replay Video By Clicking Player

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#55493]
## Problem

Today, users must click a small play icon at the bottom-left of the replay video player in order to watch the video. This could be their second click to watch a replay video if they came from the Issue Details or Txn Event Details pages, which could be frustrating. 

<img width="664" alt="Screenshot 2023-08-30 at 4 51 17 PM" src="https://github.com/getsentry/sentry/assets/77064737/f3d9ccee-45c3-43f4-90eb-8be78a9a0887">

## Solution

In order to improve ease-of-use of the Replay Details page, we should allow the entire Replay video to be clickable in order to start playing (akin to how it is on YouTube).

**Comment by Jesse-Box** [comment]
If we build replay clips for the issue details page, does this problem basically become a non issue? I understand that replay clips wont exist for the event details page; However, I think that workflow isn't as used as issues. @jas-kas @ryan953

**Comment by ryan953** [comment]
@Jesse-Box @jas-kas I agree that this is a non-issue now and I would close this ticket.. We're seeing lots of replays are being watched from the issue-details page, which has changed the game since this ticket was filed.

I think the benefit of reducing one click on the replay details page has to be weighed against the complexity of how the 'rightclick to inspect' function works. I do think it'll be a bunch of engineering to make those two things work together well.

**Comment by jas-kas** [comment]
@ryan953 I agree that this ticket is a 'won't do' atm, given that a lot of our Replay Views traffic is coming from outside of Replay Details with a pretty prominent 'play' button there. Closing
