### ISSUE TITLE
Webhook: There was an internal error with the Plugin, Summary or Text is required

### ISSUE THREAD

**Issue by Goshaka** [getsentry/sentry#55752]
Hi,
I'm trying to verify the Webhook plugin configuration to the Microsoft Teams channel, but I'm  getting the following error:
"There was an internal error with the Plugin, Summary or Text is required." 

Tried to send a message to the same channel with the curl and found that this is working properly. 

BR,
Igor.

**Comment by Kobby-Bawuah** [comment]
Hello @Goshaka, I will go ahead and route this to the appropriate team but I should point out that a result starting with 'There was an internal error with the Plugin..' only appears when the outgoing webhook request receives an error response (e.g. status code of 4xx or 5xx). There might be an error in the webhook code related to Summary or Text, but I don't think it is related to Sentry.
 
As a side note, instead of using the legacy webhooks integration (which is limited to one project), it may be easier to set up an [Internal Integration](https://docs.sentry.io/product/integrations/integration-platform/#internal-integrations).

**Comment by ceorourke** [comment]
@Goshaka we have a [Microsoft Teams Integration](https://docs.sentry.io/product/integrations/notification-incidents/msteams) and as @Kobby-Bawuah mentioned, if for some reason you can't use that we recommend using an internal integration instead.
