### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by hpiwowar** [getsentry/sentry#55765]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. In Sentry go to Integrations, GitHub, add an Installation
2. Click Configure on the screen that pops up, then Configure for the account with the repos I want
3. Click All repositories and "save"
4. GitHub page says " Okay, Sentry.io was updated for the @da-it-team account.  "

### Expected Result

Go back to Sentry, refresh page, see the Installation I just added.

### Actual Result

Go back to Sentry, refresh page, that Installation has not been added to the page (already have one there, this would be the second)

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
@cathteng can you please take a look

**Comment by cathteng** [comment]
Hi, you are seeing this because the Github organization or account you are trying to link with your Sentry org is already associated with another Sentry org.

This is also noted in the installation notes in the [Sentry Github App](https://github.com/apps/sentry-io#:~:text=Once%20this%20app%20is%20installed%20on%20a%20GitHub%20organization%20or%20account%20and%20is%20associated%20to%20a%20Sentry%20organization%2C%20that%20particular%20GitHub%20organization%20or%20account%20cannot%20be%20associated%20with%20any%20other%20Sentry%20organization.) description
> Once this app is installed on a GitHub organization or account and is associated to a Sentry organization, that particular GitHub organization or account cannot be associated with any other Sentry organization.

Clicking save in this case just updates the Sentry Github App for the existing Github integration.

**Comment by hpiwowar** [comment]
You are saying that da-it-team (the GitHub org name) was already associated
with a different Sentry org?  How can I figure out which one, and
disconnect it, so that this connection will work?

(I do know that DemsAbroad (a different GitHub org name) is already
associated with this Sentry org, but I don't think that should be a
problem, my goal is to add da-it-team.)

Thanks,
Heather

**Comment by Kobby-Bawuah** [comment]
Hello @hpiwowar,

Thank you for reaching out to us. To address your concern about identifying which Sentry Org is also using the same name, please contact our support team at `support@sentry.io`. They will be best equipped to assist you in resolving this matter.

To help our support agent better understand your situation, it would be helpful if you could attach this Github issue to your ticket. This will help to provide them with the necessary context to assist you more effectively.

**Comment by hpiwowar** [comment]
Ok will do.  Thanks!
Heather

**Comment by masinette** [comment]
Ticket was opened with Support, and is now solved. Closing out this GitHub issue.
