### ISSUE TITLE
Issue state not waiting full 7 days before changing from New to Ongoing

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#55766]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Reported by a user, but examples here are from my own test org.

New issues are not waiting the full 7 days before changing from New to Ongoing.  The behavior seems consistent across multiple orgs.  

Screenshot of activity tab for [this issue](https://francisorg.sentry.io/issues/4438177582/?project=4504089864830976) - 
<img width="933" alt="Screenshot 2023-09-06 at 9 32 06 AM" src="https://github.com/getsentry/sentry/assets/96670625/73ba7bc5-4b94-4c53-87e7-46af3da533a4">
 
[Direct link to my issue stream with the `is:ongoing` search term with many more examples](https://francisorg.sentry.io/issues/?project=-1&query=is%3Aunresolved+is%3Aongoing&referrer=issue-list&statsPeriod=14d)
 

### Expected Result

When there is not a manual review, Sentry should wait the full 7 days before marking the issue as Ongoing [per the docs](https://docs.sentry.io/product/issues/states-triage/)

### Actual Result

The issue state seems to change to Ongoing at any time.  In my org, I've seen anywhere from 4 hours to 5 days.

### Product Area

Issues

**Comment by ceorourke** [comment]
I looked into this a bit (having not ever looked at this feature before) and it looks like [here](https://github.com/getsentry/sentry/blob/master/src/sentry/tasks/auto_ongoing_issues.py#L146-L151)  we fetch some random group that was first seen 7 days ago, then [here](https://github.com/getsentry/sentry/blob/master/src/sentry/tasks/auto_ongoing_issues.py#L164-L168) we filter to unresolved new groups in the provided projects with ids less than or equal to the random group first seen 7 days ago.

I looked up the logs for the one you linked which transitioned to ongoing on 9/1:
* random group first_seen:  2023-08-06 08:07
* your group first_seen: 2023-08-30 13:12

Your group ID is less than the random group because it was created before the random group, which makes sense, but I think it should be greater than or equal to here rather than less than or equal to? I think the 2nd query should also filter by `first_seen__lte` (the same value). However when I was looking at the [test](https://github.com/getsentry/sentry/blob/master/tests/sentry/tasks/test_auto_ongoing_issues.py#L85) for this case it's behaving properly and changing lte to gte gives the opposite effect. Sooo either the test is wrong or something else needs to change, I'm going to assign this to @NisanthanNanthakumar to take a look at when he gets back because he has the most context.

**Comment by masinette** [comment]
This user on [this ticket ](https://sentry.zendesk.com/agent/tickets/100662)is seeing the same behaviour.

**Comment by Fwang36** [comment]
hey @NisanthanNanthakumar,

Can you take a look at this issue if you have time?  I see the behavior in our own Sentry org as well.
