### ISSUE TITLE
Hide event count in Issue Details

### ISSUE THREAD

**Issue by udameli** [getsentry/sentry#56038]
Currently, event count is derived from the number of occurrences. This number is different from the indexed event count we're showing in the "All Events" tab. 

1. Hide event count in the issue details
2. Rename "All Events" tab into "Samples"

**Comment by nanoburd** [comment]
Do we want to show processed event count in issue details and rename the events tab "all samples" instead?

What is more useful for troubleshooting?

**Comment by udameli** [comment]
Yes! Right, this was our latest decision 👍 I'll update the task

**Comment by narsaynorath** [comment]
In another chat I had with @udameli we said we wanted the event count to be a processed event count of events after the breakpoint over the new baseline duration. We can't filter on `transaction.duration` for the processed event count.

I think a possible way of moving forward on this would be to:
- show the event count as the number of events occurring after the breakpoint
- "All Samples" will be events occurring after the breakpoint above the baseline

I think there might be some confusion here as to what's being shown since the "All Samples" filters applies the "above the baseline" logic in the background. We could make it more clear by showing it in the filter bar as a default. Any opinions on this?

**Comment by udameli** [comment]
> We can't filter on transaction.duration for the processed event count.
I believe that's possible now. Have you experienced any troubles applying that filter?

> "All Samples" will be events occurring after the breakpoint above the baseline
In our recent conversations I believe we said we'll show all events occurring after the breakpoint without the duration filter. The reason being is that users might want to see all events in the tab - good and bad just so they have a fuller picture. 

As for filtering events for span analysis, we should still apply duration filters so that we're comparing "bad" events only. Since sometimes `p75` would stay the same and only `p95` will move which is indicative of problems affecting only that specific cluster.

**Comment by narsaynorath** [comment]
Closed by #58085
