### ISSUE TITLE
outbound proxy for sentry infrastructure

### ISSUE THREAD

**Issue by lwhorton** [getsentry/sentry#5610]
This is no small ask, but is something I would sure appreciate as consumer of Sentry services. 

When I deploy a client anywhere, I currently have the file sourcemaps hosted somewhere as well. This means I have to whitelist a big range of Sentry IPs. I have been bitten by the IPs changing without my knowledge (no heads up sent to any admin / owner account about the changes).

Why not directly upload sourcemaps instead of self-hosting? I had too many issues trying to get the whole process working a few months ago:
1) hard to coordinate multiple files into a release; a significant chunk of my build process was hand-holding cache-busting hashes and bundles for css/js upload. why so much effort when browser pragma marks + pre-existing tools have already solved this problem?
2) files too large to get a consistent upload (on both network ends). I don't have the time to write a resilient retry mechanism, nor the time to worry about deployment order and race conditions 
3) a real lack of usefulness without also uploading the source files, which further complicates 1 and 2  

It would be great if you guys setup an outband proxy with a permanent IP. I would like to be able to whitelist this server once and not have to worry about error->sourcemap information slipping through the cracks any time your IP ranges change/expand/contract.

**Comment by mattrobenolt** [comment]
We're doing this: https://blog.sentry.io/2017/06/15/notice-of-address-change

**Comment by lwhorton** [comment]
I appreciate the changes. That being said, was this sent out to your customers, or only made available on the blog? None of the owners in my organization received any sort of notification so I want to make sure we aren't misconfigured to ignore such things.

**Comment by mattrobenolt** [comment]
We emailed the owners of the orgs who were active within some period of time. I forget exactly what we pulled since I didn't do that. But I can assure you that we've put effort into this for moving forward so we limit the amount of IP addresses. The 4 IPs we listed in the blog post are intended to get very far, and we're making sure we communicate these changes better in the future.

So I apologize if this somehow didn't reach you, but we're making efforts at being better at this. And trying not to blast out every customer since a vast majority aren't affected. :(

**Comment by benvinegar** [comment]
@lwhorton – here's a summary of how we've been communicating these upcoming changes:

* We published [a blog post](https://blog.sentry.io/2017/06/15/notice-of-address-change) last Thursday (June 15th, 2017)
* Made [an announcement](https://twitter.com/getsentry/status/875506717685014528) on our official Twitter account the same day
* Sent an in-app broadcast with the same announcement + a link to the blog post, which has been active for the last week (but expired today – we're re-enabling it for another week)
![image](https://user-images.githubusercontent.com/2153/27497657-a199e182-5810-11e7-996a-6ae0c1d98b6a.png)

* Sent an email to owner and manager-level users of active accounts (on Sunday, June 18th, 2017)
  * We used our mailing list infrastructure to send these, so it's possible that if your account owners were unsubscribed from our list, they may not have gotten this (also check spam)

![image](https://user-images.githubusercontent.com/2153/27497812-48886f22-5811-11e7-947c-b944414ef299.png)

---

It's definitely disappointing to hear that you didn't get any of these notifications, because I feel we made a best-effort attempt to communicate these changes. To be 100% sure you receive news like this in the future, I'd recommend additionally following our Twitter account or subscribing to our blog.

**Comment by lwhorton** [comment]
Thanks for the detailed response. Ill make sure at least one of these channels is open moving forward.
