### ISSUE TITLE
Unmerging Merged Issues not working 

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#56334]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

- Opened the Merged Issues tab issue
- In a new tab, opened hyperlink
- Copied the event ID
- Unmerged hash x from issue 
- Searched issue stream for that event

### Expected Result

event ID will belong to the original issue

### Actual Result

no changes are made to the issue

### Product Area

Issues

**Comment by roggenkemper** [comment]
determined that unmerge is broken right now, team is looking into it.

**Comment by julianCast** [comment]
I'd like to add that is imposible to unmerge less than 2 issues. Is that intended? Thanks!
<img width="587" alt="Screenshot 2023-09-25 at 15 15 17" src="https://github.com/getsentry/sentry/assets/559677/8f8909f3-444f-4a50-a7da-2007a705e3a9">

**Comment by lobsterkatie** [comment]
> I'd like to add that is imposible to unmerge less than 2 issues.

This is bad wording on our part. The issue you see there is the issue itself, not one that's been merged into the issue. You're not the first to notice, and it's definitely on our list to fix! Sorry for any confusion.

**Comment by s-taylor** [comment]
Just wondering if there is any update on this?

**Comment by julianCast** [comment]
> > I'd like to add that is imposible to unmerge less than 2 issues.
> 
> This is bad wording on our part. The issue you see there is the issue itself, not one that's been merged into the issue. You're not the first to notice, and it's definitely on our list to fix! Sorry for any confusion.

oh! Thank you for the clarification, it's true, is the same hash.

**Comment by lobsterkatie** [comment]
@s-taylor - If you've experienced the problem in the original issue description (written by a Sentry person, so I'm not sure if you're the ultimate origin of it or not), two questions:

- Were you bitten by the same bad-wording issue as @julianCast? Or is this happening when the Merged Issues tab shows at least two events?
- If the latter, have you tried waiting a bit before searching for the event id? Unmerging has any number of cascading effects, so it can take some time to fully complete.

**Comment by s-taylor** [comment]
@lobsterkatie yes we originally reported this issue. The merged issues tab contains 26 issues, which after attempting to unmerge they still appear in the list. Speaking to the Sentry team it sounds like this is expected (I don't think it should function like this though), but also searching via event id also shows them as not having been split out.

**Comment by lobsterkatie** [comment]
@s-taylor: Are you by any chance selecting all 26 issues before you click 'unmerge'? If so, I think I get the problem, and it is, yet again, our confusing wording. If not, I return to my questions from the last comment.

**Comment by lobsterkatie** [comment]
Adding this here for completeness, since I ran into it in my testing, though it may get fixed separately:

If you merge the issues corresponding to two events captured with `captureMessage`, then a) no title shows up next to each fingerprint in the "Merged Issues" tab, and b) even once you fix that, there's still no link to a corresponding event the way there is for fingerprints from error issues.

**Comment by lobsterkatie** [comment]
Further update:

Turns out we've seen a twist on this problem before: https://github.com/getsentry/snuba/issues/4558

Meanwhile, I've discovered that at least in my testing, the results actually _are_ correct... eventually. In my tests, "eventually" has meant anywhere between 5 and 15 minutes or so, though according to some colleagues on the Search and Storage team, in prod it might be up to 24 hours. They believe it has to do with [an issue](https://github.com/ClickHouse/ClickHouse/issues/52588) in the database itself. Fortunately that bug has been patched, so if that is the problem here, upgrading clickhouse will fix it. According to the S&S team, they actually are currently working on upgrading, though there's not a definite timeline yet.

In the meantime, can you please confirm that you're seeing what I see, which is that though the data is wrong at first, it eventually corrects itself?

**Comment by lobsterkatie** [comment]
I'm going to close this as it's been more than a year since the last activity, but please feel free to re-open it if you're still having problems.
