### ISSUE TITLE
Billing errors cause infinite redirect loop when clicking `continue`

### ISSUE THREAD

**Issue by awbacker** [getsentry/sentry#5634]
This is a bug in the website.  Not sure where else to post it.  Our credit card billing failed, and I logged into the website to check it out and fix the issue.  

* Log in with google, select correct account from list
* Paste `https://sentry.io/organizations/{company-slug}/billing/details/` in the url bar of chrome
* Get popup
![image](https://user-images.githubusercontent.com/103330/27584057-e7693d7e-5b36-11e7-88e5-e506b44dfc54.png) )
* Click `Continue`
* Get redirected to same page
* Get same popup
* Click `remind me later` to get rid of it and stay on the page

I updated the billing information just to make it go away.  Still no clue what the actual error was, since the invoice page and billing page have no information returned from the processor.  There should be an error code which can be decoded, maybe that would be helpful to show.

**Comment by dcramer** [comment]
@awbacker I have a feeling our "Continue" handler isnt always propagating the cookie, so there's that. Will get that fixed immediately.

Additionally, you're right, we dont expose charge details in any meaningful way to the user when its due to the automatic renewal. We'll look into improving that.

(I'll say almost certainly the error is "card expired" or "card declined", and even when we show errors, they're going to be pretty useless due to the limited information banks provide)

**Comment by awbacker** [comment]
Perfect.  And about the charge details, if there are any they are great to see.  I remember getting some useful ones back in the day when I processed payments, but it wasn't often they were good.  I think that can be ignored 👍

**Comment by dcramer** [comment]
Closing this as we've addressed the core broken UI behavior, and will continually improve the UI.
