### ISSUE TITLE
New issue form's submit button is disabled if form untouched

### ISSUE THREAD

**Issue by frankie567** [getsentry/sentry#5658]
- Sentry version: 8.18.0.dev0 (SaaS version)

When creating a new issue, the submit button "Create Issue" is disabled if you leave the form untouched. Often, I just want to create the issue quickly from Sentry without adding further comments.

<img width="200" alt="capture d ecran 2017-06-29 a 10 06 52" src="https://user-images.githubusercontent.com/1144727/27677664-c4d8d72e-5cb2-11e7-8f3b-8283007bc3ea.png">

**Comment by frankie567** [comment]
Seems fixed today 😳 Sorry for the noise!

**Comment by dcramer** [comment]
I'm not actually seeing the same behavior, though I didn't think this changed THAT recently. It's possible I fixed it immediately after this issue was submitted.

Going to close for now. But if you're still seeing this let us know.

![screenshot 2017-07-17 11 23 32](https://user-images.githubusercontent.com/23610/28283375-70052430-6ae2-11e7-8c37-480cd39f1562.png)

**Comment by dcramer** [comment]
Doh, the browser had this page cached, pardon the noise!
