### ISSUE TITLE
x-www-form-urlencoded mistaken for JSON

### ISSUE THREAD

**Issue by dmalan** [getsentry/sentry#5673]
We deployed Sentry on one of our Flask apps today (via `pip3 install raven[flask]`), which revealed a bug we'd overlooked. But in trying to replicate the bug via Sentry's suggested `curl` command, we noticed that the suggested `curl` command seems to be mistaking POST data submitted as `x-www-form-urlencoded` for JSON.

Specifically, the suggested `curl` command in Sentry's web UI (at a URL of the form `https://sentry.io/ORG/PROJECT/issues/#/`) suggests using

```
-H "Content-Type: application/x-www-form-urlencoded"
--data "{\"username\":\"\",\"script\":\"foo\",\"cmd\":\"\",\"format\":\"html\"}"
```

among other command-line args. But the suggested `curl` command should actually be

```
-H "Content-Type: application/x-www-form-urlencoded"
--data "cmd=&format=html&username=&script=foo"
```

(among other command-line args)?

Perhaps related to https://github.com/getsentry/sentry/issues/5599, but this is perhaps just an issue in the web UI?

**Comment by benvinegar** [comment]
This seems like a relative easy change we can make. Could probably be entirely client-side. I'll take a look at an implementation soon.

**Comment by EvanPurkhiser** [comment]
In this specific case, the Flask request recording takes the url encoded form data directly from Flasks [`request.form`](http://flask.pocoo.org/docs/0.12/api/#flask.Request.form) attribute, which is an object, not a string.

https://github.com/getsentry/raven-python/blob/7a9455a7baaf0447a934c8dea5ac44a098f2d8d9/raven/contrib/flask.py#L190-L191

Then when rendering in the request as a curl command, because the data is an object we just assume it should be JSON encoded:

https://github.com/getsentry/sentry/blob/18395ed93491c70769c8e3abdd139cb8fd572ae4/src/sentry/interfaces/http.py#L170-L175

Finally, when rendering it, because it's already a string it doesn't transform it to parameters:

https://github.com/getsentry/sentry/blob/18395ed93491c70769c8e3abdd139cb8fd572ae4/src/sentry/static/sentry/app/components/events/interfaces/utils.jsx#L33-L37
