### ISSUE TITLE
Events not showing up under "Issues" (although they show up in "Overview")

### ISSUE THREAD

**Issue by chapati23** [getsentry/sentry#5691]
## Specs
• Angular 4 app
• Raven.js 3.16.1

## Description
I followed the install instruction to the letter and the integration kind of works. I have events arriving in sentry, they just don't show up in the "Issues" tab and I have no clue how to debug this.

Screenshot 1: Events in "Overview"
![image](https://user-images.githubusercontent.com/117495/27957306-36ec5bc6-631e-11e7-8d4f-354ec0dbda1e.png)

Screenshot 2: No Events in "Issues"
![image](https://user-images.githubusercontent.com/117495/27957326-4df7ec22-631e-11e7-8902-813c93764bd4.png)

Screenshot 3: One error in Devtools (disabled all content-blockers in my Chrome for testing)
![image](https://user-images.githubusercontent.com/117495/27957407-a66012ea-631e-11e7-90b9-b0573c29edfb.png)

**Comment by lovemyliwu** [comment]
also meet this issue, any idea? I am use sentry-java and log4j

![image](https://user-images.githubusercontent.com/2248369/27957695-28f07cf8-6352-11e7-8c22-28d192654dce.png)

![image](https://user-images.githubusercontent.com/2248369/27957709-38347ba6-6352-11e7-9106-da7491daf821.png)

**Comment by gander** [comment]
Me too. Panel stopped working around 2pm. Firstly I had an error reading the issue data, and now nothing comes in and I can not start new projects.

![Console](https://img42.com/HW5r_+)

**Comment by lovemyliwu** [comment]
see the sentry status page:https://status.sentry.io/incidents/w5flhd0ptnm1

Due to unforeseen circumstances, we have stopped processing events. We have identified the underlying issue and are applying a solution.
Posted about 2 hours ago. Jul 07, 2017 - 06:17 PDT

![image](https://user-images.githubusercontent.com/2248369/27963441-a50d7f24-6367-11e7-8ec7-ed9d119500a1.png)
