### ISSUE TITLE
Hybrid Onboarding is confusing

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#57129]
### Problem Statement

The onboarding for some platforms with hybrdi of wizard and snippet are really confusing. Does the wizard install and i still need to configure? Is there something the wizard doesn't do?

<img width="1191" alt="image" src="https://github.com/getsentry/sentry/assets/47563310/2418ca7e-a733-4877-805f-03af705e30f9">

### Solution Brainstorm

Ideally the optional manual config is a toggle or expandable somehow and the wording is more along the lines of, to set up automatically run this command. OR fi you want to do it your self (avengers end game meme) then you can copy paste these snippets and read the docs

### Product Area

Projects - Project Creation

**Comment by ale-cota** [comment]
@smeubank I think we can be opinionated here and recommend the "automated" way using the wizard over the manual. So instead of toggles, I would go for something like we have in Next.js and Sveltekit, which basically walks you through the wizard option and at the end offers the option to do it manually.

<img width="979" alt="Screenshot 2023-09-29 at 09 58 11" src="https://github.com/getsentry/sentry/assets/26696515/d0c3869a-5f41-48a6-93b9-081b307c7ca1">
 
<img width="1026" alt="Screenshot 2023-09-29 at 09 57 45" src="https://github.com/getsentry/sentry/assets/26696515/c1a73234-bd2b-44dc-b970-711fa26016a0">

One weird thing I notice though in these 2 > why is the verify step now gone? 😅 I know you guys redid these recently. Thanks!

**Comment by smeubank** [comment]
@romtsn i think this is at least conceptually solved since the auto/manual toggle.

<img width="965" alt="image" src="https://github.com/getsentry/sentry/assets/47563310/fae4800a-8732-421c-b71a-d01aacd4df74">
