### ISSUE TITLE
discard-groups feature not working as expected

### ISSUE THREAD

**Issue by nickjmv** [getsentry/sentry#57162]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

23.0.4

### Docker Compose Version

2.17.2

### Steps to Reproduce

Deploy sentry with the following option set to true in the sentry.conf.py file:
```
SENTRY_FEATURES['projects:discard-groups'] = True
```

### Expected Result

When opening a Sentry issue, I should be able to click on the 3 dots at the top and select 'Delete and discard future events'.

### Actual Result

Half of the time when I click on this button, Sentry says that I need to add the line in my above response to the configuration, which is already there.

**Comment by roggenkemper** [comment]
hi! did y'all update the self-hosted version/anything else between it working fine for you (while not working for others) and it not working for anyone?

**Comment by nickjmv** [comment]
Well, we upgrade our Sentry instance every month when the new release comes out. But we never noticed it being 'off'

**Comment by kristofclaes** [comment]
Additionally, we only used the feature like a handful of times in the past; definitely not often enough to notice any issues with it. We decided to start using it more a few weeks ago, to keep things clean and under control. So I can't really say for sure when the current behaviour started. We only noticed it a few weeks ago, but it is entirely possible it was broken for way longer.

I realise this is not helpful at all 🙈

**Comment by roggenkemper** [comment]
@kristofclaes any additional information is helpful, thank you! we will look into it and see if we can help out.

**Comment by snigdhas** [comment]
Hi @nickjmv, the team hasn't been able to allocate resources towards this yet. Adding to our backlog for further investigation.

**Comment by mwegner** [comment]
This is stinging me too.  At a quick glance of where `projects:discard-groups` even appears in code, I think it might be a cosmetic issue with `static/app/views/issueDetails/actions/index.tsx`, which was changed in this PR on November 29, 2023: https://github.com/getsentry/sentry/pull/60683

(But honestly I have no idea on the root cause, except that I'm pretty sure it isn't a configuration issue but downstream of that)

**Comment by snigdhas** [comment]
@mwegner Thanks for helping investigate. https://github.com/getsentry/sentry/pull/60683 was an unrelated refactor and the original bug report was from before this was released 

@mwegner @nickjmv @kristofclaes do you know if this happens on a specific project or if you've noticed this behavior on all projects within your org? I'm wondering if there's an issue with the feature flag config at the project-level, since the discard-groups feature has been stable for quite a while.

**Comment by nickjmv** [comment]
@snigdhas, this was on different (all) projects

**Comment by lobsterkatie** [comment]
This is indeed odd.

Can one of you running into this please load a project where this is happening and check out the `features` list in the response to `api/0/projects/<org-slug>/<project-slug>/`, to see if `discard-groups` is included?

![image](https://github.com/getsentry/sentry/assets/14812505/d7a9c318-ba04-48ac-84f0-2da2d3cc5cab)

(I'm trying to determine if your backend is sending the wrong information about what features are enabled or if the front end is interpreting the data wrong.)

**Comment by lobsterkatie** [comment]
> I noticed organization also has a list called features. I'm not sure if it matters, but discard-groups is not in that list.

Yup, that's expected. For what I can only assume are legacy reasons, Delete & Discard is coded as a project-level feature, even though it applies on an org level.

> The discard-groups is in the feature list. Does this help?

~Yes, that is definitely helpful, thanks! That means something's happening on the front end to make it _think_ you can't do it, even when you should be able to. Doesn't tell us what the problem is, but definitely narrows down the search!~ Or... maybe not? Before hitting Submit on this comment I went to check one more thing, and it only added to the mystery. 

I created a brand new org, on the free plan, which definitely _shouldn't_ have the feature... and it's showing up in the list of enabled features. (Trying to use the feature reflects that fact as well - no error message.) So now there are two confusing things happening:

- My free plan which shouldn't have the feature seems to have it anyway.
- Your on-prem instance which should have the feature _does_ have the feature, but the dialog box won't let you use it.

This is going to take some more investigation. 

@getsentry/revenue - Not 100% sure you're the right audience for this question, but since you deal with plans and feature enablement - do you have any idea what's going on here?

**Comment by lbenevenuto** [comment]
Happening with me in self-hosted installation
![image](https://github.com/getsentry/sentry/assets/3451320/ebb7aa6d-e8cc-4979-8e39-85adf50cb574)

**Comment by lobsterkatie** [comment]
@lbenevenuto - Just to confirm: As with the OP, you have this feature turned on in `sentry.conf.py` and are still seeing this message?

**Comment by dylode** [comment]
> @lbenevenuto - Just to confirm: As with the OP, you have this feature turned on in `sentry.conf.py` and are still seeing this message?

yes

**Comment by snigdhas** [comment]
Thanks for confirming @lbenevenuto and @dylode, we've raised this with our PM and queued it for further investigation.

**Comment by kristofclaes** [comment]
Is there any update to report on this, @snigdhas?

**Comment by chenqiang915** [comment]
![20240423-142340](https://github.com/getsentry/sentry/assets/67944136/3ba67954-1991-4fc4-a099-d576487ba326)
I have also encountered this problem, I use docker to build, the current sentry using version 24.1.0, I run docker-compose restar after explicitly configuring SENTRY_FEATURES['projects:discard-groups'] = True in the sentr.conf.py configuration, but I still have this problem

**Comment by BITS-Martin** [comment]
I encounter the same error with the same settings in 24.4.1

**Comment by leeandher** [comment]
Was able to identify the issue here, and likely why it was 'random' feeling, since only one project was ever getting the features applied. Hopefully this resolves this issue, you can track [this PR](https://github.com/getsentry/sentry/pull/69679) and update your instances accordingly.

Thanks for being patient, and providing context!
