### ISSUE TITLE
[User Story] Alerting on individual Bug Reports

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#57772]
## Problem
No way of being proactively notified of bugs

## Acceptance Criteria
- I want to be notified on any or all of the following:
  - when there’s a new bug report from a project and or environment
  - when a bug report from a project and or environment changes state from resolved to unresolved
- I want to be notified only if any, all or no reports match
  - Older or newer than a period of time
  - Assigned to
    - No one
    - Team
    - Specific member
  - The latest release
  - Specific key
    - contains value
    - ends with value
    - equals value
    - is set value
    - does not contain value
    - does not end with value
    - does not equal value
    - is not set value
- I want the alert I set up to perform one or more of the following actions
  - Send notification to
    - Suggested Assignees, 
    - Team
    - Member
    - If none can be found then send a notification to
    - Recently Active member
    - All Project Members
    - No One 
  - Send a Slack notification
  - Send a PagerDuty notification
  - Send a Discord notification
  - Create a Jira Ticket
- I want to specify an interval to perform the actions above once this often for an issue
- I want to name and assign ownership of Alert rule

## Designs
- [Alert Details](https://www.figma.com/file/ncZFVze3iDXrfAU9iPrn0M/Specs%3A-Alerts-Reports?type=design&node-id=1%3A2594&mode=design&t=chlmfRkNsvaWMjDC-1)
- [Alert Email](https://www.figma.com/file/nLS7ZsjVmuSoCmEkMG5nHn/Specs%3A-Alert-Emails?type=design&node-id=1%3A262&mode=design&t=o3IWobEupe0JzjIp-1)
![Image](https://github.com/getsentry/sentry/assets/6508377/3f9d9a25-29b9-4b01-acf0-29f05b2dc766)
<img width="698" alt="Alert Report" src="https://github.com/getsentry/sentry/assets/6508377/9ff90ec1-abfa-4cd4-8645-9d5f9f64cedc">

**Comment by ryan953** [comment]
I think the starting point for figuring out how to build this out is to look at the existing Alert Wizard page, url is `/alerts/wizard/`

It looks like this:

<img width="721" alt="SCR-20231101-udsa" src="https://github.com/getsentry/sentry/assets/187460/042308c8-cfb5-4bd8-8e09-cd9535db2d81">

# TODO:
1. What we want is to add a new Radio button to this page, called something like "User Feedback"
2. When you click into that radio button, you get a view that is basically the same as Issues, but with some conditions removed (there is no such thing as escalating feedback)

**Comment by bruno-garcia** [comment]
An update on alerting as of today, which we plan to GA in 3 days.

User Feedbacks received from the [new Widget the user can open](https://docs.sentry.io/platforms/javascript/user-feedback/#user-feedback-widget) are automatically alerted on. 

Feedback from the ['crash report modal'](https://docs.sentry.io/platforms/javascript/user-feedback/#crash-report-modal) or the [User Feedback API in the SDKs that link to an error,(e.g Flutter)](https://docs.sentry.io/platforms/flutter/user-feedback/#user-feedback-api) require users to opt-in on existant projects. Because we didn't want to introduce the risk of alerting folks who have high volume of feedback out of nowhere.

![image](https://github.com/getsentry/sentry/assets/1633368/6860c001-416b-47b6-a852-1b8e90bd341b)

New projects should have both enabled by default

**Comment by michellewzhang** [comment]
closing because this is completed
