### ISSUE TITLE
Mismatch crash free sessions/users values on browser and API for the same time frame

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#58396]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Select a project and time frame and observe the Crash Free Sessions and Crash Free Users
URL: https://<org_slug>.sentry.io/projects/<project>/?end=2023-09-30T23%3A59%3A59&environment=<environment>&project=<project_id>&start=2023-09-01T00%3A00%3A00&utc=true
![image](https://github.com/getsentry/sentry/assets/99350819/c49f39c6-5e50-477a-8903-d0f9675ebd10)
2. Call the API for the same values in the same timeframe 
URL: https://sentry.io/api/0/organizations/<org_slug>/sessions/?project=<project_id>&field=crash_rate(user)&field=crash_free_rate(user)&field=crash_rate(session)&field=crash_free_rate(session)&start=2023-09-01T00:00:00&end=2023-09-30T23:59:59&environment=<environment>&utc=true
<img width="359" alt="Screenshot 2023-10-18 at 2 47 04 PM" src="https://github.com/getsentry/sentry/assets/99350819/6bec9ef4-a2cf-44e9-a178-8bf92fcbca2b">

Observe the Crash Free Sessions and Crash Free Users are not the same:

Browser returns:
Crash Free Session Rate: 99.979%
Crash Free User Rate: 99.281%
API returns:
Crash Free Session Rate: 99.978%
Crash Free User Rate: 99.277%

The same issue was discussed [here](https://sentry.slack.com/archives/C011TCYRLF6/p1697564146967759).

### Expected Result

 The Crash Free Sessions and Crash Free Users values are the same via the API and Sentry browser.

### Actual Result

 The Crash Free Sessions and Crash Free Users values are not the same via the API and Sentry browser.

### Product Area

Projects - Project Details

**Comment by matejminar** [comment]
Heya, the reason why UI and API show slightly different values is that UI was built before the API supported crash-free rate fields. That means that in UI, we call API with sessions grouped by status (errored, healthy, abnormal, crashed) and then calculate the crash-free rate on frontend in javascript. Since then, we’ve added the native support for this field into API, but UI was not changed. For now, this is expected behavior. The difference is usually so low that no one complained. We can revisit with the team how much effort this would be to consolidate. 👍
