### ISSUE TITLE
Automatically collapse long context values

### ISSUE THREAD

**Issue by asherLZR** [getsentry/sentry#58573]
### Problem Statement

Doing `Sentry.setContext('title', { value })`, if it goes beyond a certain length, we want `value` to be collapsed in the UI and not truncated. Otherwise a long array could take up a page of space on the screen. Could we have this configurable as an option to `setContext`?

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1961) by [Unito](https://www.unito.io)

**Comment by roggenkemper** [comment]
hi! just to clarify - you're asking for the ability to collapse/expand the value field in the UI if potentially the value is too long instead of being truncated?

**Comment by asherLZR** [comment]
Yes exactly. A long value field taking up almost a full page is difficult to read. Ideally it could be collapsed with a preview of the first x number of lines, with the ability to expand it if necessary.

**Comment by malwilley** [comment]
This sounded familiar, so I searched around and found... an issue I made but was closed due to inactivity! https://github.com/getsentry/sentry/issues/48480

I think the issue here is not about truncation, since the event still has valid json to display, but that arrays are not being collapsed when they should.

[See here for a screenshot of it in action](https://github.com/getsentry/sentry/assets/10888943/3707703b-253e-48c2-a9f4-2ac9bc36785e)

We won't add collapsing as an SDK option, but we can certainly collapse long array values by default.
