### ISSUE TITLE
Clicking on settings link in a slack workflow notification doesn't take you to that project's settings

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#58601]
Steps to reproduce:
1. Have multiple orgs that your user is part of.
2. For project A, have a workflow notification setting send to Slack
3. Click on the Notification Settings link at the bottom of the notification
4. The link opens up Sentry, however to the workflow notification settings page for a different org, thus not showing Project A in the projects dropdown.

Some screenshots for context: 

Step 2&3:
![Image](https://github.com/getsentry/sentry/assets/1660873/931ecc94-3807-4750-a658-ea39794d972c)

Step 4: (notice the org selector is for 'bthi' when the snuba project is in the 'sentry' org 
![Image](https://github.com/getsentry/sentry/assets/1660873/72113034-c6d0-4378-83dc-504ee98679a7)

**Comment by ceorourke** [comment]
I looked into this a bit and I don't think it has anything to do with the Slack link specifically (since it doesn't have the organization slug in the URL). I can replicate this just by going to my notification settings page from the Sentry org, I see my test org's settings rather than the Sentry org ones. I'm not really a front end person but the component is [here](https://github.com/getsentry/sentry/blob/master/static/app/views/settings/account/notifications/organizationSelectHeader.tsx) and I'd expect that we should be able to detect which organization you're already in, and/or be able to pass an org slug param from an external link like from Slack to fix this.

**Comment by schew2381** [comment]
Investigating this, we basically just need to include the org id as a query param in the link in slack.
e.g. https://sentry.io/settings/account/notifications/workflow/?organizationId=12345
