### ISSUE TITLE
Cleanup task generates select on non-indexed fields

### ISSUE THREAD

**Issue by hexchain** [getsentry/sentry#5882]
Sentry version: 8.19
Installation method: docker

The cleanup task is stucking at "Removing expired values for EventMapping" for a long time (over 72 hours). Looking from pg_activity, the task is executing a statement like this:

```
delete from sentry_eventmapping where id = any(array( select id from sentry_eventmapping where "date_added" < '2017-08-04T17:38:29.073640+00:00'::timestamptz order by "date_added" desc limit 10000 ));
```

However the `date_added` field does not seem to be indexed. Manually executing the inner select statement takes for more than 1 minute.

Is this something that needs to be corrected?

**Comment by hexchain** [comment]
If the result set is large enough, PostgreSQL will just do sequence scan. So I guess there's no need to index that field. Closing.

**Comment by byo** [comment]
Hi,

I've recently run into this issue. Lack of index on ```date_added``` is indeed causing the problem here.

Without index, the inner query will always be full table scan. If you have a setup with large retention period, only a small portion of the data has to be removed (lowest dates). In such case the full table scan seems to be way to heavy and will be highly disproportional to the amount of data that's going to be removed.

Another, even more problematic use case, is when one would like to shorten large retention period (i.e. reduce from a year to half a year). Once started, a large amount of entries would have to be removed, it would be in batches of 10000 entries, each batch would require full table scan in the inner query, result would be a kind of O(n^2) operation.

@hexchain can you reopen this issue?

**Comment by will-** [comment]
I am running into the same situation.
https://github.com/getsentry/sentry/blob/525c9c71de21b890d90bea8e39cbee6423686568/src/sentry/runner/commands/cleanup.py#L179
Is `order by "date_added" desc` necessary ?
