### ISSUE TITLE
[Issue details] Viewing request in curl format leads to error

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#59034]
### Environment

SaaS (https://sentry.io/)

**Description**
A customer is trying to copy and paste the "request" information with ease using the curl format. However, when selecting curl, they receive the following error:
![Screenshot 2023-10-30 at 11 44 53 AM](https://github.com/getsentry/sentry/assets/8451987/c0ea4c58-9249-49fa-afe1-8516f4312c33)

Using the "Formatted" option does not expose all key value pairs unless you select every + icon manually

Customer details in support ticket - https://sentry.zendesk.com/agent/tickets/106143
Relevant Sentry issue - https://sentry.sentry.io/issues/4578014668/events/9952d8f81e8a454c91ca3eba72282a86/?project=11276

**Steps:**
1. Use example issue from Support ticket
2. Navigate to "request" section on the issue detail
3. Select curl

### Expected Result

Request to be in curl format

### Actual Result

Error when selecting curl

### Product Area

Issues

**Comment by lobsterkatie** [comment]
The problem is that there are a bunch of `null` headers, which you can see if you look at the event JSON. We should definitely handle this better, but that data also shouldn't be getting sent in the first place. 

@JLuse, can you please direct the original folks to this issue? I noticed they're still using the `raven` SDK (which has been deprecated for 5+ years), and I'm not sure, but I wonder if that's part of why bad data is getting sent. I understand that upgrading just to fix this might feel like a lot, but it's really something they should be doing in any case, both to get any bug fixes we might have done in that time and because they can't use performance or any of our other not-just-error-tracking features. Here's a [migration guide](https://docs.sentry.io/platforms/python/migration/).

**Comment by PatrickF1** [comment]
Thank you @lobsterkatie! Yes, we need to upgrade, didn't realize how out of date the SDK was 🤣
