### ISSUE TITLE
Weekly Report email showing wrong statistics

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#59076]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

A customer's Weekly Report email is showing false statistics compared to their actual event consumption.

### Expected Result

The numbers and graphs match what is seen in Sentry's statistics dashboard.

### Actual Result

The email seems to be missing information on the amount of events consumed, specifically, it is missing events from Tuesday and onwards. Screenshots included in the shadow ticket.

### Product Area

Bug Report

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1970) by [Unito](https://www.unito.io)

**Comment by snigdhas** [comment]
Sharing intermediate findings before I'm OOO for a bit - 
* the stats in the initial ticket were for approx 1 / 7 days, and the numbers lined up. So the event count in the email * 7 was in a similar ballpark to the count shown in the stats dashboard
* I was able to get another data point with the weekly email for the org this week, and it had ~1.5 days of data but still incorrect. 
* There are no new sentry errors from this task

The org has ~300 projects, so my hunch here is that the sheer volume of data for a user in all the projects is causing the error, whether it's a timeout or otherwise. My next steps would be to try and add some logging since we only log for the sentry org right now and determine whether there's any points where we could be giving up without reporting the error to Sentry. 

The _admin UI allows triggering weekly reports for the past seven days with/without dry-run and can be used to generate the logs instead of waiting for a week. The data/sns teams might have more insight on how a query of this size is expected to behave.

**Comment by isabellaenriquez** [comment]
Following up on this, Snigdha's hunch seems to be correct based on my own investigation. When we run the weekly report task, we query for the errors/transaction counts within the time period for the whole organization, grouping by project. With a large number of projects (in this case, ~3000), the cardinality of the rows gets super high, hitting the limit, and thus, losing data. We will need to figure out how to refactor the weekly report logic to account for cases like this (the number of projects can be as low as ~170 and still hit the limit). 

Additionally, it should be noted that the weekly report is tailored to the user it is sent to, so the stats are that of the user's projects, not all projects (usage stats screenshot was filtered for all projects).

**Comment by isabellaenriquez** [comment]
@InterstellarStella I believe #60833 resolved this issue! If the customer is still seeing discrepancies in their reports this Monday, please let me know, otherwise I'll close this next week.

**Comment by InterstellarStella** [comment]
@isabellaenriquez The customer has confirmed that their weekly report is showing up correctly!
