### ISSUE TITLE
Issues with Sentry Settings Section

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#59312]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

A user has raised a few issues with our settings section of Sentry that are making it impossible to do some tasks. See thread for breakdown. 

Deep Linking(Intended or broken?):
Copy the link of the api-keys page in settings and open it in a new tab. I would expect to be taken to the API keys page. The actual behaviour is that the request is given a HTTP 302 redirect to load a single-page app, loads up the basic general settings page for the organisation and changes the browser URL to https://XXX.sentry.io/settings/organization. The only way to get into a settings page is to click into it directly.

Broken API Key Links:
When viewing an API key the name of the key is displayed as a link but the link appears to be broken. An exampleis any key which links to https://XXX.sentry.io/settings/123/. When you click on it, or try to open it in a new tab, it just takes you back to the organisation settings page. As a consequence you can never edit an existing API key once it’s been saved.

Default API Key Creation:
When adding a API key, it appears to persist an API Key called “Default” and then takes to you the edit page. The URL on this occasion is something like: https://XXX.sentry.io/settings/api-keys/123/. This would appear to suggest the links displayed on the main API Keys page have the wrong path and are missing an `api-keys` in the path. But when you change the URL to use the ID of an existing key (e.g. 123) or if you refresh the Edit API Key page you land on after adding a key you get redirected over to Sentry Projects

Please see Jira for more information

### Expected Result

- Deep linking should take users to the expected settings page.
- API key links should properly navigate to the associated API key settings.
- Adding an API key should not result in incorrect URLs and redirects.

### Actual Result

See Steps to Reproduce section

### Product Area

Settings

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1978) by [Unito](https://www.unito.io)

**Comment by lobsterkatie** [comment]
This is because API keys have been deprecated since [some time in 2016](https://github.com/getsentry/sentry/pull/4776#issuecomment-273352100). We kept them enabled for orgs that already had them (which is why it shows up in the sidebar in Settings), but I'm guessing the redirect is to keep people who aren't grandfathered in from accessing that page via any links that floating out there. As for the editing URL, that does seem like a bug. I'll put it on our backlog, though I can't guarantee how soon/if we're going prioritize fixing it, given the deprecated nature of the feature. The best bet for now is to switch to using auth tokens if they can.

**Comment by mikejihbe** [comment]
This is unlikely to be prioritized anytime soon. Sorry for the inconvenience.
