### ISSUE TITLE
Feature Flag Support

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#59428]
### Problem Statement

I want to query and chart feature flag tags in relation to the crashes my users have experienced. The goal is to see the state of FFs in individual crashes and in case we make an assumption that some crashes are caused by some specific combination of flags we want the ability to query all crashes based on flags state to validate it.

### Solution Brainstorm

Current workarounds: 

**Tags**: Works great, but there's a concern of exploding the view with tags

**Additional Context**: Not indexed, better UI since formatted as an object. 

Suggestion: 

Create a reserved tag for FF

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1999) by [Unito](https://www.unito.io)

**Comment by dachakra** [comment]
@rachrwang The goal is highlighted in the problem statement above: 

_The goal is to see the state of FFs in individual crashes and in case we make an assumption that some crashes are caused by some specific combination of flags we want the ability to query all crashes based on flags state to validate it._

So both when looking at an issue and also using discover/dashboards to derive insights from the flags. As for the exploding view; the customer mentioned that they have over 50 FF, adding all those as custom tags will crowd the issue page making it less useful.

**Comment by rachrwang** [comment]
@dachakra - is the main concern currently that the prevalence of these tags is causing Issue Details to be less useful? If we were able to address the UX/UI concern there, would that meet the needs of this customer?

**Comment by Dhrumil-Sentry** [comment]
I think it's more than just a UX problem, tags today are single key value pairs, what they are asking for is a single key-multiple value object in our events that can be searched, so that they can search for issues, errors etc where the feature_Flas has values a,b,c

**Comment by volokluev** [comment]
I'm glad someone is already thinking of this and I'll add some color to it as to why it's important (from a developer perspective) and what is technically needed in order to make this work.

### Why it's necessary

As an organization grows in size, the amount of code getting shipped increases. The practice of feature flagging becomes necessary to not have to redeploy to turn off bad code. At sentry we are facing this now as more and more features are being turned on/off with the [sentry options automator](https://github.com/getsentry/sentry-options-automator). In snuba we also have our own runtime configuration tool that allows us to hide risky changes behind flags. 

Practically, this means that "releases" matter less and less. A code change being deployed is not as correlated to that code change running and our suspect commit features and release plots become not as useful for larger customers. Most importantly, the **utility of these features is decreasing for sentry developers**.


### What is needed technically

* SDKs need a way to receive feature flag changes as their own kind of event
* An ingestion pipeline that puts these events into snuba
* The UI needs to be able to query those feature flag changes and present them in an intuitive way

This is not a quick win feature but can yield a lot of benefit not only for sentry but many other customers that use feature flags. A number that is growing daily.

**Comment by bruno-garcia** [comment]
Since there was no update on this ticket for a while.
Note that we have a GitHub discussion on the matter:
* https://github.com/getsentry/sentry/discussions/73542

And this is WIP. We're starting with building FF context for Sentry itself so we can iron out UI and UX. After that we'll be expanding to external flag providers.

**Comment by cmanallen** [comment]
Sentry now supports feature flags with LaunchDarkly and OpenFeature being our initially supported SDKs.  You can learn more here: https://docs.sentry.io/product/explore/feature-flags/
