### ISSUE TITLE
Alert configuration. New issue with a number of events in a given time.

### ISSUE THREAD

**Issue by Juanjacinto123** [getsentry/sentry#59961]
Hello everyone, 

I want to create an alert based on: New issue with a number of events in a given time. For example:

New issue, with more than 10 events in a 1 hour interval.

I have tried like this:

WHEN:

-A new issue is created

-Number of events in an issue is more than
10 in one hour

IF

-The issue is newer than 24 hour(s)

THEN

-Send a email notification

The problem is that I get the notifications, but the events it takes into account are those of any other new Issue that meets the condition (10 events in 1 hour), but not those of the current Issue for which it is notifying. For example:

- Issue A (new Issue for which the notification is coming), does not meet the condition (2 events in 1 hour).
- Issue B (does not meet the condition)
- Issue C (meets the condition)

In this case, I receive the alert that there is a new Issue (Issue A), however the condition is being fulfilled in another Issue (Issue C). And as long as that other Issue (Issue C) is fulfilling the condition, I get recurring alerts for each new Issue that is detected. 

I don't know if I made myself clear. I really don't know if it's a bug or if I'm not setting up the alert configuration correctly. 

Can someone give me some advice?

**Comment by scttcper** [comment]
"new issues" in issue alerts are issues that have had their first event. They cannot have 10 events, since this will only fire on issues with 1 event.

You might be looking for an alert that fires on issues that have been made in the last x days with > 10 events.

Make sure to use a high enough action interval (1 week) that you aren't seeing repeat notifications.

![image](https://github.com/getsentry/sentry/assets/1400464/4111fe62-721e-4936-92dc-9196822c4757)
