### ISSUE TITLE
Adding Release Data to issue datasets

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#60028]
### Problem Statement

I want to create a widget that displays my project's issues showing the range of releases an issue occurred. 

We currently capture the release that introduced an issue and when it was last seen. 
<img width="1553" alt="image" src="https://github.com/getsentry/sentry/assets/86369415/fb753b87-a4e1-4c0f-9c26-2e5f016c239b">

But those data fields are not available in dashboards.

### Solution Brainstorm

You can add "firstSeen" to the issue table on the dashboard widget (which seems to just be a date). But being able to see the first release on the dashboard widget (rather than clicking into each issue) would help when reviewing issues for a release - it'd make it easier to scan through all the issues we have

<img width="1078" alt="image" src="https://github.com/getsentry/sentry/assets/86369415/b4aca335-cee5-4f00-9be6-d2e519ffb931">

### Product Area

Dashboards

**Comment by narsaynorath** [comment]
Hey @dachakra, thanks for the feedback. I can see why it's not so meaningful to only be able to see "last seen" and "first seen". This doesn't seem as trivial as a case of: the data is there and we just haven't exposed it, so we're going to have to backlog this as a feature request for now

cc: @nanoburd since it's a dashboards concern

**Comment by alexjillard** [comment]
When EAP is finished, queries against it will be able to span different datasets allowing for features like this. Closing for now as those features should be fairly automatic when all parts of the product are using EAP.
