### ISSUE TITLE
JIRA Link Accessible In Discover

### ISSUE THREAD

**Issue by sentryadam0000345** [getsentry/sentry#60234]
### Problem Statement

Be able to use search/discover to be able to filter on tags and generate links to relevant sub-views that make sense for different users dynamically

### Solution Brainstorm

Make Issues dataset not just available in the widget creator but also make it available for the Discover query.  

### Product Area

Discover

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2002) by [Unito](https://www.unito.io)

**Comment by narsaynorath** [comment]
Hi @sentryadam0000345, thanks for the suggestion!

Since Discover is focused on being an event explorer, and issue data is stored separately making joining the two more difficult, I don't think we will be able to fulfill the suggested solution of making issues data available in Discover.

Is there a reason filtering on the issues dataset doesn't currently fulfill your needs? It is the fact that Discover can contain a query specific to your account?

**Comment by alexjillard** [comment]
Closing this for now. As @narsaynorath mentioned, joining the datasets isn't something we're looking to do in Discover right now. We are working towards making some cross-dataset queries like this possible in Explore with the new EAP storage platform. Additionally, Dashboards is more suited to this sort of workflow, so we've [created an issue](https://github.com/getsentry/sentry/issues/82128) to track a broader feature that should enable this sort of workflow in the future.
