### ISSUE TITLE
Replays not being linked to issue

### ISSUE THREAD

**Issue by whitep4nth3r** [getsentry/sentry#60255]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I am building out a demo for a blog post, centred on how to deal with image 404s and fallbacks. I am using a static HTML page, with some images that 404.

I am using Sentry via the Browser JavaScript loader script.

Repo here: https://github.com/whitep4nth3r/image-404-fallbacks-and-monitoring

I am using a code snippet from [this docs page](https://docs.sentry.io/platforms/javascript/troubleshooting/#capturing-resource-404s) to send messages to Sentry when images 404.

I see issues in Sentry correctly.

![image](https://github.com/getsentry/sentry/assets/52798353/0b89f9f1-ea3e-489a-9c8b-5a93cbdc1672)

Replay is enabled for my project.

![image](https://github.com/getsentry/sentry/assets/52798353/4aa5ddd0-4217-45fc-a1a2-3998e1026a50)

I see Replays appear in the Replays view.

![image](https://github.com/getsentry/sentry/assets/52798353/5c981e35-d4ae-473e-923b-dc74c5f41a38)

However, Replays are not being linked to the issue. I see 0 Replays on the Replay tab for the issue.

![image](https://github.com/getsentry/sentry/assets/52798353/8cb08660-13f0-4e2d-b398-cd8ece003a94)

### Expected Result

When Replays are available for an issue, the Replays tab on the issue view should show a count greater than 0.

### Actual Result

See description above.

### Product Area

Replays

### Link

https://the-claw.sentry.io/issues/4650777325/?project=4506257560633344&query=is:unresolved&statsPeriod=14d&stream_index=0

### DSN

https://069d510beb8ec736246214096a3e3cd0@o4505635661873152.ingest.sentry.io/4506257560633344

**Comment by bruno-garcia** [comment]
SDK version: 7.80.1

Looking at ur link I see a replay embedded and also on the bar, towards the last of the errors:

![image](https://github.com/getsentry/sentry/assets/1633368/7e1deb68-ef82-4449-be39-6b090f19ebc8)

Seems like only 1 of the errors captured a replay:
![image](https://github.com/getsentry/sentry/assets/1633368/89d5f8e8-d373-4341-a037-657117c3234c)

Looking at stats, doesn't seem like anything got dropped server-side:
![image](https://github.com/getsentry/sentry/assets/1633368/140ec487-b80d-404b-93b7-efb8a3706692)

Not sure what's up here, we'll need to run the repro next

**Comment by ryan953** [comment]
I think the issue here is that, in this example code, the image errors are firing really super fast, well before the javascript has had a chance to download/parse/run

See this PR for an example where, if the image is added later on (in this case via a button click) then the errors are associated with the replay: https://github.com/whitep4nth3r/image-404-fallbacks-and-monitoring/pull/1/files

For Single-Page-Apps (SPA's) these types of errors are more rare because the app is starting with a small amount of html, and loading everything over JS anyway. But for server-rendered apps this type of error will be hard for any replay to catch. If caching is working extremely well, and timeouts are long enough then maybe the replay can set itself up before the error is thrown (and therefore link to the error). But if someone is using the Loader script there's a short enough cache TTL that it's JS will be deferred until after images (most) all of the time.

**Comment by whitep4nth3r** [comment]
Thank you @mydea, this makes perfect sense, and matches up with what I was seeing when I switched to use `captureException()`.

I've opened [an issue on the docs repo](https://github.com/getsentry/sentry-docs/issues/8551) to help document this better.

Thanks, everyone, for helping me look into this!

**Comment by mydea** [comment]
One thing to also note here (leaving this for the future): It may still be funky, because we trigger an error-based session immediately, but we still wait for 5s to send the replay (we do this to avoid very short replays). Maybe we need to rethink this for error-based sampling, and ignore the min. duration in this case 🤔 This could lead to the replay not being sent if you leave the page before 5s, currently.
