### ISSUE TITLE
Is there a way to get a more accurate representation of application availability other than crash-free sessions?

### ISSUE THREAD

**Issue by vinilvasani** [getsentry/sentry#60348]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Problem Statement:
We are seeking to establish a precise measure of application availability, and while crash-free sessions provide a valuable metric, they do not fully capture the user experience. As per the documentation, crash-free sessions also encompass errored sessions. However, when evaluating availability, both crashed and errored sessions represent failed user interactions with the application. Therefore, we are exploring alternative methods to accurately quantify the availability of our application. Specifically, we are investigating the feasibility of getting information from Sentry to determine the percentage of available sessions that were neither errored nor crashed, is there a way to get this data?

### How are you getting stuck?

Not able to find sufficient information on how to get this data from the docs

### Where in the product are you?

Unknown

**Comment by k-fish** [comment]
Hey there, can you tell us what platforms you're interested in?

**Comment by k-fish** [comment]
@vinilvasani thanks! Our version of browser sessions exists together with our replays product, their team should be able to answer your question in better detail.

**Comment by bruno-garcia** [comment]
>  However, when evaluating availability, both crashed and errored sessions represent failed user interactions with the application.

You can still see the healthy sessions, and errored etc, separately. In the Releases page.

![image](https://github.com/getsentry/sentry/assets/1633368/c67b7e02-5325-407a-ade3-41fd7a03924e)

Replay is useful to observe errors and how to reproduce them, and of course to empathize with your users, specially when there's a bad experience due to a slowdown or bug.

But Session Replay isn't the place to capture metrics of complete view of error-free vs errored/crashed session. Since it's unlikely you'll be capturing 100% of sessions.

Sessions on the other hands (as in Release Health) capture all sessions of ur users. Today it's based on 'page load' which isn't as intuitive and we plan on changing that, but regardless of the technical implementation, it's a cheap metric representing the status of the frontend. While samples of replay will help u debug/dig in.

**Comment by bruno-garcia** [comment]
You can use our API to fetch the metrics, you can fetch by session status (healthy, abnormal, crashed, errored):

https://docs.sentry.io/api/releases/retrieve-release-health-session-statistics/

I imagine with discover or dashboards you might be able to do the same thing actually. Possibly even alerts.

**Comment by matejminar** [comment]
What @bruno-garcia said. In dashboards, you can plot healthy/errored/crashed/abnormal session counts separately, but AFAIK sessions do not support equations so unfortunately you can't do math there.

**Comment by vinilvasani** [comment]
Thanks, folks!
So getting the percentage of healthy sessions against the total number of sessions does not seem possible?

Also is there a way for me to know which specific issue/error caused the session to be marked as errored? 
I would like to filter out sessions that have been errored by a specific issue I know did not cause any user experience breakages in my application from the total errored session count.

**Comment by bruno-garcia** [comment]
> So getting the percentage of healthy sessions against the total number of sessions does not seem possible?

I'll leave this one for @matejminar as I don't know the answer

> Also is there a way for me to know which specific issue/error caused the session to be marked as errored?

A session is marked crashed if an unhandled error happened. So you could look at events on that release that have `handled:false`. But note that session data is based on aggregates and are complete. The crash data/events could be sampled out due to many reasons (out of quota, filtered server-side, etc). So it's possible the exact numbers won't match (100 sessions, 90% crash free. Doesn't mean you'll find 10 unhandled errors necessarily all the time).

> I would like to filter out sessions that have been errored by a specific issue I know did not cause any user experience breakages in my application from the total errored session count.

What would 'filter out sessions' mean? Sessions are just aggregates to get the counts. You can get information on events (through the issues page, or Discover or Dashboards) that will be based on exact occurances of errors. Then slice by handled=true/false, etc.

**Comment by matejminar** [comment]
> So getting the percentage of healthy sessions against the total number of sessions does not seem possible?

The best bet is to create a dashboard widget like this:
![image](https://github.com/getsentry/sentry/assets/9060071/a02f543a-5917-4153-8846-cc7b170bde93)
The percentage calculation to get it down to just one number is not possible.

**Comment by vinilvasani** [comment]
Thanks @matejminar that makes sense!

@bruno-garcia My question is about errored sessions, according to the docs 
> We mark the session as errored if the SDK captures an event that contains an exception (this includes manually captured errors).

So what I wanted to know was is there a way to see the specific error or errors that have caused a session to be marked as errored, is that sort of information available in the session data? 

> Sessions are just aggregates to get the counts.
What do you mean by sessions are aggregates here?

**Comment by bruno-garcia** [comment]
> So what I wanted to know was is there a way to see the specific error or errors that have caused a session to be marked as errored, is that sort of information available in the session data?

Sessions and events (crashes) have the `release` information. So if you filter by `release` (also if you want by `environment` and time range) and you should see all events. All of the `unhandled` ones affected your crash free rate

**Comment by vinilvasani** [comment]
So does that mean that sessions do not have the information about the issue that caused them to be crashed or errored?

Example: when counting errored sessions while creating a custom dashboard widget, can I only count for errored sessions that were caused by an issue with rank P0? 



Just to reiterate, is the information about the issue that caused the sessions to be errored/crashed available in the session data?
If information about the issues does exist on session data, is there a way to write custom functions here?
<img width="846" alt="Screenshot 2023-12-06 at 2 22 06 AM" src="https://github.com/getsentry/sentry/assets/35430471/fdc66a9b-f096-4c1d-88a3-f9ec83fc49dd">

**Comment by bruno-garcia** [comment]
> Just to reiterate, is the information about the issue that caused the sessions to be errored/crashed available in the session data?

No. Sessions are aggregate and don't suffer from sampling.

**Comment by cmanallen** [comment]
You can get an accurate view of healthy and crashed sessions.  You can not get the ratio as a percentage.  We may revisit this in the future for now its closed.
