### ISSUE TITLE
Icons position looks is not aligned.

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/sentry#60383]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

In Screens with a width less than 1000px, in the top right corner, the icons for Sentry Trial, Help and Whats New is not aligned properly

### Expected Result

They should be aligned properly

### Actual Result

![image](https://github.com/getsentry/sentry/assets/43654389/ab1dc7ef-e204-43a5-a131-13a1e3fa3525)

### Product Area

Other

**Comment by Shubhdeep12** [comment]
It's a very minor issue.
if it is valid, please confirm - I'll push a fix for this.

Thanks

**Comment by roggenkemper** [comment]
I think you're right. Only happens when we have the getting quick start there, and it gets worse as the screen gets smaller. i'll add it to our backlog, but if you want to put a fix up for it, go for it!
<img width="937" alt="Screenshot 2023-11-21 at 2 02 27 PM" src="https://github.com/getsentry/sentry/assets/46740234/5047db76-0149-43d3-9b9d-d55a4d5f7666">
<img width="747" alt="Screenshot 2023-11-21 at 2 02 32 PM" src="https://github.com/getsentry/sentry/assets/46740234/5ff37eaa-bbd4-4b78-9471-318dc44cb243">

**Comment by Shubhdeep12** [comment]
Sure @roggenkemper thanks for the confirmation.
Raised a PR for the fix. 
Thanks
