### ISSUE TITLE
Enabling N+1 query detection feature on sentry

### ISSUE THREAD

**Issue by stickertyagi** [getsentry/sentry#60452]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Enabling features that allow n+1 query detection on our sentry.

Current sentry version is : 23.9.1
Python sentry-sdk version: 0.20.3

### How are you getting stuck?

What we have tried?

Enabled performance-issues-* related features as mentioned [here](https://github.com/getsentry/sentry/blob/master/src/sentry/features/__init__.py) in sentry configuration on the server where it is hosted.  Ran ./install.sh and started container, but still not getting option under project settings > performance tab to enable/disable these features. How to know it if has been enabled? 
<img width="1263" alt="Screenshot 2023-11-22 at 2 20 04 PM" src="https://github.com/getsentry/sentry/assets/106158444/8c6cd221-d1d1-49d2-9ac5-e85f1d9d2ff9">

We are trying this in UAT environment, is there something additional to above that we need to do for Production environment?

### Where in the product are you?

Performance - Queries

### Version

23.9.1

**Comment by k-fish** [comment]
Hey @stickertyagi, I'd first recommend updating your sdk since it's behind a major version (sentry-python is now 1.x+). As to why you're not seeing thresholds, that's another flag that was removed as of 23.10.1 (#58269) so you can either try upgrading or flipping that flag. 

As for seeing n+1 queries or not, I'd probably first get the settings working as mentioned above and turn down the thresholds if you expect to see issues. It's possible none of your backend events qualify as a N+1 at the default thresholds.

**Comment by gggritso** [comment]
@stickertyagi I'm going to close this issue since we haven't heard back from you in a while. If you're still having trouble please re-open, thanks!
