### ISSUE TITLE
[User Feedback Widget Set Up] Show User Feedback Widget Set Up Banner When User Feedback List Page is Populated

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#60711]
## Problem

Today, our existing User Feedback users (of the crash-report modal) do not have an easy way to discover the new User Feedback widget because we don't present info that it exists/how to set it up unless they happen to select a project without User Feedback set up whatsoever. Our assumption is that User Feedback users of the crash-report modal, would be a user segment interested/motivated to try the new User Feedback widget.

## Solution Proposal

Show _User Feedback Widget Set Up Banner_ When User Feedback List Page is Populated. We only show this banner if we can identify that they have * not * set up the new User Feedback widget * and * have an eligible web project selected. You can "X" out of the banner and it shows only one-time to unique users.

![Image](https://github.com/getsentry/sentry/assets/77064737/b7d42916-3e72-4653-9269-176f1ddfafa4)

**Comment by michellewzhang** [comment]
do we currently have the ability to tell whether an org has not set up the new user feedback widget for any projects?

**Comment by jas-kas** [comment]
@michellewzhang Good q - Josh might know

**Comment by michellewzhang** [comment]
cc @JoshFerge 

> [@michellewzhang](https://github.com/michellewzhang) Good q - Josh might know

**Comment by JoshFerge** [comment]
In order to do this, we simply need to replicate this flag, with 3 similar PRs:

and can put in ticket: we just need to replicate these 3 PRs:

https://github.com/getsentry/sentry/pull/59218
https://github.com/getsentry/sentry/pull/59214
https://github.com/getsentry/sentry/pull/59216

And the logic for modifying the flag would go here: https://github.com/getsentry/sentry/blob/18c50884aa4a3f8a99c5f6c03efc3fffc769ee7a/src/sentry/feedback/usecases/create_feedback.py#L170

where the logic would check the `FeedbackCreationSource`, and if true, flip the flag.
