### ISSUE TITLE
[Epic] Rage Click Issue and Alerting

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#60826]
We’ve heard from many customers that they want to be alerted on UX issues. We set out to do this but with the first iterations the detection logic was far from ideal. After a few iterations we believe we’re close.

Sentry is able to show you replays that have Dead and Rage Clicks. These are the first two replay UX issues we've implemented detection logic for, [here some ideas for future ones](https://github.com/getsentry/sentry/issues/45664).

Additionally, Sentry can show you selectors across all pages/replays that cause Dead and Rage clicks

### Initial intent
Automatically subscribe to alerts on Rage Click issues. Possibly (if needed) threshold might be used in the default alert (e.g., min 30 clicks on N selector) in order to find the right signal-to-noise ratio.

### Additional background

We started in the quest of detecting issues through Replay data (#45664) earlier with the goal of alerting on those. Our first iterations was on Dead click alerting and turned out to be quite noisy (https://github.com/getsentry/sentry/issues/48259#issuecomment-1593704772). We added Rage click support on top of it, which means: Rage clicking on a Dead element.

The signal here is much stronger, and with aggregation on selector, we believe we're closer to building something we can alert on.

Ultimately this is still a **research** project. We'll consider alerting on selectors, if too noisy, a metric alert could be the next best thing.
Finally, if the signal-to-noise here isn't good, we might have alerting as an opt-in or simply drop alerting altogether.

**Comment by bruno-garcia** [comment]
We plan to roll this out to all EA orgs on Monday (February 5th)

**Comment by bruno-garcia** [comment]
Rolling out to Early Adopter organizations.

**Comment by jgarplind** [comment]
Really happy with this direction. Haven't had the chance to try it yet, but it will hopefully help uncover some otherwise hard-to-detect-and-reproduce issues.

You mentioned that you focus on rage clicks now because dead clicks had too much noise, if I understand correctly.

In our use case, we serve a small user base, but we are eager to know about any dead clicks occurring, e.g. we suspect that sometimes the UI thread is too busy to handle button clicks and would like to know when that happens. What we will probably do now is to activate rage click detection and ask our small user base to keep clicking multiple times, but it would obviously be better for us if we could just create an issue on a dead click.

I fully understand that this is not the most common use case, and that the noise would be overwhelming for slightly larger projects, but I still wanted to let you know about our niche use case which in the best of worlds can help guide further development.

Thanks for reading!

**Comment by jas-kas** [comment]
Hey @jgarplind 👋🏻 

Thanks for sharing more about your use-case. :)

We don't have issue creation and alerting for dead clicks specifically (for the reason you mention above); however, we surface dead _and_ rage clicks grouped by selector on our Replay landing page. More info here: https://changelog.getsentry.com/announcements/top-selectors-with-rage-and-dead-clicks-in-session-replay (note: there are min. SDK requirements). It's ideal there is issue creation and alerting for dead clicks in your case, but I'm curious how much friction there would be if you routinely/manually check the Replay landing page every week or so? Or do you not go into Sentry unless you've been alerted? Appreciate your feedback!

**Comment by jgarplind** [comment]
Hey!

> we surface dead and rage clicks grouped by selector on our Replay landing page

That might be helpful indeed. I'm still wrapping my head around everything Sentry has to offer, and have yet to understand how to best use it all.

One counterpoint top of mind is that if the Replay is not created because of sampling rules, there would be no place to find the dead click, right?

I have yet to understand how much overhead/cost creating lots and lots of Replays mean, but my initial intention is to focus on Replays including errors.

> how much friction there would be if you routinely/manually check the Replay landing page every week or so?

Not a lot of friction, as long as there is data to be found without too much fuss.

> Or do you not go into Sentry unless you've been alerted?

That used to be the case before this weekend when I delved into everything Sentry has to offer other than basic Issues + Alerting. Hard to tell how other parts of the product will impact our behavior around Sentry.

Thanks for taking the time to engage in conversation around this topic!

**Comment by jas-kas** [comment]
Hey @jgarplind 👋🏻 

> One counterpoint top of mind is that if the Replay is not created because of sampling rules, there would be no place to find the dead click, right?

Yes, so our dead click detection logic requires a replay to be captured that exhibits a dead click. :)

> I have yet to understand how much overhead/cost creating lots and lots of Replays mean, but my initial intention is to focus on Replays including errors.

I think that's a sound approach. We recommend by default to have a 10% `replaysSessionSampleRate` (https://docs.sentry.io/platforms/javascript/session-replay/#set-up) to capture UI/UX issues such as rage and dead clicks. If you don't see any rage/dead clicks from that sample rate, it may make sense to increase it (or maybe users are simply not encountering them). 

Another way for you to understand user pain points outside of errors, is thru our [customizable User Feedback widget](https://docs.sentry.io/product/user-feedback/#user-feedback-widget) -- users can write in about any problems or confusion they're encountering on your app, and you can get alerted. And we'll connect the user message to any debugging context we have (for example, the associated replay! but if there's no replay sampled in, we'll still alert you on the user message of course). Let me know if you give that a try and what you think~

**Comment by jas-kas** [comment]
> One example of what Sentry considers a "dead click" that I don't, is when a user clicks a custom button next to an <input type="date"> element, and that populates the input with today's date. There is obvious visual feedback to the user, but it seems that is not detected by Sentry, so a dead click is recorded.

> Let me know if this is intended behavior or if you would like an issue to be created to follow up on this.

We're aware of false positive detection with dead clicks (for example, clicking a link that opens a page in a new page or a button that downloads a file to the browser), but the one you described is new to us. A ticket to the `sentry-javascript` repo would some details would be great!

**Comment by jgarplind** [comment]
> We're aware of false positive detection with dead clicks (for example, clicking a link that opens a page in a new tab or a button that downloads a file to the browser), but the one you described is new to us. A ticket to the `sentry-javascript` repo would some details would be great!

Unfortunately I can't seem to find the specific event any more. Probably because I misunderstood something the other day, but it felt very straightforward then, so I'm really not sure.

Either way - don't expect an issue as of now, and let us close the loop here to avoid derailing the main discussion this issue is supposed to be about. You can find me with the same nickname in the Discord if needed.

**Comment by ryan953** [comment]
This is done, we announced it here: https://sentry.io/changelog/rage-click-issues/
