### ISSUE TITLE
Bulk merge doesn't apply to all selected

### ISSUE THREAD

**Issue by OliverJAsh** [getsentry/sentry#6099]
Steps to reproduce
- Use the "Select the first 1,000 issues that match this search query" feature to select multiple pages of issues
- Use the UI to bulk merge issues

Upon refresh, some of the issues appear to have been merged, but many are not merged.

I did wonder if this was because the work happens asynchronously, however some issues appear to be merged immediately, leaving the user to believe the work has already completed.

**Comment by dcramer** [comment]
I feel like I noticed this too, which is odd as I thought merge changed the state synchronously.

**Comment by MaxBittker** [comment]
it's this https://github.com/getsentry/sentry/blob/master/src/sentry/api/paginator.py#L23

**Comment by MaxBittker** [comment]
looked into this with jess and dena, the problem is the query is being truncated by the paginator

**Comment by MaxBittker** [comment]
it's shared across all of the bulk query actions, and the problem is in the query search. the paginator overrides the limit with its own max limit, but the endpoint doesn't actually try to paginate through the results

**Comment by MaxBittker** [comment]
limit is set to 1000 here: https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/project_group_index.py#L451

and propagated through `search.query(**query_kwargs)` into here: 
https://github.com/getsentry/sentry/blob/master/src/sentry/search/django/backend.py#L302

the problem is that `paginator.get_result(limit, cursor, count_hits=count_hits)` overwrites the limit with a max_limit here with 100:
https://github.com/getsentry/sentry/blob/master/src/sentry/api/paginator.py#L101

and then back in `project_group_index` the paginator is cast to a list, which appears to not try to actually paginate `group_list = list(cursor_result)`
https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/project_group_index.py#L455

and group_list, with 100 items, is what is used for all of the bulk actions in the rest of the file, including merge and resolve.

**Comment by MaxBittker** [comment]
ted mentioned, broken since: https://github.com/getsentry/sentry/commit/f1bb4a1766ea782847813c4c562b5a7ca77b369f
