### ISSUE TITLE
[Needs triage] issue's event titles are different from the issue title

### ISSUE THREAD

**Issue by rachrwang** [getsentry/sentry#61332]
We have two internal reports of issue titles & event titles being different, and that causing confusion. This ticket is an investigation tickets to determine whether these are actually grouping problems.

**Example 1:** 

John Yang reported [this issue](https://sentry-st.sentry.io/issues/4587779544/events/?project=1513938).

See screenshots below.

![Image](https://github.com/getsentry/sentry/assets/82916311/8dda3a4a-ed99-4b6f-9e82-803c8e0e84ce)

![Image](https://github.com/getsentry/sentry/assets/82916311/2c209865-2379-4153-b030-0d0db4393218)

![Image](https://github.com/getsentry/sentry/assets/82916311/22eb5cbc-263b-4a41-acfe-82efe34d3a3c)

**Example 2:**

Josh Ferge reported [this issue](https://sentry.sentry.io/issues/4606899671/events/?project=1&referrer=issue-stream&sort=date&statsPeriod=30d&stream_index=9)

![Image](https://github.com/getsentry/sentry/assets/82916311/6963172f-0a22-4308-a87d-b72a74a1565b)

**Example 3:**
Reported by George: 
"These two issues are identical, I feel like they should have been one group":
https://sentry.sentry.io/issues/4720478456/
https://sentry.sentry.io/issues/4720606725/

**Comment by jangjodi** [comment]
Conclusion:

Example 1 and 2 are not grouping problems
- in-app frames in the stack traces are the same
- Same culprit (which is the group title)
- Example 1:
  - Looks like the same code is throwing a slightly different error, but both errors are related to partitioning with indexes and offsets
  - Got confirmation from John Yang that they thought they were grouped correctly, but the titles didn't match
- Example 2:
  - Looks like the same error is being thrown for different data
  
Example 3 is a known grouping problem: see [chained JS errors](https://www.notion.so/sentry/Grouping-Problems-d53117b66e4e48f89f0a4e4b7ebde418?p=9b5f5f2dd56b406c89651425ccec02fc&pm=s)

**Comment by armenzg** [comment]
The problem is likely to come that we're not using the remote traceback [1] for grouping.

If you place a remote traceback in front of another you will see that the error came from two different lines within the same function.
<img width="918" alt="image" src="https://github.com/getsentry/sentry/assets/44410/88b98f36-bda5-4752-975e-bd2a8c0df6f0">

The issue comes from [this commit](https://github.com/getsentry/sentry/commit/661145a4dff1a899401a53065a007f444086e199) which soon after it was reverted 
<img width="662" alt="image" src="https://github.com/getsentry/sentry/assets/44410/bb7c6785-629e-4aeb-9459-f2b92d3d03a0">


[1]
<img width="932" alt="image" src="https://github.com/getsentry/sentry/assets/44410/c21ec400-a4ca-4cf8-8c8a-5fab9f8e85bb">
