### ISSUE TITLE
Fingerprints via Terraform

### ISSUE THREAD

**Issue by acm19** [getsentry/sentry#61662]
### Problem Statement

I want to be able to configure fingerprints via Terraform. The reason for that is in our organisation users don't have admin permission on project, all changes are applied via Terraform. Which help us have more control over who did what and why. Sometimes users need to adjust some settings like fingerprints and they are not able to, so we need to provide temporary permission etc. Adding workload and defeating the purpose of manage infrastructure.

### Product Area

APIs

**Comment by Dhrumil-Sentry** [comment]
@acm19 Thanks for this request- We anticipate improving our grouping mechanisms in the future which is why we don't have APIs published for this yet. 

Could you please explain the type of uses cases/issues where you feel you need to override grouping rules in Sentry-we'd love to get to a point where developers don't have to do this at all
