### ISSUE TITLE
(Empty string) can not be searched

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#61933]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Add a scrubbing rule to [Remove] user ID

2. Find events in Discover with the scrubbed-out user ID:
<img width="816" alt="image" src="https://github.com/getsentry/sentry/assets/86369415/fd1925f6-8dc6-4a4d-9a1c-36559f78bffb">

Try to add the empty string to the filter: 
`!has:user.id`
<img width="1178" alt="image" src="https://github.com/getsentry/sentry/assets/86369415/f9edf43c-b4bb-47a2-8326-e65c824093b0">
`user.id:""`
<img width="1250" alt="image" src="https://github.com/getsentry/sentry/assets/86369415/aa98b8e4-c36a-43d3-ab53-759f98aeb9c4">

### Expected Result

Return the events with (empty string) 

### Actual Result

Returns nothing

### Product Area

Discover

**Comment by narsaynorath** [comment]
Heads up, I'm going to own this and take a deeper look. I'll update with any progress that I make

**Comment by endrift** [comment]
Would love a fix with this. I'm trying to make a dashboard based on a tag and I need to filter out rows without that tag being present, and I'm not sure I can do that right now since it shows up as (Empty string)

**Comment by narsaynorath** [comment]
Hey @endrift, sorry I haven't been able to fix this one yet, other things have taken my attention away from this fix. I've come up with a workaround in the meantime. You can add a version of this filter to your widget: `count_if(<YOUR TAG>,equals,""):0`

This essentially treats the count as a flag and we can filter out rows where the tag is empty. Please let me know if it works for you!

For my own context, is the empty string something you've explicitly set? Or is it occurring because of a data scrubbing rule? If it's the former, you could have a different value set that's easier to filter out for the future until this is fixed. If the latter and the product is producing empty strings by default we would want to look into that experience.

**Comment by endrift** [comment]
It's closer to the former. We try to gather some explicit context about crashes if it's available, but since it's not always available it can be (Empty string). I'm trying to create a dashboard filter of the different counts of the distinct values, but the case where it's not available isn't interesting because it could be *anything* then.

**Comment by narsaynorath** [comment]
I appreciate the context @endrift. I'm glad to hear the workaround is sufficient for now, I'll update you once again when we're able to get this fixed. Thanks for your patience on this.

**Comment by alexjillard** [comment]
This functionality should be available in the product after recent search changes.

@endrift Can you check that this is still an issue for you? You should be able to fulfil this search with `user.id is ""`

For now I'll close this issue, but if the new functionality isn't what you're looking for, please reopen the issue and let us konw what you're experiencing so we can take a look.

**Comment by endrift** [comment]
Which version was this introduced in? We're using self-hosted and are currently on 24.11.0. I can prompt the admin to update if needed.
