### ISSUE TITLE
Keep the existing data of an Issue when we delete and discard the future events for it

### ISSUE THREAD

**Issue by yuval-sentry** [getsentry/sentry#61940]
### Problem Statement

Users would like to Discard future events without needing to delete the events that were already ingested.

### Product Area

Issues

**Comment by roggenkemper** [comment]
added to our board - just to clarify , this would essentially be a "only discard future events" option , in addition to the existing "delete and discard future events"

**Comment by jboulter11** [comment]
Hey, I think this ticket may have originally been created based off my ask.  We have a strong need to be able to discard specific noisy events without losing the existing data for debugging and diagnosing the issue.

Example:
0. Some dev logs a new error
1. The error unexpectedly logs 1M events/day, but we don't know that until it hits production
2. Now we wanna fix the issue and also remove, move, or otherwise reduce the volume of that log while still getting useful information.
3. We currently would use Bugsnag's "Discard" feature which allows us, per "issue", to say only discard new info, do not delete.  Those events do not count towards quota, helping us keep our other events from getting dropped and removing the noise while we fix the issue.
4. Ship a fix 2 weeks later
5. Turn the discard off, watch as volume reduces and ideally goes away on new versions.  We'd then mark it as "fixed" if possible.

**Comment by jboulter11** [comment]
Here's what Bugsnag's UI looks like for discarding and undiscarding.  
![Screenshot by Dropbox Capture](https://github.com/getsentry/sentry/assets/6633472/65c9b485-5a96-4e49-b805-1b7ebf44829a)

It's just on a "..." menu for a specific "issue".

**Comment by jboulter11** [comment]
Here's what Sentry's UI looks like

![Screenshot by Dropbox Capture](https://github.com/getsentry/sentry/assets/6633472/60326c70-9542-49dc-ac47-f0c489591445)

**Comment by jboulter11** [comment]
We're open to other ways of acheiving this same functionality, but the key things are the following:

1. The discarded errors do not count towards quota
2. Data we already "paid for" to be collected is retained for debug/diagnosis purposes.
3. We can undo the discarding, turning that data flow back on for future monitoring.

**Comment by roggenkemper** [comment]
thanks for the scenario, I think that makes a lot of sense as a concept. let me bring the idea up with the team to get more thoughts on it

**Comment by snigdhas** [comment]
This ticket captures a similar ask https://github.com/getsentry/sentry/issues/77535

**Comment by MichaelSun48** [comment]
Closing this ticket in favor of #77535, which appears to be the same request.
