### ISSUE TITLE
Spike protection Error for Admin

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#62567]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Org settings -> Spike protection 

### Expected Result

![image](https://github.com/getsentry/sentry/assets/86369415/57d045f2-9219-42a4-8d11-06679bdc3310)

### Actual Result

Check Jira ticket

### Product Area

Settings - Spike Protection

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2060) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
@cathteng please take a look once you are back

**Comment by cathteng** [comment]
I believe the issue here is that the spike protection page loads all of the projects in the org, so when an org does not have open membership, the request can fail because a user accessing the page does not have access to all projects.

A possible fix would be to only load projects the org member has access to in the case of closed membership

**Comment by schew2381** [comment]
> I believe the issue here is that the spike protection page loads all of the projects in the org, so when an org does not have open membership, the request can fail because a user accessing the page does not have access to all projects.
> 
> A possible fix would be to only load projects the org member has access to in the case of closed membership

@cathteng Were you able to replicate the issue, and ensure the PR fixed the issue?

**Comment by cathteng** [comment]
@schew2381 i was able to replicate locally and put up a PR to fix
