### ISSUE TITLE
Design: [Replay Details] Add Dead Click min-SDK notifs

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#62611]
Idea: Add "Rage clicks and Dead clicks require SDK version xyz" to the DOM Events panel:

![Image](https://user-images.githubusercontent.com/187460/264724453-2573407f-9c0f-436c-b394-4271bfe6a602.png)
![Image](https://user-images.githubusercontent.com/187460/264724452-5ddb5607-bb0c-4f08-8348-233e9339f57f.png)

**Comment by Jesse-Box** [comment]
@ryan953 I would do something similar to the unmasking text banner we recently implemented. In the sense that, the text says something like

`Upgrade your SDK to see when users are frustrated with rage and dead clicks. Requires version >= 7.60.1.` [x]

**Comment by michellewzhang** [comment]
@Jesse-Box is this design finalized/ready for implementation 👀

**Comment by ryan953** [comment]
Maybe we should be looking at like a general "SDK checkup" kind of thing instead of one-off messages.

I'm thinking for example: for Rage Clicks, Canvas, [Component Names](https://github.com/getsentry/sentry/issues/64673), (and in the old days) Network Bodies, Server Errors... all this stuff depends on SDK version checks. 

For someone who is on a really old SDK version it wouldn't be great to have all these messages showup scattered all over the place... and the 'dismiss forever' model sucks for us because we want to show people the update instructions when they need it. 

So i'm thinking a home for this kind of info, with sdk upgrade instructions (link to them really) could be fun and would be re-usable for us in the future too

**Comment by ryan953** [comment]
related to https://github.com/getsentry/team-replay/issues/213

**Comment by billyvg** [comment]
Closing this since we don't have a DOM Events tab anymore.
