### ISSUE TITLE
Big Number widget is displaying incorrect time on Dashboard

### ISSUE THREAD

**Issue by masinette** [getsentry/sentry#62639]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. create a dashboard widget displaying custom performance metrics using the Big Number visualization

### Expected Result

Time is displayed correctly on the Dashboard

### Actual Result

<img width="738" alt="Screenshot 2024-01-04 at 2 48 34 PM" src="https://github.com/getsentry/sentry/assets/58349708/915a0f11-53af-479b-b8d8-2ff14fe524e9">

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2062) by [Unito](https://www.unito.io)

**Comment by ale-cota** [comment]
The problem seems to be caused by sending custom measurements with multiple units. This is a known issue related to custom measurements already tracked in https://github.com/orgs/getsentry/projects/248?pane=issue&itemId=73883441. The issue should be resolved once the 90 day retention period expires and there is only one unit present.
