### ISSUE TITLE
DB migration hangs on initial install, completes if you abort and try again

### ISSUE THREAD

**Issue by bradringel** [getsentry/sentry#6273]
- The version of Sentry you're using
8.2
- Whether you're using Docker or another installation method
Docker

Seeing the database migrations hang for the first time when doing a new installation of sentry.

After running this command:
`docker-compose run --rm web upgrade`

Everything goes smoothly up until this point:

```
Running migrations for search:
 - Migrating forwards to 0002_auto__del_searchtoken__del_unique_searchtoken_document_field_token__de.
 > search:0001_initial
 > search:0002_auto__del_searchtoken__del_unique_searchtoken_document_field_token__de
 - Loading initial data for search.
Installed 0 object(s) from 0 fixture(s)
```

After that, the migration hangs and the process needs to be killed
If you run the command again, the migrations finish without issue.

**Comment by mattrobenolt** [comment]
My only guess is you’re running out of memory or something while migrations are running.

**Comment by Deimos** [comment]
Just want to confirm that I just ran into the same issue, and the cause was my VM running out of memory. @mattrobenolt I'm not sure if it's worth bothering to look into, but having the initial migration run take up over 1GB of memory seems strange. It increases as the migrations progress, so I imagine it will only keep getting worse as more migrations are added.

**Comment by lilywang711** [comment]
@Deimos 
In my case, it is caused by running out of memory,  I changed to a 4g memory system.after I switch 2g to 4g ,it worked

**Comment by kslr** [comment]
Really need a lot of memory to boot...
