### ISSUE TITLE
After upgrading to 8.21, Sentry upgrade wizard hangs on auth.allow-registration

### ISSUE THREAD

**Issue by JeanFred** [getsentry/sentry#6315]
When upgrading my onpremise installation form 8.20 to 8.21 (using docker-compose), the wizard prompted me to set the “Anonymize Beacon” option. When clicking “Continue”, the following error message pops up:
> An invalid value for (auth.allow-registration) was passed to the server.

There was no such option `auth.allow-registration` set in either `sentry.conf.py` or `config.yml`.

The call to `https://sentry.example.com/api/0/internal/options/` returned a 400, with the following params:
```
system.admin-email: admin@example.com
system.url-prefix | https://sentry.example.com
auth.allow-registration | 0
beacon.anonymous | true
```
I worked around that by resending the request, changing 0 for False. My install is now fine

Running `sentry config get auth.allow-registration`, whether before the fix or after, returns:
```
        type: BOOLEAN
 from config: <not set>
     current: 0
```
This looks somehow similar to #5699.

Hope that helps!

**Comment by billyvg** [comment]
Thanks! I haven't gotten around to this PR https://github.com/getsentry/sentry/pull/6091, but it should solve the problem.

**Comment by JeanFred** [comment]
Thank you for the quick resolution @billyvg !

**Comment by ThiefMaster** [comment]
Could the docker image please be upgraded to include this fix?

**Comment by mattrobenolt** [comment]
We normally only tag new releases once per month, but I'll try to cut a patch release that includes this commit this week for 8.21.1.

**Comment by ragesoss** [comment]
@JeanFred you're one week ahead of my problems!

**Comment by mechanik0s** [comment]
@mattrobenolt week has already passed

**Comment by benh57** [comment]
Ping.. 8.21 is kinda totally broken without this fix.

**Comment by maxiko** [comment]
@mattrobenolt almost two weeks passed and there is no promised 8.21.1  :(

**Comment by mattrobenolt** [comment]
So. To be clear here, I never promised anything. We have a regular schedule for cutting releases, and that is the first week of every month. 

I don’t know how to personally reproduce this to even put together a patch release that will guarantee a fix. So the effort to go through attempting to cut an 8.21.1 by cherry picking something that might work or might not, is a lot. If I were able to confirm this behavior that was broken in 8.21, and could easily confirm it fixed in 8.21.1, I’d be more willing to do this out of band. As it stands, this is a multiple hour, if not s full day of work to go through all of this outside of normal schedule since it’d require me trying to reproduce.

It hasn’t been posted in this thread, but I’ve seen workarounds posted to get past it. It’s far from a blocking feature. I can provide a short command to run in `sentry shell` to just bypass the wizard entirely in the morning.

**Comment by kaystrobach** [comment]
i can confirm that resending the request in firefox fixes the problem

**Comment by nicois** [comment]
I also hit this problem. I ended up modifying the installed code to ignore the header altogether:

```
$ grep -A 3 has_user_registration  lib/python2.7/site-packages/sentry/utils/auth.py
def has_user_registration():
    return True

```
