### ISSUE TITLE
Regression emails show wrong (old) logs

### ISSUE THREAD

**Issue by terrbear** [getsentry/sentry#6323]
We're using sentry on sentry.io, and the java (slf4j) client sentry-java.

Yesterday I got an AmazonDynamoDBException because the schema was mismatched. Exception text: The provided key element does not match the schema (Service: AmazonDynamoDBv2; Status Code: 400; ...

Today there was another AmazonDynamoDBException, and the email showed the same message, but (after scratching my head a bit :)), and going to sentry.io, the actual error was User: arn:aws:sts::<redacted>:assumed-role/<redacted> is not authorized to perform: dynamodb:GetItem on resource <redacted>.

In this case, it made the regression email misleading/wrong. 

PS, hi @bretthoerner !

**Comment by bretthoerner** [comment]
'sup Terry.

I'm not totally sure I follow. Are these two events grouped together, or are they completely independent and Sentry just sent an incorrect notification? Did the notification link to the correct event or no?

Can you link us to the two distinct events on Sentry? That may help me grok.

**Comment by terrbear** [comment]
Ahh, it looks like it is grouping them together and just showing the first error maybe? 

Yesterday's: https://sentry.io/trustgrid/gatekeeper/issues/319832270/events/6510265594/

Today's: https://sentry.io/trustgrid/gatekeeper/issues/368961084/events/7947010891/

**Comment by bretthoerner** [comment]
OK, good (kinda). They're grouping because the stacktraces are exactly the same. There's some info on how we group here: https://docs.sentry.io/learn/rollups/

We don't decide grouping based on the error message unless it's a last resort, because we can't differentiate between parts of the string you care about vs ones you don't (like the UUID request ID that differs on every AWS error).

The only solution off the top of my head here is to set the Event fingerprint (maybe only if it's an `AmazonDynamoDBException`). The fingerprint is basically the "no Sentry, I'll tell you how I want to group" escape hatch. I don't know if the `AmazonDynamoDBException` object has any useful getters or if it just provides the huge opaque String blob though? If it offers something like "The provided key element does not match the schema" vs "AccessDeniedException" then you could set the fingerprint to that so they'd group separately (but together with other similar exceptions that have different Request IDs).

Hopefully that made any sense at all. :)

**Comment by terrbear** [comment]
That makes sense, I can do that :)

Thank you sir!

**Comment by bretthoerner** [comment]
If you're logging it... I don't think it'll be possible. You'd have to catch it and do something like,

```
        Sentry.capture(new EventBuilder()
            .withMessage(throwable.getMessage())
            .withLevel(Event.Level.ERROR)
            .withSentryInterface(new ExceptionInterface(throwable))
            .withFingerprint(throwable.getUsefulUniqueName()));
```

Kinda sucks right now tbh. Java. :(
