### ISSUE TITLE
Insights into why Errors are Dropped

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#63448]
### Problem Statement

On the topic of rate-limiting, filtering, spike protection and spend allocation, interests have been expressed to:

- Get a view into why specific errors get dropped (Similar to our internal Admin tool metrics)
- Get better insights into the frequency of deleted/discarded issues.

### Solution Brainstorm

This could be a report customers run. Or..

1.
Add reasons for dropping events in the Stats page, much like our internal admin metrics, where hovering over a timeframe can drill into reasons for dropping:
<img width="573" alt="image" src="https://github.com/getsentry/sentry/assets/103009467/b3c1ac31-baf5-44b4-9f10-d22d96ce9124">

2.
Provide counts of deleted/discarded Errors within Project Settings > Inbound Filters:
<img width="1103" alt="image" src="https://github.com/getsentry/sentry/assets/103009467/b9dc5085-9bf8-41e0-8618-c7986415570f">

3.
Share details on which issues are rate limited within Project Settings > Client Keys (DSN) > Configure (Probably not possible since this info is filtered at the ingestion layer):
<img width="1197" alt="image" src="https://github.com/getsentry/sentry/assets/103009467/8869d90c-378b-4d0d-96f6-a0720f9b1ab5">

### Product Area

Stats

**Comment by Dhrumil-Sentry** [comment]
This is a valid ask and I will link some other related issues pertaining to the org stats here. We'll add this to the backlog and I'll update the issue when we have a timeline

**Comment by realkosty** [comment]
@Dhrumil-Sentry duplicate of https://github.com/getsentry/sentry/issues/44875 ?

**Comment by Dhrumil-Sentry** [comment]
@realkosty yes this is a duplicate of the issue you linked, Closing this one as a duplicate

**Comment by mrduncan** [comment]
@priscilawebdev I think your recent stats improvements resolved this?

**Comment by realkosty** [comment]
This seems like a bit of an umbrella issue:

(1) _admin-like detailed stats 
  - Done https://sentry.io/changelog/clearer-insights-into-your-sentry-data-with-our-updated-stats-page/
 
(2) visibility into counts of delete & discard 
  - duplicate of https://github.com/getsentry/sentry/issues/47755

(3) which issues are rate limited
  - doesn't seem well defined to me. All issues are rate limited without any special preference to certain ones. It is possible that because some issues happen more toward the end of rate limit window than others but that's probably more of an edge case and most of the time relative event counts should be preserved with active rate limits. 

@kpujjigit please clarify (3) ^

**Comment by priscilawebdev** [comment]
@mrduncan Yes, the recent updates to the stats page address item 1. Users can now see the reasons why events are not accepted.
