### ISSUE TITLE
Add 'recovery mode' for ingest consumer which skip events that aren't already in processing Redis

### ISSUE THREAD

**Issue by snigdhas** [getsentry/sentry#63876]
Add a recovery mode to the consumer that to check for events that are stuck in redis. It should be able to distinguish a new event from an event stuck in the pipeline, and it should only reprocess the stuck events.

**Comment by untitaker** [comment]
i'm going into specifics that were not discussed in the postmortem by describing exact behavior. the high-level proposal was to write a script ("recovery mode" whatever you want to call it) that runs the ingest consumer again for dropped events in some incident timerange. this would trigger the pipeline for those events a second time, and as a result recover them and also remove the relevant orphaned keys from rc-processing (getting the ingest consumer unstuck)

here's how I can imagine that working:

* we have a new binary in getsentry that takes a timerange (=timerange of when we dropped events) and a topic (default ingest-events)

* it spawns a kafka consumer on a new consumer group on that topic

* it resets its own offsets to the beginning of that timerange (kafka has an API for that), and starts consuming messages using ingest consumer logic (i.e. spawning preprocess_event)
optionally, it skips events for which there is no orphaned key in redis

* it stops after it observes an event/offset that exceeds the timerange

**Comment by bmckerry** [comment]
I don't mean to increase the confusion here, when I was talking about this with @fpacifici my understanding was we wanted something like this:
- we add a new CLI argument to the events ingest consumer which, when passed, will skip over any event messages in kafka which are _not_ already in rc-processing redis
- the logic here being that, in a situation where keys are stuck in rc-processing, we would create a new consumer group, rewind its offset to before the incident started, and then create an `ingest-events-2` consumer for that group with the CLI arg passed to only process events stuck in rc-processing
  - the creation of the new recovery consumer group could be handled by a script in getsentry or the ops repo, it shouldn't matter, I believe the goal of this specific ticket was to just add the recovery mode CLI arg to the ingest consumer code
- the reasoning is that we want to only process events which we know are stuck in rc-processing. During INC-611 when we created a new consumer group to process stuck events, we accidentally set the consumer group start time too early and lost ~1 million keys in redis due to this. If we had the ability to spin up an ingest events consumer which would only process stuck events, then we could set the recovery consumer group's start time offset to well before the incident started without having it reprocess a bunch of errors which were not stuck in rc-processing 

Again sorry if this raises any confusion, happy to have a meeting to clarify the requirements of this action item anytime
