### ISSUE TITLE
Projects' transfer between the organizations fails

### ISSUE THREAD

**Issue by vikakam** [getsentry/sentry#64526]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Select project in Lightricks organization
2. Press transfer and add my (owner in both organizations) email
3. Go to email and press "approve transfer"

### Expected Result

Project tranfered to PopularPays organization

### Actual Result

Transfer fails
 Error attached
<img width="1032" alt="Screenshot 2024-02-05 at 2 44 56 AM" src="https://github.com/getsentry/sentry/assets/90634981/d6f243f8-141d-49f6-89c5-6c3da8a2866b">

### Product Area

Org Relocation

### Link

https://sentry.io/accept-transfer/?data=eyJhY3Rvcl9pZCI6MjYwMzYxMSwiZnJvbV9vcmdhbml6YXRpb25faWQiOjM4NDY3LCJwcm9qZWN0X2lkIjoyMzg2OTksInVzZXJfaWQiOjIzNzgyNDIsInRyYW5zYWN0aW9uX2lkIjoiMWYzNGIzZjYwOWFjNDQxMzgzMDczODg1YWJmNTkzNjYifToxclduMXg6SFNna3hQVXYxQzZ4SVl6VkhYWDJBRTJZNHRiWkJ3T1ViTVkwVGw3b0tsRQ

### DSN

lightricks

**Comment by schew2381** [comment]
Hi there, after clicking the approve in the email did you see the following that let you choose which organization to transfer to, or did it immediately error?

<img width="799" alt="Screenshot 2024-02-05 at 1 10 06 PM" src="https://github.com/getsentry/sentry/assets/67301797/29fd99a0-11e8-4c11-b880-156660bcae1f">

**Comment by vikakam** [comment]
Hi! I didn't see the screen you shared but immediately the error.
Thanks,
Vika

**Comment by vikakam** [comment]
Hi @schew2381 , 
Any updates regarding this issue? We are blocked.
Thanks,
Vika

**Comment by schew2381** [comment]
Hi sorry for the delay on this!
I checked the `PopularPays` organization, and it appears that your email corresponds to 2 different organization owners.

I believe the endpoint is failing because it's checking that the same user is doing the project transfer across organizations, but in `PopularPays` there's a different user tied to one of the duplicate accounts with your email.

Could you try removing the org owner with the name `Vika` (not the `Vika Kam` one) from the organization and trying the project transfer again?

**Comment by vikakam** [comment]
Worked like a charm. Thank you very much!

Vika
