### ISSUE TITLE
Cant get search transactions and profiles in the same way I do issues

### ISSUE THREAD

**Issue by gotenxds** [getsentry/sentry#64648]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I'm trying to use the search functionality in the profile and performance tabs using tags and field I can use in the issues tab

### How are you getting stuck?

While in the issues tab and the discover tab I can easily filter by tags that are being sent to sentry, for example, team name, service_name, etc:
![image](https://github.com/getsentry/sentry/assets/3519520/ca198009-424f-47bf-aead-b10eb551fbd3)

I cannot do that in the preformance or profile tab,
I will also not that the hint in the profile tab does state you can use "tags"
![image](https://github.com/getsentry/sentry/assets/3519520/ac8a62f5-39ff-47c8-afac-288d79ebe301)
But, alas, I cant:
![image](https://github.com/getsentry/sentry/assets/3519520/bcf567b5-5c50-4830-a625-3d80b4a547df)

This makes it quite hard, especially in the performance tab to find what we need.

### Where in the product are you?

Performance

**Comment by gggritso** [comment]
@gotenxds thanks for raising this!

Firstly, you're right that the search fields for Issues, Transactions, and Profiles all work differently.

The search field on the "Performances" page is a search for transaction names, to help you find transactions by name faster. Once you choose a transaction, you can click the "Sampled Events" tab to find the exact events you need, using all the available tags and properties. Also, as you mentioned, you can use Discover.

The search bar on the Profiling page is similar to the one on the Issues page, but profiles don't support all of the same fields as issues. For example, it's not possible to search for `team:` because Profiles don't have assignees the way that issues do. Our searchable properties are [listed in the documentation(https://docs.sentry.io/product/reference/search/searchable-properties/issues/), though I see that the fields for Profiling are not listed, I'll look into that.

What kinds of tags and fields (other than `team:`) are you looking to use?

**Comment by gotenxds** [comment]
Hi @gggritso sorry for the late response and thanks for the answer,

I understand the the search in the performance page is for names only, I think that is a big miss for the use case of a search there, for us at least, most tags will be the same for all events of the transaction, being able to search only by name makes it impossible to find performance issues based on tags we send to sentry.
Some of our tags are used to "group" issues, routes, and services togeter, in to many groups and sub groups.

The "team" tag is something that we send via the api, it is not the team tag sentry uses and has nothing to do with assignees, as every profile is directly attached to an event I would assume that I could find a tag that is attached to the event,

As for what tags, any tags, none of them are working for us, for example we send a tag named "server_name" and another that is called "service_name" both are available in the issues but not in the profile

**Comment by k-fish** [comment]
Hey, 👋, @gggritso is away at the moment, so I'm taking a look.

> I understand the the search in the performance page is for names only, I think that is a big miss for the use case of a search there 

That's good feedback, we've been iterating on the product and trying to find ways to let users search their transaction and profiling more effectively, right now the volume difference (transactions and profiles are usually tens if not hundreds of times more data) can make searching tags on large data difficult in a summary view.

> As for what tags, any tags, none of them are working for us, for example we send a tag named "server_name" and another that is called "service_name" both are available in the issues but not in the profile

Have you checked the Discover tab? You should be able to search transactions there by tags and group by your endpoint / frontend page etc. If your tags aren't searchable in Discover for transactions let us know. 

As for profiling, we're in the midst of adding support for better search on profiles via transaction tags etc. but that isn't ready quite yet.

**Comment by gotenxds** [comment]
Hi @k-fish Thanks for the response, I have been using the "discover" page, it does allow us to search for transactions but we cant see performance info in that page, we cant sort by p50/p95 or failure rate, etc.

The discover page as I see it is more useful to see trends than anything else.

**Comment by wmak** [comment]
Hmm you should be able to sort by p50/p95 in discover. You just need to be on [a Trial, Business, or Enterprise plan](https://sentry.io/pricing/).
To do so you just need to hit the columns button and add those columns directly.
