### ISSUE TITLE
Storing Mutation Data with Analytics Events

### ISSUE THREAD

**Issue by ehfeng** [getsentry/sentry#6465]
Stateless event data is straightforward (Jenny clicked the button yesterday), but often, we want to know *what state* changed without significantly modifying Sentry's codebase.[^1]

So far, we have two approaches: "events" and "mutations."

With **events**, after the event has occurred, we attach new state to the event. The analytics code is much simpler and less prone to breakage.

```python
analytics.record('plan.changed', customer.plan)
```

With **mutation**, we must capture the existing plan *prior* to change. This is less idea as we introduce dozens of analytics events to the code base—needing to following all the branching code paths to `e.record` makes yet another state to track within a request.

```python
e = analytics.build('plan.changed', previous=customer.plan, current=new_plan)

# ...save new plan...

e.record()
```

For ease of discussion, let's consider someone upgrades their plan. We might ask ourselves, "What was expansion revenue last month?" If we record previous and current state with each event, it's easy to select `plan.changed` events and find the delta in the plan prices. However, if we only stored the current plan with events, we'd need to select the last `plan.changed` event since the first of the month to compare it against the most recent data.

However, financial reporting rarely needs *continuous* data (usually reporting is monthly), so even if you stored previous/current state with each event, you'd need to get both the first and last "plan.changed" events within a month. The only difference is the "events" route, you select the **last** event from the previous month instead of the **first** event of the current.

Are there other interesting cases where mutation might offer significant advantages to justify the additional complexity? @mattrobenolt @alex-hofsteede @dcramer @sksembhi 

[^1]: Doing full event sourcing with Kafka + rollups might be the academically correct answer, but I'm hoping we can do something simpler and "good enough". Because of that, event data doesn't need to be *complete* so much as it needs to be *useable*.

**Comment by alex-hofsteede** [comment]
Firstly I think that something like changing a plan is a poor fit for a  stream-of-events analytics model. A users' plan choice exists over a range of time, rather than at an instant, so either approach (events or mutations) suffers from the same infinite-lookback problem. i.e. you potentially have to read all events going back to the beginning of time to know what plan a given user is currently on because maybe they haven't changed their plan in a long time.

The only way to avoid that particular problem would be to either use a more traditional mutable store so you can do things like `select * from plan_choices where current = true;` or, to store keyframe events periodically in the event stream that show the current point-in-time state per user so you only need to look back to the last keyframe.

Having said all that, I don't think you need to choose either events or mutations exclusively, they are both just types of events, the mutations just have a little more info that helps to answer a specific type of query, ie. the expansion revenue this month. In general I'd recommend just adding as many properties as possible to your analytics events.

**Comment by ehfeng** [comment]
> changing a plan is a poor fit for a stream-of-events analytics model

Yes, for understanding a user's choice in a range of time. The potential use case for this would be:

1. users receive over-quota notifications
2. some users setup rate limits

I *think* stream-of-events better answers the question, "How many users setup rate limits because of the notification?". Right now, organization rate limits are basically mutable attributes on organization—we don't have a log of who changed it to what value when. Adding these kinds of events lets us better understand what's working and what isn't.

> store keyframe events periodically in the event stream that show the current point-in-time state per user

Agreed. For that, we've just started snapshotting certain tables.

> In general I'd recommend just adding as many properties as possible to your analytics events.

I also agree. What I'm trying to understand if it's worth the added complexity the store before/after state mutation, given the extra complexity. If there are potential analyses that need it, then I'll add. But financial reporting is better done through snapshotting, and I can't think of other valuable analyses that would need it, so I don't think the extra complexity is worth it.

**Comment by jleclanche** [comment]
> Firstly I think that something like changing a plan is a poor fit for a stream-of-events analytics model. 

Stream of events is great as long as you have all the data. On our project here for example, we actually have zero plan or payment analytics of any kind. We drive *all* the payment analytics we need off our Stripe `Event` billing table (using [dj-stripe](https://github.com/dj-stripe/dj-stripe)), which has all the data Stripe has access to (and as a bonus, can very easily be rebuilt from the stripe API should it get damaged or wiped).

Because it's all in Postgres, you can even do more clever things such as sql views and UDFs to give access to timebound data (rather than having to deal with append-only data).

There's two issues with this: Bigger datasets suffer in terms of performance but that can definitely be remedied with good caching (or even a Redshift intermediary or some such, hell possibly even Sigma if you only use Stripe); and it gives potentially too-sensitive billing data access to your analytics; that can be remedied by copying only what you need from the Stripe events to analytics tables.

I can't really tell how it's organized since the Stripe side of things doesn't appear to be in the open source sentry codebase, but if you're already storing Stripe events (which you probably are in some way given that you need to process webhooks somehow), sql views / functions could be the answer to doing this without modifying sentry's code much.
Given that events always contain a full copy of the object's state, fetching the previous state is as simple as sorting by event timestamp and looking at `object->id`. You can even be lazier and use the `previous_attributes` field if you're storing the whole thing.

**Comment by ehfeng** [comment]
@jleclanche I like driving all billing analytics from Stripe, instead of Sentry customer tables as an intermediary. We already treat Stripe as a source-of-truth—why not pull directly from there? I won't be able to do this short-term (we landed on snapshotting, which is cheap), but I will definitely revisit.

@arikfr Yes, the "mutation event" idea made me realize it's completely futile—events are *at best* snapshots. Because at any moment in the code, you can never know whether you're inside a transaction or maybe a signal triggers a change elsewhere, properties attached to an event cannot and should not represent actual change. The transaction might be rolled back, the signal trigger might fail, the webhook might experience a network failure.

We ended up landing on exactly what you suggested—simple derived tables. Scheduled queries for now and, when we have an analytics/data engineering team, a processing pipeline.

I actually would *love* if Redash, in addition to having scheduled queries, could have cascading queries to exactly this. Setting up Airflow is still overkill for an organization like us. Even if that just meant, within the Python runner, being able to call `refresh_query(<query id>)`, it'd be huge.
