### ISSUE TITLE
Apply React Component Names to Replay Surface Areas

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#64673]
Apply React Component Names to....

- [x] Selector Widgets and Selector Index Page
- [x] Replay Details - Breadcrumbs
- [x] Rage Click Issues

FYI
- Documentation on how to set this up via bundler plugin is [here](https://docs.sentry.io/platforms/javascript/guides/react/features/component-tracking/)
- It is GA'ed
- Replay search works already - [reference
](https://sentry.sentry.io/replays/?project=11276&query=click.component_name%3ASmartSearchBar&statsPeriod=7d)

Rage click issues example, with only selector
![image](https://github.com/getsentry/sentry/assets/1633368/45368ba9-76b6-4c04-9015-501a567e2145)

**Comment by bruno-garcia** [comment]
Click and other DOM-related crumbs could also show the React Component name instead of the raw HTML blocks:

![image](https://github.com/getsentry/sentry/assets/1633368/1c68622d-e9dc-42bb-9f1c-55dad39ffa1a)

**Comment by bruno-garcia** [comment]
@Jesse-Box we talked to @0Calories who is going to help Replay leverage the React Component names feature he added.

We need some help with designs, on where to put the component names in the UI when available.
He's take was:

> I can make some preliminary UI changes, but I think for showing the component name in a Replay breadcrumb, I need design specs. I don’t think we should outright replace the whole HTML block with the component name, since a lot of valuable data is available in the HTML itself. We should show the component name as supplementary data

**Comment by jas-kas** [comment]
Design Update: https://github.com/getsentry/sentry/issues/65093#issuecomment-1954640111

**Comment by michellewzhang** [comment]
Did a bit of research into what needs to be done for each of the 3 surfaces:

## Effort / changes required

### 1. Replay Breadcrumbs:
- We have designs already for this
- GOAL: replace the full selector string on relevant breadcrumbs to be the React component name "tree"
- GOAL: click on component name searches by this component --> filters index page search by this component
- Good sources of more information on this topic: Ryan & Colton 
- Overall estimation of effort: medium

Steps:
- The selector is currently rendered here: https://github.com/getsentry/sentry/blob/188d41f34743cb9971ab576403c187676e141805/static/app/components/replays/breadcrumbs/breadcrumbItem.tsx#L103
- The selector info currently comes directly from the raw breadcrumb frame. Luckily, the raw breadcrumb frames also contain the `data-sentry-component` which is exactly what we need to show the component name! There are a couple frontend files to edit here, as well as potential type changes to surface the component name, but we already have this data already so it shouldn't be too difficult.
- The data we have:
<img width="467" alt="SCR-20240313-kcks" src="https://github.com/getsentry/sentry/assets/56095982/5f90fc12-cebd-40b0-9bcc-04a85872de57">
 
- Relevant file: https://github.com/getsentry/sentry/blob/188d41f34743cb9971ab576403c187676e141805/static/app/utils/replays/hydrateBreadcrumbs.tsx#L27
- One thing to note is that the `data-sentry-component` attribute appears ONLY if it exists. So if it's a click on something without a component name, this attribute won't show up
- The more complicated next step is figuring out how to show the entire component "tree". We'll need to trace the selector all the way back up to the root, remembering that not every element has a component name. We should get the most useful thing to display (whether it's the component name, or the id, class, etc.) 

From Figma:
<img width="600" alt="SCR-20240313-knfh" src="https://github.com/getsentry/sentry/assets/56095982/389611df-fc42-41bf-8d51-7a45e4fa843f">

- Another question we'll need to consider is how far down we want to show the tree -- e.g. do we want to show things that are further down the tree as well? If so --> small SDK change needed to propagate component down 
  - In this case, would also need to disambiguate which one is our current component
- Implementing search should not be difficult since we already have the search capabilities


### 2. Rage Click Issues
- Design input needed
- GOAL: replace the selector with the React component name
- Good source of more information on this topic: Josh
- Overall estimation of effort: low

Steps:
- We'd need to update this file to pass in the component name: https://github.com/getsentry/sentry/blob/188d41f34743cb9971ab576403c187676e141805/src/sentry/replays/usecases/ingest/issue_creation.py#L18
- Looks like we have access to the component name data at this level, so it shouldn't be too difficult to make this change
- See this test file here for the structure:
https://github.com/getsentry/sentry/blob/188d41f34743cb9971ab576403c187676e141805/tests/sentry/replays/unit/test_ingest_dom_index.py#L31


### 3. Selector Widgets and Selector Index Page
- Design input needed
- GOAL: replace all instances of the selectors with React component names instead
- GOAL: when the component name is clicked in the widget/table, update the search to search for the component instead of selector
- Good source of more information on this topic: Colton
- Overall estimation of effort: medium

Steps
- Update the selector endpoint to return an additional data point -- the component name if it exists
- Something like 
```
{
  "data": [
    {
      "count_dead_clicks": 2,
      "count_rage_clicks": 1,
      "dom_element": "div#myid.class1.class2",
      "element": {
        "alt": "",
        "aria_label": "",
        "class": ["class1", "class2"],
        "id": "myid",
        "role": "",
        "tag": "div",
        "testid": "",
        "title": ""
      },
      "project_id": "1",
      "component_name": "blahblah",
    }
  ]
}
```
- "We'd just have to group by the component name and add it to the select statement in the query" -- Colton (seems like not a huge effort)
- From there, can directly translate selector name to component name in the frontend. Probably need to change a good amount of files, but nothing too difficult

## Overall considerations
- Everywhere we're making these changes, we should update wording to say "components" instead of "selector" (e.g. docs, in Sentry, etc.)
- We should also consider what to show when there’s no component name available! [design input]


## Proposed Timeline
1. Get design input for Rage Click Issues & Selector Widgets, as well as what to render when no component name is available
2. Sync w/ appropriate team members on necessary prep work that needs to be done (ex. endpoint changes)
3. The changes needed for the 3 surfaces appear to be pretty unrelated, so they could be done in parallel or in any order
4. Consider whether we need to update docs, strings/other wording throughout Sentry to say "component" instead of "selector"

**Comment by c298lee** [comment]
All three areas and the docs have been updated with component names!
