### ISSUE TITLE
"Add integrations" link on Performance Page leads to nonexistent docs page for golang backend

### ISSUE THREAD

**Issue by DAcodedBEAT** [getsentry/sentry#65071]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the `Performance` tab in the left-hand main navigation
2. Choose `Backend` in the sub-navigation on the Performance page
3. Choose a Golang project
4. On the "Slow HTTP Ops", if it is empty, you should see the message:
> No transactions with HTTP spans found, you may need to [add integrations](https://docs.sentry.io/platforms/go/configuration/integrations).

<img width="587" alt="image" src="https://github.com/getsentry/sentry/assets/5031018/bd4c0dec-4902-420c-ae85-7aa460a102fa">

5. Click on "add integrations"

### Expected Result

The user is redirected to the integrations section of the Golang SDK docs

### Actual Result

The user is redirected to a Page Not Found docs page (because https://github.com/getsentry/sentry-docs/issues/6229 has not been done):
<img width="688" alt="image" src="https://github.com/getsentry/sentry/assets/5031018/7503834d-c93c-45ac-88f8-12d5d24cc17d">

### Product Area

Performance

**Comment by hubertdeng123** [comment]
Thanks for reporting this. This indeed looks like a bug. I'll make sure the performance team knows about this broken link.

**Comment by gggritso** [comment]
@DAcodedBEAT thanks for raising this, we'll take a look!

@vivianyentran this is related to https://github.com/getsentry/sentry-docs/pull/8866. Apparely only _some_ platforms have an "Integrations" sub-page, and the URL for that sub-page isn't consistent. Sometimes it's `https://docs.sentry.io/platforms/apple/integrations/`, sometimes it's `https://docs.sentry.io/platforms/ruby/configuration/integration_options/`, etc. Some platforms, like Go don't have a dedicated "Integrations" page at all. There are redirects set up for some, but not all of these.

I'm wondering if maybe Sentry should link to the platform's top-level page, rather than trying to link to an integrations page that might not exist, especially since the top-level page usually mention integration configuration as a possibility. Thoughts?

**Comment by vivianyentran** [comment]
@gggritso Thanks for the context; I'll look into standardizing where Integrations go in the platform docs and will add this to our backlog.  

In regards to the Sentry link, it's not clear to me which integrations users would need to set up to get results for the "slow HTTP ops" widget. Can you clarify what users would need to do to get it working? I'm wondering if it might make sense to link to each platform's "Set Up Performance" page instead?

**Comment by k-fish** [comment]
@vivianyentran even with performance enabled, not all users have all integrations, if you look at [the python integrations page](https://docs.sentry.io/platforms/python/integrations/) for example, you can see some are `auto-enabled` and others are not, a user is likely to know from that list if some are compatible to output http or db spans. 

With `Slow HTTP Ops` and `Slow DB Ops`, we point users towards integrations since if those panes are empty but they still have transactions, it's very likely they're missing an integration, from our research. 

In the case there are no integrations for the language yet (not sure how often this happens, but in the long run most languages likely need integrations except in some edge cases). Given we probably don't want to maintain a special list on the UI side since that's likely to break a lot, I think redirecting them to the performance page is fine, along with maybe sending some analytics to notify us a user was looking for integrations for a language.
