### ISSUE TITLE
Login with Okta SSO still asks for credentials

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry#65620]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Members from an org with Okta SSO set up are still asked to provide email and password in order to login

1. Try to log into a Sentry instance with Okta SSO set up (e.g https://sentry.io)
2. Click on "Login with Okta"

### Expected Result

Sentry should log the user in using the Okta provisioned account information

### Actual Result

Sentry requires user to provide email and password after trying to log in with Okta

[Customer Case](https://www.notion.so/sentry/Login-with-Okta-SSO-still-asks-for-credentials-47a445b6c47b495baa6e1b15158109e5)

### Product Area

Sign In

**Comment by leedongwei** [comment]
Can you have them enable `Require SSO` inside the config page for Okta?

**Comment by serglom21** [comment]
@leedongwei They already have that setting enabled

**Comment by leedongwei** [comment]
Hmm okay. That doesn't sound right. I'll investigate and follow up.

**Comment by nhsiehgit** [comment]
Followed up on [this ticket](https://www.notion.so/sentry/Login-with-Okta-SSO-still-asks-for-credentials-47a445b6c47b495baa6e1b15158109e5)

This is a non issue and afaict looks to be working as expected.

The title here is misleading.
Okta SSO is _not_ still asking them for credentials.
This user in particular is being prompted to link their account with an existing account that we've detected. In order to verify that they are indeed the owner of the detected account, we are prompting them to validate their existing account credentials so we can properly merge the two.

Once they do that once, then they should be good to go and wont' be prompted again.

closing this ticket out as a wont do
