### ISSUE TITLE
Large replays w/ canvas crashes the browser due to memory usage

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#65792]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**Description:**
A customer reported that a replay is crashing the page when they try to view the replay. 

Customer details with example in ZD: https://sentry.zendesk.com/agent/tickets/114411

Edited by @billyvg: This is because we eagerly load the entire replay (including canvas snapshots). Due to the size and quantity of the canvas snapshots, it is causing the browser to go OOM.

~Relevant Sentry issue: https://sentry.sentry.io/issues/4895039441/events/bc73d7ed17934fd2909e011b3a57fbc7/?project=11276~

### Expected Result

Replay page to load 

### Actual Result

Replay page crashes

### Product Area

Replays

**Comment by bruno-garcia** [comment]
We're investigating. THanks for raising

**Comment by bruno-garcia** [comment]
Examples: https://github.com/getsentry/team-replay/issues/399

**Comment by ryan953** [comment]
The crashes are directly related to this loop and the processing it does: https://github.com/getsentry/sentry/blob/b6f00e9ac6ec988423184a6c88803d3da3bcec44/static/app/components/replays/canvasReplayerPlugin.tsx

In one example there were ~3,100 canvas elements within a ~60min replay. Based on the type of app & session that I observed this isn't an upper bound, with sample rates see we could see up to 7,200 canvas images within a 60 minute replay.

What we can do is remove the pre-processing that happens inside the canvasReplayerPlugin and let the images be processed as needed, while the replay is playing. This should alleviate the memory pressure at pageload and let the user watch the replay.

**Comment by ryan953** [comment]
Ohh, update: on slower CPU's the pre-processing seems really important. Without the pre-processing stuff its possible for the replay to have ended, but new canvas frames are still rendered, they're totally out of sync! 

At least with the pre-processed stuff in place, even if there's some stutter to the playback, it's much more in sync with the timeline. Idk if we can just delete this code :(

What we could do is kick off the promises in batches, so that instead of doing all 3,100 at once, we do them maybe 100 at a time. We should also consider that if the user is looking at a Clip, or came into the replay from an Error, then they might be deep-linked to the middle of the replay... in those cases the current pre-processing (of 1000 items) could still take 1-2 seconds, and so it might not be ready for playback. Replay Clips can sometimes auto-start too. So maybe we can be smart about choosing which batches to run first....
