### ISSUE TITLE
Replays tab in Transaction Summary: `You cannot view events from multiple projects.`

### ISSUE THREAD

**Issue by nikolovlazar** [getsentry/sentry#65888]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When accessing the Replays tab from the Transaction Summary page I get the following error: `You cannot view events from multiple projects.`. I'm not expecting this error since I'm not viewing multiple projects. The Transaction Summary page shows events for a specific project and a specific transaction.

The request URL:
```
https://us.sentry.io/api/0/organizations/lazars-experiments/replays/?field=activity&field=browser&field=count_dead_clicks&field=count_errors&field=count_rage_clicks&field=duration&field=finished_at&field=id&field=is_archived&field=os&field=project_id&field=started_at&field=user&per_page=50&query=id%3A%5B%5D&sort=-started_at&statsPeriod=14d
```

The dashboard URL:
```
https://lazars-experiments.sentry.io/performance/summary/replays/?project=6521984&query=&statsPeriod=14d&transaction=%2F
```

My org is on the free plan. It makes sense that I can't see multiple projects because of my plan, but I wasn't trying to in this view.

The tab also shows that I have 1 replay associated with this transaction.

### Expected Result

See the replays list with the 1 replay I have associated with this transaction.

### Actual Result

![image](https://github.com/getsentry/sentry/assets/5396211/55da027f-4b9b-4125-94cf-34b24bff911c)

### Product Area

Replays

### Link

https://lazars-experiments.sentry.io/performance/summary/replays/?project=6521984&query=&statsPeriod=14d&transaction=%2F

**Comment by ryan953** [comment]
The problem here is that the request should bypass the 'cannot view multiple projects' check that we usually do.

Regardless of the plan, and regardless of whether you're looking at a single transaction form a specific project... we want to intentionally search for replays across all projects.
Why is this? It's because some customers have separate projects for their frontend and backend code. In the case that this transaction is from the backend, we need to look at the frontend project to find the replay. There's no Replays SDK for backend. It looks like in this case it's a NextJS project, so the frontend and backend would be the same project, but we still send `project=-1` (the "all projects" flag) because we don't consider the project platform when doing the query.

**Comment by ryan953** [comment]
To fix this issue we should not check `organizations:global-views` inside the organization_replay_index. Cross-project searching is required for replay on any plan tier.

@cmanallen can you make that fix for us?
