### ISSUE TITLE
Change unique constraint on monitor slugs to be `project, slug` instead of `org, slug`

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#65955]
We want to allow slugs to be reused on different projects on the same org. Alter the unique constraint to allow for this

**Comment by alekseyp** [comment]
We are facing an issue where we have many laravel projects with same cron, for example named: `scheduled_artisan-horizon-snapshot`.
I think it would randomly assign  it to different projects, each time they push.
It also provides a lot of false possessives because many projects push it as the same time.

**Comment by wedamija** [comment]
> We are facing an issue where we have many laravel projects with same cron, for example named: `scheduled_artisan-horizon-snapshot`. I think it would randomly assign it to different projects, each time they push. It also provides a lot of false possessives because many projects push it as the same time.

You're correct there, this is a known bug right now. We are fixing this in the very near future

**Comment by evanpurkhiser** [comment]
Related work for updating the Sentry.io billing side of things is tracked here https://github.com/getsentry/team-crons/issues/153
