### ISSUE TITLE
About the mute for everybody button in the alert rule page.

### ISSUE THREAD

**Issue by julienpierlot** [getsentry/sentry#66135]
### Problem Statement

In our organization, everybody is an admin, therefore can click on the "Mute for everyone" button on the alert rule page. 
This can lead to accidental actions where someone clicks on the button, and alerts are muted until someone realizes it is "too quiet". 
However, after contacting support, it is not possible to get notified when such action is performed, and there is no way to disable this option unfortunatly.

### Solution Brainstorm

- Allow possibility to disable this option.
- Send notifications for when this action is performed (email, webhook).

### Product Area

Alerts

**Comment by leedongwei** [comment]
@julienpierlot Hi! Thanks for the feedback.

I think the issue may be that everyone is an admin. 

Can you restructure your Sentry organization to use [team-level roles](https://docs.sentry.io/product/accounts/membership/#team-level-roles). This will allow people to have admin permissions for the projects that they are responsible for.

Regarding notifications, I'm not keen on sending another email because Sentry is already quite spammy. We are reworking our notification system and we will consider a zero-severity notification flow for these situations.

**Comment by ceorourke** [comment]
Closing as we haven't heard back in quite some time - feel free to reopen if this is still relevant.
