### ISSUE TITLE
user reports can be created before events finish processing

### ISSUE THREAD

**Issue by macqueen** [getsentry/sentry#6630]
And then [the group id is null](https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/project_user_reports.py#L106) and it only gets exposed via the event details api and is missing from project/group user reports.

**Comment by macqueen** [comment]
gonna reopen because still need to write data migration to fix old data

**Comment by BYK** [comment]
I think this (the lack of a data migration for the broken old data) was the cause of a lot of headaches people had while trying to upgrade form 8.x to 10+. Since we have some fixes in place now, I'm closing this.

Just demonstrates how important it is to write these migrations timely. /cc @lynnagara
