### ISSUE TITLE
Incorrect data in events when adding large integers to context data 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#66692]
Sentry is treating big values differently in tags and context causing some values to be in correct after event processing. Below is an example event I sent using the ruby SDK, the same behaviour happens in Python as well: 

Script:
```
::Sentry.init do |config|
  config.dsn = "_MY_DSN_"
end

Sentry.set_tags('bigNumber': 608548899684111178)
Sentry.configure_scope do |scope|
  scope.set_context(
    'arguments',
    {
      name: 'A big value',
      age: 608548899684111178,
    }
  )
end

Sentry.capture_message("le big number test")
```

I expect to see both tag and context showing the same value, but in the context session it is showing as `608548899684111200` This is a common issue with large integer/floating point in Node.  

A possible workaround is to add the value as a string when it is added manually, but it is not applicable when the data is automatically added by the SDK.

![Screenshot 2024-03-11 at 11 48 50](https://github.com/getsentry/relay/assets/64906376/1d25a2b3-d369-4b0c-bb80-9cf038fde3df)

**Comment by leeandher** [comment]
I was able to reproduce this as well, we are correctly storing the real value sent to us at every stage, it only errors when displaying the value on to the frontend. It seems to come from JSON parsing integers values in the API response that exceed `Number.MAX_SAFE_INTEGER` is the problem here.

I have filed the bug, and the fix will likely be in stringifying the value for these contexts at some stage (the way we do with the tag).

**Comment by jangjodi** [comment]
@masinette could you please share some instances where this is happening? I cannot replicate the issue

**Comment by NeoPhi** [comment]
We are using the sentry-rails gem to capture reports. We have noticed that the automatically captured data for active jobs ([noted here](https://github.com/getsentry/sentry-ruby/blob/master/sentry-rails/lib/sentry/rails/active_job.rb#L43)) when viewed at sentry.io is showing truncated values. The raw JSON for the event is correct but looks to still be an integer instead of a string. A redacted version of `extra` logged data looks like this:
```
{ "extra":{"active_job":"RedactedJob","arguments":[608548899684186867,{"redacted_1":true,"redacted_2":null}],"job_id":"redacted","locale":"en","provider_job_id":null,"scheduled_at":null} }
```

**Comment by jangjodi** [comment]
Thank you @NeoPhi - it appears that it isn't working since we don't stringify large integers that are nested in data structures (in this case, lists). I'll look into fixing it.
