### ISSUE TITLE
Allow to set level for Performance Issues

### ISSUE THREAD

**Issue by tiagotex** [getsentry/sentry#66867]
### Problem Statement

We have been using the [Performance Issues](https://docs.sentry.io/product/issues/issue-details/performance-issues/) to ensure performance regressions are fixed as soon as possible on our project. We can configure the Detector Threshold Setting for those Performance Issues, but we cannot set a Level, with every issue having a Level Error. 

Having every Performance Issue be an Error means our on-call developers will be pinged for those, even though those don't have the same level of urgency as a bug.

### Solution Brainstorm

Could we have a config to choose the Performance Issues Level, so we could set it as Warning?

### Product Area

Issues

**Comment by leeandher** [comment]
Thank you for writing in @tiagotex! What you've described is a known issue at Sentry with how we manage prioritizing different levels of errors as we start monitoring different aspects of your apps.

We actually have an ongoing project to address this, and you can sneak a peek [over here](https://github.com/getsentry/sentry/issues/63026#event-11460331478)!  I believe in the long run, this should address the challenges you're experiencing, but we aren't able to provide a concrete timeline at the moment for when you'll see the changes on sentry.io.

I'm going to close this issue as a duplicate since it points towards something we're actively working on but please keep posted on our changelog for updates!
