### ISSUE TITLE
Streamline resolving feedback for fixed issues

### ISSUE THREAD

**Issue by mr-v** [getsentry/sentry#67423]
### Problem Statement

I love the new search capability for the user feedback. However, I find that once the issue is fixed there's too much noise - I still see the feedback for an already resolved error.

### Solution Brainstorm

Auto resolve the feedback once the linked error is resolved.

### Product Area

User Feedback

**Comment by jas-kas** [comment]
hey @mr-v 👋 

thanks for writing in this feature request!

the reason why feedback submissions (from the crash-report modal) are not synced with the issue state (i.e., issue is marked as resolved) is because `/feedback` is about getting back to the user and closing the loop, `/issues` is about fixing code bugs. that was the assumption we built into the product and UX. 

do you (or someone else in your organization) follow up with users who submitted feedbacks via the crash-report modal to let me know an issue is resolved/you're working on/similar, etc. why or why not?
