### ISSUE TITLE
Source Map Upload - Requesting best practices/suggestions to circumvent the 2GB Artifact Bundle size limit

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#67607]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Upload Source Artifacts as part of build process to achieve deobfuscated stack traces for Javascript issues.

### How are you getting stuck?

Client's codebase's Total Source artifacts are approx. 16,000 files at 2.1GB total. This is triggering a limit of 2GB maximum for the total bundle size. None of the files within the bundle exceed the 40MB individual artifact limit. 

### Where in the product are you?

Issues - Source Maps

**Comment by lforst** [comment]
How and how big the source maps are generated is outside of the capabilities of Sentry and/or the SDK. We should recommend users to review and understand how their source maps come to be and adjust their setups accordingly.

Afaik we cannot increase the 2gb limit as of now since we are at the int limit. 2gb of source maps is **a lot** for any application and in such cases there are very likely files that can be optimized/exempted from being included in sourcemaps.

We technically removed the need for releases with debug IDs, meaning users can upload certain files only when they changed, however these files need to be individual static assets.

**Comment by Swatinem** [comment]
The 2G limit is a hard technical limit due to signed 32-bit integers, so there is no way with any reasonable effort to increase that.

Other than that, we are speaking about 2G of **compressed** source files and SourceMaps here. That is unreasonably large, not to speak of the sheer number of 16k files.

Unfortunately, Sentry uploads the original source files "duplicated", in the sense that we bundle the original source file, plus also embed it inside of the SourceMap as `sourcesContent`.

We need the copy embedded in the SourceMap to apply source context. Packaging the original source file individually is done to also support source context when no SourceMap application is needed, because the original source is being executed instead of the minified one.

---

Anyhow, that being said, I have seen quite some cases where large assets such as SVG, CSS, or other assets are being bundled up as JS files to be dynamically loaded. In those cases, all those assets would end up in the `sourcesContent`, as well as obviously inflate the number/size of generated JS files.

Similarly, it is often the case that minified artifacts are duplicated for each configured locale.

In those cases it is up to the build system configuration to reduce the number and size of assets being generated. Anything that helps reduce the bundle size in general will obviously also help with reducing the upload size to Sentry.

**Comment by AbhiPrasad** [comment]
Considering the 2GB limit seems to be our upper bound, I'm closing this issue.

**Comment by bruno-garcia** [comment]
The new limit is 4 GB: 
* https://github.com/getsentry/sentry/issues/86896
