### ISSUE TITLE
[Replay Details - UI] URL should show screen name

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#67697]
It's likely we don't need to do anything on the UI side as SDK should be sending the correct breadcrumbs.

Today the player relies on navigation breadcrumbs. We should aim to rely on the same breadcrumbs (perhaps with small adjustments like `category`)

**Comment by romtsn** [comment]
It looks like the player relies on the span frames with `op:navigation.*` at the moment ([link](https://github.com/getsentry/sentry/blob/b0067212e224f7f04e24aa8a8ab0480dd9c3ae5d/static/app/utils/replays/getCurrentUrl.tsx#L11-L47)). It would be great to move over to `navigation` breadcrumbs for inferring the current screen name on mobile, as we don't really send spans for web-like page loads, so we'd have to make them up.

The mobile SDKs should still send the full list of visited screens under `replay_event.urls` though, because this is how `count_urls` is [calculated](https://github.com/getsentry/sentry/blob/a07600352e2e7282a66de5262344f166f4819df9/src/sentry/replays/query.py#L634).
