### ISSUE TITLE
Events page column width hard to use on laptop screens

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#68015]
this column is not very helpful.  hover tooltip would be appreciated. <https://sentry.sentry.io/issues/5114515965/events/?alert_rule_id=14460873&amp;alert_type=issue&amp;notification_uuid=7d5dda37-873c-4263-9de7-aba0c46dcf4a&amp;project=1&amp;referrer=slack|https://sentry.sentry.io/issues/5114515965/events/?alert_rule_id=14460873&amp;alert_type=[…]d5dda37-873c-4263-9de7-aba0c46dcf4a&amp;project=1&amp;referrer=slack>

[Slack Message](https://sentry.slack.com/archives/C04KZQBNQ2U/p1711717936986149?thread_ts=1711717936.986149&cid=C04KZQBNQ2U)

**Comment by vuluongj20** [comment]
I think we can use a similar treatment to the events table in Transaction Summary — just letting the table scroll on overflow x — before implementing a more meaningful change to the table component's resizing behavior.

<img width="715" alt="image" src="https://github.com/getsentry/sentry/assets/44172267/d319d244-e429-4553-af50-625356388fdf">

A hover tooltip would be helpful, but I would want to see the timestamps for every row all at once without having to hover over their respective timestamp cell multiple times.

**Comment by MichaelSun48** [comment]
It seems like horizontal scrolling is already a feature in the All Events table if the columns are expanded past a certain threshold. The issue seems to stem more from the fact that the timestamp column on the All Events table is the last column, unlike the timestamp column in the Transaction Summary in Vu's comment. This causes the issue because the last column is the only non-expandable one – you can't drag the right column divider since it's the edge of the table (is this a bug?), and dragging the left column divider just expands the second-to-last column. 

I agree with @vuluongj20's sentiment that a hover tooltip would be less useful than just being able to see all values at once, so I think there are two options: 
1. Move the timestamp column in the All Events table to somewhere else 
2. Allow dragging the rightmost column divider/table edge so that the timestamp column can be expanded. 

@rachrwang any thoughts/preferences? or is there another solution I didn't consider?

**Comment by JoshFerge** [comment]
@MichaelSun48 I think moving it to the left and having the replay_id be the last column which can't be expanded makes sense! since replay will just be an id with a link shouldn't be an issue.
