### ISSUE TITLE
[Replay Details] Seeking to the first segment does not work

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#68437]
[Example Replay](https://sentry-sdks.sentry.io/replays/51b01d2959ce43cb8b83c0e52befc7df/?project=5428559&query=&referrer=%2Freplays%2F&statsPeriod=1h&yAxis=count%28%29)

The first segment is portrait, the 2nd is landscape. Let it play until it changes to landscape, then try to seek somewhere < 5 seconds, notice that the it remains in landscape. Seeking to :00 will rotate it back to portrait.

**Comment by michellewzhang** [comment]
i tracked it down to `findVideoSegmentIndex`  in `utils.tsx` returning the wrong segment index (it was returning 1 instead of 0 which is why the wrong segment was loaded when you seek), so i console logged `trackList` to see what was going on.

it looks like the first 2 + last 2 attachments have the same exact timestamp, which is why it was getting confused:

![image](https://github.com/getsentry/sentry/assets/56095982/845cf9e9-50f4-4da5-abb4-ac18ffad2799)

so i don't think it's the code, but rather something weird happened with the attachment timestamps -- seeking works normally with other replays with proper timestamps:

![image](https://github.com/getsentry/sentry/assets/56095982/00d7ce62-8b24-4226-83ca-ee5075599bd9)

**Comment by billyvg** [comment]
@michellewzhang good catch, I'm going to guess @romtsn was testing something and we got bad data. Don't think we need the UI to handle this type of bad data.
