### ISSUE TITLE
Out of Date Bitbucket Integration Docs

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#68912]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The current Bitbucket integration setup docs do not match the most recent version of Bitbucket (v8.19.0).
The UI and options used in the guide are no longer present in Bitbucket, and some mandatory options on the UI are not mentioned in the docs; for example the Client ID or recommended scopes.
![Bitbucket](https://github.com/getsentry/sentry/assets/100724053/ecfce46b-df6f-4ce4-8621-2b8888a25b46)

### Expected Result

The docs reflects the current version of the platform, in this case Bitbucket

### Actual Result

Out of date docs

### Product Area

Settings - Integrations

**Comment by dribblecastle** [comment]
FYI, i figured this out after some poking around.  Note, I was trying to integrate Sentry.io SaaS with Bitbucket Data Center (hosted).  The instructions need to be updated to provide more clarity to what you need to do on the Bitbucket end.   Hopefully this helps someone in the future.  

https://docs.sentry.io/organization/integrations/source-code-mgmt/bitbucket/#bitbucket-server

You have to select `Atlassian Product` and then enter the Application URL.   Not intuitive at all since Sentry.io is not an Atlassian company product.  
![Image](https://github.com/user-attachments/assets/ac45b674-80b1-4017-bb29-87f7c8dd5152)

On the next screen you then have to select the `Use this URL` checkbox. 
![Image](https://github.com/user-attachments/assets/afd2da49-f86e-4b36-a3b1-47285622496e)

Finally, you'll get to the Link Applications screen, which lists the fields that make sense in step 4 in your instructions. 
![Image](https://github.com/user-attachments/assets/195de47c-6360-4c3b-95af-46929f557bc0)

**Comment by sentaur-athena** [comment]
Thank you for the comment @dribblecastle. I'll send this to our docs team to consider since they're revamping some integration documentations.

**Comment by GabeVillalobos** [comment]
It looks like this has been addressed by our docs team already: https://github.com/getsentry/sentry-docs/pull/11840

If anything is incorrect or missing from the docs, please let us know and we can reopen this issue.
