### ISSUE TITLE
Sentry replays only access

### ISSUE THREAD

**Issue by profsmallpine** [getsentry/sentry#69127]
### Problem Statement

I'd like to be able to give user's access to replays but nothing else. The user roles don't seem to allow this as far as i can tell. We could customer support specialists this access without exposing them to issues. That would be real handy.

### Solution Brainstorm

Creating a customer support role would be a nice way to solve this over super specific permissioning 

### Product Area

Replays

**Comment by jas-kas** [comment]
Hey @profsmallpine 👋 

Thanks for sharing your feedback! There is no way to today to provide 'replay only' access.

One of the advantages of Sentry's Replay product is that it can connect to exceptions and you can visually see what happens when users encounter bugs. In the case of customer support tickets, it's also useful to see if and when an error happens inside replays for particular users writing in a support ticket to shed more light on the user experience. 

Out of curiosity, what are your concerns with exposing the Customer Support specialists to Issues?

CC'ing the PM that oversees our user roles and their permissions @gauthamcs

**Comment by profsmallpine** [comment]
@jas-kas That makes a lot of sense given the connection to issues from replay. Our customer support team won't be able to make sense of the issues. They will receive a complaint, go look at the session to see what the user sees, but they are not interested in the console or the error that occurred during the session. Given our business model, the product we are selling is only partially software; therefore, our customer support agents are less technical than on average. I would be worried they would get confused by the issues.

aside, just came back from toronto yesterday. Ate some slaw at lee restaurant, soooo good!

**Comment by jas-kas** [comment]
@profsmallpine 

> Given our business model, the product we are selling is only partially software; therefore, our customer support agents are less technical than on average. I would be worried they would get confused by the issues.

That makes a lot of sense. One thing I'll suggest for today is to route your errors to a different project (and keep replays on a different one for the Support team): https://docs.sentry.io/platforms/javascript/best-practices/micro-frontends/#manually-route-errors-to-different-projects

So funny that you mentioned Lee -- the Replay team will be doing a team dinner there in May! 😋

**Comment by profsmallpine** [comment]
Ok, thanks for the tip!

That makes me want to join the replay team, enjoy the meal!
