### ISSUE TITLE
Show color change in Slack when Issue is assigned

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#69199]
### Problem Statement

Feedback from Customer to Support:

> Like to have the colour bar on the left back on the messages as it was helpful to know when an issue was assigned (from red to white).

### Solution Brainstorm

Due to limitations with block kit- we cannot bring the bar back BUT we can certainly explore more options to denote that an issue has been triaged

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
Due to block kit limitations we cannot bring back the red bar, but we can certainly denote such changes by changing 🔴 🟡 to ⚪

**Comment by jeanmonod** [comment]
Hi Sentry support team,

Not sure what is the "block kit limitations", but the current situation is affecting us a lot...

We are used to work with the red/orange line at the beginning of the message. It was super useful because each time we resolved or assigned an issue to someone, it turn out to white. Like that we had a visual trick to be sure that everything was treated correctly. When a message is white, I don't need to read it. It has already been managed by a coworker. When it's red/orange, there is something to do. Now they all look the same... It's very hard to see if it's already ignored or assigned.

Is it possible to go back the the previous notification system? If not, can you maybe reimplement this intro line? Changing the circle from  🔴 🟡 to ⚪ will be less visual. But it will be good enough for a start

Thanks a lot for considering this

**Comment by Dhrumil-Sentry** [comment]
Thanks a lot for this feedback- We've added this to our backlog and will comment here once this is available

**Comment by jeanmonod** [comment]
Hi Sentry,
Do you have an update on this request? This is a point on which our team has high expectations.
Thanks in advance for your feedback

**Comment by Dhrumil-Sentry** [comment]
Hi @jeanmonod we'll be making this change available within the next few weeks, I think the change is already available for customers who are Early Adopters

**Comment by jeanmonod** [comment]
That's a really good news! Is it possible to apply to be Early Adopers?

**Comment by Dhrumil-Sentry** [comment]
@jeanmonod You can go to your Org Settings and enable the Early Adopter Toggle

**Comment by jeanmonod** [comment]
@Dhrumil-Sentry I toggle it yesterday evening, but this morning it's still not active on my Slack...

**Comment by Dhrumil-Sentry** [comment]
@jeanmonod the change we made is that if you resolve/archive/assign any alert in Slack then we will update 🔴 🟡 🔵 to ⚪ , Is that not happening for you?

**Comment by Dhrumil-Sentry** [comment]
We'll investigate this and get back

**Comment by jeanmonod** [comment]
It's working since this morning! Thanks a lot 🙏
