### ISSUE TITLE
Visualising Cardinality Limits

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#69290]
### Problem
As a user, I want to know the cardinality per metric and if data is being dropped for any given metric and for what reason.

### Acceptance Criteria
- A user can see the cardinality for each metric (for reasonable time window)
- A user can understand which metric is exceeding cardinality limits
- A user can understand why cardinality limits are exceeding
- A user can see the values for each metric tag

### Solution Sketches
![Image](https://github.com/getsentry/sentry/assets/6508377/6fe7c97d-439c-4f7a-98f1-06b43d95b9c8)
![Image](https://github.com/getsentry/sentry/assets/6508377/a2f091bd-54cb-4629-b2c3-3a5306a0084c)
![Image](https://github.com/getsentry/sentry/assets/6508377/498f5492-0f6e-4722-90c1-e9098e9eb12e)
![Image](https://github.com/getsentry/sentry/assets/6508377/35065cc5-c879-41bc-ae5f-88f472f6d921)

**Comment by obostjancic** [comment]
In order to surface cardinality of all of the metrics we can query totals of `max(g:metric_stats/cardinality@none){cardinality.window:3600} by (mri)` 
Time interval should be >=1h because of cardinality.window being 3600. 
We also probably want two show 2 numbers for cardinality. One for last 24h and one for last 1h similar to what we have in the issues list: 
![Image](https://github.com/getsentry/sentry/assets/86684834/c3376d7e-43d3-4526-a4d0-9e91229f2a91)

Regarding warning icons, we should show them only after the user has selected their metric, and not in the selector because:
1. it results in a query per metric to get the cardinality info
2. it is not very useful to know that a metric has been cardinality limited if there are no values of it shown.
