### ISSUE TITLE
Filter all the events with a specific tag in an issue alert

### ISSUE THREAD

**Issue by quintasda** [getsentry/sentry#69399]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Configure a new issue alert
- [WHEN] Number of users affected by an issue is more than 50 in 1 hour
- [IF] The event's tags match `region` contains the value `us`

### Expected Result

When a issue affects more than 50 people in an hour and every event includes the `us` region tag, the issue alert is triggered.

### Actual Result

Multiple events from the issue that trigger the alert have a different `region` tag

### Product Area

Alerts

**Comment by saponifi3d** [comment]
Thanks for the question! The reason you're seeing the events with different `region` tags is because they are still relevant to that issue, so they're still visible there. Not to worry though, I was able to confirm that the alert will only be triggered if those conditions are met.

If you have any more detailed question about the specific alert in question, can you please send a question into [support](https://sentry.zendesk.com/hc/en-us/requests/new) and attach this issue and a link to the alert in question?
