### ISSUE TITLE
Hover state for checkbox on similar issues tab is weird

### ISSUE THREAD

**Issue by mrduncan** [getsentry/sentry#69931]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to the similar issues tab on an issue which has similar issues (ex: https://sentry.sentry.io/issues/5225041747/similar/?project=1).

Note for Sentry employees: you can ignore the banner at the top of this page, this checkbox looks the same for external users too.

### Expected Result

Hovering over the checkboxes doesn't have a weird full-height effect.

### Actual Result

![Screenshot 2024-04-29 at 2 41 20 PM](https://github.com/getsentry/sentry/assets/14761/eec8c485-1ef2-4b0f-a9c3-d6543bd0eb6b)

### Product Area

Issues

### Link

https://sentry.sentry.io/issues/5225041747/similar/?project=1

**Comment by floels** [comment]
Hi,

Florian here, aspiring external contributor 😃

I was able to reproduce this locally.

The code that renders these "similar issue details" is this one:

https://github.com/getsentry/sentry/blob/f1ad8977dd6e61f4b57b7e4852f88a19f02c84a2/static/app/views/issueDetails/groupSimilarIssues/similarStackTrace/item.tsx#L130-L147

The `Details` parent component renders a `div` with `display: grid;` and no `align-items` property set. As laid out in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Box_alignment_in_grid_layout#using_align-items), this means the child components will stretch to fill the parent's height, hence the layout bug on the checkbox child element.

The most natural solution seems to set `align-items: start` on the `<Details />` parent component, and in turn set `height: 100%` on the [`<Diff />` child component](https://github.com/getsentry/sentry/blob/f1ad8977dd6e61f4b57b7e4852f88a19f02c84a2/static/app/views/issueDetails/groupSimilarIssues/similarStackTrace/item.tsx#L142-L146), so that the "Diff" button stays centered vertically:

![ezgif-5-d8813bb858](https://github.com/getsentry/sentry/assets/79283128/1d3d20ce-8dbf-4531-a691-f65e9f00eefe)

Let me know if you'd like me to open a PR for that 🙏

**Comment by roggenkemper** [comment]
@floels If you are interesting in putting up a PR to fix this, i would definitely recommend it! Feel free to follow up on this issue once you have one up!

**Comment by floels** [comment]
@roggenkemper thanks, there it is!

https://github.com/getsentry/sentry/pull/70274

**Comment by armenzg** [comment]
@floels fixed this! 🎉
