### ISSUE TITLE
Remove percentiles in product

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#70721]

**Comment by hendrikmuhs** [comment]
@matejminar This came as a surprise last week It is already removed.

Any plans to get `percentiles` back? I saw https://github.com/getsentry/sentry/issues/71515, so I can just guess the answer is "yes"?

https://github.com/getsentry/sentry/pull/71644 proposes a setting and https://github.com/getsentry/sentry/issues/71515 mentions performance implications. This brings me to the question: How do you implement percentiles? Aren't you using t-digest or HDR? Instead of a boolean flag to enable/disable percentiles, wouldn't a setting to control the error be the better option?

**Comment by matejminar** [comment]
Hi @hendrikmuhs, we were not quite satisfied with how our percentiles functioned, so we opted to eliminate them while the product is still in beta and offer them as an optional feature for those who truly wish to experiment with them. We are developing a different method that is not yet polished enough to be shared 👍 However, our aim is to include percentiles as an optional feature for those who genuinely value them in the interim.

> wouldn't a setting to control the error be the better option?
can you please elaborate on what you mean by this?

**Comment by hendrikmuhs** [comment]
> > wouldn't a setting to control the error be the better option?
> 
> can you please elaborate on what you mean by this?

This relates to my question about the implementation and your remarks regarding performance. Calculating percentiles with 100% correctness is expensive. However if one accepts some variance - and for 99% of applications that is totally fine, especially in the APM space - one can effectively calculate percentiles using approximate data structures. The most famous one is T-Digest: https://github.com/tdunning/t-digest. The good news is that one can control the error/accuracy, so basically trade-off between performance/resources and accuracy. 

Back to my suggestion. Instead of a `bool` for switching percentiles on or off, use a predefined, extendable enum, for example: `exact/very slow`, `high accuracy/slow`, `medium accuracy`, `low accuracy/fast`. I guess you don't want to bother the user with technical settings, but you could give him some limited choice of pre-defined settings with the option to extend it later _without_ backwards compatibility issues.

You find T-digest and alternative implementations in various platforms, e.g. ElasticSearch/Opensearch, Postgres, Prometheus, Redis etc. I don't know your backend stack, maybe you don't even need to implement it yourself.
