### ISSUE TITLE
Empty user project list via API

### ISSUE THREAD

**Issue by pietrop88** [getsentry/sentry#70931]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

 I have generated an user authentication token and I use this token to list all my projects using the Rest API as described [here](https://docs.sentry.io/api/projects/list-your-projects/).

### How are you getting stuck?

I created a test account with a test project to share my authentication token.
I expoit the command:

```
curl https://sentry.io/api/0/projects/ -H 'Authorization: Bearer <redacted>'
```
and the answer is an empty list instead of a list with the _test-flutter_ project.

If I perform the following request
```
curl https://sentry.io/api/0/projects/test-pietro/test-flutter/ -H 'Authorization: Bearer <redacted>'
```
I obtain a JSON object with all the project info.

### Where in the product are you?

APIs

### Link

https://test-pietro.sentry.io/projects/test-flutter/?project=4507260015804496

### DSN

https://8a7102ee544b8c6f79cf764f5c2c7cdc@o4507260014100480.ingest.de.sentry.io/4507260015804496

**Comment by sentaur-athena** [comment]
Thank you for reporting. Will investigate and get back.

**Comment by benyaminl** [comment]
This broke integration with Gitlab sadly :/

**Comment by markstory** [comment]
With DE based accounts, you cannot use the `sentry.io/api/0/projects/` endpoint, as your request doesn't contain enough information to be routed to the correct region. Instead you should be making your request to `de.sentry.io/api/0/projects/`. If using a different host is not possible, you can use the organization scoped projects list URL. `/api/0/organizations/:slug/projects/` instead.

The request to `https://sentry.io/api/0/projects/test-pietro/test-flutter/` does work because it contains an organization slug, which we're able to use to route your request to the correct region.

**Comment by pietrop88** [comment]
> With DE based accounts, you cannot use the `sentry.io/api/0/projects/` endpoint, as your request doesn't contain enough information to be routed to the correct region. Instead you should be making your request to `de.sentry.io/api/0/projects/`. If using a different host is not possible, you can use the organization scoped projects list URL. `/api/0/organizations/:slug/projects/` instead.
> 
> The request to `https://sentry.io/api/0/projects/test-pietro/test-flutter/` does work because it contains an organization slug, which we're able to use to route your request to the correct region.

I had a problem with Gitlab that was not able to load the project list in Monitor -> Error Tracking page. Using **https://de.sentry.io** in the _Sentry API URL_ field fixes the problem.

Thank you. Yuo can close the issue.
