### ISSUE TITLE
Messages from User Feedback shouldn't be dropped by quotas and rate limits!!

### ISSUE THREAD

**Issue by ebelair** [getsentry/sentry#71017]
### Problem Statement

Yes, quotas and rate limits are important to manage noisy projects, but...

With this User Feedback feature, we should make sure that those errors _**always**_ go through. If a specific user has taken their time to write a note, and send it our way... It's kinda sad to see it capped out at the source...! 😞 

Otherwise there would need to be a way to turn off feedback collection if we already know it's not likely to go through... Just to be respectful of our users' time, and not ask them for feedback if it's about to be trashed immediately anyway 🧠➡️🗑️

### Solution Brainstorm

I think we should either:
- Count User Feedback entries as a separate quota in different Sentry plans, _-or-_
- Just make sure to prioritize entries with User Feedback attached over anything else (rate limits and all)

### Product Area

User Feedback

**Comment by ryan953** [comment]
@ebelair Thanks for the feedback!

It sounds like you're worried that a user might spend all this time to write a message, and you point out how it would be terrible if that message got dropped due to quota or something like that.

Well good news... there's no quota for user submitted feedback! 

We do have [`sampleRate`](https://docs.sentry.io/platforms/javascript/configuration/options/#sample-rate) for regular errors but there is no equivalent for feedback messages. 

The idea is that we don't need to put quota on this, and we're not charging for it. Here's some of the philosophy:
- User feedback is a much lower volume than errors. Someone has to open it up and type something out, so it's not that much load.
- User feedback can be much higher signal. If a user has explained something well it can be worth 100's of errors to read the message instead.
- User feedback could be related to something that doesn't throw an error. You might not have any other way of finding out about the problem.
- Also, we were kind of thinking that if someone's site is a mess, their quota is consumed... at least user feedback should work. This way their most engaged users can stay in touch and help get things back on track. 


That doesn't mean that everything is without quota. Errors are Replays are submitted before the feedback, so quota will be used even before the user starts to type out their message. Also the screenshot feature is built on top of our attachments infrastructure which should have sufficient space on all plans for 100's or 1000's of images per month, depending on the screen size of users.

**Comment by ryan953** [comment]
If you've got more questions lmk, otherwise you will be able to see every feedback that hits our servers!

**Comment by ebelair** [comment]
@ryan953 Thanks for replying!

Unfortunately, what you're saying does not seem to be the case. Our account was maxed out on errors and we were unable to see User Feedback come through... and as soon as we provisioned more errors, it started getting in again.

I reached out to customer support and they thought this happened as intended – if you want to follow-up, our support case was no. 121621.

Thanks so much!
