### ISSUE TITLE
Add attachments metadata to SDK feedback events

### ISSUE THREAD

**Issue by aliu3ntry** [getsentry/sentry#71054]
### Problem Statement

If we want to track metrics on feedback screenshots, there's no easy way to get metadata, ex number of attachments, (currently 0/1) in the monolith. After Relay, the two types of events are processed separately and at decoupled times. 

### Solution Brainstorm

Adding a "num_attachments" field to the contexts object could help. Helpful code refs:

SDK:
https://github.com/getsentry/sentry-javascript/blob/d651f1319c95867be03c55f95c5878771c1e4c26/packages/types/src/feedback/sendFeedback.ts#L14
https://github.com/getsentry/sentry-javascript/blob/d651f1319c95867be03c55f95c5878771c1e4c26/packages/types/src/feedback/sendFeedback.ts#L34

Backend:
https://github.com/getsentry/sentry/blob/3f140db1d65dd91c267b93f95facbc98969b1bd1/src/sentry/eventtypes/feedback.py#L8-L8

#### Alternative
With the change of sending attachments in the same envelope, we _could_ do this in relay -- however ingest is a little wary about having this sort of logic there. See convo in https://github.com/getsentry/relay/pull/3603

### Product Area

User Feedback

**Comment by bruno-garcia** [comment]
After chatting with @mydea he said this doesn't seem to belong in the SDK. Since this data is sent to Relay, and there we have the feedback and attachments. Our goal is just analytics on feedbacks with attachments, this metric could be emitted from there.

Could you please share more details about the concerns from the Ingest team? I see as reviewers on that PR @Dav1dde and @jjbayer 

To expand: our goal is to understand how many Feedbacks include attachments. So attachment statistics by themselves are not helpful to us. Project A can use feedback and attachment but might not be using the Feedback+Attachment capability we just shipped.

**Comment by aliu3ntry** [comment]
Re-started discussion in https://github.com/getsentry/relay/pull/3603
