### ISSUE TITLE
S3 backend does not support STS credentials

### ISSUE THREAD

**Issue by thomas-mcdonald** [getsentry/sentry#7107]
Trying to configure my on-premise instance with S3 filestorage using STS credentials. Unfortunately the S3 configuration only appears to accept access/secret keys and does not also take the session token required to use STS credentials.

Running on 8.22, w/Docker on top of Nomad.

**Comment by mattrobenolt** [comment]
Unfortunately, we don’t use this ourselves, so if you’d like to submit a patch to add support, I’d be happy to review.

**Comment by pgrzesik** [comment]
I'm assuming right now it's not possible to use anything else than keys in config.yml file ? I'm having similar use case - could you point me where I should look in the codebase for logic that is handling this ? Maybe I'll be able to submit a patch

**Comment by mattrobenolt** [comment]
It's all in here: https://github.com/getsentry/sentry/blob/master/src/sentry/filestore/s3.py

**Comment by tomelliff** [comment]
I've not tested it yet but does https://github.com/getsentry/sentry/commit/f6dcca457eff204243769f860130286d0dad1939 not allow the use of the default credential chain when the access key and secret key are not provided to Sentry in any way?

**Comment by ccakes** [comment]
Resurrecting this because I'm having the same issue.

https://github.com/getsentry/sentry/blob/da848379e61f8b501d4c76c6fbbcf66e4f14d012/src/sentry/filestore/s3.py#L372-L387

I'm not familiar with the Python so I don't know exactly how boto works, but in my case I'm passing in STS credentials via environment variables so that would set the `access_key` and `secret_key` **without** setting the session_token. I'm guessing that boto won't automagically look for extra credentials in other locations to avoid conflicts which makes sense but doesn't help us here.

I know it's a backwards-incompatible change, but given that AWS (and all the supported SDKs) have a standard set of methods for passing in credentials, do we really need to support it via config like this? 

I tried writing a credentials file and setting `env AWS_SHARED_CREDENTIALS_FILE` but that didn't work either...

**Comment by ccakes** [comment]
**UPDATE TO THE ABOVE**\

Turns out my issue was actually this - https://github.com/getsentry/sentry-docs/pull/956 - and configuring via the credentials file did work.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
