### ISSUE TITLE
Last 30 days chart inside issues shows wrong date

### ISSUE THREAD

**Issue by infernocloud** [getsentry/sentry#7177]
On sentry.io, when viewing one of my issues I have noticed that the "Last 30 days" chart is displaying dates off by one day. Perhaps the "Last 24 hours" chart is using my local timezone and the "Last 30 Days" chart is using UTC?

Here is a screenshot showing a count of today's issues with yesterday's date:
<img width="269" alt="sentry-date-error" src="https://user-images.githubusercontent.com/1633850/35883153-f74379d8-0b4b-11e8-8d50-55a05803be08.PNG">

As you can see, the most recent chart column has a label of "2/5/2018" (yesterday) with 17 events. These are actually for "2/6/2018" (Today) and counting the issues in "Last 24 hours" matches this number.

**Comment by tkaemming** [comment]
I think this is a manifestation of an issue noted in GH-2717 — specifically, the data used to serve this API request is pre-aggregated in 24 hour intervals starting at UTC midnight, so they don't align exactly with the user-specified timezone (unless your user timezone is also UTC.)

So, if you made this request at 13:00 PST Tuesday (21:00 UTC Tuesday) this gets put into the reporting interval that runs from 0:00 Tuesday UTC to 24:00 Tuesday UTC — and since PST is UTC -8, this interval ends up being 16:00 Monday to 16:00 Tuesday in your user timezone.

This definitely could be clarified in the UI. We're also working on some storage changes that should allow for more flexibility when generating these graphs and make this a non-issue.

**Comment by LewisJEllis** [comment]
I noticed this discrepancy today as well when looking at the weekly report email; it (correctly) reports that a particular project received ~5600 events on Thursday March 1st, and that project's dashboard overview tab 1-week view shows those ~5600 events broken down into their hourly buckets between 1pm and 4pm PST on Thursday March 1st, but the "Last 30 Days" chart on the issues themselves counts those events for February 28th. Since those events happened before 16:00 PST, I think this is consistent with the 16:00-to-16:00 interval you described.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
