### ISSUE TITLE
Update Trello integration instructions

### ISSUE THREAD

**Issue by yufio** [getsentry/sentry#71820]
### Problem Statement

I tried to follow Trello integration instructions but they seem to be either outdated or not full

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
Thanks, we've added this to the backlog

**Comment by sentaur-athena** [comment]
Trello issue tracking is built over our deprecated platform "plugins". I'm going to close this since we don't provide support for plugins anymore.

If you like to continue using Trello, I recommend creating a public integration using our new platform or reaching out Trello to create a 3rd party integration: https://docs.sentry.io/organization/integrations/integration-platform/
