### ISSUE TITLE
Option to Make "Latest Event" Selection Permanent for user in the issue details page

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#72439]
### Problem Statement

Some users frequently search for errors using Exception IDs in Sentry. The current search functionality often defaults to displaying a "recommended event" rather than the "latest event." This behavior requires users to manually switch to the latest event view sometimes, adding unnecessary steps and causing delays in their workflow. 

![image](https://github.com/getsentry/sentry/assets/89524511/ca0f7614-a314-4ba2-aa0e-d6838205fa81)

### Solution Brainstorm

Introduce a user-configurable setting that allows users to permanently set their default view to "latest event" instead of "recommended event," streamlining their workflow and improving efficiency.

### Product Area

Issues

**Comment by malwilley** [comment]
@Kobby-Bawuah this setting already exists on the account settings page: https://sentry.io/settings/account/details/#defaultIssueEvent

**Comment by randy** [comment]
@malwilley, I was chatting with Kobby about this in a support ticket. For me, "Recommended" is just not useful. "Latest" and "Oldest" are not applicable when looking for a specific event related to a search. So perhaps a fourth option that somehow honors the search parameters is in order? I can see that the link in Discover when searching by ExceptionId has a `query` request parameter in it, but the same isn't true for the links on the Issues page.

I could be wrong, but I feel like that was the way it worked before the "Recommended" feature was added. I could search for a specific `ExceptionId`, see the result in Issues, click on it, and get routed to "that" event, not "an event like it."

**Comment by malwilley** [comment]
@randy thanks for that additional context! The "recommended" option was actually added to help with this workflow, because it does filter events by the search string that was used on the issue stream. Previously, only latest/oldest was available which did not use the search query in any way. However, I understand that you want to view the latest event from the queryset, not the "recommended" one which uses other heuristics as well.

I'll pass this feedback on to the team. We will soon be working on a project which will allow better filtering of events on the issue details page which may solve your use case here.
