### ISSUE TITLE
Integration token does not have attachment downloading permissions

### ISSUE THREAD

**Issue by DamGouz** [getsentry/sentry#72488]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Make a user token with just project:read
<img width="849" alt="image (1)" src="https://github.com/getsentry/sentry/assets/9088832/84889b7b-2960-44bc-9008-b3c7875c5f18">
It allows you to download attachments

Now, try the same with an integration token with all permissions. Example:
<img width="576" alt="image (2)" src="https://github.com/getsentry/sentry/assets/9088832/64810c06-71ab-44ef-a0dc-cbcfc1690ab7">
It doesn't allow you to download attachments.

### Expected Result

I would want to be able to download attachments with an integration token as well.

### Actual Result

`curl.exe -X GET https://***.sentry.io/api/0/projects/***/***/events/***/attachments/***/?download=1 -H "Authorization: Bearer ***0e03"
{"detail":"You do not have permission to perform this action."}`

### Product Area

APIs

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2198) by [Unito](https://www.unito.io)

**Comment by schew2381** [comment]
@DamGouz
Hi there, unfortunately this is restricted to user tokens by design. There's an organization setting which can restrict downloading attachments to certain organization roles shown below, so the API needs to know which user is making the request requiring the user token.

<img width="963" alt="Screenshot 2024-07-08 at 10 45 48 AM" src="https://github.com/getsentry/sentry/assets/67301797/68ab1e54-b291-4790-8ab7-794911e0d305">
