### ISSUE TITLE
Issue’s “First Seen” defaulting to Jan. 1 1970

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#72875]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Access Issue's Details
Inspect the "First Seen in Release xx.xx" Information in the sidebar

### Expected Result

First Seen should display an accurate date which could be between hours of even a few years.

### Actual Result

First Seen defaults to the date Jan. 1, 1970 - It seems to be accessing a default value.
Note that clicking into the release shows the deployment date is Not set to Jan. 1, 1970. Only seen in Issue Details.

### Product Area

Issues

**Comment by malwilley** [comment]
Thanks for the report! We're looking into it now. I can confirm that this is happening, but only for a limited number of projects and affecting only a single organization.

One thing that would help track down this issue is knowing how events are being sent to Sentry. If it is through an SDK, which one?

**Comment by malwilley** [comment]
@kpujjigit do you know if the affected users are (or were) running their own instance of Relay? In my testing I have been unable to reproduce this issue because Relay will always catch the old timestamp and correct it.

**Comment by malwilley** [comment]
After some more investigation, I've determined that the cause of these old timestamps has probably been resolved. Since May, no new issues have been recorded with this issue ([see query here](https://redash.getsentry.net/queries/7482/source)).

My plan is to merge a migration that will fix all the wrong `first_seen` values soon. Hopefully that should be the end of it!
