### ISSUE TITLE
Mobile replay settings button disabled

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry#72998]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. hover over the settings button
2. click it
3. nothing happens :)

### Expected Result

It's not clear to my why but the settings button is disabled. If it's not supposed to work for mobile replays, it should be hidden, IMO.

### Actual Result

<img width="361" alt="image" src="https://github.com/getsentry/sentry/assets/6349682/a29daa28-82d1-4649-9e68-34e17d1b4ab5">

### Product Area

Replays

### Link

https://sentry-sdks.sentry.io/replays/fca68ff962e04b0b87b39d9428e8c804/?project=5428561&query=&referrer=%2Freplays%2F&statsPeriod=7d&yAxis=count%28%29

**Comment by michellewzhang** [comment]
the settings button is hidden because we currently don't support fast forward or different playback speeds on mobile replays. we can add a tooltip over the disabled button to describe this, but i'd rather not cause more changes in layout between web and mobile by removing the button completely, especially since we'll add playback speed in at some point. @vaind

**Comment by vaind** [comment]
> the settings button is hidden

that would be preferrable. However, it is not hidden but disabled. Can we hide it without messing things up too much?

**Comment by michellewzhang** [comment]
@vaind i edited my comment to adjust my wording - i meant the button is currently disabled, not hidden. it's not preferable imo to hide the button because it'll mean we need more loading placeholders which causes jankiness on the page

**Comment by vaind** [comment]
I see. I'll leave it to you then
