### ISSUE TITLE
Sentry weekly reports being sent on Saturday instead of Monday.

### ISSUE THREAD

**Issue by mtaaha** [getsentry/sentry#73510]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

We have two Sentry servers running within our environment. Server A was deployed years ago and usually sends out weekly reports on Monday:

**Weekly Report for Sentry: June 17th, 2024 - June 24th, 2024**

However, for Server B, which we deployed a few weeks ago, we are receiving reports on Saturday:

**Weekly Report for Sentry: June 15th, 2024 - June 22nd, 2024**

Server A is on version Sentry 23.3.1 and Server B is on version Sentry 24.7.0.

Any idea what could be causing the date difference, and is it something that can be modified?

### How are you getting stuck?

Would ideally like both servers to generate weekly reports on the same day.

### Where in the product are you?

Settings

**Comment by roggenkemper** [comment]
hi! thanks for reaching out! a few months ago, the decision was made to send out the weekly alerts on Friday evening (midnight Saturday UTC) instead of Monday, so the difference you are seeing is an intentional change. it's not something that can be modified right now in-app, but since you are self-hosted, you can try modifying your sentry configuration to send it on monday again. this is the line that controls when it is sent : https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L1123

**Comment by mtaaha** [comment]
Thank you!
