### ISSUE TITLE
[User Feedback] List Item CSS Tweaks

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#73628]
## Problems
1. Too much ornamentation for indicating when a piece of user feedback is selected. 
2. The unread dots are inconsistent with how the rest of the frontend deals with “unseen” stuff (instead unread email address should be bold, normal font size when it is read)
3. Vertical spacing between email address and feedback preview is awkward when compared with the feedback preview and the footer information (project name + icons)
4. Font sizes of the feedback preview and project name are too big

![Image](https://github.com/getsentry/sentry/assets/6508377/d948fc9b-f1c9-4a0d-a787-cc1629bfeba1)

## Solution
See [Figma Library](https://www.figma.com/design/GFeNWMxm2VV088n5vTf9DU/Library%3A-User-Feedback-Product-UI?m=auto&node-id=0-2464&t=Ub1ZBYtEy0D76l7L-1)

Component in Isolation
![Image](https://github.com/getsentry/sentry/assets/6508377/d8dd9b19-c4da-497d-9243-dcecb6bcf483)

Component in Composition
![Image](https://github.com/getsentry/sentry/assets/6508377/764f74fa-eae7-488d-b011-e4705525413e)

**Comment by michellewzhang** [comment]
@Jesse-Box what did you mean by "Vertical spacing between email address and feedback preview is awkward when compared with the feedback preview and the footer information (project name + icons)"? 

with the updated font sizes, the UI now looks like this.
<img width="415" alt="SCR-20240708-niqg" src="https://github.com/getsentry/sentry/assets/56095982/b3d06c6a-cd19-4c0f-a365-bc81b612ae2a">
We leave room at the bottom of the feedback preview to account for the space that 2-line previews take up; otherwise the heights of the feedback cards wouldn't all be consistent.
<img width="566" alt="SCR-20240708-njbp" src="https://github.com/getsentry/sentry/assets/56095982/073ee8aa-9525-4cfb-b5d9-8d8f95867ae5">

it's also significantly harder to tell which feedback is unread vs read after getting rid of the purple dot

**Comment by Jesse-Box** [comment]
> what did you mean by "Vertical spacing between email address and feedback preview is awkward when compared with the feedback preview and the footer information (project name + icons)"?

I DM'd you a rewatch video, since it contains customer data. Hopefully, that explains myself as well!

> We leave room at the bottom of 1-line feedback previews to account for the space that 2-line previews take up; otherwise the heights of the feedback cards wouldn't all be consistent.

Here are my thoughts on this point right now. In practice, implementing a static height for the feedback preview results in the footer information being visually linked to the subsequent feedback item, rather than the feedback item it is actually linked to. Ideally, we can preview up to two lines of feedback, but if their feedback is short, the feedback preview height is reduced to compensate. Alternatively, we only show one line of feedback.

> Unrelated to the spacing -- it's also significantly harder to tell which feedback is unread vs read after getting rid of the purple dot.

I heard this from Ryan as well, so maybe this was a stupid idea… Can you re-introduce the dot? Sorry about that!
