### ISSUE TITLE
[Performance] Cannot longer filter by type of operation

### ISSUE THREAD

**Issue by serchavalos** [getsentry/sentry#73837]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Visit sentrio.io and navigate to "Performance" tab
2. See the table with the transaction below and try to filter by operation (either "navigation" or "pageload")

### Expected Result

I think I saw this feature before; one could see only pageload events or navigation

### Actual Result

Now it seems this feature is gone. This is what I get in the autocomplete and I also tried `op` or `transaction.op`

![Skärmavbild 2024-07-04 kl  16 12 43](https://github.com/getsentry/sentry/assets/587388/46e5a861-c790-47c8-886f-1daca02bd0b8)

### Product Area

Performance

**Comment by k-fish** [comment]
@serchavalos hey there, you are right that you could once use all event data to filter your visualizations and tables on the performance page, but since it now includes metrics data for more accurate widgets, it's limited to just searching on transaction name. If you still are looking to find your sampled event data, filtering by op will work on the transaction summary pages, discover and dashboards.
