### ISSUE TITLE
Extraction of tags with numeric values

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#73866]
```[tasklist]
- [ ] https://github.com/getsentry/sentry/pull/74118
- [ ] extend numeric conditions
```

In the example below, tags `temp` and `voltage` that always have numeric values are never available, while tag `label` whose value is always a string is normally ingested
```
{
   "category":"span",
   "mri":"c:custom/span_attribute_24@none",
   "field":null,
   "tags":[
      {
         "key":"environment",
         "field":"span.sentry_tags.environment"
      },
      {
         "key":"label",
         "field":"span.data.label"
      },
      {
         "key":"release",
         "field":"span.sentry_tags.release"
      },
      {
         "key":"span.description",
         "field":"span.description"
      },
      {
         "key":"temp",
         "field":"span.data.temp"
      },
      {
         "key":"voltage",
         "field":"span.data.voltage"
      }
   ],
   "condition":{
      "op":"not",
      "inner":{
         "name":"span.sentry_tags.sdk.name",
         "op":"eq",
         "value":null
      }
   }
}
```

related sentry error https://sentry.sentry.io/issues/5274121069/events/b7bbbcd5916b4cb4a2f57af3cefbc98a/

**Comment by jan-auer** [comment]
This is currently expected behavior. Generic metric extraction supports only strings as tag values ([source](https://github.com/getsentry/relay/blob/ec7ad6bbefb9f14716819e731c15d461e0b935ac/relay-server/src/metrics_extraction/generic.rs#L124-L127)).

Numeric values have almost guaranteed high cardinality, ideally we mark them as unavailable in the UI during selection.
