### ISSUE TITLE
[Profiling] Functions have no background color

### ISSUE THREAD

**Issue by TheDevMinerTV** [getsentry/sentry#74002]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

0. If you figure out how you can import a profile.json, you should be able to use this profile:
[placede_apollo_d6a35cc084944b5193ab3d9371ae93a3.profile.json](https://github.com/user-attachments/files/16060009/placede_apollo_d6a35cc084944b5193ab3d9371ae93a3.profile.json)

1. Create a profile which has lots of functions
    1. I'm not sure they have to run for very short amount of times

### Expected Result

The functions are clearly discernible from the background

### Actual Result

The functions are only print their names onto the profiler

https://github.com/getsentry/sentry/assets/29845135/0728e004-38eb-49d7-9be7-76e40bbc3cbf

### Product Area

Profiling

### Version

24.6.0

**Comment by JonasBa** [comment]
@TheDevMinerTV Thanks for reporting the issue. Unfortunately, we've seen this in a few rare cases and failed to isolate the root cause. My suspicion is that this occurs due to our replay SDK performing canvas snapshotting which somehow results in WebGL context loss event.

I have a few question:
1. Can you reliably reproduce the issue or does it only happen in some cases?
2. Are replays enabled? If yes, do you mind running `Sentry.getReplay().stop()` from the browser console and seeing if it fixes the issue (you will need to run this before navigating to the profile page where webgl code runs)

**Comment by TheDevMinerTV** [comment]
1. Seems to happen when I have a giant amount of spans in a profile because I'm calling something in a loop.
2. Replays are disabled. This profile is coming from the Go SDK v8, so it's definitely nothing to do with replays.

**Comment by Zylphrex** [comment]
Does the profile consistently render with color on your phone and consistently render without color on your computer? Or is this behaviour inconsistent? For example, if you refresh the page, it renders with color but other times, when you refresh the same page, it renders without color?

**Comment by TheDevMinerTV** [comment]
It seems to render consistently on my phone (Chrome Mobile), but on my PC (Brave) it consistently doesn't render with colors.

**Comment by Zylphrex** [comment]
Do you have WebGL disabled in Brave? You can check by loading a sample on https://webglsamples.org/ for example.

**Comment by TheDevMinerTV** [comment]
WebGL and WebGL 2 are both enabled and work perfectly fine in every other application.

**Comment by JonasBa** [comment]
@TheDevMinerTV I saw there was a community reply from brave, have you had the chance to test out some fixes they proposed there? I'm not entirely sure what the cause of this issue could be, but since it seems isolated to brave. I'm going to follow that discussion and try install brave on my machine to see if I can provide more info

**Comment by cmanallen** [comment]
Browser issue.
