### ISSUE TITLE
Event Occured Time Wrong

### ISSUE THREAD

**Issue by xuweixi10** [getsentry/sentry#74047]
### Self-Hosted Version

24.6.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.23.3

### Steps to Reproduce

triggle a event

### Expected Result

the latency should less than one minute

### Actual Result

<img width="634" alt="截屏2024-06-30 19 32 32" src="https://github.com/getsentry/self-hosted/assets/40662756/034dd02f-ed10-465b-9803-dc9e252d9424">

**Comment by serrrios** [comment]
any news by this issue?

**Comment by scttcper** [comment]
The latency depends on sdks and the devices where they're catching errors. For example, a crashed android app might not send the error event until the next time it is opened causing a large latency. Closing because if you're seeing lots of latency with a Sentry SDK in particular you should open an issue there.
