### ISSUE TITLE
Delete connected alerts when a span metric is deleted

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#74255]

**Comment by vgrozdanic** [comment]
Cascade deletion of alerts is not possible, due to the possible problem with permissions that could occur.

Alert deletion requires `project:write` permission, and span extraction rule requires only `project:read` permission. If we would allow alert to be deleted via span extraction rule, we would be breaking our permission system, and allow deletion of the alerts to users who shouldn't have permission to do it

**Comment by vgrozdanic** [comment]
Cascade deletion of alerts is not possible, due to the possible problem with permissions that could occur.

Alert deletion requires `project:write` permission, and span extraction rule requires only `project:read` permission. If we would allow alert to be deleted via span extraction rule, we would be breaking our permission system, and allow deletion of the alerts to users who shouldn't have permission to do it
