### ISSUE TITLE
Delete connected dashboard widgets when a span metric is deleted

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#74254]

**Comment by vgrozdanic** [comment]
Cascade deletion of widgets is not possible, due to the possible problem with permissions that could occur.

Widget deletion requires `org:write` permission, and span extraction rule requires only `project:read` permission. If we would allow widget to be deleted via span extraction rule, we would be breaking our permission system, and allow deletion of the widgets to users who shouldn't have permission to do it

**Comment by vgrozdanic** [comment]
Cascade deletion of widgets is not possible, due to the possible problem with permissions that could occur.

Widget deletion requires `org:write` permission, and span extraction rule requires only `project:read` permission. If we would allow widget to be deleted via span extraction rule, we would be breaking our permission system, and allow deletion of the widgets to users who shouldn't have permission to do it
