### ISSUE TITLE
Handle the failing of a query for a non-existent tag group by on /metrics/query

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#74261]
Ignore non existent tags, if the tag is non existent, return everything as one group (only one timeseries).

**Comment by vgrozdanic** [comment]
Update: still waiting for the response from the SnS team on this, but it seems that they are currently having bigger issues...

We will wait for a couple more days, then I will ping them again about this.

**Comment by enochtangg** [comment]
From an discussion offline, we have decided to improve snuba error messaging for missing tags in the `GROUP BY` clause. Currently, with the new span based metrics, clients are able to query for groupby tags that either might not have been ingested yet or disabled from the span attribute extraction rule. When these queries hit snuba, it reaches ClickHouse and returns an HTTP 500 with a poor error message. 

Task:
Improve snuba error response and messaging with something like "query failed: not possible to group by tag foo" rather than returning the entire ClickHouse stacktrace. By doing this, we could have the flexibility to handle missing tags differently in the metrics layer by retrying the query.

**Comment by onkar** [comment]
@vgrozdanic I resolved https://github.com/getsentry/snuba/issues/6084 through PR https://github.com/getsentry/snuba/pull/6244 which was similar i.e. column name not being resolved properly. Can you please verify if https://github.com/getsentry/snuba/pull/6244 solves this issue as well? If it does not, then please share the error response you get on `group by` and I will be happy to take another look.

**Comment by onkar** [comment]
I believe this issue is already resolved based on the previous comment. Closing this issue for now. Feel free to reopen and provide error details if you see it again.
