### ISSUE TITLE
Metric is not collected if there is disabled metric with same name but in upper case

### ISSUE THREAD

**Issue by alx-mag** [getsentry/sentry#74343]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Send counter metric with name `AN_ACTION`
2. Disable this metric in **Metric Details** page
3. Send counter metric with name `an_action`

### Expected Result

Metrics with name `an_action` are collected and became visible on metrics chart

### Actual Result

Metrics with name `an_action` are ignored and don't appear in chart, unless we enable `AN_ACTION` metrics back

### Product Area

Unknown

**Comment by matejminar** [comment]
Hi, thanks for reporting this. We're investigating what's going on.

**Comment by jan-auer** [comment]
This is a bug in Relay's matching logic ([here](https://github.com/getsentry/relay/blob/bae3dc0c888a3f29cb2b324c67446bba09797e3d/relay-server/src/services/project/metrics.rs#L44)). The underlying glob pattern used to match the name is always case insensitive ([here](https://github.com/getsentry/relay/blob/bae3dc0c888a3f29cb2b324c67446bba09797e3d/relay-common/src/glob3.rs#L58)).

**Comment by matejminar** [comment]
After an internal discussion, we decided not to fix this at the moment because we're in the process of changing the metrics API, and things will change.

More information can be found here: https://sentry.zendesk.com/hc/en-us/articles/26369339769883-Upcoming-API-Changes-to-Metrics

Please, in the meantime, work around this by using a different name for the metric, and we'll make sure this is not an issue in the new solution.
