### ISSUE TITLE
Cannot see replays with nextjs

### ISSUE THREAD

**Issue by trixobird** [getsentry/sentry#74629]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open https://adsviewer.sentry.io/replays/?project=4507503305949264&statsPeriod=24h

I can see the traces and the issues. The whole project is from a create next app and then executing `npx @sentry/wizard@latest -i nextjs`. I have put it on a public repo: https://github.com/trixobird/sample-nextjs

### Expected Result

Some replays should be visible since I have setup `sentry.client.config.ts` with `replaysOnErrorSampleRate: 1.0`

### Actual Result

No replays are visible

### Product Area

Replays

### Link

https://adsviewer.sentry.io/replays/?project=4507503305949264&statsPeriod=24h

### DSN

https://a4e338501accee2adf9e58d71b25367e@o4507502891040768.ingest.de.sentry.io/4507503305949264

**Comment by ryan953** [comment]
@trixobird The code looks good to me. I pulled it from github and put my own dsn in there; I am able to see errors and traces like you are, but also I can see a replay was recorded. So I'm thinking that the problem could be in the browser, or possibly somehow the test server isn't happy. 

First, lets look at the browser. When I run the code I'm able to see this kind of network traffic, which is the replay data itself:
![Image](https://github.com/user-attachments/assets/719e7403-d62e-4a62-a465-1e1faf4bed96). Notice the majority of the payload is binary data, this is because it's compressed in a web worker first.

If you're not seeing the same kind of requests then something is gone wrong on the browser. I would first enable debug logging here: https://github.com/trixobird/sample-nextjs/blob/main/sentry.client.config.ts#L14 and see what we get back. 

Also, it's a long shot, but it would be that web workers are disabled, or somehow not running properly: https://docs.sentry.io/platforms/javascript/session-replay/configuration/#using-a-custom-compression-worker. I'm thinking this way because the transport code to send replays is shared with errors and transactions as well, but this is different. Debug logs should show something too.

If the data is being sent though, then maybe firewalls don't like the compressed data? Try on a different network.

As i'm writing this, we're not having any service issues, so data should be ingested without an issue. Check https://status.sentry.io/ to be sure. 

Let me know if any of that helps, or what the debug output is from your machine

**Comment by trixobird** [comment]
Thank you for your fast response Ryan. I can see that replays are not coming as they should be, maybe I was impatient the previous times. There is a but though. I updated the https://github.com/trixobird/sample-nextjs/blob/main/sentry.client.config.ts to have `replaysSessionSampleRate: 0.1,` while keeping the `replaysOnErrorSampleRate: 1.0,` 

I would assume that once an error occured I would get the replay as well, alas that was not the case. I played around and only in one case the replay showed up, probably the 10% case.

Here is the network tab:


![Image](https://github.com/user-attachments/assets/86857b27-295b-4195-b9c8-015ef6d426b8)

and here are the monitoring messages after the error:


![Image](https://github.com/user-attachments/assets/d1489426-4d7b-475d-a220-194bec0da874)



![Image](https://github.com/user-attachments/assets/85acaef9-c0cd-4a3a-b361-9ca92e169b34)



![Image](https://github.com/user-attachments/assets/125cc78d-60ac-40f1-8ae2-c77694b705b6)



![Image](https://github.com/user-attachments/assets/2d9e148c-8a35-448b-994c-f8cad00ea979)

**Comment by ryan953** [comment]
Thats interesting. There's no replay message, even after waiting a moment for the timers to wrap up and send off the data? There is a replayid in the event network request in this image you post (2nd from bottom): 
![Image](https://github.com/user-attachments/assets/125cc78d-60ac-40f1-8ae2-c77694b705b6)) so the replay network request should be there too, if not immediately then quickly after.

I see you've got debug set to true: I'd wanna see that output! and anything related from the console. This really seems like a JS or browser issue.
https://github.com/trixobird/sample-nextjs/blob/c8b3b6027d5c87e033bae55d15fc69540c26271b/sentry.client.config.ts#L15

FYI new replay is started when a new tab gets opened. The `id` is saved into session storage, and re-used on the next pageload, so opening a new tab is best way to reset it and get a new `id` which can help, if the first replay is dropped or corrupted, then starting over with a new `id` can help.
Also, for testing the transport like this it's a good idea to set BOTH of the sample rates to `1.0` so you're not guessing whether something should have been sent.
```
  replaysOnErrorSampleRate: 1.0,
  replaysSessionSampleRate: 1.0,
```

**Comment by billyvg** [comment]
Can you also add `debug: true` in your `Sentry.init()` and check your Console to see if there are any Replay-related logs?
