### ISSUE TITLE
Docker --link is legacy. User Defined Networks should be supported in Dockerfile build.

### ISSUE THREAD

**Issue by AaronFixer** [getsentry/sentry#7520]
The current build script in Sentry Dockerfile relies on --link to be used for connection between containers. 

This is likely to be deprecated and potentially removed from docker in future: 

https://www.rethinkdb.com/blog/docker-networking/

Sentry build should instead rely on docker networking (this can be done manually, but it might be nice to update the Sentry messaging and build script to reflect this). 

Edit: It supports the host entry through environment variables (`SENTRY_REDIS_HOST`). Would it be a better idea to change this message: 

`sentry.runner.importer.ConfigurationError: Exception: Error: REDIS_PORT_6379_TCP_ADDR (or SENTRY_REDIS_HOST) is undefined, did you forget to `--link` a redis container?`

To this:

`sentry.runner.importer.ConfigurationError: Exception: Error: REDIS_PORT_6379_TCP_ADDR (or SENTRY_REDIS_HOST) is undefined, please configure the redis host in your environment using --env`

**Comment by mattrobenolt** [comment]
I'm going to close this for now because there's no reason not to use `--link` and it provides a few benefits, like being able to automatically read environment variables (as you've pointed out) from the linked containers.

They've also been saying this will be removed for a few years now, and it's still working fine. So we continue to use this internally as well for some stuff since it makes it simpler to automatically configure.

If we switched to docker networking as a default, it'd make setup more difficult.
