### ISSUE TITLE
Project Stats total is calculated incorrectly

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#75315]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the Stats page, filter to show data for a single project that has a Spike Protection enabled
2. Hover over a column
3. The Spike Protection threshold is currently added to the total:

![Image](https://github.com/user-attachments/assets/485e5925-9cc0-48c7-a44e-ac719cd72db6)

### Expected Result

the Spike Protection threshold should not be added to the total

### Actual Result

the Spike Protection threshold is now added to the total

### Product Area

Stats

**Comment by maximilianruesch** [comment]
Hi @brianthi, I do not quite understand your reasoning. While all other types of issues shown in the screenshot are actual issue counts and should count towards the total (except "Error Message" which is included in "Filtered"), the "Spike Protection Threshold" is only a threshold.

As such a threshold, it represents an amount of issues over which X happens (in this case spike protection kicks in). It does not represent an amount of issues that were handled in one way or another in that timeframe. Considering this, I think it should not count toward the total count of issues.

Note: While the threshold itself should not count towards all issues, the issues that were discarded due to spike protection should. However, this then needs a separate listing (I presume it already has), since the threshold and the amount of discarded issues over this threshold are separate from one another.

**Comment by brianthi** [comment]
Hi @maximilianruesch, apologies, I misread the ticket. Agree with you that the threshold itself should not be added to the totals. Will get this into our backlog and will share in this ticket when we have an update.
