### ISSUE TITLE
[EU] Linear integration does not add the linked sentry as "sentry marked link" to the linear issue.

### ISSUE THREAD

**Issue by mfn** [getsentry/sentry#75329]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

While we were still using the non-EU sentry integration for linear, whenever we linked "a linear issue from within sentry", a special rendered type of link, with the sentry icon, would appear in the respective linear issue -> this now does not happen

- have an existing linear issue
- look at a sentry you know is related
- link to your linear from within sentry
  ![Image](https://github.com/user-attachments/assets/b600bc12-9c17-41e1-9ff2-79622730da1f)

### Expected Result

In linear, there should be a dedicated list of links to sentry on an issue; here one from when we still used the US version

![Image](https://github.com/user-attachments/assets/d6438d02-a2b1-4c18-b33e-cfd84950addd)

### Actual Result

Nothing happens on linear side: the link only exist in sentry.

### Product Area

Settings - Integrations

**Comment by leedongwei** [comment]
> this now does not happen

To confirm, this is happening on the EU Saas region but not the US SaaS region?

**Comment by sentaur-athena** [comment]
@mfn thanks for adding the details. For transparency, our integrations team has been understaffed and brutally prioritizing the first party integrations which affect most of our users. The good news is that we're starting to ramp up on integration platform and fix issues like this that affect 3rd party integrations. This is on our radar and I post updates when we get to it.

**Comment by sentaur-athena** [comment]
@mfn we narrowed this down to the fact that Linear is calling our issues integration the deprecated way which was only valid before the launch of EU region. We're updating our docs to reflect this change and also reaching out to Linear to make the fix on their side. Basically all APIs should include organization in path parameter so instead of `GET https://sentry.io/api/0/issues/<issue_id>/` they should call  `GET https://sentry.io/api/0/organization/<org_id_or_slug>/issues/<issue_id>/`

**Comment by ameliahsu** [comment]
@mfn Linear has made the fix on their side and Linear issues now have EU Sentry issues properly linked. Thanks for catching this!
