### ISSUE TITLE
Dashboard - Remove the use of on-demand extraction in Dashboards

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#75522]
### Problem Statement

As we're moving in the direction of Spans, which also means dynamic sampling is something we won't be using in the future.
It would be useful for the customers to always be able to see historical data from the data they send in when using custom metadata. (including releases)

- One customer is now running a script that when their release has been created in CI/CD they also call the undocumented Widget edit api to change the tags of that widget to the last release so that they are able to capture the data from that specific moment.
- The other customer is working more with Features inside of the same application and when a new feature is being setup, that's the moment they also want to have a dashboard for this. In terms of timing they have to immediately create the widgets because of on demand extraction.

These steps are usually a lot of extra manual work as they have to get the timing right or they'll miss the historical data when they need the data.

### Solution Brainstorm

As we're moving in the direction of Spans, which also means dynamic sampling is something we won't be using in the future.
Which to me seems like this should be technically possible

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2236) by [Unito](https://www.unito.io)

**Comment by k-fish** [comment]
Thanks @Angelodaniel, just had a couple clarifying questions. 

Is this suggesting we remove this for AM2? Or just that we shouldn't be doing in moving forward into AM3? 

Some existing AM1->AM2 customers are using on-demand extraction since they are being dynamically sampled, removing it for them at the moment would cause graphs w/ counts etc. to drop. To have a completely frictionless experience (no change in their graphs, no more dashboard extraction), we would have to first increase their sampling override to 100%, wait 90d, then remove it. This also has an impact on storage volume / cost, just fyi.

**Comment by Angelodaniel** [comment]
@k-fish my request is from the new Spans model onward, so yes without the Dynamic sampling part. 
Tbh having this removed in the new model could be one of the motivations to go to the Spans model 😄 

I think it's ok to have it still on the Transactions model with Dynamic sampling at this moment 👍

**Comment by ale-cota** [comment]
Hey, @Angelodaniel! I'll close this issue since we clarified that's already the case on AM3.
