### ISSUE TITLE
Missing samples due to 400 in metrics explorer

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#75583]
For many queries, the samples endpoint returns a 400 with a "Query timeout" message - this should not happen with built-in functionality on span metrics (since we **should** always have spans)

[Example ](https://sentry.sentry.io/metrics/?interval=1d&project=1&statsPeriod=30d&widgets=%5B%7B%22mri%22%3A%22d%3Aspans%2Fduration%40millisecond%22%2C%22aggregation%22%3A%22avg%22%2C%22query%22%3A%22environment%3A%5C%22prod%5C%22+span.op%3A%5C%22queue.submit.celery%5C%22%22%2C%22groupBy%22%3A%5B%5D%2C%22powerUserMode%22%3Afalse%2C%22type%22%3A1%2C%22id%22%3A0%2C%22displayType%22%3A%22line%22%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22isHidden%22%3Afalse%2C%22overlays%22%3A%5B%22samples%22%5D%7D%5D)

**Comment by shellmayr** [comment]
The capture_exception call shows that we hit the Snuba rate limit with our queries ([SENTRY-3DCH](https://sentry.sentry.io/issues/5690103965/)) because Snuba tries to allocate 80GB for the single query.

**Comment by shellmayr** [comment]
Reached out to @Zylphrex to check whether we can/should modify the table to allow for different queries with a sample_rate - waiting to hear back if this is something we can solve through a different query.

**Comment by Zylphrex** [comment]
This error is not due to snuba allocating memory for the query. But more specifically, the issue is that we're scanning 80GB for the query which is hitting the limits imposed by snuba and resulting in this rate limit exceeded error.

The precise reason why this is happening is due to the query being used which is trying to read the description column (one of the largest columns in the spans table) over 14 days resulting in clickhouse having to scan this much data.

There's not much we can do about this product side but if this is a requirement, we should have this conversation with the SnS team and see what can be done. Feel free to loop me in on this conversation as I have seen similar issues in other places.
