### ISSUE TITLE
Configure legacy browser filtering based on browserlist standard

### ISSUE THREAD

**Issue by kellyrmilligan** [getsentry/sentry#75668]
### Problem Statement

Applications typically have a set of browsers that they target. Sentry should be able to be configured using a standard technology that tells sentry what to filter for browsers and not just the out of the box options in the project settings. 

### Solution Brainstorm

I would recommend the ability to be able to enter a browserlist config, or to upload a browserlist config during the process of uploading sourcemaps, so that the browsers that are targeted by the code base are also the ones that sentry will report things with. 

### Product Area

Settings - General

**Comment by scttcper** [comment]
@kellyrmilligan Going to close this in favor of https://github.com/getsentry/sentry/issues/54934 which seems to be the same request. 

We did look into browserlist support a little bit when we added the new browser filters and the challenges were around needing to support browserlist query parsing and supporting a somewhat different behavior. for example - browserlist query of firefox > 100 browserlist can tell you the supported versions `101, 102, 103`. But what happens when a new version comes out do we filter out 104 if its not in the list? 

And then we were trying to figure out if people should upload their browserlist query or the output of supported browsers since our version of the database might be different from theirs. "Last 3 major versions" depends on when the caniuse database was updated and questions around how to update that and inform people of when we update.
