### ISSUE TITLE
Dashboard widgets show no values when `Latest` is selected as release filter

### ISSUE THREAD

**Issue by rpropst** [getsentry/sentry#76326]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Build a dashboard for a mobile project
Select `Latest` as release
See no values in widgets

### Expected Result

Data shown

### Actual Result

All widgets display '0', (no value), or "There are no items to display"

### Product Area

Dashboards

**Comment by ale-cota** [comment]
Hi Richard,
Thanks for submitting this feedback, we'll try to reproduce and look into this.

**Comment by gggritso** [comment]
@rpropst thanks for raising this, and sorry about the delay! I've been taking a look at the code and the product and I have a theory. If you could link a specific repro case that would help.

I reproduced the error in the Sentry SDKs project. There, the issue is that the project's "Latest Release" is incorrect or maybe just surprising. For example, the `sentry-react-native` project's "Releases" page by default sorts by "Date Created", which suggests that `6.0.0` is the latest release. However, the _actual_ latest release (by semantic versioning) is `98768.0` of a completely different package! You can verify that by choosing "Semantic Version" in the "Sort By" field on the Releases page.

For your case, can you verify that the "latest" release is what you expect, and that it has data?

**Comment by ale-cota** [comment]
We've update the [docs](https://docs.sentry.io/product/releases/usage/sorting-filtering/#latest-release) and converged on adding a tooltip with the definition also in-product (or explicit subtext if it fits).
