### ISSUE TITLE
Issues aren't grouped by In-app Exception Stack-trace

### ISSUE THREAD

**Issue by yijiez-stripe** [getsentry/sentry#76389]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

we are seeing the issues are grouped by Exception Stack-trace, not In-app Exception Stack-trace:

![Image](https://github.com/user-attachments/assets/c6fc3600-e5af-4d2e-9c8f-beacbe8b0e59)

![Image](https://github.com/user-attachments/assets/b23bbe32-3da8-4f91-ad45-e3b3d23d6620)

Our grouping rules:

![Image](https://github.com/user-attachments/assets/75311c66-44ae-4588-b8f0-06545a18f1a4)

### Expected Result

Issues are grouped by In-app Exception Stack-trace

### Actual Result

Issues are grouped by Exception Stack-trace

### Product Area

Issues

### Version

11

**Comment by lobsterkatie** [comment]
Hi, @yijiez-stripe. A few questions:

1. It's not clear from your screenshots - are those the same issue? (I do see one frame in common.) 

2. There's a green check next to in-app stacktrace, so what's you're indication that it's being ignored in favor of the full stacktrace?

3. I see that the in-app stacktrace is marked as a hash mismatch, which generally happens when stacktrace rules change between the time the event is ingested and the time you're looking at the grouping information on the issue details page. (We recalculate grouping in order to display that info.) When was the event ingested, and when did you set those rules?

4. If you look at the event JSON (click the `{ }` button to the right of the event id, at the top of the page), what is the value for `hashes`?

**Comment by colinlmcdonald-stripe** [comment]
hello @lobsterkatie, i'm a colleague of @yijiez-stripe. thanks for helping us out!

1. Yes those are the same issue.
2. When we inspect the event JSON we see that the `hashes` array contains just one hash, and it is the hash for the full stacktrace, not the in-app stacktrace.
3. We changed the stack trace rules a week ago. Looking at events that were ingested today it still shows "hashing algorithm produced a hash that does not match the event".
4. I don't have the exact event that @yijiez-stripe posted, but looking at that issue today the most recent events are showing just one hash, and that hash matches the full stacktrace, not the in-app stcktrace.

**Comment by lobsterkatie** [comment]
Thanks for that info. That does indeed sounds like confusing behavior. Can you please let me know the id of the issue, so I can take a look? When you're on the detail page for the issue, it's the number after `issues` in the URL: `https://xxxxx.sentry.io/issues/<issue id>`.

**Comment by yijiez-stripe** [comment]
It's `9077235`

**Comment by mrduncan** [comment]
@yijiez-stripe sorry, just to confirm, is this a self-hosted deployment or are you using a sentry.io organization?

If it's self-hosted, it'll be difficult for us to dig too deeply into this without access to all of your configuration. I'd recommend reviewing the changes made to stack trace rules. If you can share the full stack trace rules and an event with the full stack trace we can try to help identify the problem as well.

**Comment by lobsterkatie** [comment]
Oh - sorry. Just looked for it, couldn't find it, and then realized you're on-prem (so we don't have access to your data). But I found a similar example in our own Sentry instance, where it says that it's grouping by both the in-app and full stacktraces (which is by itself a strange thing which will need more debugging), but there is one difference from your event: in the JSON, `hashes` has both values, rather than just the one that your event has.

So I think that's the first thing we have to debug. One thing I noticed - you're using both an outdated grouping config. What version of Sentry are you using? 

(I also noticed you're using an outdated SDK - 5.30.0, whereas the current version is 8.26.0. Your SDK version is unlikely to be the problem, but as someone who actually worked on the SDK for a few years, I can tell you there've been a large number of improvements in the last four years!)

**Comment by yijiez-stripe** [comment]
Hi all, sorry for the late reply!

@mrduncan, it's self-hosted, i should've mentioned earlier. I've attached the full event for that issue (sentry_9077235.json)
@lobsterkatie, we use the `getsentry/sentry:21.4.1` version, will upgrading sentry help the grouping in this case?

[sentry_9077235.json](https://github.com/user-attachments/files/16787765/sentry_9077235.json)

**Comment by lobsterkatie** [comment]
> will upgrading sentry help the grouping in this case?

I can't guarantee that it will, but I'd say it's a good first step. 

One thing to keep in mind is that doing so will temporarily slow down your ingestion a bit, as it calculates correspondences between the old and new hashes. I actually am just in the middle of rolling out a fix for that, but you'd have to wait until the September release to get it. 

To give you a sense of scale, here's what it looked like when I turned the fix on internally two weeks ago. You can see how the time it took to save an event from projects in the middle of a grouping config update (dark blue) dropped to essentially even with that of events from projects which are not mid-ugrade (light blue). A dramatic change, but also the difference of a little less than 100 milliseconds. You can decide, depending on your situation, whether you'd rather wait or go ahead.

![Image](https://github.com/user-attachments/assets/37abafe4-b181-48e3-ba3a-551a8755b720)

**Comment by yijiez-stripe** [comment]
@lobsterkatie thanks for the context, we can definitely wait util September release given our team doesn't have bandwidth to upgrade it as well.

In the meanwhile, what's the best way to debug the current grouping logic? Is the event json I shared helpful?

**Comment by lobsterkatie** [comment]
My hope is that the Sentry upgrade (which will put you on the new grouping logic) will fix this for groups going forward. I want to be helpful, but I'm not sure there's a lot of sense in trying to figure out why a years-old version is behaving the way it is. If the new version still has the problem, then we can do a deeper dive.

In the meantime, for the groups which already exist: Is the consequence of it grouping on full (rather than in-app) stacktrace that too many events are getting grouped together? If so, can you apply [fingerprinting rules](https://docs.sentry.io/product/issues/grouping-and-fingerprints/#fingerprint-rules) to differentiate the events into more groups?

**Comment by colinlmcdonald-stripe** [comment]
@lobsterkatie understood.

we don't create sourcemaps for our vendor files. as a result we're seeing that the grouping for these are unreliable and often change release to release and we release multiple times a day.

**Comment by lobsterkatie** [comment]
Ah, got it. Yeah, I can how that'd be super annoying! Sorry you're running into that.

Your best bet in that case is to use [stacktrace rules](https://docs.sentry.io/concepts/data-management/event-grouping/stack-trace-rules/) to remove your vendor code from consideration when grouping. (See the third line of the first example on the linked docs page.)

**Comment by colinlmcdonald-stripe** [comment]
@lobsterkatie yeah we have those set-up and is the reason that we created this ticket. you can check out the rules we have set-up in the original comment, maybe we are doing something wrong there?

**Comment by lobsterkatie** [comment]
You're using `-app`, but right now that doesn't matter because the the in-app/non-in-app bit isn't affecting grouping like it should. I'm suggesting that you try using `-group`, as shown in the third example on that page (`stack.abs_path:**/generated/**.js         -group`).

**Comment by yijiez-stripe** [comment]
hi @lobsterkatie would you mind elaborating the difference between `-app` and `-group` here?

**Comment by MichaelSun48** [comment]
Hey there @yijiez-stripe, I can chime in here with that question. As per our [docs](https://docs.sentry.io/concepts/data-management/event-grouping/stack-trace-rules/#actions), `-app` is used to explicitly label or unlabel stacktrace frames as in-app, whereas `-group` is used to mark stacktrace frames to be considered for grouping. 

Katie is suggesting that you mark frames with absolute paths that match `**/generated/**.js` with `-group`, which will make our grouping algorithms not consider those frames. This should help reduce some noise in your grouping  If those files are the culprit.

**Comment by colinlmcdonald-stripe** [comment]
@MichaelSun48 @lobsterkatie thank you both, that appears to be working!

**Comment by lobsterkatie** [comment]
Great! I'm going to leave this open for now, since the underlying problem isn't solved, but great to hear that you're sorted until you can do the upgrades. Once you do, please let us know if the in-app hash still isn't being used for new issues.
