### ISSUE TITLE
Add ability to use OR operator in Issues landing page.

### ISSUE THREAD

**Issue by bfpepper87sentry** [getsentry/sentry#76392]
### Problem Statement

Right now the OR operator does not work in the issues search bar. It does work in Discover. This is to request that the issues page matches Discover in this functionality. 

### Product Area

Unknown

**Comment by mrduncan** [comment]
This is a [documented limitation](https://docs.sentry.io/concepts/search/#using-or-and-and), however it's possible to OR within an individual field.

For example: `issue.priority:[high, medium]` will find issues with a matching `issue.priority` that is either `high` or `medium` and our new upcoming search improvements will make this a bit more clear:

![Image](https://github.com/user-attachments/assets/64c26495-f2b4-40b6-bf80-1d8d7763c792)


Due to the complexity, I don't anticipate this will get added to our roadmap any time in the near future but I've added this to our backlog.

**Comment by mrduncan** [comment]
Closing this for now to keep our board clean as this isn't something we'll likely get to any time soon.

**Comment by gid-sentry** [comment]
Adding in another customer has made a request for this (just for the record)
