### ISSUE TITLE
Escalating issues algorithm doesn't take into account inactive previous week

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#76530]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Have an archived issue that received no errors during the previous week, but then started receiving tens of errors during the current week.

### Expected Result

The issue should be marked as escalating since 0 -> 15 errors in one hour is a sudden difference.

### Actual Result

The issue is not marked as escalating because there is no data from the previous week to set an escalation limit with.
![Image](https://github.com/user-attachments/assets/41e4f780-01e8-45c5-b853-15571bdefa18)

Issue link in the [shadow ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2267).

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2267) by [Unito](https://www.unito.io)

**Comment by leeandher** [comment]
Going to look into this one to see if the algorithm did something abnormal, but it may just be that the volume didn't exceed the necessary threshold to be marked as escalating.

**Comment by jangjodi** [comment]
If an issue has not been seen in 7 days and the previous threshold expired, a threshold of 10 is set for the issue when it is triggered again (see [here](https://github.com/getsentry/sentry/blob/e604ffb27994fde2c282a00f7a8ba57ca250f2f8/src/sentry/issues/escalating_group_forecast.py#L64-L81)). 

In this case, I'm guessing that the small spike on August 20th set the threshold to above 20 and that is why this issue didn't escalate. 

I will close this for now since the escalation algorithm does take inactive previous weeks into account, but please re-open this if an issue that has been inactive for 2 weeks does not escalate with a count over 10.
