### ISSUE TITLE
[SDK] [react-native] No errors reported

### ISSUE THREAD

**Issue by tristanbes** [getsentry/sentry#7665]
Hello,

I did follow those steps yesterday:

```
yarn add react-native-sentry
react-native link react-native-sentry
```
(`"react-native": "0.53.3"`)

It successfully created `sentry.properties` with correct keys for both ios and andoid folders. And modified others files too.
The only problem is that not a single error were reported when using the application (and we know there are bugs in the app :D)

The documentation refers to ` index.ios.js / index.android.js`
https://docs.sentry.io/clients/react-native/#client-configuration
But it seems the project has none.

Can you confirm that running the 2 command above are enough to get reporting ? Or did we miss something ?

**Comment by tristanbes** [comment]
Indeed, some information was missing from src/index.js that isn't added by the wizzard.
I don't get why though.

**Comment by tristanbes** [comment]
Especially when all the credential are present in index.ios.js / index.android.js and then you have to manually re-setup sentry in the index.js file. it's counter intuitive and never mentionned :(

**Comment by HazAT** [comment]
OK, so it was actually an issue with the wizard.
If you added Sentry to your index before you ran the wizard we will not mess with your index.ios.js again see:
https://github.com/getsentry/sentry-wizard/blob/master/lib/Steps/Integrations/ReactNative.ts#L152-L158

So not really sure if you did it, I will close this for now since I suppose you found the error.
