### ISSUE TITLE
Auth - Azure SSO SCIM - Being able to change Team slugs without breaking the integration

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#77009]
### Problem Statement

This is a follow up based on https://github.com/getsentry/sentry/issues/76503

Currently the matching has been done when provisioning a team through SCIM is based on the Team name. And when this changes through the Sentry UI it will break the rest of the provisioning on that team on those users.

Ideally this should not break that way

### Solution Brainstorm

When SCIM is enabled our Users go on "lock", this doesn't happen with Teams.
If this is expected then it would be nice to not match on team name but rather on some Team ID or similar so the name can be changed by the own Sentry members if needed.

### Product Area

Settings - Auth

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2278) by [Unito](https://www.unito.io)

**Comment by MikeBlomm** [comment]
Currently we are facing this issue within our organization. Due to the fact that our Identity & Access team requires certain naming conventions, it leads to having hard to read team names within Sentry. It seems that the name of the Entra ID group has a 1 on 1 relation to the Team slug. For us, this ends up with a Team name of something like **_organizationappsentryteamnameusers_**

Not ideal when we need to onboard quite a few teams and keep it somewhat organized

**Comment by leedongwei** [comment]
Hi, thanks for the feedback. Unfortunately, this is a limitation of the technical design and we don't have resources to prioritize a refactor at the moment.

**Comment by MikeBlomm** [comment]
@leedongwei Is it possible to give some timelines when (or if at all) this could be made possible? Technically it's not blocking, however it is quite inconvenient.

**Comment by leedongwei** [comment]
Yea, we can lock team names to start. I'll schedule an engineer to start on this on Oct 7.
