### ISSUE TITLE
Improve activity tab message when linking a Sentry issue to an exsisting Azure issue

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#77410]
### Problem Statement

Currently, when [a Sentry issue](https://org2-w7.sentry.io/issues/5793208489/activity/?project=4507704420139008&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=7) is linked to an Azure issue, the activity tab message is: 
![Image](https://github.com/user-attachments/assets/00b156ca-f45a-4969-8221-86c9311387d3)
This isn't too clear and has caused confusion with azure issue assignment. 

### Solution Brainstorm

It would be helpful if the message made it clear that the user linked the Sentry issue to an existing Azure issue instead of suggesting a new Azure issue was created. 

Something like the below:
User linked this issue to Azure DevOps issue titled [Error: new next test](https://dev.azure.com/int4sentry/_workitems/edit/5)

### Product Area

Issues

**Comment by MichaelSun48** [comment]
Hey @kerenkhatiwada! This is a great suggestion - I've put up a [PR](https://github.com/getsentry/sentry/pull/77423) to make the requested copy change.

**Comment by snigdhas** [comment]
We use the same activity type (CREATE_ISSUE) to track activity for creating and linking external issues today. It looks like this was attempted to be fixed in https://github.com/getsentry/sentry/issues/72924 but the fix didn't add the changes to the frontend. Putting up https://github.com/getsentry/sentry/pull/82064 to fix this
