### ISSUE TITLE
React Sentry hideSourceMap

### ISSUE THREAD

**Issue by richhapal** [getsentry/sentry#78114]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I want to hide source map from devtools.

### How are you getting stuck?

There is not key to hide sourcemap in react sentry like sentry/next. I'm able to see source code from devtool.
this is current script-> "build": " react-scripts build && yarn sentry:sourcemaps",

now i want that GENERATE_SOURCEMAP=false so how to hide sourceMap in react sentry

### Where in the product are you?

Issues - Source Maps

**Comment by chargome** [comment]
Hi @richhapal, did you check https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/uploading/create-react-app/#manual-setup? Also, what does `yarn sentry:sourcemaps` point to?

**Comment by richhapal** [comment]
hi @chargome `yarn sentry:sourcemap` point to this script ` "sentry:sourcemaps": "sentry-cli sourcemaps inject --org physics-wallah-nn --project pw-video-player-fe-react ./build && sentry-cli sourcemaps upload --org physics-wallah-nn --project pw-video-player-fe-react ./build"`

**Comment by richhapal** [comment]
Hi @chargome .map file are not generating

![Image](https://github.com/user-attachments/assets/ab240c13-3fbf-4292-b1d1-52fdc6cdfa0c)

**Comment by richhapal** [comment]
@chargome yes, we are using create-react-app. but there no .js.map file inside build folder. bcz we are using GENERATE_SOURCEMAP=false so can you tell me any other method to hide sourcemap. One method i'm using `GENERATE_SOURCEMAP=true react-scripts build && yarn sentry:sourcemaps && find ./build -name '*.map' -delete"` but it's not a good way

**Comment by chargome** [comment]
With the bare react-scripts I'm not aware if there is a better option, you will need to turn sourcemap on in order to upload them – and in your case delete them manually afterwards.

If you want to make use of one of our [bundler plugins](https://github.com/getsentry/sentry-javascript-bundler-plugins) this will all be done automatically. If you want to do that you could e.g. switch to vite or [eject](https://create-react-app.dev/docs/available-scripts/#npm-run-eject) and update your webpack config in order to use our [webpack plugin](https://www.npmjs.com/package/@sentry/webpack-plugin#sourcemapsfilestodeleteafterupload).
