### ISSUE TITLE
Prevent a single issue from using all of the quota

### ISSUE THREAD

**Issue by Siecje** [getsentry/sentry#79552]
### Problem Statement

One issue can use the entire quota. 

### Solution Brainstorm

There should be a configuration to limit the number of events per issue.

### Product Area

Issues

**Comment by JoshFerge** [comment]
Hi @Siecje -- will tag our @getsentry/support here. there are various ways to manage sentry ingestion, and we'll get back to you on various options.

**Comment by JoshFerge** [comment]
See here in particular for delete and discard -- https://docs.sentry.io/pricing/quotas/manage-event-stream-guide/

**Comment by souredoutlook** [comment]
Hey @JoshFerge seeing as this was filed as a feature request I am not sure that @Siecje is looking for help. 

After looking in Zendesk I believe this user wrote in here: https://sentry.zendesk.com/agent/tickets/135862 (this is a private link for anyone following along at home)

I believe the crux of the argument here is that for any given amount of quota safeguards should be put in place to prevent a single issue from consuming the whole quota.

I don't want to overstep but I assume we'll close this as a unplanned since these kind of guardrails that morph or skew the reported recurrence of a given issue can become an impediment to real-time monitoring of the scale of actual problems that are occurring in an application.

As always (and for anyone else who happens upon this feature request) we're happy to do what we can to help out any customer that's encountered an unfortunate circumstance that has caused unexpected depletion of quota and loss of visibility into production errors. 

@Siecje I'll follow up with your ticket and see if there is anything we can do to help out in this case.

**Comment by Siecje** [comment]
Why was this closed?

Can we at least get a reason why this feature will never be added?

Is it just because billing depends on errors and with a max per specific
error you won't be charged as much?
