### ISSUE TITLE
Please keep Phabricator support

### ISSUE THREAD

**Issue by tdrhq** [getsentry/sentry#79682]
### Problem Statement

Just got the email that Phabricator support will end in a month's time. 

We're still using Phabricator, and many large companies are still using forks of Phabricator.

While Phabricator itself isn't maintained, there's a maintained fork called Phorge: https://phorge.it/, and the conduit API is identical. (We use Phorge.)

I think this is critical for me to even want to keep using commercial Sentry, because all of the information about my crashes are inside Phabricator Maniphest issues.

### Product Area

Unknown

**Comment by sentaur-athena** [comment]
@tdrhq we're deprecating phabricator plugin because it was built based on an unsupported internal platform other than our [integrations platform](https://docs.sentry.io/organization/integrations/integration-platform/public-integration/). It is causing technical dependencies that we cannot maintain.

We're always open to community contributions if you like to build on and publish using the public integrations doc provided above. You can also open a feature request ticket for us to build  a first party phabricator integration and we prioritize if it gets a lot of upvotes.

I'm going to close this ticket since unfortunately we can't keep this one.
