### ISSUE TITLE
[Quick Start] Allow Users to close this forever.

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry#79857]
### Problem Statement

It is not possible to get rid of seeing "quick start" in the UI without completing all the steps. 

### Solution Brainstorm

Give users the ability to close this forever.

### Product Area

Other

**Comment by souredoutlook** [comment]
https://sentry.zendesk.com/agent/tickets/136314

**Comment by priscilawebdev** [comment]
Hey @souredoutlook, thanks for pointing this out! You're right...currently, there’s no way for users to dismiss the quick start with a single click. The only options are either to complete all the tasks or dismiss them individually. That's why we've created [another task](https://github.com/getsentry/projects/issues/350) to explore a way to allow users to dismiss it all at once.

**Comment by priscilawebdev** [comment]
We’ve decided not to provide a one-click option to skip the quick start for now. We’ll monitor feedback and may consider it in the future. Closing this task for now.
