### ISSUE TITLE
[Replay Search] Duration Search Fails Due to Suggested Syntax

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry#79870]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Session replay view: https://sentry.sentry.io/replays/?project=11276&query=duration%3A%3E10s&statsPeriod=90d
2. Add 'duration' filter and choose a suggested option like 10s (same as link above)
3. Observe the failure message which seems to be focused on numeric fields that are meant for data measurements:
![Image](https://github.com/user-attachments/assets/a2d0efd1-f2b0-4728-b531-b9cf69773272)
4. Remove the "s" from the URL like so: https://sentry.sentry.io/replays/?project=11276&query=duration%3A%3E10&statsPeriod=90d
5. Observe that the search works as expected.

### Expected Result

That the suggeste search for duration conforms to the search terms outlined in our docs: https://docs.sentry.io/concepts/search/searchable-properties/session-replay/#duration

Or, that the suffix denoting s, h, m, d etc are honored

### Actual Result

Search fails with a bad error message that isn't relevant

### Product Area

Replays

**Comment by souredoutlook** [comment]
https://sentry.zendesk.com/agent/tickets/136170

**Comment by michellewzhang** [comment]
hmm @aliu39 looks like the new search bar isn't compatible with the way replays does duration search (which accepts no suffix - just a number). before the new search bar update, we could get away with this because the search bar let us put in a duration without a unit, but now the search bar forces a unit which means we can never search on a duration anymore.

do we want to update the replay search to take in a suffix?

**Comment by aliu39** [comment]
Took a look and this is unrelated to replay backend, the error is raised [here](https://github.com/getsentry/sentry/blob/3b83d055a9d589824c0424e04aca4f23974bc350/src/sentry/search/utils.py#L197-L197) before it reaches our query code. Strange because we define this as a DURATION field [here](https://github.com/getsentry/sentry/blob/3b83d055a9d589824c0424e04aca4f23974bc350/static/app/utils/fields/index.ts#L2036).

**Comment by aliu39** [comment]
Never mind, this was a problem with our backend's SearchConfig. This can be fixed in a day or two, thanks for reporting! https://github.com/getsentry/sentry/blob/07751a568bd1c39d9614311a43ab9f63164ac33f/src/sentry/replays/query.py#L336-L336
