### ISSUE TITLE
Unavailable or unwanted features cluttering available functionality.

### ISSUE THREAD

**Issue by rossborchers** [getsentry/sentry#79941]
### Problem Statement

Its quite painful to use sentry as a user with team plan due to the sheer amount of features that I don't have access to, or dont want  to use, cluttering the UI.

Can we please have a way to hide them?

As somebody not familiar with the UI its quite difficult to navigate. And difficult to know what features I have access to. I see there are some icons showing what requires business plan, but there are also other features that require additional payments without any visible distinction. 

Id love to have the money to use the fully featured product, but in light of not being able to afford the higher tiers, bells and whistles, it would be nice to have a bit of a more streamlined user experience <3 

### Solution Brainstorm

- "Hide features I cant use" toggle in project settings.
- "Hide <feature x>" toggle in project settings"
- Group all features you don't have access to, or have not set up, separately in the navigation pane.
- Allow reordering/regrouping of items in the navigation pane. 

Any, all or some of this would go a long way.

### Product Area

Settings

**Comment by lobsterkatie** [comment]
Thanks for this feedback! Overall site organization is in fact something we're starting to look at, now that we've added a number of new product offerings. I'll pass this along to the team!

**Comment by rachrwang** [comment]
@rossborchers - thanks for sharing this with us! I'd love to learn more about your experience - would you be open for a quick chat? If so, you can book directly with me here: https://calendar.app.google/6HMuLCgr59dtP5Nj6

**Comment by ericjeker** [comment]
I think this issue goes hand in hand with the incomprehensible mess the migration of the Team plan is. I manage 10+ different organizations on Sentry. They all have a Team Plan subscription ($29/m), but none have a similar interface:

- Some have the Insights still in BETA.
- Some still have access to Insights (not in BETA).
- Some don't have access to Insights anymore, but we can still see all the icons, the features were silently disabled from one day to another?

For all these accounts we are paying customers, but we are still being requested to start trials for feature we are already using. Probably because they will be silently removed later?

There seem to be no clarity, stability or consistency in any of this. Do you have a roadmap somewhere showing which features we'll have access to, or not anymore, in 6-12 months from now and the related cost increase/plan changes?

**Comment by rossborchers** [comment]
Its great to see you are aware of the issue and making changes!
The screenshot you shared seems a lot better. I'd still like some ability to hide insights that are not relevant to me.
However, I'm going to close the issue so as to not clutter your UI. 👍
