### ISSUE TITLE
Improve the information structor of issue list

### ISSUE THREAD

**Issue by kozaxinan** [getsentry/sentry#80373]
### Problem Statement

Sentry issue list uses Exception name as bold title. The subtitle is the last element of the stacktrace. It would be better to have 

Last element as title and bold
Exception and exception message as subtitle

The exception is nice and important but it doesnt have good detail level for quick look. Which class or method causes that exception should be more important on UI. And common message or method and tag could be part of the UI as well to help us to identify.

![Image](https://github.com/user-attachments/assets/5de6798c-8ff8-4658-8929-02a10968bd90)
![Image](https://github.com/user-attachments/assets/a9ae70d5-9ac6-426f-9ab1-477991364ea9)

### Product Area

Unknown

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2338) by [Unito](https://www.unito.io)

**Comment by leeandher** [comment]
@kozaxinan Thanks for writing in, this is currently something we are looking into with some redesigns. Unfortunately, we will not be changing the issue titles, as how those are computed varies by issue type, available event data, and SDK so a sweeping change must be made with caution. That said, the feedback about what data is useful as a subtitle is something were considering, so I will pass that along to the team.

That said, if you feel strongly that your use case would be served better by changing the issue titles, you can do so with [Custom Titles](https://docs.sentry.io/concepts/data-management/event-grouping/fingerprint-rules/#custom-titles) via fingerprints. Just keep in mind that these changes will affect grouping issue grouping, so you may introduce more unique issues as a result.

**Comment by leeandher** [comment]
@kozaxinan We try to avoid special casing changes across our product depending on platforms, as that can cause more problems and confusion for users navigating different projects. In general issue titles use available information (often times preferring error class titles) to be created, and the UI avoids manipulating that to again prevent bugs/confusion. I do suggest taking a look at the custom titles docs I mentioned earlier though if you feel a grouping change like this would be more useful to your workflow. Another possible solution could be creating saved [discover query](https://docs.sentry.io/product/explore/discover-queries/) to find issues/events grouped by their `stack.filename` attribute, or something similar.

Other platforms, teams, and developers (for example, us who use Sentry at Sentry) do find more use in the current naming scheme than files or function calls since its always a click away to get to code anyway, but at a glance the type of problem can be inferred. It may just be a difference of opinion, but if others find this thread and feel strongly otherwise we could revisit this and find some compromise, but for now I'll be closing this issue out.
