### ISSUE TITLE
UX: Logger name should be an event highlight by default

### ISSUE THREAD

**Issue by karolinepauls** [getsentry/sentry#80460]
### Problem Statement

Default event highlights are chosen oddly to begin with, they're heavily biased towards web applications but they ignore that an overwhelming majority of applications use logging.

For example here:
- URL and status code are useless in non-web applications
- "Runtime" is wasting space, could be 1 column instead of 2.
- I don't really know what "handled" means, this is a log.
- **For log level, the user needs to scroll to the bottom.**

**Call for action: make event source (integration) and log level default event highlights.**

I am aware that the highlights are configurable but most devs won't have permissions to do that.

![Image](https://github.com/user-attachments/assets/af666e1f-0386-42f1-a755-61caeab17ef1)

### Product Area

Issues

**Comment by karolinepauls** [comment]
@leeandher Logger name is by default in the "logger" tag and the source I believe is the default logging integration. I believe "Origin" in the screenshot comes from the trace, not the actual integration that captures logs.

![Image](https://github.com/user-attachments/assets/7250918f-2902-49c7-adf3-b571c3e1a7b5)

The even itself comes from this joyful code snippet:
```
                    # we shouldn't need to log it but callers may suppress exceptions
                    logger.error("Unrecoverable OpenAI error, %r", e)
                    raise
```

**Comment by karolinepauls** [comment]
I use the standard logging integration, here is where it adds the "logger" tag: https://github.com/getsentry/sentry-python/blob/200d0cdde8eed2caa89b91db8b17baabe983d2de/sentry_sdk/integrations/logging.py#L232

That's how it's set up in a call to `sentry_sdk.init` (v2.14.0):
```
            integrations=[
                AsyncioIntegration(),
                ArqIntegration(),
                LoggingIntegration(
                    level=logging.ERROR,  # Capture only error and above as breadcrumbs
                    event_level=logging.ERROR,  # Send only error and above as events
                ),
            ],
```

**Comment by leeandher** [comment]
Thank you for the details! Even though its a standard integration, as its not part of the on-by-default set of tags or context that Sentry will be sending, and isn't standard across the SDKs. Since it will not be applicable for many users depending on their project, or SDK setup, we're unfornately not going to be adding it to the default set of highlights at this moment. In this case it would be best to request the update to your project highlights from someone in your Sentry organization with appropriate permissions.

The feedback about the the current selection of highlights has been noted, but again this applies across a large swath of different developer needs and use cases, so changes to defaults are made with caution.
