### ISSUE TITLE
Date picker in Traces shows "Invalid Period" for 1h

### ISSUE THREAD

**Issue by shellmayr** [getsentry/sentry#80520]
https://github.com/user-attachments/assets/7d7ea068-e666-4c7d-8abf-d1f5c085c568

**Comment by constantinius** [comment]
The immediate reason we see this error is because `1h` is not in the list of available time periods.

![Image](https://github.com/user-attachments/assets/9bdc86cd-0995-4236-83b1-b0ea30421232)

This happens because `1h` and `90d` are considered [`PREMIUM_PERIODS`](https://github.com/getsentry/getsentry/blob/master/static/getsentry/gsApp/components/features/disabledSelectorItems.tsx#L15) which are then subsequently removed from the list of available time periods, thus resulting in the error message `"Invalid Period"` in non-premium orgs.
