### ISSUE TITLE
Dashboard - Big number widget shows no data when switching from Last 7 days to actual selection of start <> end date of 7 days.

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#80529]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open url in Jira ticket -> Customer iOS p90 <Metric>
2. Switch from 7 days to today -> 7 days back
3. No result shows.

### Expected Result

Almost the same numbers pop up

### Actual Result

0.00ms shows

### Product Area

Dashboards

### Link

See jira issue linked

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2348) by [Unito](https://www.unito.io)

**Comment by gggritso** [comment]
This issue has a customer data aspect and a product behaviour aspect. I'll respond to the Jira ticket with the customer data information, and discuss the product behaviour here.

When the Dashboards page loads it takes these steps:

- confirm whether the selected projects are eligible to use metrics data
- check whether the selected project data has enough metrics data to be useful

If the project is eligible _and_ has metrics data, we use the metrics dataset to load the widgets. Otherwise, we use the transactions dataset.

If a customer chooses a relative duration like "last 7 days", we only check project data for the last hour. If they make an explicit selection like "Nov 5th to 12th" we check the project data for the selected range. This is a performance optimization to improve loading times.

If the state of the data in the last hour is very different from the state in the explicit range, we might fall down to a different dataset and show very different data. This is happening to the customer in question.

Since this isn't a product bug, I'd like to close this issue and solve the customer issue in Jira, if that's okay!

**Comment by gggritso** [comment]
Closing this one! See Jira ticket and https://github.com/getsentry/sentry/issues/80679 for follow-up discussions 👍🏻
