### ISSUE TITLE
Loss of events in Web UI.

### ISSUE THREAD

**Issue by agaibura-tripleten** [getsentry/sentry#80549]
### Self-Hosted Version

24.8.0

### CPU Architecture

x86_64

### Docker Version

25.0.5

### Docker Compose Version

2.29.5

### Steps to Reproduce

1. run a Django 3 application with sentry-sdk.
2. write a middleware to handle any Exception and log every sentry event id: `sentry_event_id = sentry_sdk.capture_exception(exc)`
3. fetch a non-nullable sentry_event_id on self-hosted instance, e.g., https://<my-instance>/organizations/sentry/discover/<my-project>:cf4dc5abe7844cbba4cd5d333c17058c/ 

### Expected Result

I see the event data.

### Actual Result

The actual result is "Page Not Found".

What I tried to do:
1. check memory backpressure. It's only 50% consumption at a peak.
2. check `buffer.envelopes_mem` metric. It's less than 200KB at a peak.
3. check disk io backpressire. We don't utilize even 10% of throughput or iops.
4. tried to increase number of relay replicas from 1 to 2.

**Comment by Dav1dde** [comment]
You can confirm in self hosted that events make it to your instance by directly checking what is ingested into Kafka. 

Also you can [configure a DSN](https://docs.sentry.io/product/relay/options/#internal-error-reporting) and see if Relay reports any errors, but if there is no error, Relay did not drop any events. Note, these errors are also logged to the console.

Additionally you should be able to confirm in your stats page how many events make it through to Storage.

**Comment by IdeoG** [comment]
We have finally resolved this mysterious issue.

We had Cloudflare before Sentry self-hosted instance and the bots detection and ban mechanism were enabled on the account. Sometimes the edge (Cloudflare) answers 429 to the NAT gateway of our production cluster (so our applications go through the internet to connect to self-hosted Sentry). 

We also dug into the python client Sentry library and realized that if a client receives a 429 response code, then it should stop sending any events to Sentry for 1 minute.

We lost our events randomly because of misconfiguration on the networking level.
So checking all proxies code answers could help to investigate this issue faster.

**Comment by Dav1dde** [comment]
Closing for now, feel free to re-open with new info, or open a new issue in [self-hosted](https://github.com/getsentry/self-hosted).
