### ISSUE TITLE
Can the public API return the committers/suspect commits?

### ISSUE THREAD

**Issue by pbernery** [getsentry/sentry#80771]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I am exploring the Sentry public API (https://docs.sentry.io/api/) as I am considering to use it for an internal tool.

I wonder if the API is able to return the suspect commits, as we can see it in some issues? This is not in the documentation, but may be it's actually implemented?

### How are you getting stuck?

Cannot find the information in the documentation, or feature may not exist.

### Where in the product are you?

APIs

**Comment by sentaur-athena** [comment]
We have an API that returns committers here: https://github.com/getsentry/sentry/blob/a3f9b451364aa451495f673e99b766419f6fc187/src/sentry/api/endpoints/event_file_committers.py#L17

It is marked private though which is why we don't have public documentations about it. Sending to issues team, the owner of the API, so see if this should actually be documented.

**Comment by snigdhas** [comment]
I think we can make this public, adding it to the epic for API publishing

**Comment by pbernery** [comment]
Great, thank you. 

Does it also mean I could use any private API, at my own risk as I guess it means the API could change or disappear anytime?

**Comment by snigdhas** [comment]
That's correct - an API marked private is one which may end up with breaking changes down the line since we aren't expecting customers to rely on it.
