### ISSUE TITLE
Merging issues is not working with the "All Projects" filter

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#81115]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. On the Issues tab, select "All Projects"
2. Select 2 or more issues **from the same project** and merge them
3. Refresh the page

### Expected Result

The issues are successfully merged.

### Actual Result

Initially, all selected issues disappear. Upon reloading the page, they all appear again separated, so the merging did not happen.

Video reproduction here:
https://github.com/user-attachments/assets/5ea150fd-c8d9-4c93-8416-c1783693c125

The issue can be resolved by selecting a specific project in the project filter.

### Product Area

Issues

**Comment by lobsterkatie** [comment]
Yup, this is definitely a bug - a few of them actually. 1) The merging should work. 2) If the merging doesn't work, we shouldn't respond with a 200. In this case, if we think it's an illegal request, we should send a 400. 3) The UI shouldn't make the issues disappear, especially if nothing has actually happened to them.

For whoever picks this up: 

When you try to do it, the request is `PUT https://us.sentry.io/api/0/organizations/sentry/issues/?id=6076137886&id=6075862012&statsPeriod=7d`, and the response is a 200, with a payload of `{detail: "Merging across multiple projects is not supported"}`.

If you do it with a single project selected in the issue stream, though, the request is `PUT https://us.sentry.io/api/0/organizations/sentry/issues/?id=6076137886&id=6075862012&project=6178942&statsPeriod=7d`. (In other words, the project id is included in the query string.) The response is again a 200, but this time the payload is `{merge: {parent: "6076137886", children: ["6075862012"]}}`.

Interestingly, the FE already has some knowledge of the projects to which the selected issue belong, because if you select issues from different projects, it's doesn't even let you try to merge them:

![Image](https://github.com/user-attachments/assets/3832d168-e76c-4d88-8c3e-079895aabfec)

To-dos:

- In multi-project view, take whatever knowledge the FE has about project ids of the selected issues (it clearly knows project ids, or it wouldn't be able to grey out merging as shown in the screenshot) and use it to append the project id to the query string if the issues all come from the same project.
- Change the endpoint to return a 400 if indeed we do manage to request to merge issues across projects.
- The fact that both issues disappear is probably just a downstream effect of the combo of getting a 200 back but not getting a parent issue id back, but might also be worth looking into?

Putting this into the backlog.

**Comment by lobsterkatie** [comment]
Two updates:

- The underlying problem (sending no project ids triggers the multiple-projects error) has since been fixed, and https://github.com/getsentry/sentry/pull/81618 adds a test showing that it now works.

- Given the above, we now shouldn't ever land in the multiple-projects branch (at least from the UI we shouldn't), but just in case, https://github.com/getsentry/sentry/pull/81644 changes the response code from a 200 to a 400.
