### ISSUE TITLE
Glob Syntax inconsistent in Inbound Filters

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#81868]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Example: say we want to filter out all errors beginning with `TypeError1234`

1. Access Inbound Filters under Project Settings > Inbound Filters > Error Message
2. Trail the Error Message in inbound filters with a wildcard * as intended -> `TypeError1234*`

### Expected Result

All errors beginning with `TypeError1234` are filtered.

### Actual Result

Trailing an Error Message in inbound filters with a wildcard `*` as intended, will not work.

Instead, the message needs to be encapsulated in wildcards, like `*TypeError1234*` even if it's the start of the message. 

### Product Area

Settings

**Comment by Dav1dde** [comment]
This is historic and probably too late to change now because it involves to many already configured rules,

Relay prepends the message which is a matched against the glob with the exception type, e.g. `{"ty": "Error", "value": "Foobar XXX"}` means your glob must be `Error: Foobar*` not just `Foobar*`.

**Comment by kpujjigit** [comment]
Perhaps a workaround for now is to clarify how this works in the Filter's description, something like "Structure is ErrorType:Message"

![Image](https://github.com/user-attachments/assets/08a35bb2-df8b-4659-834c-e5696e45c0e7)

**Comment by jjbayer** [comment]
Thanks, I will open a PR to improve the help text.
