### ISSUE TITLE
Poor security around invitation system

### ISSUE THREAD

**Issue by rodush** [getsentry/sentry#8431]
## Security Concerns / Reporting Bugs

STR: 
1. user is a member of organization and logged in
1. admin removes user from step 1 and invites another team member
1. user receives an invitation in the new emailbox and clicks the link
1. user joined the team / organisation with their old email

Environment:
web site control panel

**Comment by mattrobenolt** [comment]
Hey @rodush, I'm not entirely sure what the issue here is. I understand what you're saying, but step 3 and 4 are saying that you're inviting a new user, and the user from step 1 also has access to this email as well, so they just rejoin. I'd argue that'd expected behavior and working as intended. There's no way for us to understand the actual intent here. What if the user were accidentally removed and you attempt to re-invite? It's the same story. You're just suggesting that the user has access to another user's email, in which case, that's a completely different issue.

**Comment by rodush** [comment]
okay, sorry for commenting in Closed task, just to make sure we understood each other.
- user.a@example.com is logged in
- admin@example.com removes user.a
- admin invites user.b@another.com
- user.b received the code and clicked

Expected:
user.b@another.com joined the organisation

Actual:
user.a@example.com joined the organization

This behavior is unexpected and I consider it a broken implementation.

**Comment by mattrobenolt** [comment]
Right, but how did user.a get access to the invite intended for user.b? If user.a has access to the email for user.b, that's a different problem. You have an assumption that the invite is getting into someone's hands that's unintended, and there's not really anything else we can do here about that. Invitations aren't tied to a specific email address.

**Comment by rodush** [comment]
It is not an assumption. User.a and user.b are the same person. Imagine one mailbox is gmail and another - hotmail accounts. So I remove user with gmail and invite another, hotmail user. I expect to not see gmail user, but the hotmail one...

**Comment by rodush** [comment]
only when that person logged out explicitly and click on invite link later, the proper user was added. I think you guys have some wierd approach to handling sessions....

**Comment by mattrobenolt** [comment]
If user.a and user.b are the same person, what's the issue?

In Sentry, a user's identity is shared between multiple different organizations. So it's not really great to say, make a new account for every organization they are a part of. If you invite a user and they already have an account, they're allowed to accept the invite and join. It doesn't matter what their email is. They can always change their email later since it's not tied to the organization in any way.

It sounds like you're making an assumption that you'd expect a user to have a new account for every organization they're a part of? And we don't really encourage that. We allow you to be a member of multiple orgs.

**Comment by rodush** [comment]
I understand that you don't see the problem here. If you guys think it is a good design... I am sorry to hear that. 
I tried to explain the issue in different ways, with a more or less concrete examples, but probably failed... 
We found a workaround (by logging out the old username), so the problem was solved for us.
Thanks for your time.

**Comment by Hardik-Vibe** [comment]
I think this is worst design ever. I have also encounter this issue. Let me refresh the case.

I am working for one IT firm and one of the project has requirement to integrate sentry. Moreover I have one personal account on sentry.io which is hardik.rajput14@yahoo.in for my personal stuff.

Now my firm wants me to have account on sentry.io with organization email address.

I was invited from our team on my official organization email id. As soon as I clicked on invitation link, I had joined with my personal Id because at that moment I was logged in with my personal id in sentry. 

Now, can you tell me if you are running any IT firm, will it be acceptable that any outside can watch your logs? and if I leave the organization then also I will be able to access and read the logs for my x company.

I would say this is pathetic system design who even can't track which email id is allow to join the team.

And this is not a design but a living bug which could create a big problem.

I would recommend sentry experts who can understand this case and take appropriate actions.

**Comment by dcramer** [comment]
Enable SSO and it resolves your IT security concerns.

I'm also closing this thread because 1) its from 2018, and 2) you started the conversation by attacking our product "worst design ever".
