### ISSUE TITLE
The count of unresolved issues needs to be updated when issues are deleted

### ISSUE THREAD

**Issue by heliodor** [getsentry/sentry#9150]
At sentry.io, when I go to the list of unresolved issues, I see the title as: `Unresolved Issues(7)   v`

I select one or more issues,
click the button with the ellipsis on it, which pops open a menu,
then I click on Delete in the menu.

The issues are deleted (removed from the list) but the count in the title is not updated: `Unresolved Issues(7)   v`

Reloading the page shows the correct count.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by heliodor** [comment]
This makes no sense. Why would you close a bug report that's not fixed?

**Comment by BYK** [comment]
@heliodor - well fair enough. My assumption was that this was already fixed with numerous updates in the past 2 years but to our shame, it is still there just as you described.

Reopening the issue and apologies for the subpar experience. Hoping to get this resolved soon (way less than 2 years at least 😀 )

**Comment by priscilawebdev** [comment]
I recently noticed the same issue. We will fix it soon 😉

**Comment by priscilawebdev** [comment]
just an update: we are investigating this issue

**Comment by priscilawebdev** [comment]
fixed in this PR https://github.com/getsentry/sentry/pull/24775 😉
