### ISSUE TITLE
Organization switcher has lower z-index than Getting Started drawer

### ISSUE THREAD

**Issue by cameronmcefee** [getsentry/sentry#9259]
![screen shot 2018-07-31 at 1 17 29 pm](https://user-images.githubusercontent.com/72919/43485428-0fa43cfc-94c6-11e8-8b36-c76172e8c0c1.png)

Reproduce:

- Create a new project.
- Click the progress bar in the bottom left that opens the Getting Started drawer
- Try to switch orgs

**Comment by samsch** [comment]
It looks like this could be fixed by changing the definition of `SidebarSectionGroup` in `/sentry/blob/master/src/sentry/static/sentry/app/components/sidebar/index.jsx` to:
```jsx
const SidebarSectionGroup = styled('div')`
  ${responsiveFlex};
  flex-shrink: 0;
  z-index: ${p => p.raised ? '1' : '0'};
`;
```
And changing usage on line 174 to `<SidebarSectionGroup raised>`.

This is untested as code, as I don't have the dev environment setup at the moment, but making the changes in the inspector shows this as a working solution.

**Comment by ckj** [comment]
@samsch ah, that would have also worked. In our case, we have an existing z-index system that just wasn't being utilized for this component. Fix should be out shortly.
