### ISSUE TITLE
Too Large Events (>100k) result in incomplete request

### ISSUE THREAD

**Issue by samweiller** [getsentry/sentry#9284]
I am using the Javascript API to send some information back to Sentry from my app (using `Raven.captureMessage()`. I am logging a few breadcrumbs elsewhere in the app that have the potential to be larger that 100k in some rare cases. When triggering `captureMessage` with an event that is greater than 100k, however, the request gets sent and then nothing happens. Sentry doesn't accept it (obviously, because the event is too large), but also Chrome Dev Tools shows the request as 'pending' forever. I know promises in `captureMessage`/`captureException` aren't built into the JS API yet, but is there another way to figure out if Sentry is rejecting the request? Thanks!

**Comment by benvinegar** [comment]
If Sentry rejects the packet because it is too large, it should return HTTP status code 413 (Request Entity Too Large). You can override the transport in the JavaScript SDK, check if the request fails with a 413, and if so drop some frames/`extra_data`/other bits and attempt to resend.

Closing because this should arguably be opened on [getsentry/sentry-javascript](https://github.com/getsentry/sentry-javascript).
