### ISSUE TITLE
Create a sample event  error

### ISSUE THREAD

**Issue by WenChaoGit** [getsentry/sentry#9598]
when i try click button 'Create a sample event'  it return an error 
{"detail": "Internal Error", "errorId": "f92c229092cb44d78880d0d3289575d6"}
where i can select this errorId  for more infomation

sentry version 9 
installation method docker && docker-compose

**Comment by benvinegar** [comment]
@WenChaoGit This was likely logged to the "Internal" Sentry project on your local install (you can search for `f92c229092cb44d78880d0d3289575d6` inside that project).

If you can locate and paste those details here, we'll look further, but in the meantime since we can't reproduce and nobody has piled on, we're going to close.

**Comment by myzhoulang** [comment]
@WenChaoGit [https://forum.sentry.io/t/waiting-for-events-our-error-robot-is-waiting-to-devour-receive-your-first-event/4355](https://forum.sentry.io/t/waiting-for-events-our-error-robot-is-waiting-to-devour-receive-your-first-event/4355 )

**Comment by kumaraditya1999** [comment]
I am using sentry for an Angular Project. I integrated it yesterday but I am not able to create a sample event from sentry's website.When ever I hover on the button it says select a project even though I have already selected and after clicking on it it simply says that "Unable to create sample" event in the bottom of the page.

A bit more detail is required, is it my fault or its it the issue with sentry's server.If its my fault at least it should tell what did I do wrong.I followed the steps of integration thoroughly and I want to test if its working or not
