### ISSUE TITLE
Add comment/name to Auth Tokens

### ISSUE THREAD

**Issue by nijel** [getsentry/sentry#9600]
With many Auth Tokens it's quite easy to loose track of them. Having comment or name field for each Auth Token it would be easier to found the ones which are no longer used and can be safely removed.

I'm currently using sentry.io service if that matters.

**Comment by Nowaker** [comment]
GitLab tokens have names. GitHub tokens have names. DataDog tokens have names. The list never ends. Please let us define a name for Sentry tokens too.

**Comment by Nowaker** [comment]
Bad bot

**Comment by Nowaker** [comment]
Closing feature requests ain't good.

**Comment by Willt123** [comment]
Don't want to be a +1'er but this feature is integral to any business use of Sentry.
Currently, we're keeping a seperate spreadsheet of token last 4 digits to project mapping which is not great for security. 

I've looked into the branch this request is tracking (75) and I can't see names for tokens mentioned. 
Personally, I feel if a system allows you to request multiple tokens we should be able to name them, otherwise we're going to have to go down the route of creating an internal integration for each project just to to be able to name the token.

**Comment by mdtro** [comment]
For those following this issue, I'm working on this. 🙂 Names on your API tokens should be available soon.
I'll update here once it is.

**Comment by mdtro** [comment]
We now support adding names to newly created tokens! 🙂 

We don't yet have support for editing an existing token to add a name to it, but that'll be coming soon.
