### ISSUE TITLE
Bitbucket Integration: Can't see private team repositories

### ISSUE THREAD

**Issue by bloodpet** [getsentry/sentry#9942]
This is probably a bitbucket problem, but I can't seem to see a team that I don't own (just a member of) when I visit: https://bitbucket.org/site/addons/authorize?descriptor_uri=https://sentry.io/extensions/bitbucket/descriptor/ to integrate our bitbucket repositories.

**Comment by benvinegar** [comment]
@bloodpet – hey, sorry this is expected behavior. You need to be an owner of the team or we can't move forward with the integration.

**Comment by rdsedmundo** [comment]
Why this has changed @benvinegar? I have used Sentry before with BitBucket and I'm absolutely sure that this was possible. I'm running a trial on my company of the tool, and how I'm going to ask to have admin rights on the team? They already gave me on the repository-level that I'm going to test, this should have been sufficient. I definitely disagree with this measure.

**Comment by rdsedmundo** [comment]
@dcramer May you include your thought here?

**Comment by lauryndbrown** [comment]
@rdsedmundo the reason is that with the new integration we moved from oauth to atlassian connect apps. With that auth system you only have access to the teams the account you auth with is an owner of, which wasn't the case with the old version of the bitbucket integration. It's expected behavior in this case.
